### ISSUE TITLE
Conv3d argument 'input' must be Tensor not int()

### ISSUE THREAD

**Issue by darrenjkt** [pytorch/xla#1013]
Hi I am trying to move my GPU code to TPU with xla. 

However I keep running into this issue when porting my code. This model works in GPU so I'm quite sure that I've coded the network correct. I've converted the input to the model into a tensor using torch.from_numpy() so I'm quite sure that my model is being fed a torch Tensor.
 
```
Exception in model function for device=xla:2: conv3d(): argument 'input' (position 1) must be Tensor, not int
Traceback (most recent call last):
  File "/anaconda3/envs/pytorch-0.1/lib/python3.6/site-packages/torch_xla_py/data_parallel.py", line 204, in _module_runner
    result.result = loop_fn(module, loader, torch.device(device), context)
  File "train_all_tpu.py", line 56, in train_loop_fn
    output = model(x)
  File "/anaconda3/envs/pytorch-0.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 525, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/darrenjkt3/BTS_DL/models/DMFNet_16x.py", line 199, in forward
    x1 = self.encoder_block1(x)# H//2 down = 32x64x64x64
  File "/anaconda3/envs/pytorch-0.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 525, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda3/envs/pytorch-0.1/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 483, in forward
    self.padding, self.dilation, self.groups)
TypeError: conv3d(): argument 'input' (position 1) must be Tensor, not int
```

I successfully ran the MNIST xla file so I'm quite sure that I've done the installation correctly. How can I solve this? Thanks in advance for any responses!

**Comment by dlibenzi** [comment]
Hard to diagnose without code ... but our loader (the one you get within the train function) is an enumerate()-like thing, so it is like:
```Python
for batch_number, data in loader:
  ...
```

And `data` is whatever data your real loader returns.

**Comment by darrenjkt** [comment]
Here is my training code snippet. 

```
from data import datasets_nopkl
from data.sampler import CycleSampler
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

import torch_xla_py.xla_model as xm
import torch_xla_py.data_parallel as dp

def main():
    torch.set_default_tensor_type('torch.FloatTensor')
    torch.manual_seed(args.seed)
    random.seed(args.seed)
    np.random.seed(args.seed)
    
    model = DMFNet(**args.net_params)
    devices = xm.get_xla_supported_devices()
    model_parallel = dp.DataParallel(model, device_ids=devices)

    Dataset = getattr(datasets_nopkl, args.dataset) #
    
    # Training Data
    train_list = os.path.join(args.train_data_dir, args.train_list)
    train_set = Dataset(train_list, root=args.train_data_dir, for_train=True,transforms=args.train_transforms)
    
    num_iters = args.num_iters or (len(train_set) * args.num_epochs) // args.batch_size
    num_iters -= args.start_iter
    train_sampler = CycleSampler(len(train_set), num_iters*args.batch_size)
    train_loader = DataLoader(dataset=train_set, batch_size=args.batch_size, collate_fn=train_set.collate,
        sampler=train_sampler,num_workers=args.workers,pin_memory=True,worker_init_fn=init_fn)
    
    for epoch in range(args.epoch):
        model_parallel(train_loop_fn, train_loader)
        
def train_loop_fn(model, loader, device, context):

    optimizer = torch.optim.Adam(model.parameters(), **args.opt_params)
    criterion = getattr(criterions, args.criterion)
    losses = AverageMeter()
    torch.set_grad_enabled(True)
    model.train()

    for i, data in enumerate(loader):
        
        x, target = data[:2]        
        output = model(x)
        loss = criterion(output, target)
        losses.update(loss.item(), target.numel())
        
        loss.backward()
        optimizer.zero_grad()
        xm.optimizer_step(optimizer)
        xm.mark_step()       
        losses.reset()
```

**Comment by dlibenzi** [comment]
Hi!
Your optimizer fetching inside the loop function should do something like this:

https://github.com/pytorch/xla/blob/a8d9bc1b3f387fb4afbf10a13c77eb8e077e08ba/test/test_train_mnist.py#L113

Otherwise it will be created every time, and it's state reset.
Your `loader` enumeration should not be explicit. Look at MNIST:

https://github.com/pytorch/xla/blob/a8d9bc1b3f387fb4afbf10a13c77eb8e077e08ba/test/test_train_mnist.py#L135

Should be:
```Python
for batch_number, (x, target) in loader:
  output = model(x)
  loss = criterion(output, target)
  ...
```

Do not call `xm.mark_step()` as that is done automatically from our `DataLoader`.
I am not sure what `losses` does, but with TPU it is better not to perform `item()` calls as those prevent full fusion of our IR graph.
I'd use the tensor values and do operations with those, instead of downgrading to Python scalars.

Again, not knowing what `losses.reset()` does, I would move that right after calling `model(x)` to allow more overlapping of the step `N - 1` TPU computation, with step `N` pytorch API executions.

**Comment by mruberry** [comment]
@darrenjkt Did @dlibenzi's suggestion resolve your issue? 

Closing for now as it appears the issue was resolved.
