### ISSUE TITLE
`F.one_hot` IR lowering check fails

### ISSUE THREAD

**Issue by jysohn23** [pytorch/xla#1418]
## 🐛 Bug

`F.one_hot` IR lowering check fails.

## To Reproduce

```
import torch
from torch.nn import functional as F
import torch_xla
import torch_xla.core.xla_model as xm

# Repro setup
seg_mat = torch.randint(0, 2, (128,1,32,), dtype=torch.int64).to(xm.xla_device())
token_type_ids = torch.randint(1, 5, (128, 32,), dtype=torch.int64).to(xm.xla_device())
cat_ids = torch.randint(1, 5, (128, 32,), dtype=torch.int64).to(xm.xla_device())
dtype_float = torch.float32

# token_type_ids: <class 'torch.Tensor'> torch.Size([128, 32]) torch.int64
# cat_ids: <class 'torch.Tensor'> torch.Size([128, 32]) torch.int64

seg_mat = (token_type_ids[:, None] != cat_ids[None, :]).long()
seg_mat = F.one_hot(seg_mat, num_classes=2).to(dtype_float)
print(seg_mat)
```

Stack trace looks like:
```
[128, 1, 32, 1] vs. [128, 128, 32]
Traceback (most recent call last):
  File "/home/jysohn/repros/one_hot.py", line 21, in <module>
    print(seg_mat, flush=True)
  File "/home/jysohn/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 159, in __repr__
    return torch._tensor_str._str(self)
  File "/home/jysohn/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/_tensor_str.py", line 311, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/jysohn/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/_tensor_str.py", line 209, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/jysohn/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/_tensor_str.py", line 87, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: Error while lowering: s64[128,1,32,1]{3,2,1,0} aten::view, output_size=(128, 1, 32, 1)
Error: torch_xla/csrc/data_ops.cpp:60 : Check failed: total_element_count == xla::util::Multiply<xla::int64>(output_sizes) (524288 vs. 4096)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        torch_xla::GetCompleteShape(absl::Span<long long const>, absl::Span<long long const>)
        torch_xla::BuildView(xla::XlaOp const&, absl::Span<long long const>)
        torch_xla::ir::ops::View::Lower(torch_xla::ir::LoweringContext*) const
        torch_xla::ir::LoweringContext::LowerNode(torch_xla::ir::Node const*)
        torch_xla::ir::LoweringContext::GetOutputOp(torch_xla::ir::Output const&)
        torch_xla::XLATensor::SyncTensorsGraphInternal(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*, absl::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch_xla::XLATensor::SyncTensorsConfig const&)
        torch_xla::XLATensor::GetTensorsFused(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*)
        torch_xla::XLATensor::GetTensors(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*)
        torch_xla::bridge::XlaCreateTensorList(c10::ArrayRef<at::Tensor> const&)
        torch_xla::AtenXlaTypeDefault::masked_select(at::Tensor const&, at::Tensor const&)
        torch_xla::AtenXlaType::masked_select(at::Tensor const&, at::Tensor const&)
        c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, at::Tensor const&), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&> >, at::Tensor (at::Tensor const&, at::Tensor const&)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&)
```

IR Graph: 
```
torch_xla._XLAC._get_xla_tensors_text([seg_mat]): IR {
  %0 = s64[] prim::Constant(), value=1
  %1 = s64[128,1,32,2]{3,2,1,0} aten::expand(%0), size=[128, 1, 32, 2]
  %2 = s64[128,32]{0,1} xla::device_data(), device=TPU:0
  %3 = s64[1,128,32]{2,1,0} aten::view(%2), output_size=(1, 128, 32)
  %4 = s64[1,128,32]{2,1,0} xla::select(%3), dim=1, start=0, end=128, stride=1
  %5 = s64[128,32]{0,1} xla::device_data(), device=TPU:0
  %6 = s64[128,32]{0,1} xla::select(%5), dim=0, start=0, end=128, stride=1
  %7 = s64[128,1,32]{2,1,0} aten::view(%6), output_size=(128, 1, 32)
  %8 = pred[128,1,32]{2,1,0} aten::ne(%7, %4)
  %9 = s64[128,1,32]{2,1,0} xla::cast(%8), dtype=Long
  %10 = s64[128,1,32,1]{3,2,1,0} aten::view(%9), output_size=(128, 1, 32, 1)
  %11 = s64[] prim::Constant(), value=0
  %12 = s64[128,1,32,2]{3,2,1,0} aten::expand(%11), size=[128, 1, 32, 2]
  %13 = s64[128,1,32,2]{3,2,1,0} aten::scatter(%12, %10, %1), dim=3
  %14 = f32[128,1,32,2]{3,2,1,0} xla::cast(%13), dtype=Float, ROOT=0
}
```

To clarify, the following will *not* error:
```
seg_mat = torch.randint(0, 2, (128,1,32,), dtype=torch.int64).to(xm.xla_device())
dtype_float = torch.float32

seg_mat = F.one_hot(seg_mat, num_classes=2).to(dtype_float)
print(seg_mat, flush=True)
```

**Comment by dlibenzi** [comment]
Thanks for the repro @jysohn23 !
Does this block you?
Can you temporarily get around it?

**Comment by jysohn23** [comment]
I could try to find workarounds by manually creating the matrix of one hot encoded vectors maybe? But I do have other stuff on my plate right now that I was planning on working on (HF benchmarking for the BERTs vs Voltas). Thanks @dlibenzi!

**Comment by dlibenzi** [comment]
Got it.
Looks like PyTorch `!=` (`Ne`) needs to broadcast inputs:

```
IR {
  %0 = s64[] prim::Constant(), location=test_fn@test_operations.py:1230, value=1
  %1 = s64[128,1,32,2]{3,2,1,0} aten::expand(%0), location=test_fn@test_operations.py:1230, size=[128, 1, 32, 2]
  %2 = s64[128,32]{1,0} xla::device_data(), location=test_fn@test_operations.py:1229, device=CPU:0
  %3 = s64[1,128,32]{2,1,0} aten::view(%2), location=wrapped@tensor.py:28, output_size=(1, 128, 32)
  %4 = s64[1,128,32]{2,1,0} xla::select(%3), location=wrapped@tensor.py:28, dim=1, start=0, end=128, stride=1
  %5 = s64[128,32]{1,0} xla::device_data(), location=test_fn@test_operations.py:1229, device=CPU:0
  %6 = s64[128,32]{1,0} xla::select(%5), location=wrapped@tensor.py:28, dim=0, start=0, end=128, stride=1
  %7 = s64[128,1,32]{2,1,0} aten::view(%6), location=wrapped@tensor.py:28, output_size=(128, 1, 32)
  %8 = pred[128,1,32]{2,1,0} aten::ne(%7, %4), location=wrapped@tensor.py:28
  %9 = s64[128,1,32]{2,1,0} xla::cast(%8), location=test_fn@test_operations.py:1229, dtype=Long
  %10 = s64[128,1,32,1]{3,2,1,0} aten::view(%9), location=test_fn@test_operations.py:1230, output_size=(128, 1, 32, 1)
  %11 = s64[] prim::Constant(), location=test_fn@test_operations.py:1230, value=0
  %12 = s64[128,1,32,2]{3,2,1,0} aten::expand(%11), location=test_fn@test_operations.py:1230, size=[128, 1, 32, 2]
  %13 = s64[128,1,32,2]{3,2,1,0} aten::scatter(%12, %10, %1), location=test_fn@test_operations.py:1230, dim=3, ROOT=0
} 
```
