### ISSUE TITLE
maximum recursion depth exceeded error with parallel_loader

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#1443]
## To Reproduce

1.  Go to this [colab](https://colab.research.google.com/drive/1MDY5ZpjlIU9Np4r0xSFNevtGekZT6vZk)
2.  Run the cells

The third cell which actually runs the command changes occasionally.  Here is the exact contents of it at the moment I saw this error:

```
# !cd ae-wavenet && git pull
!cd ae-wavenet && git checkout master
!cd ae-wavenet && git pull
!cd ae-wavenet && git checkout c38fd45

# delete all currently loaded ae-wavenet modules
import sys
d = list(map(lambda m: m[0], filter(lambda m: hasattr(m[1], '__file__') and 'ae-wavenet' in m[1].__file__, sys.modules.items())))
def dn(n): del sys.modules[n]
list(map(dn, d))

# %env XLA_USE_32BIT_LONG=0
# %env XLA_DENSE_GATHER_FACTOR=1
VER=!git -C ae-wavenet rev-parse --short HEAD
%run -d ae-wavenet/train.py new -af ae-wavenet/par/arch.ae.json -tf ae-wavenet/par/train.basic.json -hw TPU-single -pi 1 -dlo 8 -dng 0 -lrr 1e-6 -lrs 0 -nw 100 -nb 8 -si 5000 ./basic.full.%.ckpt ae-wavenet/dat/librispeech.some.dat
# !./xla/scripts/debug_run.py --tidy --outfile ./gdrive/My\ Drive/ai/{VER[0]}.dlo128.debug_run.tar.gz -- python ae-wavenet/train.py new -ms 20 -dlo 128 -pi 20 -af ae-wavenet/par/arch.ae.json -tf ae-wavenet/par/train.basic.json -hw TPU-single -dng 0 -lrr 1e-6 -lrs 0 -nw 100 -nb 8 -si 5000 ./basic.full.%.ckpt ae-wavenet/dat/librispeech.some.dat

```
3.  Get traceback:
```python
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/parallel_loader.py", line 165, in _worker
    batch = xm.send_cpu_data_to_device(batch, device)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 505, in send_cpu_data_to_device
    return ToXlaTensorArena(convert_fn, select_fn).transform(data)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 295, in transform
    self._collect_tensors(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 283, in _collect_tensors
    xu.for_each_instance(inputs, lambda x: self._select_fn(x), collect_fn)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/utils/utils.py", line 112, in for_each_instance
    for_each_instance(x, select_fn, fn)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/utils/utils.py", line 112, in for_each_instance
    for_each_instance(x, select_fn, fn)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/utils/utils.py", line 115, in for_each_instance
    for_each_instance(value.__dict__[k], select_fn, fn)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/utils/utils.py", line 115, in for_each_instance
    for_each_instance(value.__dict__[k], select_fn, fn)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/utils/utils.py", line 115, in for_each_instance
    for_each_instance(value.__dict__[k], select_fn, fn)
  [Previous line repeated 981 more times]
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/utils/utils.py", line 104, in for_each_instance
    if select_fn(value):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 283, in <lambda>
    xu.for_each_instance(inputs, lambda x: self._select_fn(x), collect_fn)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 503, in select_fn
    return type(v) == torch.Tensor and v.device.type == 'cpu'
RecursionError: maximum recursion depth exceeded while calling a Python object
```

## Environment

 - reproducible on XLA backend [CPU/TPU]:
 - torch_xla version:
 - Any other relevant information:

## Additional context

I have been using this same codebase for awhile now, but have never seen this error.  Although I have made some changes to the `torch.utils.data.IterableDataset` which supplies the loader, it still runs fine on GPU.

**Comment by dlibenzi** [comment]
I can see what is going on.
There is a reference counting cycle (object1 holding reference to object2, and down the chain of references held by object2, there is a link back to object1).
Will need to fix this.
