### ISSUE TITLE
[PT_BREAK] Fix nll_loss to support empty tensors on GPU

### ISSUE THREAD

**Issue by pbelevich** [pytorch/xla#1539]
All tests except XLA passed in the PR
https://github.com/pytorch/pytorch/pull/31491

```
Jan 17 00:56:12 ======================================================================
Jan 17 00:56:12 FAIL [0.271s]: test_nll_loss_empty_tensor_xla (__main__.TestNNDeviceTypeXLA)
Jan 17 00:56:12 ----------------------------------------------------------------------
Jan 17 00:56:12 Traceback (most recent call last):
Jan 17 00:56:12   File "/var/lib/jenkins/workspace/test/common_device_type.py", line 181, in instantiated_test
Jan 17 00:56:12     return test(self, device_arg)
Jan 17 00:56:12   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10490, in test_nll_loss_empty_tensor
Jan 17 00:56:12     helper([0, 3], "mean", nan)
Jan 17 00:56:12   File "/var/lib/jenkins/workspace/xla/test/../../test/test_nn.py", line 10478, in helper
Jan 17 00:56:12     self.assertEqual(output, expected)
Jan 17 00:56:12   File "/var/lib/jenkins/workspace/test/common_device_type.py", line 336, in assertEqual
Jan 17 00:56:12     return DeviceTypeTestBase.assertEqual(self, x, y, prec, message, allow_inf)
Jan 17 00:56:12   File "/var/lib/jenkins/workspace/test/common_utils.py", line 859, in assertEqual
Jan 17 00:56:12     assertTensorsEqual(x, y)
Jan 17 00:56:12   File "/var/lib/jenkins/workspace/test/common_utils.py", line 817, in assertTensorsEqual
Jan 17 00:56:12     self.assertTrue(torch.equal(nan_mask, torch.isnan(b)), message)
Jan 17 00:56:12 AssertionError: False is not true : 
```
This is because
```
F.nll_loss(
  torch.rand([0, 3], requires_grad=True),
  torch.randint(3, (0,)),
  reduction='mean'
) = tensor(0) on XLA, but expected to be tensor(nan) like on CPU/CUDA
```

**Comment by dlibenzi** [comment]
Likely this:

https://github.com/pytorch/xla/blob/2024f30390fe693d761792a2c1114a9ecdc60f21/torch_xla/csrc/nll_loss.cpp#L99

Let me try letting div-by-zero through.

**Comment by dlibenzi** [comment]
If we fix that, it breaks our backward test for NLLLoss.
I am inclined to mark the test skipped.
Anything which relies on explicit checking for NANs is going to create problems.

**Comment by pbelevich** [comment]
@dlibenzi I disabled that test for XLA, thank you!

**Comment by dlibenzi** [comment]
Where?
I did not mean to disable in pytorch.
I meant here:

https://github.com/pytorch/xla/blob/2024f30390fe693d761792a2c1114a9ecdc60f21/test/torch_test_meta.py#L176

**Comment by pbelevich** [comment]
@dlibenzi got it! I will change `xla/test/torch_test_meta.py` and will remove `expectedFailureXLA` in pytorch

**Comment by dlibenzi** [comment]
Wait ... let's see what @mruberry thinks ...

**Comment by mruberry** [comment]
For some reason Github never notified me of this thread (thanks, Github!) 

Sorry for the late and moot response. Making a change in torch_test_meta.py (as @dlibenzi suggests) sounds good to me!
