### ISSUE TITLE
Porting Style-GAN 2 to TPU

### ISSUE THREAD

**Issue by NaxAlpha** [pytorch/xla#1558]
## ❓ Questions and Help

Main issue #1557 

I am trying to port StyleGAN-2 to TPU. Here is link to colab:

https://colab.research.google.com/drive/13_lcZyUgDVcAa6lQY6IQQZkfP2_w9XPN

So I have changed some components to make it work with TPU but when I tried to debug, it is taking like 5-7 minutes to compile. 

Can anyone help me where things are going wrong?

**Comment by dlibenzi** [comment]
It is possible for a big graph compilation to take minutes.
In general, if the compilations stabilizes (graphs are the same in the following steps), you'd pay that price only once.
The TPU VM also have a compilation cache, but it drains if the TPU VM is restarted, so I am not sure how this works with Colab.

**Comment by jysohn23** [comment]
Yeah, if you restart your runtime in Colab or leave it idle for too long, it'll clean up the compilation cache on the TPU VM.

**Comment by NaxAlpha** [comment]
Thanks but the problem is for every iteration, it re-compiles. That's the weird thing I am trying to figure out. I checked training loop, it does change graph but after 4 steps. So after first compilation graph should not be compiled again but it is tries to compile graph every time.

I am mostly monitoring my compilation and colab is not disconnected. Are you saying that if my compilation takes 10 minutes then runs one iteration but the graph is cleared so it compiles again?

**Comment by dlibenzi** [comment]
Can you print the metrics at every step?

**Comment by NaxAlpha** [comment]
I am not sure about metrics but I have added print commands at different stages. Here is a debug run on sample that I shared. As you can see from logs, it gets stuck every time at 

`> Optimizing generator...` stage `Compiling IR graph hash 123 on device TPU:0 ...`

[run.txt](https://github.com/pytorch/xla/files/4110737/run.txt)

**Comment by dlibenzi** [comment]
Yeah, I can see the hashes always differ, hence the graphs are changing.
You also have many syncs with very low SyncTensorsGraphSize.
I feel you are using an operator which we do not support.
Can you try to print the metrics at every step?
```Python
import torch_xla.debug.metrics as met
print(met.metrics_report())
```

**Comment by NaxAlpha** [comment]
Here are results of the run (with metrics):

[run.txt](https://github.com/pytorch/xla/files/4111725/run.txt)

**Comment by NaxAlpha** [comment]
I did another experiment where I did `xm.mark_step()` at every step to see what is causing delay. But found something very interesting. Surprisingly after a few iterations it somehow becomes very fast!!! I think it may be because of `xm.mark_step` breaks graph into smaller chunks so if graph repeats itself, then it re-uses that graph.

**Comment by dlibenzi** [comment]
If you are not using the `ParallelLoader`, you need to pass `barrier=True` to the last call to `xm.optimizer_step()` you do.
But I suggest you using `ParallelLoader` instead of manual `.to(device)` as the former overlaps data transfer to device with Python and TPU computations.

**Comment by NaxAlpha** [comment]
I have implemented parallel loader functionality but getting this error (I have updated the latest code in notebook):

![image](https://user-images.githubusercontent.com/11090613/73131873-624e5800-4034-11ea-8475-42ff3f75c104.png)

Besides this I have two questions! 

* What does `xm.mark_step()` do? Does it break the graph at given point and compiles it and push it to tpu for execution? And how does graph caching handles broken graphs?
* I am following [this notebook](https://github.com/pytorch/xla/blob/master/contrib/colab/resnet18-training-xrt-1-15.ipynb) for parallel training. I am not sure when network weights are synced across the devices, is it at `barrier=True`. And also I am using two networks but barrier is at the last stage. Will all the networks still be synced?

**Comment by dlibenzi** [comment]
PyTorch/XLA design introduces Lazy Tensors:

https://github.com/pytorch/xla/blob/master/API_GUIDE.md#xla-tensors-are-lazy

The `xm.mark_step()` call makes sure that the IR graph which is built by the Lazy Tensor infrastructure does not get unrolled across training steps. It is what we refer to as `barrier`.

You do not need `barrier=True` if you are using the parallel loader, as that is done automatically by it:

https://github.com/pytorch/xla/blob/0926885dc187ff7bbfccf8d9398d5eddb91592f1/torch_xla/distributed/parallel_loader.py#L34

From I can gather from the error above, there is an attempt to do replication with one single device.
If you want to use a single device (hence non replicated), set `nprocs=1` at this level:

https://github.com/pytorch/xla/blob/0926885dc187ff7bbfccf8d9398d5eddb91592f1/test/test_train_mp_mnist.py#L181

**Comment by Tylersuard** [comment]
@NaxAlpha I'm getting an error when running your linked notebook:
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 116, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 109, in _setup_replication
    xm.set_replication(str(device), [str(device)])
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 200, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 187, in xla_replication_devices
    .format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8

**Comment by dlibenzi** [comment]
It is calling XLA functions at global scope, together with multi-processing, which is not allowed.
I'd just move the XLA function calls (the device get is one) inside the xmp.spawn() target function call stack.

**Comment by NaxAlpha** [comment]
@Tylersuard As mentioned by @dlibenzi, there is a bug in my code which gets the wrong device potentially locking the code to single TPU code. I ll look into the bug and share the update once it is fixed.

**Comment by Tylersuard** [comment]
Thank you!  It would be a huge help to me.

**Comment by foobar8675** [comment]
@NaxAlpha , did you ever get it working? I stumbled across this bug looking into getting lucidrains code to work on tpus.

**Comment by NaxAlpha** [comment]
The main issue was calling xm.device locks with single tpu core and
disables using multiple devices. The solution would be to wrap up entire
setup into a single function and than use xmp.spawn

**Comment by foobar8675** [comment]
@NaxAlpha that is great. thank you. Just out of curiosity, did you do the implementation? I'm just curious as to if there were any unexpected surprises.
