### ISSUE TITLE
RuntimeError Unimplemented thrown 

### ISSUE THREAD

**Issue by leogao2** [pytorch/xla#1657]
## To Reproduce

1. Using https://github.com/lucidrains/reformer-pytorch
2. Replace all `.type(xyz.type())` in reformer_pytorch.py with `.type_as(xyz)` (xla throws an error if this isn't changed)
3. Try to run reformer_pytorch with XLA:
```
# relevant code

import reformer_pytorch

import os
os.environ['XLA_SYNC_WAIT'] = '1'

# imports pytorch
import torch

# imports the torch_xla package
import torch_xla
import torch_xla.core.xla_model as xm

dev = xm.xla_device()

model = reformer_pytorch.ReformerLM(
    num_tokens = 1000, # vocab size
    dim = 1024,  # embed dim
    depth = 12, # layers
    max_seq_len = 4096, # ctx len
    heads = 8,
    lsh_dropout = 0.1,
    emb_dim = 128,        # embedding factorization for further memory savings
    causal = True,        # auto-regressive or not
    bucket_size = 64,     # average size of qk per bucket, 64 was recommended in paper
    n_hashes = 4,         # 4 is permissible per author, 8 is the best but slower
    ff_chunks = 200,      # number of chunks for feedforward layer, make higher if there are memory issues
    weight_tie = False,   # tie parameters of each layer for no memory per additional depth
    attn_chunks = 8,        # process lsh attention in chunks, only way for memory to fit when scaling to 16k tokens
    num_mem_kv = 128,       # persistent learned memory key values, from all-attention paper
    twin_attention = False, # both branches of the reversible network will be attention
    use_full_attn = False,  # use full self attention, for comparison
    full_attn_thres = 1, # use full attention if context length is less than set value
    use_scale_norm = False,  # use scale norm from 'Transformers without tears' paper
).to(dev)

x = torch.randint(0, 999, (1, 4096)).to(dev)
y = model(x)
print(y)
```

```

RuntimeError: Unimplemented: From /job:tpu_worker/replica:0/task:0:
While rewriting computation to not contain X64 element types, XLA encountered an HLO for which this rewriting is not implemented: %sort.5728 = (s64[3,16896]{1,0}, s32[3,16896]{1,0}) sort(s64[3,16896]{1,0} %add.5720, s32[3,16896]{1,0} %iota.5721), dimensions={1}, to_apply=%compare-less-than.5722
	 [[{{node XRTCompile}}]]
```

The stack trace shows that the error happens in a Linear layer:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-71941de8e7c6> in <module>()
     76     
     77     x = torch.randint(0, 999, (1, 4096)).to(dev)
---> 78     y = model(x)
     79     print(y)
     80     # other code

20 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, **kwargs)
    550 
    551         x = self.to_model_dim(x)
--> 552         x = self.reformer(x, **kwargs)
    553         return self.to_logits(x)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, **kwargs)
    530         x = torch.cat([x, x], dim = -1)
    531         self.set_reversible_args(**kwargs)
--> 532         x = self.layers(x)
    533         return torch.stack(x.chunk(2, dim=-1)).sum(dim=0)
    534 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/revtorch/revtorch.py in forward(self, x)
    197         :return: Output tensor
    198         '''
--> 199         x = _ReversibleModuleFunction.apply(x, self.reversible_blocks, self.eagerly_discard_variables)
    200         return x

/usr/local/lib/python3.6/dist-packages/revtorch/revtorch.py in forward(ctx, x, reversible_blocks, eagerly_discard_variables)
    144         for block in reversible_blocks:
    145             assert (isinstance(block, ReversibleBlock))
--> 146             x = block(x)
    147         ctx.y = x.detach() #not using ctx.save_for_backward(x) saves us memory by beeing able to free ctx.y earlier in the backward pass
    148         ctx.reversible_blocks = reversible_blocks

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/revtorch/revtorch.py in forward(self, x)
     49             y1 = x1 + self.f_block(x2)
     50             self._init_seed('g')
---> 51             y2 = x2 + self.g_block(y1)
     52 
     53         return torch.cat([y1, y2], dim=self.split_along_dim)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x)
     95     def forward(self, x):
     96         chunks = x.chunk(self.chunks, dim = self.dim)
---> 97         return torch.cat([self.fn(c) for c in chunks], dim = self.dim)
     98 
     99 class SettableArgs(nn.Module):

/usr/local/lib/python3.6/dist-packages/reformer_pytorch/reformer_pytorch.py in <listcomp>(.0)
     95     def forward(self, x):
     96         chunks = x.chunk(self.chunks, dim = self.dim)
---> 97         return torch.cat([self.fn(c) for c in chunks], dim = self.dim)
     98 
     99 class SettableArgs(nn.Module):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x)
     84     def forward(self, x):
     85         x = self.norm(x)
---> 86         return self.fn(x)
     87 
     88 class Chunk(nn.Module):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x)
    483 
    484     def forward(self, x):
--> 485         return self.net(x)
    486 
    487 # reformer lm

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py in forward(self, input)
     98     def forward(self, input):
     99         for module in self:
--> 100             input = module(input)
    101         return input
    102 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py in forward(self, input)
     85 
     86     def forward(self, input):
---> 87         return F.linear(input, self.weight, self.bias)
     88 
     89     def extra_repr(self):

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in linear(input, weight, bias)
   1377         ret = torch.addmm(bias, input, weight.t())
   1378     else:
-> 1379         output = input.matmul(weight.t())
   1380         if bias is not None:
   1381             output += bias
```

## Environment

 - torch_xla version: 0.8+b06662c
 - Colab

## Additional context

N/A

**Comment by dlibenzi** [comment]
Yeah, the support for XLA %sort op for 64bit integers is very limited.
You can try to either cast around the pytorch op that generated the sort to Int and then back to Long, or use:
```Shell
export XLA_USE_32BIT_LONG=1
```

**Comment by leogao2** [comment]
Thanks! That seems to solve the error, but now it seems to be running incredibly slow (a single model call has not completed in half an hour now, much slower than on gpu).

**Comment by dlibenzi** [comment]
It is probably recompiling.
Can you run a few steps using debug_run and post the targz?

https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information

**Comment by leogao2** [comment]
Here is the file:

https://drive.google.com/file/d/1r2T4UzmysxI-VvnjYcGSCro23tI-9E9m/view?usp=sharing

(I ran it with a scaled-down version to get a result within a reasonable amount of time)

**Comment by dlibenzi** [comment]
Did you strip the metrics out of the report?
Those would have helped.

In any case, there seem to be item() (or equivalent) calls at that stack frame below.
```
Frame has 256 graph(s) (256 unique):                                                                                    
  __format__ (/usr/local/lib/python3.6/dist-packages/torch/tensor.py:418)                                               
  __init__ (/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py:83)                                             
  _tensor_str (/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py:209)                                         
  _str (/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py:311)                                                
  __repr__ (/usr/local/lib/python3.6/dist-packages/torch/tensor.py:162)                                                 
  <module> (test.py:49)                                                                                                 
                                                                                                                        
  Frame 254 (len=11, count=1, id=254) vs 255 (len=11, count=1, id=255)                                                  
  --- frame-254                                                                                                         
  +++ frame-255                                                                                                         
  @@ -5,7 +5,7 @@                                                                                                       
     s32[1,256]{1,0} xla::as_strided_view_update(?, ?), location=__format__@tensor.py:418, size=[1, 256], storage_offse\
t=0                                                                                                                     
     s32[1,256]{1,0} aten::as_strided(?), location=__format__@tensor.py:418, size=[1, 256], storage_offset=0            
     s32[256]{0} aten::view(?), location=__format__@tensor.py:418, output_size=(256)                                    
  -  s32[1]{0} xla::generic_slice(?), location=__format__@tensor.py:418, base_indices=(254), sizes=(1)                  
  +  s32[1]{0} xla::generic_slice(?), location=__format__@tensor.py:418, base_indices=(255), sizes=(1)                  
     s32[] aten::view(?), location=__format__@tensor.py:418, output_size=(), ROOT=0                                     
   } 
```

**Comment by leogao2** [comment]
No, I haven't changed anything from running the command provided on the troubleshooting page.

I'm not sure how to interpret this stack frame and locate the item() call. A quick cursory search over the reformer_pytorch code turns up no item() calls, so I'm not sure what to do from here.

**Comment by dlibenzi** [comment]
Hmm, this is what a debug_run folder should look like:
```
drwxr-x---  2 user group     4096 Feb 23 05:42 graphdir/
-rw-r-----  1 user group   149480 Feb 23 05:42 graph_report
-rw-r-----  1 user group 13133770 Feb 23 05:42 graphs
-rw-r-----  1 user group   172108 Feb 23 05:42 logs
-rw-r-----  1 user group   828692 Feb 23 05:42 metrics
drwxr-x---  2 user group     4096 Feb 23 05:42 metrics_imgdir/
-rw-r-----  1 user group    69588 Feb 23 05:42 metrics_report
```

Your is missing all the metrics, which can tell us information about the source of `item()` or similar calls.

**Comment by leogao2** [comment]
It seems like the code isn't running to completion because of an error and thus not writing all the data to the debug_run (?):
```
2020-02-23 16:30:58.618250: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: input_shape.dimensions(i) == index_shape.dimensions(i) (264 vs. 1056)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	xla::XlaBuilder::ReportErrorOrReturn(std::function<stream_executor::port::StatusOr<xla::XlaOp> ()> const&)
	torch_xla::CreateScatter(xla::XlaOp, xla::XlaOp, xla::XlaOp, long long, std::function<xla::XlaOp (xla::XlaOp, xla::XlaOp)> const&)
	torch_xla::ir::ops::ScatterAdd::Lower(torch_xla::ir::LoweringContext*) const
	torch_xla::ir::LoweringContext::LowerNode(torch_xla::ir::Node const*)
	torch_xla::ir::LoweringContext::GetOutputOp(torch_xla::ir::Output const&)
	torch_xla::XLATensor::Compile(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> > const&, absl::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch_xla::XLATensor::SyncTensorCollection const&)
	torch_xla::XLATensor::SyncTensorsGraphInternal(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*, absl::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch_xla::XLATensor::SyncTensorsConfig const&)
	torch_xla::XLATensor::SyncTensorsGraph(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*, absl::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, bool, bool)
	torch_xla::XLATensor::SyncLiveTensorsGraph(torch_xla::Device const*, absl::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, bool)
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	PyEval_EvalCode
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main
	_start
*** End stack trace ***
```
The exact same code works perfectly fine on cpu.

**Comment by dlibenzi** [comment]
Something is off, IR graph wise:

```
  %1463 = s32[4,1056,2]{2,1,0} aten::expand(%1462), location=batched_index_select@reformer_pytorch.py:26, size=[4, 1056, 2]
  ...
  %2515 = f32[4,1056,2]{2,1,0} aten::view(%2514), location=backward@__init__.py:99, output_size=(4, 1056, 2)
  %2516 = f32[] prim::Constant(), location=backward@__init__.py:99, value=0
  %2517 = f32[4,264,2]{2,1,0} aten::expand(%2516), location=backward@__init__.py:99, size=[4, 264, 2]
  %2518 = f32[4,264,2]{2,1,0} aten::scatter_add(%2517, %1463, %2515), location=backward@__init__.py:99, dim=1
```

Do you mind printing the shapes of `values` and `indices` when entering here?

https://github.com/lucidrains/reformer-pytorch/blob/3c370fe4aa992eed7bebf0eca44217bcebd333fd/reformer_pytorch/reformer_pytorch.py#L24

So we can write a test in our code ...

**Comment by dlibenzi** [comment]
The issue looks like to be in the backward code though.
The target of the scatter_add is a zero expanded to a wrong shape [4,264,2] instead of [4,1056,2].

**Comment by dlibenzi** [comment]
Oh, I see, we need to fix our `scatter_add()`:
```
self, index and other should have same number of dimensions. It is also required that index.size(d) <= other.size(d) for all dimensions d, and that index.size(d) <= self.size(d) for all dimensions d != dim.
```

_index.size(d) <= self.size(d) **for all dimensions d != dim**_

**Comment by dlibenzi** [comment]
Dense Scatter needs fixing. Sparse is OK.

**Comment by dlibenzi** [comment]
https://github.com/pytorch/xla/pull/1679 should fix the `scatter_add()`, although, this was not the original issue in this thread.

**Comment by leogao2** [comment]
It runs to completion this time and the debug_run seems to be populated:

https://drive.google.com/file/d/1dG1TKT4m_RSvrLjSmooyR3QKF8z3ZkmY/view?usp=sharing

**Comment by leogao2** [comment]
Might it have to do with me printing out the result tensor (`print(y)`) after each iteration to force syncing? I'm not sure if that explains each iteration itself taking ages though. 

Also, any ideas how to check that? I can't find any direct calls to __format__ anywhere in the library.

**Comment by dlibenzi** [comment]
No, that must be an inner loop.
You have done only 3 steps, and 906 item() calls.

**Comment by dlibenzi** [comment]
That is coming from `<module> (test.py:50)`

**Comment by dlibenzi** [comment]
And here:

https://github.com/pytorch/pytorch/blob/2eb95d8f4a1717cc93b1c63a02d1d51117bfde88/torch/tensor.py#L162
https://github.com/pytorch/pytorch/blob/2eb95d8f4a1717cc93b1c63a02d1d51117bfde88/torch/_tensor_str.py#L315
https://github.com/pytorch/pytorch/blob/2eb95d8f4a1717cc93b1c63a02d1d51117bfde88/torch/_tensor_str.py#L213
https://github.com/pytorch/pytorch/blob/2eb95d8f4a1717cc93b1c63a02d1d51117bfde88/torch/_tensor_str.py#L84

**Comment by leogao2** [comment]
Here is the content of test.py (slightly different from the code in my original post):
```

import os
os.environ['XLA_USE_32BIT_LONG'] = '1'

# imports pytorch
import torch

# imports the torch_xla package
import torch_xla
import torch_xla.core.xla_model as xm

dev = xm.xla_device()

import torch
import torch.nn.functional as F
import torch.optim as optim

import numpy as np
import reformer_pytorch
from dotdict import dotdict
from tqdm import tqdm

config = dotdict(
    num_tokens = 100, # vocab size
    dim = 8,  # embed dim
    depth = 3, # layers
    max_seq_len = 256, # ctx len
    heads = 4,
    lsh_dropout = 0.1,
    emb_dim = 128,        # embedding factorization for further memory savings
    causal = True,        # auto-regressive or not
    bucket_size = 4,     # average size of qk per bucket, 64 was recommended in paper
    n_hashes = 4,         # 4 is permissible per author, 8 is the best but slower
    ff_chunks = 1,      # number of chunks for feedforward layer, make higher if there are memory issues
    weight_tie = False,   # tie parameters of each layer for no memory per additional depth
    attn_chunks = 1,        # process lsh attention in chunks, only way for memory to fit when scaling to 16k tokens
    num_mem_kv = 8,       # persistent learned memory key values, from all-attention paper
    twin_attention = False, # both branches of the reversible network will be attention
    use_full_attn = False,  # use full self attention, for comparison
    full_attn_thres = 1, # use full attention if context length is less than set value
    use_scale_norm = False,  # use scale norm from 'Transformers without tears' paper
)
batch_size = 2
model = reformer_pytorch.ReformerLM(**config).to(dev)
opt = optim.Adam(model.parameters(), lr=3e-5)

for i in range(3):
  opt.zero_grad()
  x = torch.randint(0, 100, (1, 256)).to(dev)
  print(x)
  y = F.log_softmax(model(x), dim=-1)
  print(y)

  loss = F.nll_loss(y.reshape(y.shape[0] * y.shape[1], -1)[:-1], x.reshape(x.shape[0] * x.shape[1])[1:])
  loss.backward()
  print('LOSS ======================', loss)

  xm.optimizer_step(opt, barrier=True)
```

**Comment by leogao2** [comment]
Printing the trace from tensor.py#L416, for each iteration I get many (dozens) repetitions of the following trace:
```
    print(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 162, in __repr__
    return torch._tensor_str._str(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 315, in _str
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 213, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 84, in __init__
    value_str = '{}'.format(value)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 418, in __format__
    traceback.print_stack()
```

Followed by many of this trace:
```
  File "test.py", line 52, in <module>
    print(y)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 162, in __repr__
    return torch._tensor_str._str(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 315, in _str
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 213, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.6/dist-packages/torch/_tensor_str.py", line 127, in __init__
    value_str = ('{{:.{}f}}').format(PRINT_OPTS.precision).format(value)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 418, in __format__
    traceback.print_stack()
```

I can't seem to find any other different traces.

**Comment by ailzhang** [comment]
@leogao2 Yes printing tensors in the middle of training will result in graph evaluation and slows down a lot. Removing them is definitely recommended after you're done with debugging. 

Do you have a updated metrics report after you removed the print statements? That'll tell us what's slowing things down.

**Comment by dlibenzi** [comment]
I'd start with removing the print, and doing the export:
```Shell
export XLA_EXPERIMENTAL="masked_select"
```
Your model has dynamic shapes, so it would be interesting to see what debug_run output look like once you removed the print and exported the above variable.
You should be left with `normal_` which we are fixing it.

**Comment by leogao2** [comment]
Ok, I've removed all the prints (even the one for the loss), and added the environment variable. Here's the new debug_run:

[debug_run_3.tar.gz](https://github.com/pytorch/xla/files/4263988/debug_run_3.tar.gz)

**Comment by leogao2** [comment]
I've removed all the prints and added the export:
[debug_run_3.tar.gz](https://github.com/pytorch/xla/files/4263999/debug_run_3.tar.gz)

**Comment by dlibenzi** [comment]
It seems to have stabilized, compilation wise.
You are going to pytorch CPU due to `normal_()` but that should be fixed today or tomorrow.

Do the results look OK?

**Comment by leogao2** [comment]
It still seems to be running unbearably slow. Here's the new debug_run with a slightly larger model:
[debug_run_4.tar.gz](https://github.com/pytorch/xla/files/4339567/debug_run_4.tar.gz)

**Comment by dlibenzi** [comment]
You have done only 3 steps.
Can you try letting run for 50..10 steps?

**Comment by leogao2** [comment]
Here is a 50 step run:

[debug_run_5.tar.gz](https://github.com/pytorch/xla/files/4340218/debug_run_5.tar.gz)

**Comment by dlibenzi** [comment]
Oh, I see. The normal distribution it's getting different seeds:
```
  -  f32[1,8,4,33]{3,2,1,0} aten::normal(?, ?), location=hash_vectors@reformer_pytorch.py:168, seed=16174198708314942886
  +  f32[1,8,4,33]{3,2,1,0} aten::normal(?, ?), location=hash_vectors@reformer_pytorch.py:168, seed=18288375882524214872
```
Which change the graph's hashes.

**Comment by dlibenzi** [comment]
Not a solution, but can you try adding `torch.manual_seed(SOME_SEED)` inside the training step?

**Comment by dlibenzi** [comment]
Also, does the randomness need to happen at every step?
Can you create the normal into a CPU tensor outside the training loop, and use that instead of the normal() op?

**Comment by leogao2** [comment]
The randomness is a placeholder for a future data loading operation. I'm not sure if these suggestions will still apply for actual data loading.

**Comment by dlibenzi** [comment]
I am not sure I parse that, but while we are working on this, can you try to see if that fixes your issue?

**Comment by dlibenzi** [comment]
This should stabilize the graphs: https://github.com/pytorch/xla/pull/1770
