### ISSUE TITLE
Error while lowering: f32[32,24,112,112]{3,2,1,0} aten::mul Error: torch_xla/csrc/convert_ops.cpp:49 : Unsupported XLA type 12

### ISSUE THREAD

**Issue by Gopi-Durgaprasad** [pytorch/xla#1725]
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-0fbd56f1832d> in <module>()
    356 
    357 if __name__ == "__main__":
--> 358     main()

3 frames
<ipython-input-17-0fbd56f1832d> in main()
    326     for epoch in range(start_e, EPOCHS+1):
    327 
--> 328         train_loss, train_score = train(train_dataset,train_loader, model, optimizer, epoch)
    329         val_loss, val_score = evaluate(valid_dataset, valid_loader, model)
    330 

<ipython-input-17-0fbd56f1832d> in train(dataset, data_loader, model, optimizer, epoch)
    196         loss.backward()
    197         #optimizer.step()
--> 198         xm.optimizer_step(optimizer, barrier=True)
    199 
    200         final_loss += loss

/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py in optimizer_step(optimizer, barrier, optimizer_args)
    450   loss = optimizer.step(**optimizer_args)
    451   if barrier:
--> 452     mark_step()
    453   return loss
    454 

/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py in mark_step()
    406   torch_xla._XLAC._xla_step_marker(
    407       torch_xla._XLAC._xla_get_default_device(), [],
--> 408       wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
    409   # Only emit metrics from the first local device index, to avoid emitting the
    410   # same values from different threads.

RuntimeError: Error while lowering: f32[32,24,112,112]{3,2,1,0} aten::mul
Error: torch_xla/csrc/convert_ops.cpp:49 : Unsupported XLA type 12
Python Frames:
```

**Comment by TaridaGeorge** [comment]
I have a similar problem: Unsupported XLA type 10 while trying to train wav2vec2.0

`Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.6/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/hydra_train.py", line 91, in cli_main
    hydra_main()
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/distributed/utils.py", line 361, in call_main
    main(cfg, **kwargs)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/train.py", line 143, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/train.py", line 206, in train
    itr = utils.tpu_data_loader(itr)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/utils.py", line 673, in tpu_data_loader
    xm.mark_step()
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Error while lowering: f32[768]{0} xla::cast, location=build_fp32_params@fp16_optimizer.py:66, type=f32, dtype=Float, stype=Half
Error: torch_xla/csrc/convert_ops.cpp:84 : Unsupported XLA type 10
Python Frames:
  build_fp32_params (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/optim/fp16_optimizer.py:66)
  build_optimizer (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/optim/fp16_optimizer.py:289)
  _build_optimizer (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/trainer.py:239)
  lr_scheduler (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/trainer.py:214)
  lr_step (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/trainer.py:849)
  load_checkpoint (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/trainer.py:401)
  load_checkpoint (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/checkpoint_utils.py:201)
  main (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/train.py:126)
  call_main (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/distributed/utils.py:361)
  hydra_main (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/hydra_train.py:45)
  run_job (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/core/utils.py:127)
  run (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/hydra.py:112)
  <lambda> (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py:350)
  run_and_report (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py:198)
  _run_hydra (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py:347)
  decorated_main (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/main.py:37)
  cli_main (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/hydra_train.py:91)
  <module> (/anaconda3/envs/torch-xla-1.6/bin/fairseq-hydra-train:33)`

**Comment by taylanbil** [comment]
@TaridaGeorge [here's a working branch](https://github.com/taylanbil/fairseq/commits/w2v2_rebased) of wav2vec2.0

**Comment by TaridaGeorge** [comment]
@taylanbil which branch?

**Comment by TaridaGeorge** [comment]
using w2v2_rebased I get this error:

```
2021-02-12 02:36:21,798][fairseq_cli.train][INFO] - Start iterating over samples
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq_cli/hydra_train.py", line 91, in cli_main
    hydra_main()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq/distributed/utils.py", line 364, in call_main
    main(cfg, **kwargs)
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq_cli/train.py", line 143, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq_cli/train.py", line 244, in train
    log_output = trainer.train_step(samples)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq/trainer.py", line 588, in train_step
    raise e
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq/trainer.py", line 562, in train_step
    ignore_grad=is_dummy_batch,
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq/tasks/fairseq_task.py", line 476, in train_step
    optimizer.backward(loss)
  File "/home/tarida_george/saa-am-builder/vendor/fairseq/fairseq/optim/fairseq_optimizer.py", line 95, in backward
    loss.backward()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [XLAFloatType [192, 768, 1, 58]], which is output 0 of UnsqueezeBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by taylanbil** [comment]
@TaridaGeorge let s keep this issue as is, and discuss the crash in a separate issue. could you open a new issye with more info, such as instructions to repro, when the crash hapoens etc.
