### ISSUE TITLE
TPU throws error until restart

### ISSUE THREAD

**Issue by bkkaggle** [pytorch/xla#1731]
## 🐛 Bug

Pytorch xla will throw an error every time you run a multiprocessing training script after cancelling a multiprocessing training script using `ctrl-c` until you restart the Cloud TPU. 

## To Reproduce

1. Run a script on a TPU with multiprocessing
2. Ctrl-c to stop execution of the script
3. Try running the script a second time, it will throw an error
4. Shutdown the Cloud TPU and start it again.
5. Run the script, it will work

Stack trace:

```
2020-03-06 21:12:24.724923: E    2858 tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Internal: From /job:tpu_worker/replica:0/task:0:
Global core array does not contain host cores [0x0x0_TC0,0x0x0_TC1,1x0x0_TC0,1x0x0_TC1,0x1x0_TC0,0x1x0_TC1,1x1x0_TC0,1x1x0_TC1]
	 [[{{node configure_distributed_tpu/_0}}]] vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::XrtComputationClient::InitializeAndFetchTopology(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::ConfigProto const&)
	xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::ComputationClient::Create()
	xla::ComputationClient::Get()
	
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main
	
*** End stack trace ***


wandb: Waiting for W&B process to finish, PID 2881
wandb: Program failed with code 17. Press ctrl-c to abort syncing.
Exception in device=TPU:0: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1198 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Internal: From /job:tpu_worker/replica:0/task:0:
Global core array does not contain host cores [0x0x0_TC0,0x0x0_TC1,1x0x0_TC0,1x0x0_TC1,0x1x0_TC0,0x1x0_TC1,1x1x0_TC0,1x1x0_TC1]
	 [[{{node configure_distributed_tpu/_0}}]] vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::XrtComputationClient::InitializeAndFetchTopology(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::ConfigProto const&)
	xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::ComputationClient::Create()
	xla::ComputationClient::Get()
	
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main
	
*** End stack trace ***

Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 119, in _start_fn
    fn(gindex, *args)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 474, in tpu_train
    model.to(xm.xla_device())
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 137, in xla_device
    devkind=[devkind] if devkind is not None else None)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 41, in get_xla_supported_devices
    xla_devices = torch_xla._XLAC._xla_get_devices()
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1198 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Internal: From /job:tpu_worker/replica:0/task:0:
Global core array does not contain host cores [0x0x0_TC0,0x0x0_TC1,1x0x0_TC0,1x0x0_TC1,0x1x0_TC0,0x1x0_TC1,1x1x0_TC0,1x1x0_TC1]
	 [[{{node configure_distributed_tpu/_0}}]] vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::XrtComputationClient::InitializeAndFetchTopology(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::ConfigProto const&)
	xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
	xla::ComputationClient::Create()
	xla::ComputationClient::Get()
	
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	_PyObject_FastCallDict
	_PyObject_Call_Prepend
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main
	
*** End stack trace ***

```

## Expected behavior

You should be able to ctrl-c a training script without having to restart the TPU

## Environment

 - reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly
- on a Google cloud TPU v3-8 
- Can't reproduce error on colab

**Comment by zcain117** [comment]
You might also want to try `pkill -9 python` or something similar to make sure all the Python process are done from your previous run. Sometimes we see stragglers

**Comment by dlibenzi** [comment]
We rely on pytorch multiprocessing, which tries to prevent this (sets `PR_SET_PDEATHSIG`):

https://github.com/pytorch/pytorch/blob/079de7f376ebaa104dde35f2b4c48afa0e2ba7e9/torch/multiprocessing/spawn.py#L17

I think the issue might be related to how Colab processes are handled.
For example, if the parent process does not die, the child will not get the death sig (SIGINT), and they will not terminate.

**Comment by bkkaggle** [comment]
The error happens on Colab and GCP with a n1-standard-8 vm and a v3-8 TPU. The error happens even if nprocs = 1.

The error only started happening in the last week, so would following the instructions [here](https://github.com/pytorch/xla#-consume-prebuilt-docker-images) to install an older version of pytorch xla on the vm and the cloud tpu work?

**Comment by dlibenzi** [comment]
You can try rolling back, but I think it won't change.
Like Zach mentioned, you can check, after hitting CTRL^C, that there are still the old processes lingering, and keeping TPU cores bound.
I think that, if you really have to use CTRL^C, you need to make sure to kill existing lingering TPU processes.
In GCP, you can try setting start_method=spawn (or not setting it at all).

**Comment by bkkaggle** [comment]
I checked using `start_method=spawn`, using a version of pytorch/xla from March 1st, and killing all python processes with `pkill -9 python`. 

I'm pretty sure there aren't any python TPU processes still remaining after ctrl-c'ing the script:
```
$ ps -ef | grep python
root       867     1  0 Mar08 ?        00:00:00 /usr/bin/python3 /usr/bin/google_network_daemon
root       869     1  0 Mar08 ?        00:00:00 /usr/bin/python3 /usr/bin/google_accounts_daemon
root       870     1  0 Mar08 ?        00:00:00 /usr/bin/python3 /usr/bin/google_clock_skew_daemon
bilal     3218  2805  0 00:10 pts/0    00:00:00 grep python
```

**Comment by dlibenzi** [comment]
I have tried in my VM using:
```Shell
python test/test_train_mp_mnist.py
```
When I hit `CTRL^C` I can end up in two different states.
No lingering processes, or with lingering processes (this happens if I hit `CTRL^C` twice).
In the latter case, if I issue `pkill -9 python`, I can restart the training every single time.
How is your script run?
Does it use `python SCRIPT ...` explicitly?

**Comment by dlibenzi** [comment]
OK, now I got it into that state.
But after I got the latest nightly for the TPU VM.
Might be a regression there.

**Comment by dlibenzi** [comment]
Filed a bug internally.

**Comment by dlibenzi** [comment]
There was a bug introduced by a CL which was reverted yesterday.
Hopefully today's nightly builds will capture it.
Sorry about that.

**Comment by jysohn23** [comment]
Just verified that today's nightly does capture the fix. Thanks!
