### ISSUE TITLE
1.5 install on old VM

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#1954]
## 📚 Documentation

Are there any additional dependencies etc. that I need to take into account when installing 1.5 on a VM where I've used nightlies before, i.e. can I just pip install from git? 

I'd prefer to use my old VM instead of creating a new one, but I also tried to create a new VM and apparently the Debian GNU/Linux 9 Stretch + PyTorch/XLA is gone from the dropdown menu :/

**Comment by harpone** [comment]
Uhh I mean installing from the wheels... but I guess this will be fine(?). Would be nice to have updated docs btw.

**Comment by harpone** [comment]
OK not working... getting

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/anaconda3/envs/torch-xla-1.5/lib/python3.6/site-packages/torch_xla/__init__.py", line 41, in <module>
    import _XLAC
ImportError: /anaconda3/envs/torch-xla-1.5/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6native6einsumENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEN3c108ArrayRefINS_6TensorEEE
```
