### ISSUE TITLE
Exception on a TPU worker after several hours of training

### ISSUE THREAD

**Issue by harpone** [pytorch/xla#1973]
## 🐛 Bug

Everything is working fine for several hours, then getting an exception:

```
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	xla::XrtComputationClient::GetWorkerForXrtDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
	xla::XrtComputationClient::GetSessionForXrtDevice(xla::XrtSessionCache*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xla::XrtSessionCache::Ref, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, xla::XrtSessionCache::Ref> > >*)
	
	
	
	
	
	clone
*** End stack trace ***
/job:tpu_worker/replica:0/task:0/device:TPU:2
Exception in thread Thread-66:
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py", line 165, in _worker
    batch = xm.send_cpu_data_to_device(batch, device)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 518, in send_cpu_data_to_device
    return ToXlaTensorArena(convert_fn, select_fn).transform(data)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 290, in transform
    self._convert()
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 262, in _convert
    self._converted_tensors = self._convert_fn(self._tensors)
  File "/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 513, in convert_fn
    return torch_xla._XLAC._xla_tensors_from_aten(tensors, devices)
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:164 : Check failed: tensorflow::DeviceNameUtils::ParseFullName(device, &parsed_device) && parsed_device.has_job && parsed_device.has_task && parsed_device.has_id && parsed_device.has_type 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	xla::XrtComputationClient::GetWorkerForXrtDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
	xla::XrtComputationClient::GetSessionForXrtDevice(xla::XrtSessionCache*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xla::XrtSessionCache::Ref, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, xla::XrtSessionCache::Ref> > >*)
	
	
	
	
	
	clone
*** End stack trace ***
/job:tpu_worker/replica:0/task:0/device:TPU:2

```

## To Reproduce

Can't really post a repro, but hoping instead that someone experienced with XLA would be able to spot what's going on (maybe just TPU OOM, although not getting that specifically).

## Environment

 - Reproducible on XLA backend: TPU
 - torch_xla version: 1.5

**Comment by dlibenzi** [comment]
That seems odd as the TF device name looks correct.
Moreover, as error parsing a TF device string would have shown up at app start time, more than after hours.

**Comment by harpone** [comment]
Maybe it's faulty hardware? I'll try running on a different TPU machine...

**Comment by dlibenzi** [comment]
It is a really strange error for sure.
The printed TF device name `/job:tpu_worker/replica:0/task:0/device:TPU:2` is valid and matches the constraints required by the check.

**Comment by harpone** [comment]
Haven't been getting these after updating the VM so closing.
