### ISSUE TITLE
multicore training on kaggle gives error

### ISSUE THREAD

**Issue by apthagowda97** [pytorch/xla#1995]
When I tried to run this code 
```
def simple_map_fn(rank, flags):
  torch.manual_seed(1234)
  device = xm.xla_device()  
  print("Process", rank ,"is using", xm.xla_real_devices([str(device)])[0])
  xm.rendezvous('init')
flags = {}
xmp.spawn(simple_map_fn, args=(flags,), nprocs=8, start_method='fork')
```
I am getting the below error on kaggle.
```
Exception in device=TPU:3: tensorflow/compiler/xla/xla_client/mesh_service.cc:247 : Failed to meet rendezvous 'init': Socket closed (14)
Exception in device=TPU:4: tensorflow/compiler/xla/xla_client/mesh_service.cc:247 : Failed to meet rendezvous 'init': Socket closed (14)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 225, in _start_fn
Exception in device=TPU:6: tensorflow/compiler/xla/xla_client/mesh_service.cc:247 : Failed to meet rendezvous 'init': Socket closed (14)
Exception in device=TPU:7: tensorflow/compiler/xla/xla_client/mesh_service.cc:247 : Failed to meet rendezvous 'init': Socket closed (14)
  File "<ipython-input-11-bda6862c29b1>", line 5, in simple_map_fn
    xm.rendezvous('init')
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 225, in _start_fn
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 225, in _start_fn
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 614, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload)
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:247 : Failed to meet rendezvous 'init': Socket closed (14)
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 225, in _start_fn
  File "<ipython-input-11-bda6862c29b1>", line 5, in simple_map_fn
    xm.rendezvous('init')
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 614, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload)
  File "<ipython-input-11-bda6862c29b1>", line 5, in simple_map_fn
    xm.rendezvous('init')
  File "<ipython-input-11-bda6862c29b1>", line 5, in simple_map_fn
    xm.rendezvous('init')
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 614, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload)
  File "/opt/conda/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 614, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload)
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:247 : Failed to meet rendezvous 'init': Socket closed (14)
```

**Comment by dlibenzi** [comment]
I have tried this in Google Cloud TPU and it worked.

Is that repeatable every time you run it?
Did you try to restart the runtime?

**Comment by apthagowda97** [comment]
For me, it works perfectly in colab also. But when I tried to run this in Kaggle I am getting this error.
Tried nightly, 20200415, and even 20200325 all have same errors but strangely sometimes the code runs fine ( 1 out of 10 times) in Kaggle.

**Comment by dlibenzi** [comment]
I tried on Kaggle, and yes, I can repro that.

**Comment by apthagowda97** [comment]
A couple of days back Kaggle updated their python from 3.6 to 3.7 at that time xla was not working. Now they rolled back to 3.6  but I am not sure what else they changed.

**Comment by dlibenzi** [comment]
Oh, I think it's a timing issue.
Rank 0 (the mesh master) exits first and closes the master service socket.
If you add something like this, it will fix it (of course, this is not a real fix):
```Python
if rank == 0:
  time.sleep(1)
```

**Comment by apthagowda97** [comment]
Yes, it fixes the issue for now.
