### ISSUE TITLE
TPU instance in "sick" state after interrupting multi-process execution

### ISSUE THREAD

**Issue by hrbigelow** [pytorch/xla#2219]
## ❓ Questions and Help

I wondered, is there some code to trap an interrupt signal to do proper cleanup in a multi-processing context?  Right now, I don't have any, and I frequently need to do Ctrl-m Ctrl-i as part of my development cycle.

I have the following test code:

```
import torch as t
import torch_xla.distributed.xla_multiprocessing as xmp
import torch_xla.core.xla_model as xm


import sys
from sys import stderr
import torch as t
import time


def _map_fn(index):
    t.manual_seed(2507)

    # Acquires the (unique) Cloud TPU core corresponding to this process's index
    pre_dev_time = time.time()
    print(f'Replica {index} acquiring a device...', end='', file=stderr)
    device = xm.xla_device()  
    device_str = xm.xla_real_devices([str(device)])[0]
    elapsed = time.time() - pre_dev_time
    print(f'process {index} acquired {device_str} in {elapsed} seconds', file=stderr) 
    stderr.flush()

    xm.rendezvous('init')


print('Spawning new processes.', file=stderr)
    stderr.flush()
    xmp.spawn(_mp_fn, args=(hps, dat_file), nprocs=8, start_method='fork')
```

In a freshly started TPU instance (under torch_xla nightly), it behaves as expected.  However, after several cycles of running a real application in a Colab, I tried to repeat the test, and it hangs with the following result:

```
Spawning new processes.
Replica 3 acquiring a device...process 3 acquired TPU:3 in 0.00012969970703125 seconds
Replica 6 acquiring a device...process 6 acquired TPU:6 in 0.00012731552124023438 seconds
Replica 5 acquiring a device...process 5 acquired TPU:5 in 0.00013756752014160156 seconds
Replica 4 acquiring a device...process 4 acquired TPU:4 in 0.00016021728515625 seconds
Replica 7 acquiring a device...process 7 acquired TPU:7 in 0.00013375282287597656 seconds
Replica 1 acquiring a device...process 1 acquired TPU:1 in 0.00013947486877441406 seconds
Replica 2 acquiring a device...process 2 acquired TPU:2 in 0.00011682510375976562 seconds

...three minutes elapse...

Exception in device=TPU:3: tensorflow/compiler/xla/xla_client/mesh_service.cc:294 : Failed to meet rendezvous 'init': Duplicate ordinal: 3 (3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "/content/ae-wavenet/train.py", line 43, in _map_fn
    xm.rendezvous('init')
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 679, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload, replicas)
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:294 : Failed to meet rendezvous 'init': Duplicate ordinal: 3 (3)
```
Terminating and restarting the instance fixes it.  I believe that what puts the instance into the "sick" state is to first run a multi-core program, and then interrupt it with Ctrl-m Ctrl-i.  Subsequent tests then return the error as above, or the following error:

```
Spawning new processes.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-6-1ff77a7162b6> in <module>()
     27 print('Spawning new processes.', file=stderr)
     28 stderr.flush()
---> 29 xmp.spawn(_map_fn, args=(), nprocs=8, start_method='fork')

2 frames
/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    117         msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    118         msg += original_trace
--> 119         raise Exception(msg)
    120 
    121 

Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 228, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 220, in _setup_replication
    device = xm.xla_device()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 146, in xla_device
    devkind=[devkind] if devkind is not None else None)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 50, in get_xla_supported_devices
    xla_devices = torch_xla._XLAC._xla_get_devices()
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:259 : Check failed: impl_->channel->WaitForConnected( std::chrono::system_clock::now() + std::chrono::seconds(connect_wait_seconds)) 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::service::MeshClient::MeshClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	xla::service::MeshClient::Get()
	xla::ComputationClient::Create()
	xla::ComputationClient::Get()
	
	
	
	_PyEval_EvalFrameDefault
	

	
...truncated...	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
*** End stack trace ***
Failed to connect to client mesh master: fce341034f1a:60911
```

**Comment by dlibenzi** [comment]
You can try calling this before `xmp.spawn()`:
```Python
import psutil

def _clear_stray_processes():
  curr_proc = psutil.Process()
  curr_cmdline = list(curr_proc.cmdline())
  for proc in psutil.process_iter():
    if proc.pid != curr_proc.pid and proc.cmdline() == curr_cmdline:
      proc.kill()
```

Will see if it makes sense to have it integrated with multi-processing, or at the least as utility API.
