### ISSUE TITLE
torch STFT causes xla training to crash

### ISSUE THREAD

**Issue by btomtom5** [pytorch/xla#2241]
## To Reproduce
Attempt to run stft on an audio sample loaded from torchaudio inside of the target function of a multiprocess xla job. [Colab Notebook](https://colab.research.google.com/drive/15q36fYGdZhHp7qVy2YXyXdQTzklBYdRV?usp=sharing
) for easy reproduction is provided. I expect torch.stft to return a tensor result but it instead crashes the xla master process and its children. This minimal example produces the following error.
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-29-73174769e3d1> in <module>()
----> 1 xmp.spawn(_mp_fn, args=(), nprocs=8, start_method='fork')

2 frames
/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    106                 raise Exception(
    107                     "process %d terminated with signal %s" %
--> 108                     (error_index, name)
    109                 )
    110             else:

Exception: process 0 terminated with signal SIGABRT

**Comment by btomtom5** [comment]
I'm not fully sure if it's related but I found that a more complicated example also breaks when trying to perform a stft but it has a different error code.

However, I found that a more complicated example produced a different error:
```
2020-06-19 00:08:29.077481: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: storage_offset + slice_size <= input_element_count (1310720 vs. 591872)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	torch_xla::ir::ops::AsStrided::Lower(torch_xla::ir::LoweringContext*) const
	torch_xla::ir::LoweringContext::LowerNode(torch_xla::ir::Node const*)
	torch_xla::ir::LoweringContext::LoweringContext(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, torch_xla::Device, absl::lts_2020_02_25::Span<torch_xla::ir::Node const* const>, std::unordered_map<torch_xla::ir::Node const*, torch_xla::ir::Util::EmitStatus, std::hash<torch_xla::ir::Node const*>, std::equal_to<torch_xla::ir::Node const*>, std::allocator<std::pair<torch_xla::ir::Node const* const, torch_xla::ir::Util::EmitStatus> > >)
	torch_xla::XLATensor::Compile(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> > const&, absl::lts_2020_02_25::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch_xla::XLATensor::SyncTensorCollection const&, torch_xla::XLATensor::PostOrderData*)
	torch_xla::XLATensor::SyncTensorsGraphInternal(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*, absl::lts_2020_02_25::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch_xla::XLATensor::SyncTensorsConfig const&)
	torch_xla::XLATensor::GetTensorsFused(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*)
	torch_xla::XLATensor::GetTensors(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*)
	torch_xla::bridge::XlaCreateTensorList(c10::ArrayRef<at::Tensor> const&)
	torch_xla::AtenXlaTypeDefault::_fft_with_size(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long> > >, at::Tensor (at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>)>::call(c10::OperatorKernel*, at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>)
	
	at::_fft_with_size(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>)
	
	
	
	at::_fft_with_size(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>)
	
	at::native::rfft(at::Tensor const&, long, bool, bool)
	
	
	
	
	at::Tensor::rfft(long, bool, bool) const
	at::native::stft(at::Tensor const&, long, c10::optional<long>, c10::optional<long>, at::Tensor const&, bool, bool)
	
	
	
	
	
	at::Tensor::stft(long, c10::optional<long>, c10::optional<long>, at::Tensor const&, bool, bool) const
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	_PyFunction_FastCallDict
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	PyEval_EvalCode
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main
	_start
*** End stack trace ***

Traceback (most recent call last):
  File "/content/fvc-melgans/scripts/tpu_train.py", line 299, in <module>
    xmp.spawn(_mp_fn, args=(), nprocs=8, start_method='fork')
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 296, in spawn
    start_method=start_method)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGSEGV
```

**Comment by dlibenzi** [comment]
The support for `as_strided()` is limited on XLA backend.
The whole `as_strided()` saga is based on the fact that backends have a storage, and one can play tricks with strides and sizes.
XLA is graph based, and even the supported `as_strided()` combinations (aside the trivial ones) require actual mapping to transposes, reshapes, slices, etc...
I suggest o look whether the offending `as_strided()` op can be mapped to some other op combo.

This came up recently as well: https://github.com/pytorch/xla/issues/2238

https://github.com/pytorch/xla/issues/2239

**Comment by jaideep11061982** [comment]
> The support for `as_strided()` is limited on XLA backend. The whole `as_strided()` saga is based on the fact that backends have a storage, and one can play tricks with strides and sizes. XLA is graph based, and even the supported `as_strided()` combinations (aside the trivial ones) require actual mapping to transposes, reshapes, slices, etc... I suggest o look whether the offending `as_strided()` op can be mapped to some other op combo.
> 
> This came up recently as well: #2238
> 
> #2239

@dlibenzi any work around
