### ISSUE TITLE
Trying to install pytorch/xla in a Dockerfile

### ISSUE THREAD

**Issue by zcain117** [pytorch/xla#2242]
My Dockerfile looks like this:

```
FROM google/cloud-sdk:slim

# install versions
ARG PYTHON_VERSION=3.6

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         ca-certificates

# add non-root user
RUN useradd --create-home --shell /bin/bash containeruser
WORKDIR /home/containeruser

# install conda and python
RUN curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /home/containeruser/conda && \
    rm ~/miniconda.sh && \
    /home/containeruser/conda/bin/conda clean -ya && \
    /home/containeruser/conda/bin/conda install -y python=$PYTHON_VERSION

# add conda to path
ENV PATH /home/containeruser/conda/bin:$PATH

RUN pip uninstall -y torch && \
    gsutil cp 'gs://tpu-pytorch/wheels/torch-nightly-cp36-cp36m-linux_x86_64.whl' . && \
    gsutil cp 'gs://tpu-pytorch/wheels/torch_xla-nightly-cp36-cp36m-linux_x86_64.whl' . && \
    gsutil cp 'gs://tpu-pytorch/wheels/torchvision-nightly-cp36-cp36m-linux_x86_64.whl' . && \
    pip install 'torch-nightly-cp36-cp36m-linux_x86_64.whl' && \
    pip install 'torch_xla-nightly-cp36-cp36m-linux_x86_64.whl' && \
    pip install 'torchvision-nightly-cp36-cp36m-linux_x86_64.whl' && \
    apt-get install -y libomp5
CMD ["/bin/bash"]
```

But when I try to use the image:
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/containeruser/conda/lib/python3.6/site-packages/torch/__init__.py", line 188, in <module>
    _load_global_deps()
  File "/home/containeruser/conda/lib/python3.6/site-packages/torch/__init__.py", line 141, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/containeruser/conda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
```

My Dockerfile is trying to mimic the [VM portion of the Colab setup script](https://github.com/pytorch/xla/blob/master/contrib/scripts/env-setup.py#L68)

I tried adding in all of the `conda installs` from the `build_torch_wheels.py` script before running the `pip install` of the downloaded wheels but I still get the same error.

I'll keep investigating

**Comment by dlibenzi** [comment]
We had a conversation about this on Slack. Try to look that up, and see whether that file is present in RPATH.

**Comment by zcain117** [comment]
`libmkl_intel_lp64.so` has come up a few times in Slack:
1. ~June 17: this was fixed by a pytorch PR revert but like we discussed it's probably not affecting this case
2. ~March 3: mentioned briefly but I don't think anyone was seeing an error
3. ~April 28: I think mentioned that installing MKL from conda helped? I tried `conda install mkl` as well but it did not help

I tried setting `LD_LIBRARY_PATH` and got a new error:
```
(containeruser) root@zcain-test5:/# find / -iname libmkl_intel_lp64.so
/opt/conda/lib/libmkl_intel_lp64.so
/opt/conda/pkgs/mkl-2019.5-281/lib/libmkl_intel_lp64.so
/opt/conda/envs/containeruser/lib/libmkl_intel_lp64.so
(containeruser) root@zcain-test5:/# export LD_LIBRARY_PATH=/opt/conda/envs/containeruser/lib(containeruser) root@zcain-test5:/# python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/containeruser/lib/python3.6/site-packages/torch/__init__.py", line 188, in <module>
    _load_global_deps()
  File "/opt/conda/envs/containeruser/lib/python3.6/site-packages/torch/__init__.py", line 141, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/opt/conda/envs/containeruser/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libomp.so.5: cannot open shared object file: No such file or directory
```

Does `libomp.so.5` rely on `LD_LIBRARY_PATH` too or is there another env var or something?

**Comment by dlibenzi** [comment]
```Shell
$ find /opt/conda/envs/ -name libtorch_global_deps.so
```

Then:
```Shell
$ readelf -d PATH_TO_LIB_ABOVE | grep RUNPATH
```

Then check whether `libmkl_intel_lp64.so` is in any of the RUNPATH.

**Comment by zcain117** [comment]
```
(containeruser) root@zcain-test5:/# find root/miniconda3/envs/ -name libtorch_global_deps.so
root/miniconda3/envs/containeruser/lib/python3.6/site-packages/torch/lib/libtorch_global_deps.so

(containeruser) root@zcain-test5:/# readelf -d root/miniconda3/envs/containeruser/lib/python3.6/site-packages/torch/lib/libtorch_global_deps.so | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:/root/anaconda3/envs/pytorch/lib]

(containeruser) root@zcain-test5:/# find root/miniconda3/envs/ -name libmkl_intel_lp64.so
root/miniconda3/envs/containeruser/lib/libmkl_intel_lp64.so
```

**Comment by zcain117** [comment]
ok I had the wrong path plus the wrong version of `libomp`.

These 2 steps fixed me in my local testing VM:
1. export LD_LIBRARY_PATH=root/miniconda3/envs/containeruser/lib
2. apt-get install -y libomp5

Now I can `import torch`. I'll try to recreate all these steps in my Dockerfile

**Comment by zcain117** [comment]
Dockerfile changes:

```
...install conda...
ENV PATH=/root/miniconda3/bin:$PATH
RUN conda create -y --name container python=$PYTHON_VERSION
SHELL ["conda", "run", "-n", "container", "/bin/bash", "-c"]
...gsutil cp wheels and pip install and apt-get install -y libomp5 etc...
ENV LD_LIBRARY_PATH=root/miniconda3/envs/container/lib
...rest of the Dockerfile...
```
