### ISSUE TITLE
Why Failed to retrieve mesh configuration: Connection reset by peer (14)

### ISSUE THREAD

**Issue by sharkdeng** [pytorch/xla#2341]
## ❓ Questions and Help
when I run this code in kaggle tpu, I got this error. Why? thank you.
```
# test if spawn working

def train(rank, flags):
    torch.manual_seed(1234)

    device = xm.xla_device()  
    t = torch.randn((2, 2), device=device)
    
    print("Process", rank ,"is using", xm.xla_real_devices([str(device)])[0])



flags = {}
xmp.spawn(train, args=(flags,), nprocs=8, start_method='fork')
```
The above code is from colab tutorial which run well. Don't know why in kaggle would have this error?

This is the error log

```
Exception in device=TPU:6: tensorflow/compiler/xla/xla_client/mesh_service.cc:331 : Failed to retrieve mesh configuration: Connection reset by peer (14)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 315, in _setup_replication
    device = xm.xla_device()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 231, in xla_device
    devkind=[devkind] if devkind is not None else None)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 136, in get_xla_supported_devices
    xla_devices = _DEVICES.value
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/utils/utils.py", line 32, in value
    self._value = self._gen_fn()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 18, in <lambda>
    _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:331 : Failed to retrieve mesh configuration: Connection reset by peer (14)
```

**Comment by dlibenzi** [comment]
It's a matter of timing.
To to add `xm.rendezvous('exit_from_here')` after the print ...

**Comment by sharkdeng** [comment]
> It's a matter of timing.
> To to add `xm.rendezvous('exit_from_here')` after the print ...

Thank you!!
