### ISSUE TITLE
[PT_BREAK] `torch.where` scalar support : test_where_scalar_xla_float32

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/xla#2347]
Reference PR: https://github.com/pytorch/pytorch/pull/40336

Probably need to blacklist the test.

```
Jul 14 13:12:59 ======================================================================
Jul 14 13:12:59 FAIL [0.006s]: test_where_scalar_xla_float32 (__main__.TestTorchDeviceTypeXLA)
Jul 14 13:12:59 ----------------------------------------------------------------------
Jul 14 13:12:59 Traceback (most recent call last):
Jul 14 13:12:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
Jul 14 13:12:59     result = test(self, device_arg, dtype)
Jul 14 13:12:59   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 18127, in test_where_scalar
Jul 14 13:12:59     torch.where(condition, x, scalar_1)
Jul 14 13:12:59 AssertionError: RuntimeError not raised
Jul 14 13:12:59 
Jul 14 13:12:59 ======================================================================
Jul 14 13:12:59 FAIL [0.006s]: test_where_scalar_xla_float64 (__main__.TestTorchDeviceTypeXLA)
Jul 14 13:12:59 ----------------------------------------------------------------------
Jul 14 13:12:59 Traceback (most recent call last):
Jul 14 13:12:59   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
Jul 14 13:12:59     result = test(self, device_arg, dtype)
Jul 14 13:12:59   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 18127, in test_where_scalar
Jul 14 13:12:59     torch.where(condition, x, scalar_1)
Jul 14 13:12:59 AssertionError: RuntimeError not raised
```

Thanks.

@ailzhang

**Comment by JackCaoG** [comment]
Hi @kshitij12345 , thanks for reporting! You are right that we usually disable tests that checks for runtime error. I took a look at your test and it seems like it also tests regular `torch.where` behavior. It would be great if you can separate out the `runtime error check` and mark that part as `@onlyOnCPUAndCUDA`. This way xla(and other backends) won't love coverage. What do you think? 😄

**Comment by kshitij12345** [comment]
Makes sense. Thanks! Will close this issue once that succeeds.
