### ISSUE TITLE
Kaggle kernel fails nondeterministically, probably related to ParallelLoader

### ISSUE THREAD

**Issue by jacekpoplawski** [pytorch/xla#2358]
hello,

I use Kaggle for a long time, I know pytorch from last competition so I decided to use it also in current one, however, this time I need to use TPU instead GPU. My code works without any issues on GPU, but on TPU I see random Kaggle kernel crashes, after a week of debugging I am still puzzled.

The code works on Kaggle TPU, I am able to train my model, but it fails after some epochs. Once I was able to train for 100 epochs for about 1 hour then I changed learning rate and it crashed in epoch 16. 

I will describe what I am doing:

I use 8 cores following way:

```
def _mp_fn(rank, config):
  log = {}
  print("running system on device {} ordinal {}".format(xm.xla_device(), xm.get_ordinal()))
  run_system(config, model, log)

xmp.spawn(_mp_fn, args=(config,), nprocs=8,
          start_method='fork')
```

Inside run_system I was using prints, I removed them, looks like stability improved, question - are we allowed to use print (not xm.master_print) on each core or can it lead to crashes?

I also create additional log for each core and to see where am I, in case of crash the last message in each core is always here:

```
    if (use_tpu):
        para_loader = pl.ParallelLoader(data_loader, [device])
        tk0 = para_loader.per_device_loader(device)        
    else:
        tk0 = tqdm(data_loader, total=len(data_loader))
    
    t_before_loop = datetime.now()    
    
    logger.log("before batches")
    for ii, (data, target) in enumerate(tk0):    

        logger.log("starting batch {}".format(ii))

```

Last message is "before batches" and as you can see next should be "starting batch {}", so it must die inside ParallelLoader.

My current approach is to try running other people kernels on Kaggle using PyTorch and TPU and find out will it crash. However I don't see what can I do differently, so I decided to ask here, maybe you have some tips what to check.

I create dataloader following way:

```
    if (use_tpu):
        sampler = torch.utils.data.distributed.DistributedSampler(
            dataset,
            num_replicas = xm.xrt_world_size(),
            rank = xm.get_ordinal(),
            shuffle = shuffle
        )
        dataloader = DataLoader(
            dataset = dataset,
            batch_size = batch_size,
            num_workers = 0,
            sampler = sampler, 
            drop_last = shuffle # True for Train only
        )        
    else:
        dataloader = DataLoader(
            dataset = dataset,
            batch_size = batch_size,
            num_workers = workers,
            pin_memory = True,
            shuffle = shuffle   
        )        
        
```

Kaggle kernel dies with following log:
```
392.4s18Traceback (most recent call last):
392.4s19  File "/opt/conda/bin/jupyter-nbconvert", line 11, in <module>
392.4s20    sys.exit(main())
392.4s21  File "/opt/conda/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
392.4s22    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
392.4s23  File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
392.4s24    app.start()
392.4s25  File "/opt/conda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
392.4s26    self.convert_notebooks()
392.4s27  File "/opt/conda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
392.4s28    self.convert_single_notebook(notebook_filename)
392.4s29  File "/opt/conda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
392.4s30    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
392.4s31  File "/opt/conda/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
392.4s32    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
392.4s33  File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
392.4s34    return self.from_file(f, resources=resources, **kw)
392.4s35  File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
392.4s36    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
392.4s37  File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
392.4s38    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
392.4s39  File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
392.4s40    nb_copy, resources = self._preprocess(nb_copy, resources)
392.4s41  File "/opt/conda/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
392.4s42    nbc, resc = preprocessor(nbc, resc)
392.4s43  File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
392.4s44    return self.preprocess(nb, resources)
392.4s45  File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
392.4s46    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
392.4s47  File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
392.4s48    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
392.4s49  File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
392.4s50    reply, outputs = self.run_cell(cell, cell_index, store_history)
392.4s51  File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 589, in run_cell
392.4s52    msg = self.kc.iopub_channel.get_msg(timeout=timeout)
392.4s53  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/blocking/channels.py", line 55, in get_msg
392.4s54    return self._recv()
392.4s55  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/blocking/channels.py", line 43, in _recv
392.4s56    return self.session.deserialize(smsg)
392.4s57  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
392.4s58    raise ValueError("Duplicate Signature: %r" % signature)
392.4s59ValueError: Duplicate Signature: b'0b713e7bffd9a9453ab26c3d14097994c9f17b0779c6c9a5e759851c41a29396'
393.2s60[NbConvertApp] Converting notebook __notebook__.ipynb to html
393.8s61[NbConvertApp] Writing 283974 bytes to __results__.html
393.8s62
393.8s64Failed. Exited with code 1.
```
There is no output for any cell but output files are readable, that's why I used logs in files.

**Comment by dlibenzi** [comment]
You can use prints, like:
```python
print(xla_tensor)
```

But this will be quite a bit faster:
```python
print(xla_tensor.cpu())
```

What you **cannot** do is:
```python
if ordinal == X:
  print(xla_tensor)
```

You **cannot** also do this:
```python
if ordinal == X:
  cpu_tensor = xla_tensor.cpu()
  print(cpu_tensor)
```

You **can** do this:
```python
cpu_tensor = xla_tensor.cpu()
if ordinal == X:
  print(cpu_tensor)
```


From you code is hard to tell what is wrong with it.
Can you share it all?

**Comment by jacekpoplawski** [comment]
hello @dlibenzi 
thanks a lot for reply, this is very interesting

you wrote that I can't do:
```
if ordinal == X:
  print(xla_tensor)
```
but I can do:
`print(xla_tensor)`
Could you explain the difference? I can call print, but I can't call print for specific ordinal only?
I was thinking I can call print only for master, but looking at your examples I don't understand how it works.

I removed all prints and writting to files and my last 6 kernel calls were stable.

**Comment by dlibenzi** [comment]
There is the requirement that every core has to run the same XLA tensor code, so the former violates that requirement.
So these are OK because they run the same XLA tensor code:
```Python
print(xla_tensor)
```

```Python
print(xla_tensor.cpu())
```

While this is OK because, even though there is a conditional execution, that is on PyTorch CPU tensors, not XLA tensors:
```Python
cpu_tensor = xla_tensor.cpu()
if SOMETHING:
  print(cpu_tensor)
```

**Comment by jacekpoplawski** [comment]
"There is the requirement that every core has to run the same XLA tensor code"
I didn't know that. That explains a lot, thank you! Probably my previous code was violating that because I was printing and logging things.
