### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by sharkdeng** [pytorch/xla#2359]
## ❓ Questions and Help
Hello, I was trying to put an EfficientNet-B1 with image size 1536X1536 and batch size 2 to the TPU using spawn (x8). But it always gave me OOM issue. 
I reduced image size to 1530 + batch size 2 or 1536 + batch size 1. Neither working.
I also tried !export XLA_USE_BF16=1, no magic. 
How to solve this problem? Thank you.

**Comment by dlibenzi** [comment]
Host or device OOM?

**Comment by sharkdeng** [comment]
> Host or device OOM?

I am using Kaggle's TPU v3-8.

**Comment by dlibenzi** [comment]
What I meant was, where the OOM is?
Is it the device OOM, where you get a clear OOM message?
Is it a host OOM, where maybe your processes gets killed?
Can you post a log message of some sort?

**Comment by sharkdeng** [comment]
It is host OOM, the screenshot is as follows:

<img width="1405" alt="Screen Shot 2020-07-19 at 1 08 28 AM" src="https://user-images.githubusercontent.com/16201315/87855554-855f2200-c95c-11ea-8c09-7aaa9264cbc8.png">


The log is as follows:
```
xla:0, 1.76771879196167:.4f
xla:0, 0.4883955419063568:.4f
xla:0, 0.10019142180681229:.4f
xla:1, 0.3067125082015991:.4f
xla:0, 3.5955307483673096:.4f
xla:0, 1.5275529623031616:.4f
xla:0, 1.6302789449691772:.4f
xla:0, 1.3990187644958496:.4f

Exception in device=TPU:6: DataLoader worker (pid(s) 1235) exited unexpectedly
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1235) is killed by signal: Killed. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-26-f9f6f7208c4d>", line 11, in _mp_fn
    train_on(1, train_dl)
  File "<ipython-input-25-42be89b517ea>", line 11, in train_on
    for i, (x, y) in bar:
  File "/opt/conda/lib/python3.7/site-packages/tqdm/notebook.py", line 218, in __iter__
    for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1127, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 388, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1003, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 970, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 821, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 1235) exited unexpectedly
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-27-2479bae6159a> in <module>
      1 FLAGS={}
----> 2 xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=8, start_method='fork')

/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py in spawn(fn, args, nprocs, join, daemon, start_method)
    393         join=join,
    394         daemon=daemon,
--> 395         start_method=start_method)
    396 
    397 

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    156 
    157     # Loop on join until it returns True or raises an exception.
--> 158     while not context.join():
    159         pass
    160 

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    111                 raise Exception(
    112                     "process %d terminated with exit code %d" %
--> 113                     (error_index, exitcode)
    114                 )
    115 

Exception: process 6 terminated with exit code 17

```

Thank you so much for helping!!
( https://cloud.google.com/tpu/docs/inception-v3-advanced )

**Comment by dlibenzi** [comment]
Can you post a link to the Kaggle?
Can you try if one device works (`xmp.spawn(..., nprocs=1)`?

**Comment by sharkdeng** [comment]
> Can you post a link to the Kaggle?
> Can you try if one device works (`xmp.spawn(..., nprocs=1)`?

sure, no problem. The competion ends in 4 days, can I post then?

**Comment by dlibenzi** [comment]
Of course, but I thought you wanted to solve this before submission ...
