### ISSUE TITLE
torch.load() -> Cannot replicate if number of devices (1) is different from 8

### ISSUE THREAD

**Issue by jacekpoplawski** [pytorch/xla#2364]
I train my model on Google Colab TPU

I am doing following:

```
model = build_model(config, with_extra)

import torch
path = "/content/drive/My Drive/KaggleLogs/session_07_20_2058/model_0.pth"
#f = torch.load(path)
#model.load_state_dict(f)


import pickle

import torch_xla.distributed.xla_multiprocessing as xmp    
import torch_xla.core.xla_model as xm

def _mp_fn(rank, config):
        log = {}
        run_system(config, model, log, None, None)

print("running system on TPU")        
model = xmp.MpModelWrapper(model)
xmp.spawn(_mp_fn, args=(config,), nprocs=8,
          start_method='fork')
```

When torch.load is commented out it starts.
When I uncomment torch.load I see:

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 225, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 218, in _setup_replication
    xm.set_replication(str(device), [str(device)])
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 217, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/core/xla_model.py", line 204, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
```

I was searching in archives and I found it can be related to calling xm.xla_device()
However, how torch.load can be related to that?
I uncommented only line with torch.load, not even touched the model state.

**Comment by JackCaoG** [comment]
Can you provided a runnable repo? I tried the following code that does the load outside the mp function and it seems to be working.
```
import io                                                                                                                                                                                                                              
import os                                                                                                                                                                                                                              
import tempfile                                                                                                                                                                                                                        
import torch                                                                                                                                                                                                                           
import torch_xla                                                                                                                                                                                                                       
import torch_xla.core.xla_model as xm                                                                                                                                                                                                  
import torch_xla.distributed.xla_multiprocessing as xmp                                                                                                                                                                                
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                       
def _create_state_dict(device):                                                                                                                                                                                                        
  a = torch.randn(3, 4, device=device)                                                                                                                                                                                                 
  b = torch.randn(3, 4, device=device)                                                                                                                                                                                                 
  c = torch.randn(3, 4, device=device)                                                                                                                                                                                                 
  d = dict()                                                                                                                                                                                                                           
  d['a'] = a                                                                                                                                                                                                                           
  d['b'] = b                                                                                                                                                                                                                           
  d['c'] = c                                                                                                                                                                                                                           
  d['a+b'] = a + b                                                                                                                                                                                                                     
  return d                                                                                                                                                                                                                             
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                       
def _get_temp_file():                                                                                                                                                                                                                  
  fd, path = tempfile.mkstemp()                                                                                                                                                                                                        
  os.close(fd)                                                                                                                                                                                                                         
  return path                                                                                                                                                                                                                          
                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                       
def _get_data_str(data):                                                                                                                                                                                                               
  bio = io.BytesIO()                                                                                                                                                                                                                   
  torch.save(data, bio)                                                                                                                                                                                                                
  return bio.getvalue()                                                                                                                                                                                                                
                                                                                                                                                                                                                                       
temp_file = _get_temp_file()                                                                                                                                                                                                           
device = xm.xla_device()                                                                                                                                                                                                               
dd = _create_state_dict(device)                                                                                                                                                                                                        
xm.save(dd, temp_file)                                                                                                                                                                                                                 
ldd = torch.load(temp_file)                                                                                                                                                                                                            
                                                                                                                                                                                                                                       
def _mp_fn(index, temp_file):                                                                                                                                                                                                          
  pdd = _get_data_str(ldd)                                                                                                                                                                                                             
  data = xm.rendezvous('xm_save_test', pdd)                                                                                                                                                                                            
  if xm.get_local_ordinal() == 0:                                                                                                                                                                                                      
    os.remove(temp_file)                                                                                                                                                                                                               
                                                                                                                                                                                                                                       
if __name__ == '__main__':                                                                                                                                                                                                             
  xmp.spawn(_mp_fn, args=(temp_file,),                                                                                                                                                                                                 
            start_method='fork') 
```

**Comment by jacekpoplawski** [comment]
> 
> 
> edit1: forgot to set the nproc in my example, removing that.
> 
> Can you provided a runnable repo?

I can't, I am working on Kaggle competition. If needed maybe I can prepare separate project. Do you mean it won't happen on your side?

**Comment by davidel** [comment]
How did you save your model?
Did you use `xm.save()`?
For Colab/Kaggle it might be best to use the XLA serialization API, which has lower memory requirements.
```python
import torch_xla.utils.serialization as xser

xser.save(...)
xser.load(...)
```

**Comment by jacekpoplawski** [comment]
> 
> 
> How did you save your model?
> Did you use `xm.save()`?
> For Colab/Kaggle it might be best to use the XLA serialization API, which has lower memory requirements.
> 
> ```python
> import torch_xla.utils.serialization as xser
> 
> xser.save(...)
> xser.load(...)
> ```

Thanks David it may be the reason:

```
def save_model(model, optimizer, valid, path, epoch):
    torch.save(model.state_dict(), path + "model_{}.pth".format(valid))
    torch.save(optimizer.state_dict(), path + "optimizer_{}.pth".format(valid))

```

**Comment by davidel** [comment]
The `torch_xla.utils.serialization` use much less memory but has a different format.
If you want to convert back a checkpoint created with that API, to one that torch can load directly, you can:
```python
import torch_xla.utils.serialization as xser

data = xser.load(...)
torch.save(data, ...)
```

**Comment by jacekpoplawski** [comment]
there is small problem:

`ModuleNotFoundError: No module named 'torch_xla.utils.serialization'`

that works:

`import torch_xla.core.xla_model as xm`

I used:

```
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py 
```

do I need to do it differently to have utils?

**Comment by jysohn23** [comment]
That setup script has the following default date that it installs wheel for: `20200515 ` https://github.com/pytorch/xla/blob/master/contrib/scripts/env-setup.py#L146 whereas that API landed in 20200529. Can you try the 20200530 build or some other one after that?

**Comment by jacekpoplawski** [comment]
I confirm I am able to import:
`
import torch_xla.utils.serialization as xser`

when using:

`!python pytorch-xla-env-setup.py  --version 20200530 `

**Comment by jacekpoplawski** [comment]
I used following code:
```
        xser.save(model.state_dict(), path + "model.pth", master_only=True)
        xser.save(optimizer.state_dict(), path + "optimizer.pth", master_only=True)    
```

it works very slow, I save from colab on google drive and already 3 minutes passed and it still saves
it created directory called model.pth.tensors with many files inside

Should it be so slow?

**Comment by davidel** [comment]
Depends on the size of the parameters, and whether you do that for the first time (it will be compiling also, in this case).
I remember I tried an "hot" resnet50 and took a few second to save the model's state.

**Comment by jacekpoplawski** [comment]
I switched to the previous code (torch.save) and it saved the model immediately, so there must be something different when using xser.save, because time is 1s vs few minutes.

**Comment by davidel** [comment]
`torch.save()` cannot be used with XLA devices.
Can you please share a repro o Colab?

**Comment by jacekpoplawski** [comment]
I can't share code now :( 
some snippets of my current code:

```
   for e in range(config["epochs"]):
        if (use_tpu):
            xm.master_print("epoch {}".format(e))
        else:
            print("epoch ", e)
        
        result = epoch(m_o_s, dataloaders, device, criterion)
        
        current_lr = m_o_s["optimizer"].param_groups[0]['lr']
        result["lr"] = current_lr
        
        if (use_tpu):
            xm.master_print(result)
        else:
            print(result)
        
        stats.append(result)
        stats.save()
        
        score = result["valid_score"]
        if (score > best_score):
            best_score = score
            if (use_tpu):
                if (xm.is_master_ordinal()):
                    xm.master_print("saving model, score {}".format(score))
                    save_model(m_o_s["model"], m_o_s["optimizer"], output_dir)
            else:
                print("saving model, score {}".format(score))
                save_model(m_o_s["model"], m_o_s["optimizer"], output_dir)
```

```
import torch
import pickle
try:
    import torch_xla.core.xla_model as xm
    use_tpu = True
except ImportError:
    use_tpu = False
    
def save_model(model, optimizer, path):
    if (use_tpu):
        xm.save(model.state_dict(), path + "model.pth")
        xm.save(optimizer.state_dict(), path + "optimizer.pth")
    else:
        torch.save(model.state_dict(), path + "model.pth")
        torch.save(optimizer.state_dict(), path + "optimizer.pth")
```

current output:
```
running system on TPU
created directory: /content/drive/My Drive/KaggleLogs/session_07_27_0908/
train_csv (24376, 13) valid_csv (8325, 13)
epoch 0
{'train_score': 0.5466408551679393, 'valid_score': 0.7071530817618111, 'train_loss': 0.22755814910492508, 'valid_loss': 0.13639846735526107, 'duration': 504.333752, 'lr': 0.00020949270073339615}
saving model, score 0.7071530817618111
```

so it is still on xm.save for many minutes, can you spot mistake here?

path is /content/drive/My Drive/KaggleLogs/session_07_27_0908/

in the directory I see model.pth but no optimizer.pth

**Comment by jacekpoplawski** [comment]
no locking after removing is_master_ordinal
this is counter-intuitive but now understable

**Comment by davidel** [comment]
You cannot do **anything** which involves XLA tensors (CPU tensors are OK), under an if-master condition branch:
```python
if (xm.is_master_ordinal()):
  ...
```
This is why we have:

https://github.com/pytorch/xla/blob/8cefb2a9a74d58ffe3d1592cbc8e248558d08a6a/torch_xla/core/xla_model.py#L861

**Comment by jacekpoplawski** [comment]
Yes I realized that while reading my code, thanks for the help!

**Comment by lezwon** [comment]
I faced this issue once. It was due to using `torch.save` instead of `xm.save`. I suppose the tensors were saved as XLA tensors with `device='xla:1'`. When calling `torch.load` on this file, they were automatically loaded to `xla:1` on the main process, which acquires a single device. Calling `xm.spawn(nprocs=8)` after this results in the error.
