### ISSUE TITLE
[PT_BREAK] Implement torch.nextafter, test_nextafter_xla_float32

### ISSUE THREAD

**Issue by muthuArivoli** [pytorch/xla#2406]
PR: pytorch/pytorch#42580
Currently getting this error on the xla test
```
Aug 05 06:37:27 ======================================================================
Aug 05 06:37:27 ERROR [0.012s]: test_nextafter_xla_float32 (__main__.TestTorchDeviceTypeXLA)
Aug 05 06:37:27 ----------------------------------------------------------------------
Aug 05 06:37:27 Traceback (most recent call last):
Aug 05 06:37:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
Aug 05 06:37:27     result = test(self, device_arg, dtype)
Aug 05 06:37:27   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 16996, in test_nextafter
Aug 05 06:37:27     actual = torch.nextafter(t1, t2)
Aug 05 06:37:27 RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
Aug 05 06:37:27 
Aug 05 06:37:27 ======================================================================
Aug 05 06:37:27 ERROR [0.011s]: test_nextafter_xla_float64 (__main__.TestTorchDeviceTypeXLA)
Aug 05 06:37:27 ----------------------------------------------------------------------
Aug 05 06:37:27 Traceback (most recent call last):
Aug 05 06:37:27   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 241, in instantiated_test
Aug 05 06:37:27     result = test(self, device_arg, dtype)
Aug 05 06:37:27   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 16996, in test_nextafter
Aug 05 06:37:27     actual = torch.nextafter(t1, t2)
Aug 05 06:37:27 RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
```

Potentially related to #929

**Comment by JackCaoG** [comment]
Hi @muthuArivoli , thanks for reporting! XLA does not has storage so any attempt to access the storage will result in a runtime error. You can mark the test as `onlyOnCPUAndCUDA` so it won't be run on the xla😄 .
