### ISSUE TITLE
[PT_BREAK] "std_cpu" not implemented for 'BFloat16' in 44758

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/xla#2494]
XLA test is breaking in https://github.com/pytorch/pytorch/pull/44758

```
Sep 16 01:13:30 ======================================================================
Sep 16 01:13:30 ERROR [0.027s]: test_var_neg_dim_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Sep 16 01:13:30 ----------------------------------------------------------------------
Sep 16 01:13:30 Traceback (most recent call last):
Sep 16 01:13:30   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 270, in instantiated_test
Sep 16 01:13:30     result = test_fn(self, *args)
Sep 16 01:13:30   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20167, in fn
Sep 16 01:13:30     device_result = getattr(device_tensor, op_str)(*device_args)
Sep 16 01:13:30 RuntimeError: "std_cpu" not implemented for 'BFloat16'
Sep 16 01:13:30 
Sep 16 01:13:30 ----------------------------------------------------------------------
```

**Comment by JackCaoG** [comment]
@zasdfgbnm This seems to be caused by the native CPU implementation of `var`in [here](https://github.com/pytorch/pytorch/blob/a860be898ee0fbafac14bf68e920187a76ded70d/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp#L151) uses `std_cpu` but it does not support `BFloat16`. This is an easy lowering so I will try to submit a lowering today so this op don't need to use the pytorch native implementation.

**Comment by JackCaoG** [comment]
Hmm... actually `cpu_tensor.var` with bfloat16 also doesn't work, the failure coming from the test_torch.py `generate_test_function`.

Although the `dtype=bfloat16`
```
        cpu_tensor = tensor_ctor(dtype, 'cpu')                                                                                                                                                                                    
        cpu_args = arg_ctor(dtype, 'cpu')                                                                                                                                                                                         
                                                                                                                                                                                                                                  
        # Converts CPU tensors to device tensors                                                                                                                                                                                  
        device_tensor = cpu_tensor.to(dtype=dtype, device=device)                                                                                                                                                                 
        device_args = [arg.to(device=device) if isinstance(arg, torch.Tensor) else arg for arg in cpu_args] 
```
I am still seeing
```
(Pdb) cpu_tensor.dtype
torch.float32
```
while device tensor has type float16.
