### ISSUE TITLE
[PT_BREAK] missing elementwise operators acosh, asinh, and atanh

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/xla#2497]
I believe this is the same problem as https://github.com/pytorch/xla/issues/2494 and this is a test failure of XLA at https://github.com/pytorch/pytorch/pull/44813

The following operators are missing implementation:
- acosh
- asinh
- atanh

Message:
```
Sep 17 22:50:54 ======================================================================
Sep 17 22:50:54 ERROR [0.020s]: test_acosh_inplace_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Sep 17 22:50:54 ----------------------------------------------------------------------
Sep 17 22:50:54 Traceback (most recent call last):
Sep 17 22:50:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 270, in instantiated_test
Sep 17 22:50:54     result = test_fn(self, *args)
Sep 17 22:50:54   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20172, in fn
Sep 17 22:50:54     device_result = getattr(device_tensor, op_str)(*device_args)
Sep 17 22:50:54 RuntimeError: "acosh_cpu" not implemented for 'BFloat16'
Sep 17 22:50:54 
Sep 17 22:50:54 ======================================================================
Sep 17 22:50:54 ERROR [0.015s]: test_acosh_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Sep 17 22:50:54 ----------------------------------------------------------------------
Sep 17 22:50:54 Traceback (most recent call last):
Sep 17 22:50:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 270, in instantiated_test
Sep 17 22:50:54     result = test_fn(self, *args)
Sep 17 22:50:54   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20172, in fn
Sep 17 22:50:54     device_result = getattr(device_tensor, op_str)(*device_args)
Sep 17 22:50:54 RuntimeError: "acosh_cpu" not implemented for 'BFloat16'
Sep 17 22:50:54 
Sep 17 22:50:54 ======================================================================
Sep 17 22:50:54 ERROR [0.015s]: test_asinh_inplace_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Sep 17 22:50:54 ----------------------------------------------------------------------
Sep 17 22:50:54 Traceback (most recent call last):
Sep 17 22:50:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 270, in instantiated_test
Sep 17 22:50:54     result = test_fn(self, *args)
Sep 17 22:50:54   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20172, in fn
Sep 17 22:50:54     device_result = getattr(device_tensor, op_str)(*device_args)
Sep 17 22:50:54 RuntimeError: "asinh_cpu" not implemented for 'BFloat16'
Sep 17 22:50:54 
Sep 17 22:50:54 ======================================================================
Sep 17 22:50:54 ERROR [0.014s]: test_asinh_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Sep 17 22:50:54 ----------------------------------------------------------------------
Sep 17 22:50:54 Traceback (most recent call last):
Sep 17 22:50:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 270, in instantiated_test
Sep 17 22:50:54     result = test_fn(self, *args)
Sep 17 22:50:54   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20172, in fn
Sep 17 22:50:54     device_result = getattr(device_tensor, op_str)(*device_args)
Sep 17 22:50:54 RuntimeError: "asinh_cpu" not implemented for 'BFloat16'
Sep 17 22:50:54 
Sep 17 22:50:54 ======================================================================
Sep 17 22:50:54 ERROR [0.012s]: test_atanh_inplace_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Sep 17 22:50:54 ----------------------------------------------------------------------
Sep 17 22:50:54 Traceback (most recent call last):
Sep 17 22:50:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 270, in instantiated_test
Sep 17 22:50:54     result = test_fn(self, *args)
Sep 17 22:50:54   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20172, in fn
Sep 17 22:50:54     device_result = getattr(device_tensor, op_str)(*device_args)
Sep 17 22:50:54 RuntimeError: "atanh_cpu" not implemented for 'BFloat16'
Sep 17 22:50:54 
Sep 17 22:50:54 ======================================================================
Sep 17 22:50:54 ERROR [0.014s]: test_atanh_xla_bfloat16 (__main__.TestTensorDeviceOpsXLA)
Sep 17 22:50:54 ----------------------------------------------------------------------
Sep 17 22:50:54 Traceback (most recent call last):
Sep 17 22:50:54   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 270, in instantiated_test
Sep 17 22:50:54     result = test_fn(self, *args)
Sep 17 22:50:54   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 20172, in fn
Sep 17 22:50:54     device_result = getattr(device_tensor, op_str)(*device_args)
Sep 17 22:50:54 RuntimeError: "atanh_cpu" not implemented for 'BFloat16'
Sep 17 22:50:54 
Sep 17 22:50:54 ----------------------------------------------------------------------
```

**Comment by zasdfgbnm** [comment]
cc: @JackCaoG

**Comment by JackCaoG** [comment]
I will take a look.. If I don't have time to lower all of them, I will submit a pr to skip some of the bfloat16 tests
