### ISSUE TITLE
Can I use XlaBuilder:TriangularSolve in PyTorch?

### ISSUE THREAD

**Issue by DDeChoU** [pytorch/xla#2498]
## ❓ Questions and Help
I found TriangularSolve in the xla webpage: https://www.tensorflow.org/xla/operation_semantics#triangularsolve
Is it possible to use this through the pytorch/xla? It seems the triangular_solve in PyTorch is very slow even on TPU. Is there a way I can directly invoke the xla version just like using functions like dynamic_slice(...)?

I am looking for it in torch_xla.core but do not see TriangularSolve api offered. Is this the right place to see what api is offered? 
- If not, where should I refer to? 
- If yes, does that mean TriangularSolve is not supported yet. Can I expect it to be available in the future?

**Comment by JackCaoG** [comment]
Yes, you can use xlabuilder api from python, we didn't have a very good document about it yet but the implementation is in [here](https://github.com/pytorch/xla/blob/a8550c78c1e53848d5c2c6cc3046f0005ca14881/torch_xla/core/xla_builder.py). You can find the origional pr in [here](https://github.com/pytorch/xla/pull/2125). That being said pytorch/xla   traingularSolve is implemented using `xla:TriangularSolve ` in [here](https://github.com/pytorch/xla/blob/85c1dee566aa140fcace2b2a703678cafab05c36/torch_xla/csrc/ops/triangular_solve.cpp#L61), I don't think using xlaBuilder api will help the performance in this case.

**Comment by DDeChoU** [comment]
It seems in the xla_builder.py, no function called triangularSolve is defined. With it implemented in triangular_solve.cpp, how can I access it through Python apis?

**Comment by JackCaoG** [comment]
Hmm, yeah you right, I need to add a hook in `xla_builder.py` to expose the `xlabuilder.triangualr_solve`. 

What I meant by "pytorch/xla traingularSolve is implemented using `xla:TriangularSolve`" is when you called `torch.triangular_solve` on xlaTensor, the pytorch/xla will translate this operation into `xla:triangualr_solve` automatically. This is true for all of the op we supported (you can find all of the ops we supported in [this file](https://github.com/pytorch/xla/blob/a8550c78c1e53848d5c2c6cc3046f0005ca14881/torch_xla/csrc/aten_xla_type.h), the c++ function name usually map directly to pytorch python api), we translate pytorch ops into xla ops. You don't need to call `xlabuilder.triangularSolve` directly in this case.

**Comment by DDeChoU** [comment]
I see. Thank you for the reply. I want to use xlabuilder.triangularSolve mainly because the TriangularSolve of XLA displayed [here](https://www.tensorflow.org/xla/operation_semantics#triangularsolve) has an option of left_side. Such an option does not exist in that of torch documented [here](https://pytorch.org/docs/stable/generated/torch.triangular_solve.html).

This means the torch can only solve X for AX = b and it cannot solve XA = b, which xlbuilder.triangularSolve can.

**Comment by JackCaoG** [comment]
I see.. I will look into this tomorrow, should be a relatively small change.

**Comment by DDeChoU** [comment]
Sure. Thank you!

**Comment by JackCaoG** [comment]
@DDeChoU the XLABuilder TriangualrSolve api is now exposed, I had an example on the pr linked example about how to use it. In the high level you need to define and register a new custom op that consist of only `xla::TriangularSolve` and use this op going forward. I will close this issue for now, feel free to reopen it if you encountered any problems.

**Comment by DDeChoU** [comment]
Hi, 
Thank you for the help and the function works pretty well in Colab. Now I am trying to use it on a cloud VM with TPU. However, I encounter a weird error. Pytorch and pytorch/xla are all compiled from source using the latest version online.
The test code is:
```
import torch                                                                                                                                                                                                                               
import torch_xla.core.xla_builder as xb                                                                                                                                                                                                    
import torch_xla.core.xla_op_registry as xor                                                                                                                                                                                               
import torch_xla.core.xla_model as xm                                                                                                                                                                                                      
import torch_xla.utils.utils as xu 

# new custom op that perform the xla::triangular_solve
def op_fn(b, A, left_side, lower, unit_diagonal, transpose_a):                                                                                                                                                                             
    return A.triangualr_solve(b, True, lower, unit_diagonal, transpose_a)

# register this op                                                                                                                                                                                                                                           
op = xor.register('xla_triangualr_solve', op_fn) 

n = 3
# setup parameters                                                                                                                                                                                          
device = xm.xla_device()                                                                                                                                                                                                                   
A = torch.randn(n, n).triu()                                                                                                                                                                                                               
b = torch.randn(n, n)                                                                                                                                                                                                                      
args = {                                                                                                                                                                                                                                   
    'left_side': False,                                                                                                                                                                                                                     
    'lower': True,                                                                                                                                                                                                                         
    'unit_diagonal': False,                                                                                                                                                                                                                
    'transpose_a': False                                                                                                                                                                                                                   
}                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                           
res = op(*[b.to(device), A.to(device)], **args)
print(type(res))                                                                                                                                                                                            
print(res) 
```

The error encountered is:
```
2020-11-24 19:22:03.156423: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] >>> Dumping Computation 0
2020-11-24 19:22:03.156553: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] HloModule SyncTensorsGraph.34
2020-11-24 19:22:03.156563: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
2020-11-24 19:22:03.156568: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] %xla_triangualr_solve.13 (p0.14: f32[3,3], p1.15: f32[3,3]) -> f32[3,3] {
2020-11-24 19:22:03.156573: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %p1.15 = f32[3,3]{1,0} parameter(1)
2020-11-24 19:22:03.156578: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %p0.14 = f32[3,3]{1,0} parameter(0)
2020-11-24 19:22:03.156583: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   ROOT %triangular-solve.16 = f32[3,3]{1,0} triangular-solve(f32[3,3]{1,0} %p1.15, f32[3,3]{1,0} %p0.14), left_side=true, lower=true, transpose_a=NO_TRANSPOSE
2020-11-24 19:22:03.156589: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] }
2020-11-24 19:22:03.156593: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
2020-11-24 19:22:03.156599: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] ENTRY %SyncTensorsGraph.34 (p0.1: f32[3,3], p1.7: f32[3,3], p2.23: f32[]) -> (f32[9], pred[9]) {
2020-11-24 19:22:03.156604: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %constant.2 = f32[] constant(0)
2020-11-24 19:22:03.156609: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %reshape.3 = f32[1,1]{1,0} reshape(f32[] %constant.2)
2020-11-24 19:22:03.156614: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %broadcast.4 = f32[1,1]{1,0} broadcast(f32[1,1]{1,0} %reshape.3), dimensions={0,1}
2020-11-24 19:22:03.156619: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %reshape.5 = f32[] reshape(f32[1,1]{1,0} %broadcast.4)
2020-11-24 19:22:03.156624: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %broadcast.6 = f32[3,3]{1,0} broadcast(f32[] %reshape.5), dimensions={}
2020-11-24 19:22:03.156629: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %constant.8 = f32[] constant(0)
2020-11-24 19:22:03.156633: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %reshape.9 = f32[1,1]{1,0} reshape(f32[] %constant.8)
2020-11-24 19:22:03.156638: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %broadcast.10 = f32[1,1]{1,0} broadcast(f32[1,1]{1,0} %reshape.9), dimensions={0,1}
2020-11-24 19:22:03.156643: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %reshape.11 = f32[] reshape(f32[1,1]{1,0} %broadcast.10)
2020-11-24 19:22:03.156648: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %broadcast.12 = f32[3,3]{1,0} broadcast(f32[] %reshape.11), dimensions={}
2020-11-24 19:22:03.156652: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %p1.7 = f32[3,3]{1,0} parameter(1)
2020-11-24 19:22:03.156657: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %p0.1 = f32[3,3]{1,0} parameter(0)
2020-11-24 19:22:03.156662: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %call.17 = f32[3,3]{1,0} call(f32[3,3]{1,0} %p1.7, f32[3,3]{1,0} %p0.1), to_apply=%xla_triangualr_solve.13
2020-11-24 19:22:03.156667: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %reshape.18 = f32[9]{0} reshape(f32[3,3]{1,0} %call.17)
2020-11-24 19:22:03.156672: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %compare.27 = pred[9]{0} compare(f32[9]{0} %reshape.18, f32[9]{0} %reshape.18), direction=EQ
2020-11-24 19:22:03.156676: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %convert.28 = u8[9]{0} convert(pred[9]{0} %compare.27)
2020-11-24 19:22:03.156681: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %abs.24 = f32[9]{0} abs(f32[9]{0} %reshape.18)
2020-11-24 19:22:03.156686: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %p2.23 = f32[] parameter(2)
2020-11-24 19:22:03.156691: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %broadcast.25 = f32[9]{0} broadcast(f32[] %p2.23), dimensions={}
2020-11-24 19:22:03.156696: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %compare.26 = pred[9]{0} compare(f32[9]{0} %abs.24, f32[9]{0} %broadcast.25), direction=NE
2020-11-24 19:22:03.156706: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %convert.29 = u8[9]{0} convert(pred[9]{0} %compare.26)
2020-11-24 19:22:03.156711: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %multiply.30 = u8[9]{0} multiply(u8[9]{0} %convert.28, u8[9]{0} %convert.29)
2020-11-24 19:22:03.156716: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %convert.31 = pred[9]{0} convert(u8[9]{0} %multiply.30)
2020-11-24 19:22:03.156721: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %constant.19 = s64[] constant(0)
2020-11-24 19:22:03.156726: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %convert.20 = f32[] convert(s64[] %constant.19)
2020-11-24 19:22:03.156731: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %broadcast.21 = f32[9]{0} broadcast(f32[] %convert.20), dimensions={}
2020-11-24 19:22:03.156736: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %compare.22 = pred[9]{0} compare(f32[9]{0} %reshape.18, f32[9]{0} %broadcast.21), direction=NE
2020-11-24 19:22:03.156740: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   %and.32 = pred[9]{0} and(pred[9]{0} %convert.31, pred[9]{0} %compare.22)
2020-11-24 19:22:03.156745: E tensorflow/compiler/xla/xla_client/xla_util.cc:76]   ROOT %tuple.33 = (f32[9]{0}, pred[9]{0}) tuple(f32[9]{0} %reshape.18, pred[9]{0} %and.32)
2020-11-24 19:22:03.156750: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] }
2020-11-24 19:22:03.156755: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
2020-11-24 19:22:03.156759: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
2020-11-24 19:22:03.156764: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] OutputShape: (f32[9]{0}, pred[9]{0})
2020-11-24 19:22:03.156769: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
2020-11-24 19:22:03.156774: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] StackTrace:
2020-11-24 19:22:03.156779: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] *** Begin stack trace ***
2020-11-24 19:22:03.156784: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	tensorflow::CurrentStackTrace[abi:cxx11]()
2020-11-24 19:22:03.156789: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	xla::util::ReportComputationError(tensorflow::Status const&, absl::lts_2020_02_25::Span<xla::XlaComputation const* const>, absl::lts_2020_02_25::Span<xla::Shape const* const>)
2020-11-24 19:22:03.156794: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	xla::XrtComputationClient::CheckCompileStatus(tensorflow::Status const&, std::vector<xla::ComputationClient::CompileInstance, std::allocator<xla::ComputationClient::CompileInstance> > const&, xla::XrtComputationClient::SessionWork const&)
2020-11-24 19:22:03.156799: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	
2020-11-24 19:22:03.156804: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	xla::util::MultiWait::Complete(std::function<void ()> const&)
2020-11-24 19:22:03.156809: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	
2020-11-24 19:22:03.156813: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	
2020-11-24 19:22:03.156818: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	
2020-11-24 19:22:03.156823: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 	clone
2020-11-24 19:22:03.156828: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] *** End stack trace ***
2020-11-24 19:22:03.156832: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] 
2020-11-24 19:22:03.156837: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] Status: Not found: Op type not registered 'XRTMemoryInfo' in binary running on n-20b44ff6-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Traceback (most recent call last):
  File "test_triangular.py", line 28, in <module>
    print(res) 
  File "/usr/local/lib/python3.8/dist-packages/torch/tensor.py", line 179, in __repr__
    return torch._tensor_str._str(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor_str.py", line 372, in _str
    return _str_intern(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor_str.py", line 352, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor_str.py", line 241, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor_str.py", line 89, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: Not found: Op type not registered 'XRTMemoryInfo' in binary running on n-20b44ff6-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1110 : Check failed: session->session()->Run( feed_inputs, {}, {cached_node.operations[0]}, &outputs) == ::tensorflow::Status::OK() (Invalid argument: A session is not created yet.... vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	xla::XrtComputationClient::ReleaseHandles(std::vector<xla::XrtComputationClient::DeviceHandle, std::allocator<xla::XrtComputationClient::DeviceHandle> >*, std::function<xla::XrtSession::CachedNode const& (xla::XrtSession*, tensorflow::Scope const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&, xla::metrics::Metric*, xla::metrics::Counter*)
	xla::XrtComputationClient::HandleReleaser()
	xla::util::TriggeredTask::Runner()
	
	
	clone
*** End stack trace ***
```
What is the potential reason for this and how can I solve it?

Thank you in advance!

**Comment by JackCaoG** [comment]
@DDeChoU Your TPU version seems to be mismatched with your pt/xla version. If you are using nightly, you can simply restart your TPU and it will fetch the latest nightly server image. If you are using pt/xla 1.6 or 1.7, you should select the corresponding TPU image version.

**Comment by JackCaoG** [comment]
or you can run 
```
curl -X POST http://$TPU_IP:8475/requestversion/pytorch-devYYYYMMDD
```
on your vm and replaced the TPU_IP and date. This will also update your TPU version to a specified date.

**Comment by DDeChoU** [comment]
Thank you. I did not notice the version match before.

I have another question regarding the efficiency of the triangular solve. I was benchmarking the speed of the operation as below:
```
import torch                                                                                                                                                                                                                               
import torch_xla.core.xla_builder as xb                                                                                                                                                                                                    
import torch_xla.core.xla_op_registry as xor                                                                                                                                                                                               
import torch_xla.core.xla_model as xm                                                                                                                                                                                                      
import torch_xla.utils.utils as xu 
import time

# new custom op that perform the xla::triangular_solve
def op_fn(b, A, left_side, lower, unit_diagonal, transpose_a):                                                                                                                                                                             
    return A.triangualr_solve(b, True, lower, unit_diagonal, transpose_a)                                                                                                                                                                  

# register this op                                                                                                                                                                                                                                           
op = xor.register('xla_triangualr_solve', op_fn) 

#start the benchmarking
n=5000
repeat_times = 10
dev = xm.xla_device(n=1, devkind='TPU')
A = torch.randn(n,n).triu()
b = torch.randn(n,n)
A = A.to(dev)
b = b.to(dev)
L = torch.zeros(n,n, device=dev)
args = {                                                                                                                                                                                                                                   
    'left_side': False,                                                                                                                                                                                                                     
    'lower': True,                                                                                                                                                                                                                         
    'unit_diagonal': False,                                                                                                                                                                                                                
    'transpose_a': False                                                                                                                                                                                                                   
}
start = time.time()
for i in range(repeat_times):
  L += op(*[b, A], **args)
print(torch.norm(L))
end = time.time()
testStart = time.time()
print(torch.norm(L))
testEnd = time.time()
complexity = (n**2 + n**3) * repeat_times
finalTime = (end - start - (testEnd - testStart))
TFLOPS = complexity/finalTime/10**12
print('Time: {}s, Speed: {} TFLOPS'.format(finalTime, TFLOPS))
```
Surprisingly, the speed detected is very low, i.e., 0.006TFLOPS. I am curious whether the speed is supposed to be that low even when executing on TPU or did I make any mistake in either measurements or execution, which limits its execution speed? Is there any certified way to measure the speed of the execution speed of such commands on TPU?
