### ISSUE TITLE
Please help me with Google Colab TPU error (Gradation error)

### ISSUE THREAD

**Issue by asigalov61** [pytorch/xla#2529]
## ❓ Questions and Help
Hey guys,

Thank you so much for your hard work on PyTXLA as it is very needed and appreciated.

I need quick help with TPUs so if someone can help, it will be super.

Here is a TPU version of my colab. It is based on minGPT-PTL implementation by William Falcon but for some reason the code suggestions do not work in my colab.

https://colab.research.google.com/drive/1GPNnt942ti1DM7O8hrX4pUWhSYLF7XxK?usp=sharing

I get the following error

----------------

```
Exception in device=TPU:3: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Traceback (most recent call last):
Exception in device=TPU:1: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Exception in device=TPU:4: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Exception in device=TPU:7: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Exception in device=TPU:5: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Exception in device=TPU:6: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
Exception in device=TPU:2: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 1049, in optimizer_closure
    training_step_output_for_epoch_end = copy(training_step_output)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 1049, in optimizer_closure
    training_step_output_for_epoch_end = copy(training_step_output)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/usr/lib/python3.6/copy.py", line 88, in copy
    return copier(x)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 1049, in optimizer_closure
    training_step_output_for_epoch_end = copy(training_step_output)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 1049, in optimizer_closure
    training_step_output_for_epoch_end = copy(training_step_output)
  File "/usr/lib/python3.6/copy.py", line 88, in copy
    return copier(x)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 1049, in optimizer_closure
    training_step_output_for_epoch_end = copy(training_step_output)
  File "/usr/lib/python3.6/copy.py", line 88, in copy
    return copier(x)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 1049, in optimizer_closure
    training_step_output_for_epoch_end = copy(training_step_output)
  File "/usr/lib/python3.6/copy.py", line 88, in copy
    return copier(x)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/step_result.py", line 302, in __copy__
    newone[k] = copy(v)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 844, in run_training_batch
    self.hiddens
  File "/usr/lib/python3.6/copy.py", line 88, in copy
    return copier(x)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/step_result.py", line 302, in __copy__
    newone[k] = copy(v)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/step_result.py", line 302, in __copy__
    newone[k] = copy(v)
  File "/usr/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 1049, in optimizer_closure
    training_step_output_for_epoch_end = copy(training_step_output)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/step_result.py", line 302, in __copy__
    newone[k] = copy(v)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/step_result.py", line 302, in __copy__
    newone[k] = copy(v)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 103, in __reduce_ex__
    arg_xla = (self.cpu().numpy(),
  File "/usr/lib/python3.6/copy.py", line 88, in copy
    return copier(x)
  File "/usr/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
  File "/usr/lib/python3.6/copy.py", line 88, in copy
    return copier(x)
  File "/usr/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
  File "/usr/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 103, in __reduce_ex__
    arg_xla = (self.cpu().numpy(),
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/step_result.py", line 302, in __copy__
    newone[k] = copy(v)
  File "/usr/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 103, in __reduce_ex__
    arg_xla = (self.cpu().numpy(),
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/step_result.py", line 302, in __copy__
    newone[k] = copy(v)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 103, in __reduce_ex__
    arg_xla = (self.cpu().numpy(),
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 103, in __reduce_ex__
    arg_xla = (self.cpu().numpy(),
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
  File "/usr/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 103, in __reduce_ex__
    arg_xla = (self.cpu().numpy(),
  File "/usr/lib/python3.6/copy.py", line 96, in copy
    rv = reductor(4)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 103, in __reduce_ex__
    arg_xla = (self.cpu().numpy(),
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Exception in device=TPU:0: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py", line 112, in tpu_train_in_process
    results = trainer.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1239, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 394, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 491, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-30-bc11544a2b6a> in <module>()
      1 #@title (OPTION 1) Train the model
----> 2 trainer.fit(model, train_loader)

5 frames
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/states.py in wrapped_fn(self, *args, **kwargs)
     46             if entering is not None:
     47                 self.state = entering
---> 48             result = fn(self, *args, **kwargs)
     49
     50             # The INTERRUPTED state can be set inside the run function. To indicate that run was interrupted

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders, datamodule)
   1076             self.accelerator_backend = TPUBackend(self)
   1077             self.accelerator_backend.setup()
-> 1078             self.accelerator_backend.train(model)
   1079             self.accelerator_backend.teardown(model)
   1080

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py in train(self, model)
     85                 args=(model, self.trainer, self.mp_queue),
     86                 nprocs=self.trainer.tpu_cores,
---> 87                 start_method=self.start_method
     88             )
     89

/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py in spawn(fn, args, nprocs, join, daemon, start_method)
    393         join=join,
    394         daemon=daemon,
--> 395         start_method=start_method)
    396
    397

/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    155
    156     # Loop on join until it returns True or raises an exception.
--> 157     while not context.join():
    158         pass
    159

/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    110                 raise Exception(
    111                     "process %d terminated with exit code %d" %
--> 112                     (error_index, exitcode)
    113                 )
    114

Exception: process 1 terminated with exit code 17
```

**Comment by jysohn23** [comment]
Seems like it comes down to this error:

```
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

Was wondering whether it was a new behavior on PT/XLA side so rolled back to version `1.6` but that doesn't seem to help. Is this some issue / change you're aware of in PTL @zcain117 ?

**Comment by zcain117** [comment]
TPU CI for Pytorch Lightning still looks fine for training models this morning, e.g.: https://app.circleci.com/pipelines/github/PyTorchLightning/pytorch-lightning/13279/workflows/a0d4a620-9de4-4603-a955-63ead68910af/jobs/60067

Seems to be something specific to this model

**Comment by zcain117** [comment]
@asigalov61 could you try running on just 1 TPU core?  It would make the stack trace easier to follow.
Right now this looks like a change would need to happen in the Pytorch Lightning training code

**Comment by asigalov61** [comment]
@zcain117 (and  @jysohn23 ) Thanks, guys, for the quick response and for looking into it.

Unfortunatelly running on even 1 TPU core, produced the same error (see below). So am I to understand that it is on your end (PTXLA issue?)?

Thank you.

```
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-bc11544a2b6a> in <module>()
      1 #@title (OPTION 1) Train the model
----> 2 trainer.fit(model, train_loader)

14 frames
/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/states.py in wrapped_fn(self, *args, **kwargs)
     46             if entering is not None:
     47                 self.state = entering
---> 48             result = fn(self, *args, **kwargs)
     49 
     50             # The INTERRUPTED state can be set inside the run function. To indicate that run was interrupted

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders, datamodule)
   1076             self.accelerator_backend = TPUBackend(self)
   1077             self.accelerator_backend.setup()
-> 1078             self.accelerator_backend.train(model)
   1079             self.accelerator_backend.teardown(model)
   1080 

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py in train(self, model)
     85                 args=(model, self.trainer, self.mp_queue),
     86                 nprocs=self.trainer.tpu_cores,
---> 87                 start_method=self.start_method
     88             )
     89 

/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py in spawn(fn, args, nprocs, join, daemon, start_method)
    385   pf_cfg = _pre_fork_setup(nprocs)
    386   if pf_cfg.num_devices == 1:
--> 387     _start_fn(0, pf_cfg, fn, args)
    388   else:
    389     return torch.multiprocessing.start_processes(

/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py in _start_fn(index, pf_cfg, fn, args)
    322   # environment must be fully setup before doing so.
    323   _setup_replication()
--> 324   fn(gindex, *args)
    325 
    326 

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/tpu_backend.py in tpu_train_in_process(self, tpu_core_idx, model, trainer, mp_queue)
    110 
    111         # Run the pretrain routine
--> 112         results = trainer.run_pretrain_routine(model)
    113 
    114         # save weights at the end of training

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py in run_pretrain_routine(self, model)
   1237 
   1238         # CORE TRAINING LOOP
-> 1239         self.train()
   1240 
   1241     def _run_sanity_check(self, ref_model, model):

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in train(self)
    392                 # RUN TNG EPOCH
    393                 # -----------------
--> 394                 self.run_training_epoch()
    395 
    396                 if self.max_steps and self.max_steps <= self.global_step:

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in run_training_epoch(self)
    489             # TRAINING_STEP + TRAINING_STEP_END
    490             # ------------------------------------
--> 491             batch_output = self.run_training_batch(batch, batch_idx)
    492 
    493             # only track outputs when user implements training_epoch_end

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in run_training_batch(self, batch, batch_idx)
    842                     opt_idx,
    843                     optimizer,
--> 844                     self.hiddens
    845                 )
    846                 using_results_obj = isinstance(opt_closure_result.training_step_output, Result)

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py in optimizer_closure(self, split_batch, batch_idx, opt_idx, optimizer, hiddens)
   1047                 training_step_output_for_epoch_end = training_step_output_for_epoch_end.detach()
   1048             elif is_result_obj:
-> 1049                 training_step_output_for_epoch_end = copy(training_step_output)
   1050                 training_step_output_for_epoch_end.detach()
   1051             else:

/usr/lib/python3.6/copy.py in copy(x)
     86     copier = getattr(cls, "__copy__", None)
     87     if copier:
---> 88         return copier(x)
     89 
     90     reductor = dispatch_table.get(cls)

/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/step_result.py in __copy__(self)
    300         newone = type(self)()
    301         for k, v in self.items():
--> 302             newone[k] = copy(v)
    303         return newone
    304 

/usr/lib/python3.6/copy.py in copy(x)
     94         reductor = getattr(x, "__reduce_ex__", None)
     95         if reductor:
---> 96             rv = reductor(4)
     97         else:
     98             reductor = getattr(x, "__reduce__", None)

/usr/local/lib/python3.6/dist-packages/torch/tensor.py in __reduce_ex__(self, proto)
    101         #    and serialize them one by one.
    102         if self.device.type == 'xla':
--> 103             arg_xla = (self.cpu().numpy(),
    104                        self.dtype,
    105                        str(self.device),

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.`
```

**Comment by zcain117** [comment]
@ailzhang what do you think? Should we switch [this line](https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L103) to `self.cpu().detach().numpy()` like the error message suggests? Or is there something the model code is doing wrong?

**Comment by asigalov61** [comment]
@zcain117 Hey guys, I've tried to add .detach() before .numpy() and it seems to be working (I think). So it seems that the problem may be on your end in the /usr/local/lib/python3.6/dist-packages/torch/tensor.py in __reduce_ex__(self, proto)

Please correct me if I am wrong here as I am still not sure.

Also, right now it is running but the progress indicator does not show anything. (Still at 0) But if I interrupt, then it does say that it is saving checkpoint and stuff...

Hope this is helpful.

Thank you.

**Comment by asigalov61** [comment]
Here is a screenshot now:

![image](https://user-images.githubusercontent.com/56325539/94942488-3882e600-048b-11eb-8ced-510d5f8eff78.png)

**Comment by zcain117** [comment]
I was wondering, does the model still converge if you make this change?  I am worried that the `.detach()` will interrupt backpropagation somehow.

It's strange that we're seeing this error since @ailzhang added the code a year ago in [this PR](https://github.com/pytorch/pytorch/pull/27041/files) but we never saw this error message until now

**Comment by asigalov61** [comment]
@zcain117 I can't tell if the model is training/how is it training cuz the progress bar does not move from 0. I waited 30 min but the model would not produce good output so I am assuming that something is seriously wrong.

Maybe it is my code but I reverted it back to the original minGPT and everything works great now again. Albeit on TPU, so even your GPU implementation does not really provide a significant advantage (which is why I wanted to use TPU) over a vanilla minGPT IMHO and AFAIK.

However, it would be cool to see a TPU working in minGPT play_char colab on which mine is based also.

Thanks again for your responses and feedback.

Please let me know what you think/how to fix this issue for now.
