### ISSUE TITLE
Bug in "PyTorch/XLA ResNet18/CIFAR10 Training" tutorial if you change Model and Dataset

### ISSUE THREAD

**Issue by KaleabTessera** [pytorch/xla#2537]
## 🐛 Bug
If you use the exact code from the "PyTorch/XLA ResNet18/CIFAR10 Training" tutorial and change the Model to WideResnet-50 and use CIFAR-100, you get an exception. This only happens when using a larger model and `nprocs=8` (`nprocs=1` works), and it works with CIFAR-100 and resnet18 (with `nprocs=8` and `nprocs=1`). This happens at end of training, after all the epochs are complete.

## To Reproduce

1. Open "PyTorch/XLA ResNet18/CIFAR10 Training"
2. Change dataset to CIFAR-100
3. Change classifier to Wideresnet-50

Stack Trace and Error:
```
Metric: CompileTime
  TotalSamples: 6
  Accumulator: 08s530ms339.300us
  ValueRate: 163ms499.101us / second
  Rate: 0.130272 / second
  Percentiles: 1%=010ms926.800us; 5%=010ms926.800us; 10%=010ms926.800us; 20%=020ms526.260us; 50%=056ms788.776us; 80%=03s058ms765.514us; 90%=04s340ms925.836us; 95%=04s340ms925.836us; 99%=04s340ms925.836us
Metric: DeviceLockWait
  TotalSamples: 209
  Accumulator: 16s724ms621.345us
  ValueRate: 261ms355.679us / second
  Rate: 3.47397 / second
  Percentiles: 1%=000.907us; 5%=001.042us; 10%=001.091us; 20%=001.192us; 50%=074ms440.345us; 80%=174ms294.837us; 90%=188ms376.244us; 95%=199ms419.523us; 99%=272ms031.871us
Metric: ExecuteTime
  TotalSamples: 207
  Accumulator: 50s378ms384.330us
  ValueRate: 839ms145.287us / second
  Rate: 3.44797 / second
  Percentiles: 1%=061ms785.587us; 5%=061ms180.846us; 10%=061ms456.508us; 20%=062ms154.154us; 50%=078ms057.205us; 80%=198ms856.178us; 90%=199ms296.972us; 95%=268ms888.740us; 99%=283ms414.735us
Metric: InboundData
  TotalSamples: 81
  Accumulator: 636.00B
  ValueRate: 10.66B / second
  Rate: 1.35715 / second
  Percentiles: 1%=4.00B; 5%=8.00B; 10%=8.00B; 20%=8.00B; 50%=8.00B; 80%=8.00B; 90%=8.00B; 95%=8.00B; 99%=8.00B
Metric: InputOutputAliasCount
  TotalSamples: 6
  Accumulator: 653.00
  ValueRate: 15.16 / second
  Rate: 0.139328 / second
  Percentiles: 1%=1.00; 5%=1.00; 10%=1.00; 20%=1.00; 50%=119.00; 80%=245.00; 90%=245.00; 95%=245.00; 99%=245.00
Metric: IrValueTensorToXlaData
  TotalSamples: 100
  Accumulator: 01s374ms916.254us
  ValueRate: 989ms870.483us / second
  Rate: 71.9746 / second
  Percentiles: 1%=001ms125.839us; 5%=001ms287.394us; 10%=001ms367.935us; 20%=001ms471.603us; 50%=002ms800.983us; 80%=008ms339.876us; 90%=038ms812.238us; 95%=147ms367.188us; 99%=166ms239.476us
Metric: OutboundData
  TotalSamples: 136
  Accumulator: 291.62MB
  ValueRate: 4.82MB / second
  Rate: 2.24789 / second
  Percentiles: 1%=4.00B; 5%=64.00B; 10%=640.00B; 20%=640.00B; 50%=2.50KB; 80%=6.00MB; 90%=6.00MB; 95%=6.00MB; 99%=14.06MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 445
  Accumulator: 08s592ms232.410us
  ValueRate: 127ms611.617us / second
  Rate: 7.42103 / second
  Percentiles: 1%=542.695us; 5%=643.067us; 10%=746.877us; 20%=867.082us; 50%=002ms519.002us; 80%=029ms042.154us; 90%=074ms189.786us; 95%=085ms609.594us; 99%=093ms749.865us
Metric: TensorsGraphSize
  TotalSamples: 208
  Accumulator: 116258.00
  ValueRate: 1935.86 / second
  Rate: 3.4635 / second
  Percentiles: 1%=202.00; 5%=202.00; 10%=202.00; 20%=202.00; 50%=206.00; 80%=1751.00; 90%=1751.00; 95%=1751.00; 99%=1751.00
Metric: TransferFromServerTime
  TotalSamples: 81
  Accumulator: 870ms452.063us
  ValueRate: 015ms584.353us / second
  Rate: 1.35715 / second
  Percentiles: 1%=001ms098.024us; 5%=001ms431.002us; 10%=002ms505.495us; 20%=002ms574.951us; 50%=002ms833.373us; 80%=023ms379.156us; 90%=041ms884.847us; 95%=056ms269.343us; 99%=073ms944.690us
Metric: TransferToServerTime
  TotalSamples: 136
  Accumulator: 42s543ms410.441us
  ValueRate: 684ms412.321us / second
  Rate: 2.24055 / second
  Percentiles: 1%=001ms121.653us; 5%=001ms339.342us; 10%=001ms379.180us; 20%=002ms614.531us; 50%=002ms109.675us; 80%=374ms962.950us; 90%=465ms240.203us; 95%=479ms788.491us; 99%=720ms674.102us
Metric: TransferToServerTransformTime
  TotalSamples: 136
  Accumulator: 150ms813.882us
  ValueRate: 002ms476.216us / second
  Rate: 2.24789 / second
  Percentiles: 1%=107.942us; 5%=111.144us; 10%=115.256us; 20%=126.998us; 50%=165.817us; 80%=001ms394.833us; 90%=002ms711.442us; 95%=002ms050.985us; 99%=025ms733.367us
Counter: CachedCompile
  Value: 202
Counter: CreateCompileHandles
  Value: 6
Counter: CreateDataHandles
  Value: 15550
Counter: CreateXlaTensor
  Value: 27646
Counter: DestroyDataHandles
  Value: 15301
Counter: DestroyXlaTensor
  Value: 27400
Counter: DeviceDataCacheMiss
  Value: 4
Counter: MarkStep
  Value: 128
Counter: ReleaseDataHandles
  Value: 15301
Counter: UncachedCompile
  Value: 6
Counter: XRTAllocateFromTensor_Empty
  Value: 26
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtMemoryInfo_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 128
Counter: aten::_local_scalar_dense
  Value: 81
Counter: xla::_copy_from
  Value: 119
Counter: xla::_log_softmax
  Value: 48
Counter: xla::_log_softmax_backward_data
  Value: 48
Counter: xla::add
  Value: 5454
Counter: xla::add_
  Value: 8804
Counter: xla::addmm
  Value: 126
Counter: xla::as_strided
  Value: 119
Counter: xla::avg_pool2d
  Value: 126
Counter: xla::avg_pool2d_backward
  Value: 48
Counter: xla::clone
  Value: 62
Counter: xla::convolution_backward_overrideable
  Value: 1056
Counter: xla::convolution_overrideable
  Value: 2772
Counter: xla::empty
  Value: 2561
Counter: xla::empty_strided
  Value: 119
Counter: xla::eq
  Value: 78
Counter: xla::fill_
  Value: 48
Counter: xla::max
  Value: 78
Counter: xla::mm
  Value: 96
Counter: xla::mul_
  Value: 2914
Counter: xla::native_batch_norm
  Value: 2394
Counter: xla::native_batch_norm_backward
  Value: 912
Counter: xla::nll_loss_backward
  Value: 48
Counter: xla::nll_loss_forward
  Value: 48
Counter: xla::relu_
  Value: 2394
Counter: xla::sum
  Value: 126
Counter: xla::t
  Value: 270
Counter: xla::threshold_backward
  Value: 912
Counter: xla::view
  Value: 300
Counter: xla::zero_
  Value: 2914
Metric: XrtAllocateFromTensor
  TotalSamples: 25039
  Accumulator: 01m04s539ms622.317us
  Mean: 003ms922.722us
  StdDev: 002ms073.421us
  Rate: 86.7791 / second
  Percentiles: 25%=800.993us; 50%=004ms625.390us; 80%=005ms961.183us; 90%=005ms320.845us; 95%=006ms619.033us; 99%=007ms564.064us
Metric: XrtCompile
  TotalSamples: 392
  Accumulator: 12m05s161ms277.971us
  Mean: 02s850ms901.219us
  StdDev: 03s891ms594.827us
  Rate: 0.21581 / second
  Percentiles: 25%=003ms676.866us; 50%=011ms414.034us; 80%=04s401ms330.771us; 90%=05s016ms011.294us; 95%=09s445ms352.322us; 99%=10s627ms085.931us
Metric: XrtExecute
  TotalSamples: 13848
  Accumulator: 31m10s705ms600.849us
  Mean: 068ms333.623us
  StdDev: 008ms135.760us
  Rate: 88.3975 / second
  Percentiles: 25%=060ms201.894us; 50%=063ms350.175us; 80%=077ms552.919us; 90%=077ms779.856us; 95%=077ms924.231us; 99%=077ms346.364us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 5277
  Accumulator: 03s310ms712.205us
  Mean: 602.088us
  StdDev: 205.407us
  Rate: 1.48819 / second
  Percentiles: 25%=474.658us; 50%=572.079us; 80%=739.418us; 90%=826.685us; 95%=914.193us; 99%=001ms236.164us
Metric: XrtReleaseAllocation
  TotalSamples: 41432
  Accumulator: 15s844ms033.914us
  Mean: 105.679us
  StdDev: 116.838us
  Rate: 144.043 / second
  Percentiles: 25%=024.533us; 50%=042.077us; 80%=208.913us; 90%=248.743us; 95%=298.670us; 99%=507.579us

Exception in device=TPU:3: Cancelled: From /job:tpu_worker/replica:0/task:0:
Cancelled by TearDown.
	 [[{{node XRTExecute}}]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
Exception in device=TPU:2: Cancelled: From /job:tpu_worker/replica:0/task:0:
Cancelled by TearDown.
	 [[{{node XRTExecute}}]]  File "<ipython-input-8-fe0e48bf7337>", line 6, in _mp_fn
    accuracy, data, pred, target = train_resnet18()

  File "<ipython-input-6-07501835cb1c>", line 110, in train_resnet18
    accuracy, data, pred, target  = test_loop_fn(para_loader.per_device_loader(device))
  File "<ipython-input-6-07501835cb1c>", line 93, in test_loop_fn
    correct += pred.eq(target.view_as(pred)).sum().item()
Traceback (most recent call last):
RuntimeError: Cancelled: From /job:tpu_worker/replica:0/task:0:
Cancelled by TearDown.
	 [[{{node XRTExecute}}]]
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-8-fe0e48bf7337>", line 6, in _mp_fn
    accuracy, data, pred, target = train_resnet18()
  File "<ipython-input-6-07501835cb1c>", line 110, in train_resnet18
    accuracy, data, pred, target  = test_loop_fn(para_loader.per_device_loader(device))
  File "<ipython-input-6-07501835cb1c>", line 93, in test_loop_fn
    correct += pred.eq(target.view_as(pred)).sum().item()
RuntimeError: Cancelled: From /job:tpu_worker/replica:0/task:0:
Cancelled by TearDown.
	 [[{{node XRTExecute}}]]

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-12-fe0e48bf7337> in <module>()
     10 
     11 xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=8,
---> 12           start_method='fork')

2 frames
/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    110                 raise Exception(
    111                     "process %d terminated with exit code %d" %
--> 112                     (error_index, exitcode)
    113                 )
    114 

Exception: process 0 terminated with exit code 17
```

## Environment

 - Reproducible on XLA backend [CPU/TPU]: Colab TPU
 - torch_xla version: nightly (torch-xla-1.6+1bdbe54)

## Additional
This also happens even when setting the number of epochs to 1. 

Output of `free-h`:
```
Mem:            35G        1.1G         23G        936K         10G         33G
Swap:            0B          0B          0B
```

Output of `!cat /proc/cpuinfo | grep processor | wc -l` :
``` 40```

**Comment by KaleabTessera** [comment]
Adding `xm.rendezvous('checking_out')` to the end of `_mp_fn` worked.
