### ISSUE TITLE
Dataloader and Sampler Settings for Imagenet

### ISSUE THREAD

**Issue by KaleabTessera** [pytorch/xla#2574]
####  Is there an optimal `num_workers` and `num_replicas` config for imagenet dataloaders that doesn't cause memory issues? 

I am using the dataloaders and sampler settings from imagenet example as follows:
https://github.com/pytorch/xla/blob/9d7fbee365c28e3a0892b38543efbc3d2cf287e8/test/test_train_imagenet.py#L114-L164 

I am training a v3-8 tpu on imagenet, with a VM which has 30 gb of memory and a cpu with 8 cores. 

When running resnet50 with a batch size of `512, 1024 , 2048` , and `num_workers=4, pin_memory=True`  I keep getting out of memory errors, such as: 
``` 
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Exception in thread Thread-114:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 2929) exited unexpectedly
``` 
or 
```
Exception in thread Thread-114:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 139, in __getitem__
    sample = self.transform(sample)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 92, in __call__
    return F.to_tensor(pic)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 84, in to_tensor
    return img.float().div(255)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 602112 bytes. Error code 12 (Cannot allocate memory)
```

I have increased my shm memory to 120GB to address error one, but still no luck. I am considering increase my memory to address error 2. 

Is this caused by `num_replicas=xm.xrt_world_size()`? I assume it is making a copy of the data accross each core and this is causing memory issues since my code works when `nprocs=1`. Is there a suggested `num_workers` and `num_replicas` config that would well in my case?

**Comment by taylanbil** [comment]
typically we suggest a bigger machine than what you said (30 gb mem, 8 vcpus -- n1-standard-8?) for imagenet type workloads, which requires resources on the VM to preprocess the data. Having numworkers 4 (per process that drives the device, i.e. 32 total data preparation processes, + 8 that drives the training) is a bit much to handle for this VM spec it sounds like.

**Comment by KaleabTessera** [comment]
@taylanbil So I tried a n1-standard-16 instance (16 vCPUs, 60 GB memory). 

Even with this instance and increasing shm memory (`/dev/shm`) to 300GB, I still get this:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 9235) exited unexpectedly

ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 8962) exited unexpectedly


ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 9157) exited unexpectedly
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 172, in _worker
    batch = xm.send_cpu_data_to_device(batch, device)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 701, in send_cpu_data_to_device
    return ToXlaTensorArena(convert_fn, select_fn).transform(data)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 346, in transform
    self._convert()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 318, in _convert
    self._converted_tensors = self._convert_fn(self._tensors)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 696, in convert_fn
    return torch_xla._XLAC._xla_tensors_from_aten(tensors, devices)
MemoryError: std::bad_alloc
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 9082) exited unexpectedly

^CTraceback (most recent call last):
  File "main.py", line 224, in <module>
    main()
  File "main.py", line 86, in main
    train_tpu(config)
  File "/home/kaleabtessera/code/NAS-Research/run_tpu.py", line 203, in train_tpu
    start_method='fork')
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 300, in spawn
    start_method=start_method)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 78, in join
    timeout=timeout,
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 9302, 9303, 9304, 9305) exited unexpectedly
```
When checking the shm usage, it was only 1-5%, but it still resulted in the error above.

I also tried setting `num_wokers=2`, it ran very slowly, for a few steps, and eventually errored out: 
``` 
2 root error(s) found.
  (0) Resource exhausted: Failed to allocate request for 336.00MiB (352321536B) on device ordinal 0
	 [[{{node XRTAllocateFromTensor_33}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[XRTAllocateFromTensor_34_G169]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: Failed to allocate request for 336.00MiB (352321536B) on device ordinal 0
	 [[{{node XRTAllocateFromTensor_33}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored. vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	
	xla::util::MultiWait::Complete(std::function<void ()> const&)
	
	
	
	clone
*** End stack trace ***

Exception in thread Thread-115:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 172, in _worker
    batch = xm.send_cpu_data_to_device(batch, device)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 701, in send_cpu_data_to_device
    return ToXlaTensorArena(convert_fn, select_fn).transform(data)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 346, in transform
    self._convert()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 318, in _convert
    self._converted_tensors = self._convert_fn(self._tensors)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 696, in convert_fn
    return torch_xla._XLAC._xla_tensors_from_aten(tensors, devices)
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:382 : Check failed: session->session()->Run( session_work->feed_inputs, session_work->outputs_handles, &outputs) == ::tensorflow::Status::OK() (Resource exhausted: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Resource exhausted: Failed to allocate request for 336.00MiB (352321536B) on device ordinal 0
	 [[{{node XRTAllocateFromTensor_33}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[XRTAllocateFromTensor_34_G169]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: Failed to allocate request for 336.00MiB (352321536B) on device ordinal 0
	 [[{{node XRTAllocateFromTensor_33}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored. vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	
	xla::util::MultiWait::Complete(std::function<void ()> const&)
	
	
	
	clone
*** End stack trace ***


Exception in thread Thread-114:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 11519, 11520) exited unexpectedly
``` 

My VM on gcp is using the `pytorch-1-6-xla-v20201013` image, with python 3.7.8 and tpus are using pytorch-nightly build.

Could it be that I need to pass --shm-size somehow to this image? Could it be related to these other data loader pytorch issues - https://github.com/pytorch/pytorch/issues/28820, https://github.com/PyTorchLightning/pytorch-lightning/issues/4289, specifically https://github.com/pytorch/pytorch/issues/36515#issuecomment-613150083 and this PR https://github.com/pytorch/pytorch/pull/36542 ? 

Is there a working resnet50 on imagenet, using gcp example?

**Comment by taylanbil** [comment]
see [tutorial](https://cloud.google.com/tpu/docs/tutorials/resnet-pytorch), which suggests n1-highmem-96.

**Comment by KaleabTessera** [comment]
`n1-highmem-96` is really costly vm, even with `n1-highmem-96` and batch size of `128`, the training is really slow.

How can you efficiently train resnet50 on imagenet, using a `v3-8` tpu? Due to cost reasons, I am using a n1-highmem-16, and training using the official code as follows `python test_train_mp_imagenet.py --datadir=/home/kaleabtessera/datasets/imagenet --model=resnet50 --num_epochs=90 --num_workers=6 --batch_size=768 --log_steps=200`. 

Tensorflow manages to train resnet50 on imagenet, in like 24-30h, using a smaller vm and a v3 tpu. Using a bigger vm and pytorch takes a week? I have followed the discussion here https://github.com/pytorch/xla/issues/1858#issuecomment-607285898  and know that going forward Pytorch will have a similiar arch to that of tensorflow, but how we imagenet be training efficiently currently? Would using a `CachedDataset` help?

**Comment by KaleabTessera** [comment]
Running the imagenet is slower than expected.

After running
`python test_train_mp_imagenet.py --datadir=/home/kaleabtessera/datasets/imagenet --model=resnet50 --num_epochs=90 --num_workers=6 --batch_size=768 --log_steps=10 --env=XLA_USE_
BF16=1`

Here are logs. 
```
Epoch 1 train begin 11:09:40
| Training Device=xla:0/4 Epoch=1 Step=0 Loss=7.12500 Rate=2.54 GlobalRate=2.54 Time=11:14:42
| Training Device=xla:0/2 Epoch=1 Step=0 Loss=7.09375 Rate=2.55 GlobalRate=2.55 Time=11:14:42
| Training Device=xla:0/1 Epoch=1 Step=0 Loss=7.09375 Rate=2.54 GlobalRate=2.54 Time=11:14:42
| Training Device=xla:0/7 Epoch=1 Step=0 Loss=7.09375 Rate=2.54 GlobalRate=2.54 Time=11:14:42
| Training Device=xla:0/3 Epoch=1 Step=0 Loss=7.09375 Rate=2.54 GlobalRate=2.54 Time=11:14:42
| Training Device=xla:0/6 Epoch=1 Step=0 Loss=7.15625 Rate=2.54 GlobalRate=2.54 Time=11:14:42
| Training Device=xla:1/0 Epoch=1 Step=0 Loss=7.09375 Rate=2.54 GlobalRate=2.54 Time=11:14:42
| Training Device=xla:0/5 Epoch=1 Step=0 Loss=7.12500 Rate=2.54 GlobalRate=2.54 Time=11:14:42
| Training Device=xla:0/7 Epoch=1 Step=10 Loss=6.96875 Rate=12.87 GlobalRate=12.23 Time=11:21:10
| Training Device=xla:0/3 Epoch=1 Step=10 Loss=6.90625 Rate=12.87 GlobalRate=12.23 Time=11:21:10
| Training Device=xla:0/5 Epoch=1 Step=10 Loss=6.90625 Rate=12.87 GlobalRate=12.23 Time=11:21:10
| Training Device=xla:0/2 Epoch=1 Step=10 Loss=6.90625 Rate=12.87 GlobalRate=12.24 Time=11:21:10
| Training Device=xla:0/1 Epoch=1 Step=10 Loss=6.96875 Rate=12.87 GlobalRate=12.23 Time=11:21:10
| Training Device=xla:0/4 Epoch=1 Step=10 Loss=6.96875 Rate=12.87 GlobalRate=12.23 Time=11:21:10
| Training Device=xla:0/6 Epoch=1 Step=10 Loss=6.96875 Rate=12.87 GlobalRate=12.23 Time=11:21:10
| Training Device=xla:1/0 Epoch=1 Step=10 Loss=6.90625 Rate=12.87 GlobalRate=12.23 Time=11:21:10
/opt/conda/lib/python3.7/site-packages/PIL/TiffImagePlugin.py:792: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
| Training Device=xla:0/3 Epoch=1 Step=20 Loss=6.96875 Rate=11.24 GlobalRate=11.14 Time=11:33:47
| Training Device=xla:0/7 Epoch=1 Step=20 Loss=7.00000 Rate=11.24 GlobalRate=11.14 Time=11:33:47
| Training Device=xla:1/0 Epoch=1 Step=20 Loss=7.00000 Rate=11.24 GlobalRate=11.14 Time=11:33:47
| Training Device=xla:0/6 Epoch=1 Step=20 Loss=7.03125 Rate=11.24 GlobalRate=11.14 Time=11:33:47
| Training Device=xla:0/2 Epoch=1 Step=20 Loss=7.00000 Rate=11.24 GlobalRate=11.14 Time=11:33:47
| Training Device=xla:0/1 Epoch=1 Step=20 Loss=7.00000 Rate=11.24 GlobalRate=11.14 Time=11:33:47
| Training Device=xla:0/5 Epoch=1 Step=20 Loss=7.00000 Rate=11.24 GlobalRate=11.14 Time=11:33:47
| Training Device=xla:0/4 Epoch=1 Step=20 Loss=6.96875 Rate=11.24 GlobalRate=11.14 Time=11:33:47
| Training Device=xla:0/3 Epoch=1 Step=30 Loss=7.03125 Rate=10.66 GlobalRate=10.84 Time=11:46:15
| Training Device=xla:0/7 Epoch=1 Step=30 Loss=7.00000 Rate=10.66 GlobalRate=10.84 Time=11:46:15
| Training Device=xla:0/1 Epoch=1 Step=30 Loss=7.00000 Rate=10.66 GlobalRate=10.84 Time=11:46:15
| Training Device=xla:1/0 Epoch=1 Step=30 Loss=7.21875 Rate=10.66 GlobalRate=10.84 Time=11:46:15
| Training Device=xla:0/2 Epoch=1 Step=30 Loss=7.00000 Rate=10.66 GlobalRate=10.85 Time=11:46:15
| Training Device=xla:0/6 Epoch=1 Step=30 Loss=7.09375 Rate=10.66 GlobalRate=10.84 Time=11:46:15
| Training Device=xla:0/4 Epoch=1 Step=30 Loss=7.09375 Rate=10.66 GlobalRate=10.84 Time=11:46:15
| Training Device=xla:0/5 Epoch=1 Step=30 Loss=7.00000 Rate=10.66 GlobalRate=10.84 Time=11:46:15
``` 

Is this normal? I am using the nightly version of pytorch-xla on a n1-highmem-16, with pytorch version 1.6. At this rate this would take weeks to finish. If you use a smaller batch size, would that help. I thought smaller batch sizes take longer to train.

**Comment by KaleabTessera** [comment]
Following from https://github.com/pytorch/xla/issues/2530#issuecomment-707186540, I decreased the num_workers to 1 and it helped a little. 

I just think currently Pytorch TPUs operations are slower than TF TPU operations due to what was mentioned https://github.com/pytorch/xla/issues/2530#issuecomment-707186540.

**Comment by taylanbil** [comment]
resnet50 does train around ~10 hours or so with the configuration specified in the tutorial linked above, using `n1-highmem-96`.

The comment you linked is a difference in the current TF and PT setups, which is certainly a bigger problem for IO bound workloads (such as this one) compared to, for example, NLP workloads which are light in terms of data processing.

I'm not sure what setup https://github.com/pytorch/xla/issues/2574#issuecomment-717206885 was run on. I think with that large of a batch size, the tpu could be swapping tensors in and out of hbm which slows it down. Try reducing the batch size.

num workers will speed it up only if you have resources for it (cpus to drive it, memory to load the data, etc). There's certainly an optimal value to be found. if you have 8 cpus, probably that value is closer to 0. If you have an n1-highmem-96, you could go higher, to, say, 10 at least.

**Comment by zcain117** [comment]
for this model, the main bottleneck is image loading. More powerful VM = faster model. But you are right that right now we would expect PyTorch to be slower than Tensorflow.

The `num_workers` arg is number of workers per process. Since you have 8 TPU cores, there are 8 processes on your VM. I would recommend keeping the total `num_workers` less or equal number of CPU cores on your VM. Since you have 16 CPU cores, you could try `num_workers=2`. But it still will be pretty slow on this size VM. I didn't see any benefit for imagenet dataset + torchvision resnet50 beyond 64 total workers.

In the coming months, we hope to have a new way of using TPUs where you won't need such a powerful VM that is separate from your TPU

**Comment by jysohn23** [comment]
@KaleabTessera The PyTorch/TPU operations that run on device are **not** slower than that of TF/TPU operations running on the chip. However, here the different you're seeing is where the input pipeline is running. On TF/TPU your input pipeline (jpeg decoding and data augmentation) is running on the TPU host, whereas on PyTorch/XLA case it's running on your VM, giving you additional flexibility (in TF case you'd need to express your entire input pipeline in terms of TF ops). We plan on improving this experience in the coming future where you should be able to run your input pipeline on the TPU host as well for PyTorch/XLA.

**Comment by KaleabTessera** [comment]
Okay thanks for clarifying @taylanbil @zcain117 and @jysohn23 . For now, due to limited resources, I will have to use TF to run my imagenet exps. I will eagerly keep my eye out for the change that allows PyTorch input pipelines to be run on TPU!

**Comment by KaleabTessera** [comment]
Also @taylanbil  @zcain117  @jysohn23 , maybe add something in the docs or resnet50 tpu example explaining that it is currently slower than TF when having high IO and why, but there will be a new change coming out. I spend a lot of time trying to get similiar TPU performance to TF resnet50 examples and so I want to save other people time.

**Comment by VarunReigns** [comment]
Epoch 0/29
----------
---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
~\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in _try_get_data(self, timeout)
   1010         try:
-> 1011             data = self._data_queue.get(timeout=timeout)
   1012             return (True, data)

~\anaconda3\lib\multiprocessing\queues.py in get(self, block, timeout)
    113                     if not self._poll(timeout):
--> 114                         raise Empty
    115                 elif not self._poll():

Empty: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16944/47204633.py in <module>
      8 exp_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size=50, gamma=0.5)
      9 
---> 10 model = train_model(model, optimizer, exp_lr_scheduler,
     11                     num_epochs=30,
     12                     seg_loss=seg_loss,

~\AppData\Local\Temp/ipykernel_16944/1574865802.py in train_model(model, optimizer, scheduler, num_epochs, seg_loss, cl_loss, test_step)
     16         running_loss = 0.0
     17         # Iterate over data.
---> 18         for index, (inputs, labels, fbs) in enumerate(dataloaders['train']):
     19             labels = labels*100
     20             labels = skimage.measure.block_reduce(labels.cpu().numpy(),(1,1,1,4,4),np.sum)

~\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in __next__(self)
    528             if self._sampler_iter is None:
    529                 self._reset()
--> 530             data = self._next_data()
    531             self._num_yielded += 1
    532             if self._dataset_kind == _DatasetKind.Iterable and \

~\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in _next_data(self)
   1205 
   1206             assert not self._shutdown and self._tasks_outstanding > 0
-> 1207             idx, data = self._get_data()
   1208             self._tasks_outstanding -= 1
   1209             if self._dataset_kind == _DatasetKind.Iterable:

~\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in _get_data(self)
   1171         else:
   1172             while True:
-> 1173                 success, data = self._try_get_data()
   1174                 if success:
   1175                     return data

~\anaconda3\lib\site-packages\torch\utils\data\dataloader.py in _try_get_data(self, timeout)
   1022             if len(failed_workers) > 0:
   1023                 pids_str = ', '.join(str(w.pid) for w in failed_workers)
-> 1024                 raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
   1025             if isinstance(e, queue.Empty):
   1026                 return (False, None)

RuntimeError: DataLoader worker (pid(s) 16260, 9428, 17152, 3648, 7384, 14000, 13160, 13044, 9352, 10188, 3720, 5688, 12544, 7572, 11716, 7144) exited unexpectedly

​please help me with this error
