### ISSUE TITLE
[PT_BREAK] torch.transpose : Invalid Argument Crash

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/xla#2608]
Reference PR: https://github.com/pytorch/pytorch/pull/46041

https://app.circleci.com/jobs/github/pytorch/pytorch/8724656

```
======================================================================
Nov 05 14:55:32 ERROR [0.027s]: test_transpose_invalid_xla_float32 (__main__.TestTorchDeviceTypeXLA)
Nov 05 14:55:32 ----------------------------------------------------------------------
Nov 05 14:55:32 Traceback (most recent call last):
Nov 05 14:55:32   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 272, in instantiated_test
Nov 05 14:55:32     result = test_fn(self, *args)
Nov 05 14:55:32   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 19441, in test_transpose_invalid
Nov 05 14:55:32     fn(x, 5, 0)
Nov 05 14:55:32 RuntimeError: torch_xla/csrc/helpers.cpp:97 : Check failed: min_shape_dim <= dim && dim <= max_shape_dim 
Nov 05 14:55:32 *** Begin stack trace ***
Nov 05 14:55:32 	tensorflow::CurrentStackTrace[abi:cxx11]()
Nov 05 14:55:32 	torch_xla::XlaHelpers::GetCanonicalDimensionIndex(long long, long long)
Nov 05 14:55:32 	torch_xla::XlaHelpers::MakeTransposePermutation(long long, long long, long long)
Nov 05 14:55:32 	torch_xla::XLATensor::transpose(torch_xla::XLATensor const&, long long, long long)
Nov 05 14:55:32 	torch_xla::AtenXlaType::transpose(at::Tensor const&, long, long)
Nov 05 14:55:32 	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor (*)(at::Tensor const&, long, long), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long, long> >, at::Tensor (at::Tensor const&, long, long)>::call(c10::OperatorKernel*, at::Tensor const&, long, long)
Nov 05 14:55:32
```

**Comment by JackCaoG** [comment]
@kshitij12345 This actually is expected, the test passed a invalid dimension but xla error is not catched by `self.assertRaisesRegex` (This is a known behavior). Do you mind mark this test as `@onlyOnCPUAndCUDA` so it does not get run on xla? Thanks!

**Comment by kshitij12345** [comment]
Sure. Thanks!
