### ISSUE TITLE
Exception: process 5 terminated with exit code 17

### ISSUE THREAD

**Issue by rabeehk** [pytorch/xla#2645]
Hi
I am getting this error when trying to run a pytorch XLA code thank you for your help. I am using gcr.io/tpu-pytorch/xla:r1.7  image.

lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/root/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "xla_spawn.py", line 71, in <module>
    main()
  File "xla_spawn.py", line 67, in main
    xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 395, in spawn
    start_method=start_method)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 112, in join
    (error_index, exitcode)
Exception: process 5 terminated with exit code 17

**Comment by taylanbil** [comment]
the semaphore_tracker warnings are unrelated to the real error. You probably have zombie processes you'd need to clean up (run `ps aux | grep python` when you're not running anything to see if anything comes up -- if it does, run pkill -9 python to nuke them). If you scroll up further, the real traceback should appear?

**Comment by rabeehk** [comment]
thank you you were right, here is the actual cause of failure, thank you in
advance.


2 root error(s) found.
  (0) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[2,128,768]

         [[{{node XRTCompile}}]]
  (1) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[2,128,768]

         [[{{node XRTCompile}}]]
         [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File
"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py",
line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File
"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py",
line 324, in _start_fn
    fn(gindex, *args)
  File "/home/rabeeh/internship/seq2seq/evaluate/similarity_search.py",
line 176, in _mp_fn
    main()
  File "/home/rabeeh/internship/seq2seq/evaluate/similarity_search.py",
line 153, in main
    trainer.train()
  File "/home/rabeeh/internship/seq2seq/evaluate/trainer.py", line 96, in
train
    for step, (inputs, targets) in enumerate(epoch_iterator):
#self.train_dataloader):
  File
"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py",
line 31, in __next__
    return self.next()
  File
"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py",
line 37, in next
    xm.mark_step()
  File
"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/core/xla_model.py",
line 716, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Failed precondition: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[2,128,768]

         [[{{node XRTCompile}}]]
  (1) Failed precondition: Expected comparison type FLOAT or TOTALORDER.
actual: UNSIGNED
operand: f32[2,128,768]

         [[{{node XRTCompile}}]]
         [[XRTCompile_G6]]
0 successful operations.
0 derived errors ignored.
Traceback (most recent call last):
  File "xla_spawn.py", line 71, in <module>
    main()
  File "xla_spawn.py", line 67, in main
    xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
  File
"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py",
line 395, in spawn
    start_method=start_method)
  File
"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py",
line 157, in start_processes
    while not context.join():
  File
"/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py",
line 112, in join
    (error_index, exitcode)
Exception: process 7 terminated with exit code 17

**Comment by rabeehk** [comment]
I also put the main part of the codes, 

file similarity_search.py => the main file I call with xla_spawn.py 
```
# python similarity_search.py --model_name_or_path ../outputs/test_man1/ --encoder_pooling attentive --tasks "wmt16-ro-en" "wmt16-en-ro"
# python similarity_search.py --model_name_or_path t5-base --encoder_pooling max --tasks "imdb" --n_obs 10
import argparse
import torch
import logging

from seq2seq.models import T5Config
from seq2seq.tasks import TaskCollator
from transformers import AutoTokenizer
from transformers import set_seed


from torch.utils.data.dataloader import DataLoader
from seq2seq.models import POOLING_MAPPING
from seq2seq.tasks import AutoTask
from collections import defaultdict

# TODO: why relative does not work?
from seq2seq.evaluate.indexing import IndexCreate, IndexSearchMultiple, IndexPrintConfusionMatrix
from seq2seq.evaluate.utils import ClassificationCollator,  _setup_devices
from seq2seq.evaluate.trainer import Trainer
from seq2seq.evaluate.utils import get_train_sampler, is_world_process_zero, get_eval_sampler
from transformers.file_utils import is_torch_tpu_available

if is_torch_tpu_available():
    import torch_xla.core.xla_model as xm

logger = logging.getLogger(__name__)


def get_dataloader(args, task, tokenizer, split):
    """Returns a dataloader for the given split of the task."""
    TaskDataset = AutoTask.get(task)
    dataset = TaskDataset.get_dataset(split=split, n_obs=args.n_obs)
    category = TaskDataset.task.category
    if category == "classification":
        label_list = TaskDataset.label_list
        data_collator = ClassificationCollator(tokenizer, args, label_list, args.tpu_num_cores)
    else:
        data_collator = TaskCollator(tokenizer, args, args.tpu_num_cores)

    if split == "train":
        sampler = get_train_sampler(dataset)
    else:
        sampler = get_eval_sampler(dataset)

    dataloader = DataLoader(
        dataset,
        sampler=sampler,
        batch_size=args.train_batch_size,
        collate_fn=data_collator,
        drop_last=False,
        num_workers=args.num_workers,
    )
    return dataloader


def get_embeddings(args, dataloader, model):
    """Given a dataloader and a pretrained T5 model, obtains the embeddings."""
    model.eval()
    embeddings = []
    with torch.no_grad():
        for step, inputs in enumerate(dataloader):
            for key, value in inputs.items():
                inputs[key] = value.to(args.device)
            embedding = model(**inputs)[4]
            embeddings.append(embedding)
        embeddings = torch.cat(embeddings)
        return embeddings.cpu().numpy().squeeze()


def split_tasks_per_category(tasks):
    category_to_tasks = defaultdict(list)
    for task in tasks:
        category = AutoTask.get(task).task.category
        category_to_tasks[category].append(task)
    return category_to_tasks


def train_batch_size(args):
    args.train_batch_size = args.per_device_batch_size* max(1, args.n_gpus)
    if is_torch_tpu_available():
        train_batch_size = args.train_batch_size * xm.xrt_world_size()
    args.learning_rate = args.learning_rate*max(1, args.n_gpus)


def main():
    parser = argparse.ArgumentParser("Computes the similarity between different languages.")
    parser.add_argument('--dataloader_num_workers', type=int, default=0,
        help="Number of subprocesses to use for data loading (PyTorch only).\
         0 means that the data will be loaded in the main process.")
    parser.add_argument('--per_device_batch_size', type=int, default=128,
        help="Batch size per GPU core/CPU for training.")
    parser.add_argument("--num_workers", type=int, default=0, help="Defines the number of workers for\
        loading the data.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--model_name_or_path", type=str, required=True, help="Path to the trained model.")
    parser.add_argument("--cache_dir", type=str, default=None,
                        help="Where do you want to store the pretrained models downloaded from s3")
    #parser.add_argument("--batch_size", type=int, default=128, help="Batch size.")
    parser.add_argument("--max_source_length", type=int, default=128,
        help = "Maximum source sequence length.")
    parser.add_argument("--max_target_length", type=int, default=128,
        help = "Maximum target sequence length. ")
    parser.add_argument("--n_obs", type=int, default=None, help="Number of data samples.")
    parser.add_argument("--fixed_length_emb", default=True, action="store_true", help="Whether to learn fixed length"
        " embeddings or not. Goes into model.config.")
    parser.add_argument("--learning_rate", type=float, default=1e-3,
        help="Defines the learning rate.")
    parser.add_argument("--num_train_epochs", type=int, default=4,
        help="Defines the number of training epochs for training the classifier.")
    parser.add_argument("--hidden_dim", type=int, default=512,
        help="Defines the number of hidden states of the classifier.")
    parser.add_argument("--encoder_pooling", type=str, default="max",
        help=f"Pooling layer to use in case of learning fixed length embeddings. "
        f"Selected in {sorted(POOLING_MAPPING.keys())}. Goes into model.config.")
    parser.add_argument("--tpu_num_cores", default=0, help="Defines number of cores of TPU. can be 1 or 8.")
    parser.add_argument("--tasks", nargs="+", type=str, default=[], help=f"The list of tasks to consider.")
    args = parser.parse_args()
    args.device, args.n_gpus = _setup_devices()
    train_batch_size(args)

    # TODO: does logger needs to be set for multiple gpus?
    logger.warning("device: %s, n_gpu: %s", args.device, args.n_gpus)
    set_seed(args.seed)
    # TODO: this needs to work also with a name not a model directory.
    config = T5Config.from_pretrained(
        args.model_name_or_path,
        cache_dir=args.cache_dir,
    )
    if is_torch_tpu_available():
        # Set an xla_device flag on the model's config.
        # We'll find a more elegant and not need to do this in the future.
        config.xla_device = True

    extra_model_params = ("fixed_length_emb", "encoder_pooling")
    for p in extra_model_params:
        if getattr(args, p, None):
            assert hasattr(config, p), f"({config.__class__.__name__}) doesn't have a `{p}` attribute"
            setattr(config, p, getattr(args, p))
    # TODO: save the tokenizer too.
    tokenizer = AutoTokenizer.from_pretrained("t5-base", cache_dir=args.cache_dir)
    category_to_tasks = split_tasks_per_category(args.tasks)

    # Trains a classifier on top of freezed embeddings for classification tasks.
    if "classification" in category_to_tasks:
        for task in category_to_tasks["classification"]:
            train_dataloader = get_dataloader(args, task, tokenizer, split="train")
            eval_dataloader = get_dataloader(args, task, tokenizer, split="validation")
            args.num_classes = len(AutoTask.get(task).label_list)
            args.input_dim = config.d_model
            trainer = Trainer(args, config, train_dataloader, eval_dataloader)
            trainer.train()
            accuracy = trainer.evaluate()
            if is_world_process_zero():
                logger.warning("###### task {} accuracy {}".format(task, accuracy.item()))

    # Computes the similarity between language embeddings for translation tasks.
    if "translation" in category_to_tasks:
        embeddings = []
        for task in category_to_tasks["translation"]:
            dataloader = get_dataloader(args, task, tokenizer, split="validation")
            embeddings.append(get_embeddings(args, dataloader,  model))
        all_data = []
        all_index = []
        for embs in  embeddings:
            idx = IndexCreate(embs, 'FlatL2')
            all_data.append(embs)
            all_index.append(idx)
        err = IndexSearchMultiple(all_data, all_index)
        IndexPrintConfusionMatrix(err, category_to_tasks["translation"])


def _mp_fn(index):
    # For xla_spawn (TPUs)
    main()

if __name__ == "__main__":
    main()
```


file trainer.py => this is where I define the model:
```
"""Defines the classifier class to train a classifier on top of embeddings."""

import math
import torch
import torch.nn as nn
from transformers import AdamW
from seq2seq.models import T5ForConditionalGeneration

from torch.utils.data.dataloader import DataLoader
from torch.utils.data.distributed import DistributedSampler
from transformers import is_torch_tpu_available


if is_torch_tpu_available():
    import torch_xla.core.xla_model as xm
    import torch_xla.distributed.parallel_loader as pl

class ClassificationNet(nn.Module):
    def __init__(self, args, config):
        super(ClassificationNet, self).__init__()
        self.input_dim = args.input_dim
        self.hidden_dim = args.hidden_dim
        self.num_classes = args.num_classes
        self.encoder = T5ForConditionalGeneration.from_pretrained(
        args.model_name_or_path,
        from_tf=".ckpt" in args.model_name_or_path,
        config=config,
        cache_dir=args.cache_dir,
        )
        self.encoder = self.freeze(self.encoder)
        self.encoder = self.freeze(self.encoder)
        self.classifier = nn.Sequential(
            nn.Linear(self.input_dim, self.hidden_dim),
            nn.ReLU(),
            nn.Linear(self.hidden_dim, self.hidden_dim),
            nn.ReLU(),
            nn.Linear(self.hidden_dim, self.num_classes)
        )
        self.device = args.device

    def freeze(self, model):
        """Freezes the given model's parameters."""
        for p in model.parameters():
            p.requires_grad = False
        return model

    def forward(self, inputs):
        for key, value in inputs.items():
            inputs[key] = value.to(self.device)
        embedding = (self.encoder(**inputs)[4]).squeeze()
        output = self.classifier(embedding)
        return output



class Trainer(nn.Module):
    """This class trains a classifier on top of pretrained embeddings."""
    def __init__(self, args, config, train_dataloader, eval_dataloader):
        super(Trainer, self).__init__()
        self.learning_rate = args.learning_rate
        self.num_train_epochs = args.num_train_epochs
        self.model = ClassificationNet(args, config)
        self.device = args.device
        self.model.to(self.device)
        self.loss_fn = nn.CrossEntropyLoss()
        self.optimizer = AdamW(self.model.parameters(), lr=self.learning_rate)
        if args.n_gpus > 1:
            self.model = torch.nn.DataParallel(self.model)
        self.train_dataloader = train_dataloader
        self.eval_dataloader = eval_dataloader
        self.n_gpus = args.n_gpus


    def train(self):
        """Trains the classifier on the training embeddings."""
        num_train_epochs = math.ceil(self.num_train_epochs)
        #self.encoder.zero_grad()
        #self.encoder.train()
        # TODO: is this okay in multiple gpus?
        self.model.train()
        self.model.zero_grad()
        for epoch in range(num_train_epochs):

            if isinstance(self.train_dataloader, DataLoader) and \
                isinstance(self.train_dataloader.sampler, DistributedSampler):
                self.train_dataloader.sampler.set_epoch(epoch)
            if is_torch_tpu_available():
                parallel_loader = pl.ParallelLoader(self.train_dataloader, [self.device]).per_device_loader(
                    self.device
                )
                epoch_iterator = parallel_loader
            else:
                epoch_iterator = self.train_dataloader
            #steps_in_epoch = len(epoch_iterator)

            for step, (inputs, targets) in enumerate(epoch_iterator): #self.train_dataloader):
                output = self.model(inputs)
                targets = targets.to(self.device)
                self.optimizer.zero_grad()
                loss = self.loss_fn(output, targets)
                if self.n_gpus > 1:
                    loss = loss.mean()
                loss.backward()

                if is_torch_tpu_available():
                    xm.optimizer_step(self.optimizer)
                else:
                    self.optimizer.step()

                self.model.zero_grad()

    def evaluate(self):
        """Evaluates the classifier accuracy on the given inputs."""
        self.model.eval() #encoder.eval()
        correct = 0
        with torch.no_grad():
            for step, (inputs, targets) in enumerate(self.eval_dataloader):
                output = self.model(inputs)
                targets = targets.to(self.device)
                predictions = output.data.max(1)[1]
                correct += predictions.long().eq(targets.data.long()).cpu().sum()
        num_samples = len(self.eval_dataloader.dataset)
        accuracy = correct/num_samples
        return accuracy
```

thank you

**Comment by JackCaoG** [comment]
I checked our test and I saw the similar failure. I will update when I have a better idea.

**Comment by taylanbil** [comment]
related to https://github.com/pytorch/xla/issues/2641 ?

**Comment by JackCaoG** [comment]
@rabeehk Could you try today's nightly? That error should be gone.
