### ISSUE TITLE
Failed to connect to client mesh master

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/xla#2651]
Hi
I tried to put "xm.rendezvous('done')" after function of xla_spawn and I am getting this error, is there an issue with this operation? thank you 

```
Traceback (most recent call last):
  File "/home/rabeeh//internship/seq2seq/xla_spawn.py", line 106, in <module>
    main()
  File "/home/rabeeh//internship/seq2seq/xla_spawn.py", line 91, in main
    xm.rendezvous('done')
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 861, in rendezvous
    return torch_xla._XLAC._xla_rendezvous(get_ordinal(), tag, payload, replicas)
RuntimeError: tensorflow/compiler/xla/xla_client/mesh_service.cc:316 : Check failed: impl_->channel->WaitForConnected( std::chrono::system_clock::now() + std::chrono::seconds(connect_wait_seconds)) 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	xla::service::MeshClient::MeshClient(std::string const&)
	xla::service::MeshClient::Get()
	
	
	_PyCFunction_FastCallDict
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main
	
*** End stack trace ***
Failed to connect to client mesh master: attentive-proj-32-ig-pj4f.c.ruse-xgcp.internal:38973

```

**Comment by taylanbil** [comment]
Rendezvous cannot come after spawned processes have completed. The whole point of rendezvous is to sync the processes that are running in parallel. Once xmp.spawn returns, there's no subprocesses running.
