### ISSUE TITLE
Issues with running the tutorial of running on POD

### ISSUE THREAD

**Issue by rabeehk** [pytorch/xla#2665]
Hi
I followed the tutorial https://cloud.google.com/tpu/docs/tutorials/pytorch-pod till this step:

`gcloud compute ssh instance-name --zone=us-central1-a
`
I am getting this error, thank you for your help

```
ERROR: (gcloud.compute.start-iap-tunnel) Error while connecting [4003: 'failed to connect to backend'].
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

**Comment by rabeehk** [comment]
After ssh to one of the instances to run the codes I am also getting this error:

(torch-xla-1.7) rabeeh@podgroup-cl7h:~$ python -m torch_xla.distributed.xla_dist       --tpu=tpu-pod           --env XLA_USE_BF16=1         -- python /usr/share/torch-xla-1.7/pytorch/xla/test/test_train_mp_imagenet.py       --fake_data
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/cloud_tpu_client/client.py", line 237, in _fetch_cloud_tpu_metadata
    return r.execute()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/googleapiclient/http.py", line 898, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://tpu.googleapis.com/v1/projects/ruse-xgcp/locations/europe-west4-a/nodes/tpu-pod?alt=json returned "Resource 'projects/ruse-xgcp/locations/europe-west4-a/nodes/tpu-pod' was not found". Details: "[{'@type': 'type.googleapis.com/google.rpc.ResourceInfo', 'resourceName': 'projects/ruse-xgcp/locations/europe-west4-a/nodes/tpu-pod'}]">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_dist.py", line 520, in <module>
    cluster = cluster_resolver.get_cluster()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/cluster.py", line 396, in get_cluster
    service_workers = self.get_service_workers()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/cluster.py", line 378, in get_service_workers
    xu.parallel_work(len(self._tpus), add_service_worker, self._tpus)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/utils/utils.py", line 293, in parallel_work
    return [res for res in results]  # Iterating to re-raise any exceptions
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/utils/utils.py", line 293, in <listcomp>
    return [res for res in results]  # Iterating to re-raise any exceptions
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/cluster.py", line 354, in add_service_worker
    if ctc.state() != 'READY':
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/cloud_tpu_client/client.py", line 274, in state
    return self._get_tpu_property('state')
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/cloud_tpu_client/client.py", line 245, in _get_tpu_property
    metadata = self._fetch_cloud_tpu_metadata()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/cloud_tpu_client/client.py", line 241, in _fetch_cloud_tpu_metadata
    'constructor. Exception: %s' % (self._tpu, e))
ValueError: Could not lookup TPU metadata from name 'tpu-pod'. Please doublecheck the tpu argument in the TPUClusterResolver constructor. Exception: <HttpError 404 when requesting https://tpu.googleapis.com/v1/projects/ruse-xgcp/locations/europe-west4-a/nodes/tpu-pod?alt=json returned "Resource 'projects/ruse-xgcp/locations/europe-west4-a/nodes/tpu-pod' was not found". Details: "[{'@type': 'type.googleapis.com/google.rpc.ResourceInfo', 'resourceName': 'projects/ruse-xgcp/locations/europe-west4-a/nodes/tpu-pod'}]">
