### ISSUE TITLE
ValueError: range() arg 3 must not be zero when running on a POD

### ISSUE THREAD

**Issue by rabeehk** [pytorch/xla#2666]
Hi
I followed the running on POD tutorial to run my codes on POD, they run fine on 1 TPU, when I run the codes I get following error:
```
f1df5ac2e4c3759fadea38f6cb29c4. Subsequent calls will reuse this data.
2020-12-05 12:02:26 10.164.15.249 [0] Traceback (most recent call last):
2020-12-05 12:02:26 10.164.15.249 [0]   File "/home/rabeeh/ruse/seq2seq/finetune_t5_trainer.py", line 268, in <module>
2020-12-05 12:02:26 10.164.15.249 [0]     main()
2020-12-05 12:02:26 10.164.15.249 [0]   File "/home/rabeeh/ruse/seq2seq/finetune_t5_trainer.py", line 191, in main
2020-12-05 12:02:26 10.164.15.249 [0]     model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
2020-12-05 12:02:26 10.164.15.249 [0]   File "/home/rabeeh/ruse/seq2seq/trainers/trainer.py", line 799, in train
2020-12-05 12:02:26 10.164.15.249 [0]     xm.optimizer_step(self.optimizer)
2020-12-05 12:02:26 10.164.15.249 [0]   File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 778, in optimizer_step
2020-12-05 12:02:26 10.164.15.249 [0]     reduce_gradients(optimizer, groups=groups)
2020-12-05 12:02:26 10.164.15.249 [0]   File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 747, in reduce_gradients
2020-12-05 12:02:26 10.164.15.249 [0]     cctx = CollectiveContext()
2020-12-05 12:02:26 10.164.15.249 [0]   File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 76, in __init__
2020-12-05 12:02:26 10.164.15.249 [0]     self.replica_devcount, self.world_size)
2020-12-05 12:02:26 10.164.15.249 [0]   File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 110, in _make_interhost_group
2020-12-05 12:02:26 10.164.15.249 [0]     ranks = tuple(range(0, world_size, replica_devcount))
2020-12-05 12:02:26 10.164.15.249 [0] ValueError: range() arg 3 must not be zero
  0%|          | 0/4602 [00:01<?, ?it/s]
Process Process-1:
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_dist.py", line 388, in _run_cmd
    self._start_run(script_map)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_dist.py", line 383, in _start_run
    len(script_map), _run_script, script_map.values(), script_map.keys())
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/utils/utils.py", line 293, in parallel_work
    return [res for res in results]  # Iterating to re-raise any exceptions
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/utils/utils.py", line 293, in <listcomp>
    return [res for res in results]  # Iterating to re-raise any exceptions
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_dist.py", line 369, in _run_script
    'Remote command exitted with code: {}'.format(exit_code))
RuntimeError: Remote command exitted with code: 1
```

to reproduce the error, please run:

```
git clone https://github.com/google-research/ruse.git
go to multitask branch 
python setup.py 
and then run: 
python -m torch_xla.distributed.xla_dist \
      --tpu=$TPU_NAME \
      --conda-env=torch-xla-1.7 \
      --env XLA_USE_BF16=1 \
      -- python /home/rabeeh/ruse/seq2seq/finetune_t5_trainer.py /home/rabeeh/ruse/seq2seq/configs/mnli/tpu/finetune-3e-3.json 
```

thank you.

**Comment by taylanbil** [comment]
so, `replica_devcount` is 0.

Comes from [this line](https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L56).

@jysohn23 can you take a look?

@rabeehk w/o this file: `/home/rabeeh/ruse/seq2seq/configs/mnli/tpu/finetune-3e-3.json`, we cannot repro this.

**Comment by jysohn23** [comment]
Taking a look at https://github.com/google-research/ruse/tree/multitask/seq2seq I don't see a single call to get any xla device (either [`xla_device()` call](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/google-research/ruse%24%40multitask+xla_device&patternType=literal) or [device='xla'](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/google-research/ruse%24%40multitask+xla&patternType=literal#9)).

Seems like you just copied HugginFace's code, but I think you may have missed some parts like [this](https://sourcegraph.com/github.com/huggingface/transformers@b08843c/-/blob/src/transformers/training_args.py?subtree=true#L425:25) were the device gets created by XLA?

**Comment by taylanbil** [comment]
Per @rabeehk , ruse imports from HF, and things are sent to tpu properly.

We looked offline at the logs, and the instance group was set up wrong. only the main vm had the code, so remote processes exited, and run errored @ the first communication point.
