### ISSUE TITLE
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage while doing loss.backward()

### ISSUE THREAD

**Issue by mobassir94** [pytorch/xla#2704]
i was trying pytorch xla for image classification problem in kaggle notebook using tpu v3-8, during training i get **RuntimeError: Cannot access data pointer of Tensor that doesn't have storage** and seems like the error is coming from loss.backward()
full error log : 
```

Training with 0 started
17117 4280
mydevice xla:1
Training with 0 started
17117 4280
mydevice xla:0
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/tf_efficientnet_b4_ns-d6313a46.pth" to /root/.cache/torch/hub/checkpoints/tf_efficientnet_b4_ns-d6313a46.pth
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/tf_efficientnet_b4_ns-d6313a46.pth" to /root/.cache/torch/hub/checkpoints/tf_efficientnet_b4_ns-d6313a46.pth
Training with 0 started
17117 4280
Training with 0 started
17117 4280
mydevice xla:0
Training with 0 started
17117 4280
Training with 0 started
17117 4280
Training with 0 started
mydevice xla:0
17117 4280
mydevice xla:0
mydevice xla:0
mydevice xla:0
Training with 0 started
17117 4280
mydevice xla:0
  0%|          | 0/2140 [00:55<?, ?it/s]
Exception in device=TPU:0: Cannot access data pointer of Tensor that doesn't have storage
  0%|          | 0/2140 [00:48<?, ?it/s]Traceback (most recent call last):
  0%|          | 0/2140 [00:52<?, ?it/s]  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  0%|          | 0/2140 [00:51<?, ?it/s]

Exception in device=TPU:5: Cannot access data pointer of Tensor that doesn't have storage


Exception in device=TPU:3: Cannot access data pointer of Tensor that doesn't have storage
Exception in device=TPU:1: Cannot access data pointer of Tensor that doesn't have storage

Exception in device=TPU:7: Cannot access data pointer of Tensor that doesn't have storage
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
Traceback (most recent call last):
Exception in device=TPU:2: Cannot access data pointer of Tensor that doesn't have storage
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<ipython-input-21-fbdc51ff9648>", line 6, in _mp_fn
    res = train_model()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "<ipython-input-20-84fe7c942c9e>", line 50, in train_model
    train_one_epoch(epoch, model, loss_tr, optimizer, para_loader.per_device_loader(device), device, scheduler=scheduler, schd_batch_update=False)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-21-fbdc51ff9648>", line 6, in _mp_fn
    res = train_model()
  File "<ipython-input-20-84fe7c942c9e>", line 50, in train_model
    train_one_epoch(epoch, model, loss_tr, optimizer, para_loader.per_device_loader(device), device, scheduler=scheduler, schd_batch_update=False)
  0%|          | 0/2140 [00:51<?, ?it/s]  File "<ipython-input-21-fbdc51ff9648>", line 6, in _mp_fn
    res = train_model()
  File "<ipython-input-19-9eb2133c7656>", line 70, in train_one_epoch
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "<ipython-input-20-84fe7c942c9e>", line 50, in train_model
    train_one_epoch(epoch, model, loss_tr, optimizer, para_loader.per_device_loader(device), device, scheduler=scheduler, schd_batch_update=False)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-19-9eb2133c7656>", line 70, in train_one_epoch
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "<ipython-input-21-fbdc51ff9648>", line 6, in _mp_fn
    res = train_model()
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "<ipython-input-19-9eb2133c7656>", line 70, in train_one_epoch
    loss.backward()
  File "<ipython-input-21-fbdc51ff9648>", line 6, in _mp_fn
    res = train_model()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
  0%|          | 0/2140 [00:51<?, ?it/s]  File "<ipython-input-19-9eb2133c7656>", line 70, in train_one_epoch
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "<ipython-input-20-84fe7c942c9e>", line 50, in train_model
    train_one_epoch(epoch, model, loss_tr, optimizer, para_loader.per_device_loader(device), device, scheduler=scheduler, schd_batch_update=False)
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "<ipython-input-20-84fe7c942c9e>", line 50, in train_model
    train_one_epoch(epoch, model, loss_tr, optimizer, para_loader.per_device_loader(device), device, scheduler=scheduler, schd_batch_update=False)
  File "<ipython-input-19-9eb2133c7656>", line 70, in train_one_epoch
    loss.backward()
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag

Exception in device=TPU:6: Cannot access data pointer of Tensor that doesn't have storage
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "<ipython-input-21-fbdc51ff9648>", line 6, in _mp_fn
    res = train_model()
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
Traceback (most recent call last):
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
  File "<ipython-input-20-84fe7c942c9e>", line 50, in train_model
    train_one_epoch(epoch, model, loss_tr, optimizer, para_loader.per_device_loader(device), device, scheduler=scheduler, schd_batch_update=False)

  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
Exception in device=TPU:4: Cannot access data pointer of Tensor that doesn't have storage
  File "<ipython-input-19-9eb2133c7656>", line 70, in train_one_epoch
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "<ipython-input-21-fbdc51ff9648>", line 6, in _mp_fn
    res = train_model()
  File "<ipython-input-20-84fe7c942c9e>", line 50, in train_model
    train_one_epoch(epoch, model, loss_tr, optimizer, para_loader.per_device_loader(device), device, scheduler=scheduler, schd_batch_update=False)
  File "<ipython-input-19-9eb2133c7656>", line 70, in train_one_epoch
    loss.backward()
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-21-fbdc51ff9648>", line 6, in _mp_fn
    res = train_model()
  File "<ipython-input-20-84fe7c942c9e>", line 50, in train_model
    train_one_epoch(epoch, model, loss_tr, optimizer, para_loader.per_device_loader(device), device, scheduler=scheduler, schd_batch_update=False)
  File "<ipython-input-19-9eb2133c7656>", line 70, in train_one_epoch
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-21-fbdc51ff9648> in <module>
      7 
      8 FLAGS={}
----> 9 xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=8, start_method='fork')

/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py in spawn(fn, args, nprocs, join, daemon, start_method)
    393         join=join,
    394         daemon=daemon,
--> 395         start_method=start_method)
    396 
    397 

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    155 
    156     # Loop on join until it returns True or raises an exception.
--> 157     while not context.join():
    158         pass
    159 

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    110                 raise Exception(
    111                     "process %d terminated with exit code %d" %
--> 112                     (error_index, exitcode)
    113                 )
    114 

Exception: process 5 terminated with exit code 17
```

i have uploaded my code in colab to share that with you,here it is : https://colab.research.google.com/drive/1LUpYywvUqCPQE_RaHWutEF2Pcdh81ZKU?usp=sharing

is there any implementation bug?

**Comment by kozodoi** [comment]
I encountered the same issue a few days ago when trying to do `loss.backward()` with `nn.CrossEntropyLoss()` on xla 1.7. So far, I have not been able to find a solution.

**Comment by JackCaoG** [comment]
The failure pattern is similar to https://github.com/pytorch/xla/issues/2652. The solution is likely bring back some default kernel to the pytorch. I will leave this to @ailzhang
