### ISSUE TITLE
[PT_BREAK] Add `dtype` kwarg support for `torch.sin`.

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/xla#2727]
PR https://github.com/pytorch/pytorch/pull/49404 adds `dtype` kwarg support for `torch.sin`. 

However this  breaks the XLA build.

```
Jan 12 09:39:12 Generated 1853 wrappers for /var/lib/jenkins/workspace/xla/scripts/../../build/aten/src/ATen/RegistrationDeclarations.h
Jan 12 09:39:12 AtenXlaType function missed override: Tensor sin(const Tensor& self); // sin(Tensor)->Tensor
Jan 12 09:39:12 Traceback (most recent call last):
Jan 12 09:39:12   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1195, in <module>
Jan 12 09:39:12     generate(args)
Jan 12 09:39:12   File "/var/lib/jenkins/workspace/xla/scripts/gen.py", line 1165, in generate
Jan 12 09:39:12     assert check_overrides(overrides, overridden)
Jan 12 09:39:12 AssertionError
Jan 12 09:39:13 Building torch_xla version: 1.6
Jan 12 09:39:13 XLA Commit ID: e62799edcc8ef199e3903ef778b6715aa8a16468
Jan 12 09:39:13 PyTorch Commit ID: 11c465f2b23fea06ee5d2ac4b298cd15b410e8c0
Jan 12 09:39:13 Failed to generate ATEN bindings: ['/var/lib/jenkins/workspace/xla/scripts/generate_code.sh']
Jan 12 09:39:13 =================== sccache compilation log ===================
```

**Comment by JackCaoG** [comment]
@kshitij12345 If I understand i correctly, when `dtype` is provided, we need to cast the `out` to be that `dtype`, otherwise we don't modify the `out` tensor type. Does that sounds right?

**Comment by JackCaoG** [comment]
There is issue with `RuntimeError: Cannot access data pointer of Tensor that doesn't have storage`, I replied in https://github.com/pytorch/pytorch/pull/49404#issuecomment-759131139

**Comment by JackCaoG** [comment]
Close this issue as upstream torch pr is discarded
