### ISSUE TITLE
Does the xla support RoIAlign now?

### ISSUE THREAD

**Issue by TianshengSun** [pytorch/xla#2734]
## ❓ Questions and Help
I have to use RoIAlign in my project. but the RoIAlign needs cuda. So is there any solution for RoIAlign?

**Comment by Huntersts** [comment]
There is a error happened when I running the model's forward. The log as follows:
`Traceback (most recent call last):
  File "scripts/train.py", line 44, in <module>
    trainer(cfg)
  File "./train_net.py", line 189, in trainer
    xmp.spawn(train_net, args=(flags, ), nprocs=1, start_method='fork')
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 386, in spawn
    _start_fn(0, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "./train_net.py", line 132, in train_net
    train_info = train(training_loader, model, device, optimizer, epoch, cfg)
  File "./train_net.py", line 216, in train_volleyball
    actions_scores, activities_scores = model((batch_data[0], batch_data[1]))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./base_model.py", line 134, in forward
    boxes_idx_flat)  # B*T*N, D, K, K,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/roi_align-0.0.2-py3.6-linux-x86_64.egg/roi_align/roi_align.py", line 48, in forward
    return CropAndResizeFunction.apply(featuremap, boxes, box_ind, self.crop_height, self.crop_width, self.extrapolation_value)
  File "/usr/local/lib/python3.6/dist-packages/roi_align-0.0.2-py3.6-linux-x86_64.egg/roi_align/crop_and_resize.py", line 29, in forward
    ctx.extrapolation_value, ctx.crop_height, ctx.crop_width, crops)
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage`
According to the log above, I think the case of error is this:
`  File "./base_model.py", line 134, in forward
    boxes_idx_flat)  # B*T*N, D, K, K,`
And in the code it is this:
`
    ...
    self.roi_align = RoIAlign(*self.cfg.crop_size)
    ...
    boxes_features = self.roi_align(features_multiscale,
                                        boxes_in_flat,
                                        boxes_idx_flat)  # B*T*N, D, K, K,

`
This is the [link](https://github.com/longcw/RoIAlign.pytorch.git) of the roi_align that I am using.

The code are running on the Colab and the  nprocs=1.

Waiting for reply.

**Comment by JackCaoG** [comment]
Similar to https://github.com/pytorch/xla/issues/2652, It is likely Pytorch needs to add some default kernel back. @ailzhang could you take a look?
