### ISSUE TITLE
debug_macros.h:27 : Check failed

### ISSUE THREAD

**Issue by TianshengSun** [pytorch/xla#2737]
## ❓ Questions and Help
When I running my code, I meet this problem. I don't know how to deal with that.
It happened then I running 
```python
activities_loss = F.cross_entropy(activities_scores, activities_in, weight=activity_weights)
```
activities_scores: shape=(12, 9) dtype=(torch.float32)
activities_in: shape=(12, 9) dtype=(torch.int64)

Waiting for reply.

The whole error information as follows:
```python
Exception in device=TPU:0: /pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/xla_client/debug_macros.h:27 : Check failed: status.status() == ::tensorflow::Status::OK() (Invalid argument: Size of broadcast_dimensions has to match operand's rank; operand rank: 2, size of broadcast_dimensions 1. vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	xla::Shape const* ConsumeValue<xla::Shape const*>(stream_executor::port::StatusOr<xla::Shape const*>&&)
	torch_xla::XlaHelpers::ShapeOfXlaOp(xla::XlaOp)
	torch_xla::ir::ops::InferOutputShape(absl::lts_2020_02_25::Span<xla::Shape const>, std::function<xla::XlaOp (absl::lts_2020_02_25::Span<xla::XlaOp const>)> const&)
	
	torch_xla::ir::Node::GetOpShape(std::function<xla::Shape ()> const&) const
	torch_xla::ir::Node::Node(torch_xla::ir::OpKind, absl::lts_2020_02_25::Span<torch_xla::ir::Value const>, std::function<xla::Shape ()> const&, unsigned long, absl::lts_2020_02_25::uint128)
	torch_xla::ir::ops::NllLoss::NllLoss(torch_xla::ir::Value const&, torch_xla::ir::Value const&, absl::lts_2020_02_25::optional<torch_xla::ir::Value> const&, torch_xla::ReductionMode, int)
	torch_xla::XLATensor::nll_loss(torch_xla::XLATensor const&, torch_xla::XLATensor const&, torch_xla::XLATensor const&, long, int)
	torch_xla::AtenXlaType::nll_loss_forward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::tuple<at::Tensor, at::Tensor> (*)(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long), std::tuple<at::Tensor, at::Tensor>, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long> >, std::tuple<at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	
	at::nll_loss_forward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	
	
	
	at::nll_loss_forward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	at::native::nll_loss(at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long)
	
	
	
	at::nll_loss(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	PyEval_EvalCode
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main
	_start
*** End stack trace ***

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "./train_net.py", line 127, in train_net
    train_info = train(training_loader, model, device, optimizer, epoch, cfg)
  File "./train_net.py", line 218, in train_volleyball
    actions_loss = F.cross_entropy(actions_scores, actions_in, weight=actions_weights)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2632, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2393, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: /pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/xla_client/debug_macros.h:27 : Check failed: status.status() == ::tensorflow::Status::OK() (Invalid argument: Size of broadcast_dimensions has to match operand's rank; operand rank: 2, size of broadcast_dimensions 1. vs. OK)
*** Begin stack trace ***
	tensorflow::CurrentStackTrace()
	xla::Shape const* ConsumeValue<xla::Shape const*>(stream_executor::port::StatusOr<xla::Shape const*>&&)
	torch_xla::XlaHelpers::ShapeOfXlaOp(xla::XlaOp)
	torch_xla::ir::ops::InferOutputShape(absl::lts_2020_02_25::Span<xla::Shape const>, std::function<xla::XlaOp (absl::lts_2020_02_25::Span<xla::XlaOp const>)> const&)
	
	torch_xla::ir::Node::GetOpShape(std::function<xla::Shape ()> const&) const
	torch_xla::ir::Node::Node(torch_xla::ir::OpKind, absl::lts_2020_02_25::Span<torch_xla::ir::Value const>, std::function<xla::Shape ()> const&, unsigned long, absl::lts_2020_02_25::uint128)
	torch_xla::ir::ops::NllLoss::NllLoss(torch_xla::ir::Value const&, torch_xla::ir::Value const&, absl::lts_2020_02_25::optional<torch_xla::ir::Value> const&, torch_xla::ReductionMode, int)
	torch_xla::XLATensor::nll_loss(torch_xla::XLATensor const&, torch_xla::XLATensor const&, torch_xla::XLATensor const&, long, int)
	torch_xla::AtenXlaType::nll_loss_forward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<std::tuple<at::Tensor, at::Tensor> (*)(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long), std::tuple<at::Tensor, at::Tensor>, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long> >, std::tuple<at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	
	at::nll_loss_forward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	
	
	
	at::nll_loss_forward(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	at::native::nll_loss(at::Tensor const&, at::Tensor const&, at::Tensor const&, long, long)
	
	
	
	at::nll_loss(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long, long)
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	_PyFunction_FastCallDict
	
	
	
	_PyObject_FastCallKeywords
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	PyEval_EvalCode
	
	PyRun_FileExFlags
	PyRun_SimpleFileExFlags
	Py_Main
	main
	__libc_start_main
	_start
*** End stack trace ***

Traceback (most recent call last):
  File "scripts/train_volleyball_stage1.py", line 44, in <module>
    trainer(cfg)
  File "./train_net.py", line 184, in trainer
    xmp.spawn(train_net, args=(flags, ), nprocs=8, start_method='fork')
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 394, in spawn
    start_method=start_method)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 144, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 17
```

**Comment by JackCaoG** [comment]
Hi, can you provide a small repo so we can better debug this problem? The real error is 
```
Invalid argument: Size of broadcast_dimensions has to match operand's rank; operand rank: 2, size of broadcast_dimensions 1. vs. OK)
```

which is likely came from https://github.com/tensorflow/tensorflow/blob/e42383872c2152a3d5c0c16c964129b0ebd8fefc/tensorflow/compiler/xla/client/xla_builder.cc#L901
