### ISSUE TITLE
How to change torch tpu v3 baseline into torch tpu pod v2?

### ISSUE THREAD

**Issue by mobassir94** [pytorch/xla#2750]
i was trying to run this working torch tpu v3 baseline : https://www.kaggle.com/mobassir/faster-pytorch-tpu-baseline-for-cld-cv-0-9 into torch tpu pod v2.

i changed hardware accelerator from tpu v3-8 to tpu v2 pod in kaggle and changed used batch size = 1 and 

```
def _mp_fn(rank, flags):
    global acc_list
    torch.set_default_tensor_type('torch.FloatTensor')
    res = train_model()

FLAGS={}
xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=32//8, start_method='fork')
```
but i get error saying "process 0 terminated with exit code 1"
i am not finding any resource or tutorial to convert tpu v3 notebook into tpu pod v2 in pytorch xla,so i wanted to give it a try myself,,,, @taylanbil need your help

**Comment by taylanbil** [comment]
`process 0 terminated with exit code 1` is not the real error, it's just the error in the main process that waits for the spawned processes. You'd need to look deeper in the stderr to find the real error.

Typically you don't need to change anything when you want to run on a v2, other than the consideration of v2's having half the HBM compared to v3's (8gb vs 16gb). So, not all models that fit in a v3 will fit in a v2.

in the code snippet above though, the real problem I'm seeing is, you're spawning 4 processes. `torch_xla` doesn't support that, you can either spawn 1, or 8 processes. In a pod setting, there's no reason to go with 1, so you should be launching 8 processes.

in the 4 vms that launch 8 each, there will be 32 processses total, matching v2-32's core count..

**Comment by mobassir94** [comment]
@taylanbil  i tried this too for tpu pod : 
```

def _mp_fn(rank, flags):
    global acc_list
    torch.set_default_tensor_type('torch.FloatTensor')
    res = train_model()

FLAGS={}
xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=8, start_method='fork')
```

but same error

**Comment by taylanbil** [comment]
Can you provide full stack trace then? It's likely that you're running out of HBM memory, but I'd like to confirm by looking @ logs..

**Comment by mobassir94** [comment]
if i choose batch size = 2 then will it be 8x4 in tpu pod or 32x4? as tpu pod has 32 core?

**Comment by mobassir94** [comment]
```
---------------------------------------------------------------------------
ProcessExitedException                    Traceback (most recent call last)
<timed exec> in <module>

/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py in spawn(fn, args, nprocs, join, daemon, start_method)
    380   if not _is_xla_config():
    381     # If this is not an XLA setup, jump to normal multi-processing.
--> 382     return _run_direct(fn, args, nprocs, join, daemon, start_method)
    383 
    384   pf_cfg = _pre_fork_setup(nprocs)

/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py in _run_direct(fn, args, nprocs, join, daemon, start_method)
    344   else:
    345     return torch.multiprocessing.spawn(
--> 346         fn, args=args, nprocs=nprocs, join=join, daemon=daemon)
    347 
    348 

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon, start_method)
    228                ' torch.multiprocessing.start_process(...)' % start_method)
    229         warnings.warn(msg)
--> 230     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    186 
    187     # Loop on join until it returns True or raises an exception.
--> 188     while not context.join():
    189         pass
    190 

/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    142                     error_index=error_index,
    143                     error_pid=failed_process.pid,
--> 144                     exit_code=exitcode
    145                 )
    146 

ProcessExitedException: process 2 terminated with exit code 1
```

while running this kernel on tpu pod  : https://www.kaggle.com/mobassir/vit-pytorch-xla-tpu-for-leaf-disease?scriptVersionId=52151758


i just reduced batch from 10 to 4 for tpu pod and ran,then got the error(As shown above)

**Comment by taylanbil** [comment]
this is the stack trace that contains no info on the real error. Is there nothing else other than this in stderr?

**Comment by mobassir94** [comment]
i will get full log if i commit the kernel but i fair to do so,because i lost a lot of kaggle tpu hour recently,,a tpu code that works fine for 5 epoch,gives oom error for 15 epoch run and i don't know how to handle this situation,,so if there is any OOM then kaggle kernel will get stuck during commit mode and stay stuck for 9 hours even if i get OOM after 1 hour :(
kaggle team is working on this issue,,okay i am still trying,,will share the log(just committed the kernel)

**Comment by mobassir94** [comment]
full log @taylanbil 

```
Time
Line #
Log Message
11.2s
1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
11.2s
2
                                 Dload  Upload   Total   Spent    Left  Speed
11.4s
3

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5116  100  5116    0     0  31776      0 --:--:-- --:--:-- --:--:-- 31776
12.4s
4
Updating... This may take around 2 minutes.
12.4s
5
Updating TPU runtime to pytorch-nightly ...
14.3s
6
Found existing installation: torch 1.5.0
15.2s
7
Uninstalling torch-1.5.0:
26.2s
8
  Successfully uninstalled torch-1.5.0
27.2s
9
Found existing installation: torchvision 0.6.0a0+35d732a
27.2s
10
Uninstalling torchvision-0.6.0a0+35d732a:
31.7s
11
Done updating TPU runtime
45.4s
12
  Successfully uninstalled torchvision-0.6.0a0+35d732a
48.6s
13
Copying gs://tpu-pytorch/wheels/torch-nightly-cp37-cp37m-linux_x86_64.whl...
50.3s
14
/ [0 files][    0.0 B/123.1 MiB]                                                
-
- [0 files][ 73.0 MiB/123.1 MiB]                                                
\
\ [1 files][123.1 MiB/123.1 MiB]                                                

50.3s
15
Operation completed over 1 objects/123.1 MiB.                                    
52.3s
16
Copying gs://tpu-pytorch/wheels/torch_xla-nightly-cp37-cp37m-linux_x86_64.whl...
54.2s
17
/ [0 files][    0.0 B/132.0 MiB]                                                
-
- [0 files][ 75.3 MiB/132.0 MiB]                                                
\
\ [1 files][132.0 MiB/132.0 MiB]                                                
|

54.2s
18
Operation completed over 1 objects/132.0 MiB.                                    
56.3s
19
Copying gs://tpu-pytorch/wheels/torchvision-nightly-cp37-cp37m-linux_x86_64.whl...
56.5s
20
/ [0 files][    0.0 B/  4.9 MiB]                                                
/ [1 files][  4.9 MiB/  4.9 MiB]                                                

56.5s
21
Operation completed over 1 objects/4.9 MiB.                                      
58.2s
22
Processing ./torch-nightly-cp37-cp37m-linux_x86_64.whl
63.1s
23
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from torch==nightly) (1.18.5)
63.1s
24
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.7/site-packages (from torch==nightly) (3.7.4.1)
68.4s
25
[31mERROR: fastai 1.0.61 requires torchvision, which is not installed.[0m
68.4s
26
[31mERROR: kornia 0.3.1 has requirement torch==1.5.0, but you'll have torch 1.8.0a0+unknown which is incompatible.[0m
68.4s
27
[31mERROR: allennlp 1.0.0 has requirement torch<1.6.0,>=1.5.0, but you'll have torch 1.8.0a0+unknown which is incompatible.[0m
68.4s
28
Installing collected packages: torch
78.8s
29
Successfully installed torch-1.8.0a0+unknown
79.2s
30
[33mWARNING: You are using pip version 20.1.1; however, version 21.0 is available.
79.2s
31
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.[0m
80.9s
32
Processing ./torch_xla-nightly-cp37-cp37m-linux_x86_64.whl
89.4s
33
Installing collected packages: torch-xla
98.5s
34
Successfully installed torch-xla-1.6+774f493
98.8s
35
[33mWARNING: You are using pip version 20.1.1; however, version 21.0 is available.
98.8s
36
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.[0m
100.3s
37
Processing ./torchvision-nightly-cp37-cp37m-linux_x86_64.whl
100.7s
38
Requirement already satisfied: torch in /opt/conda/lib/python3.7/site-packages (from torchvision==nightly) (1.8.0a0+unknown)
100.7s
39
Requirement already satisfied: pillow>=4.1.1 in /opt/conda/lib/python3.7/site-packages (from torchvision==nightly) (7.2.0)
100.7s
40
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from torchvision==nightly) (1.18.5)
100.7s
41
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.7/site-packages (from torch->torchvision==nightly) (3.7.4.1)
105.0s
42
Installing collected packages: torchvision
107.5s
43
Successfully installed torchvision-0.9.0a0+f16322b
107.8s
44
[33mWARNING: You are using pip version 20.1.1; however, version 21.0 is available.
107.8s
45
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.[0m
109.4s
46

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 7%

Reading package lists... 7%

Reading package lists... 60%

Reading package lists... 63%

Reading package lists... 63%

Reading package lists... 64%

Reading package lists... 64%

Reading package lists... 72%

Reading package lists... 72%

Reading package lists... 73%

Reading package lists... 73%

Reading package lists... 83%

Reading package lists... 83%

Reading package lists... 83%

Reading package lists... 83%

Reading package lists... 83%

Reading package lists... 83%

Reading package lists... 83%

Reading package lists... 83%

Reading package lists... 90%

Reading package lists... 90%

Reading package lists... 90%

Reading package lists... 90%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 97%

Reading package lists... 97%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done

109.6s
47

Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       

109.6s
48

Reading state information... 0%

Reading state information... 0%

Reading state information... Done

109.9s
49
The following NEW packages will be installed:
109.9s
50
  libomp5
110.0s
51
0 upgraded, 1 newly installed, 0 to remove and 59 not upgraded.
110.0s
52
Need to get 234 kB of archives.
110.0s
53
After this operation, 774 kB of additional disk space will be used.
110.3s
54

0% [Working]
            
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp5 amd64 5.0.1-1 [234 kB]
110.8s
55

5% [1 libomp5 14.2 kB/234 kB 6%]
                                
100% [Working]
              
Fetched 234 kB in 1s (279 kB/s)
111.3s
56
debconf: delaying package configuration, since apt-utils is not installed
111.5s
57
Selecting previously unselected package libomp5:amd64.
112.0s
58
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 107745 files and directories currently installed.)
112.0s
59
Preparing to unpack .../libomp5_5.0.1-1_amd64.deb ...
112.0s
60
Unpacking libomp5:amd64 (5.0.1-1) ...
112.2s
61
Setting up libomp5:amd64 (5.0.1-1) ...
112.2s
62
Processing triggers for libc-bin (2.27-3ubuntu1) ...
115.4s
63
Collecting git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git
115.4s
64
  Cloning https://github.com/ildoonet/pytorch-gradual-warmup-lr.git to /tmp/pip-req-build-m6j_tlge
115.4s
65
  Running command git clone -q https://github.com/ildoonet/pytorch-gradual-warmup-lr.git /tmp/pip-req-build-m6j_tlge
117.0s
66
Building wheels for collected packages: warmup-scheduler
117.9s
67
  Building wheel for warmup-scheduler (setup.py) ... [?25l- \ done
117.9s
68
[?25h  Created wheel for warmup-scheduler: filename=warmup_scheduler-0.3.2-py3-none-any.whl size=3881 sha256=8bbaa4fee2f42867e4d39c715a8f0698448b855451a195c57d0040a6191014ad
117.9s
69
  Stored in directory: /tmp/pip-ephem-wheel-cache-g7ed4gr2/wheels/bf/81/52/0e3bc0b645a339f94c76b4dcb8c8b7a5f588a614f5add83b9f
117.9s
70
Successfully built warmup-scheduler
122.0s
71
Installing collected packages: warmup-scheduler
122.3s
72
Successfully installed warmup-scheduler-0.3.2
122.6s
73
[33mWARNING: You are using pip version 20.1.1; however, version 21.0 is available.
122.6s
74
You should consider upgrading via the '/opt/conda/bin/python3.7 -m pip install --upgrade pip' command.[0m
130.2s
75
[34m[1mwandb[0m: [33mWARNING[0m W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
132.9s
76
1.8.0a0+48b6b92
138.8s
77
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vitjx/jx_vit_base_p16_384-83fb41ba.pth" to /root/.cache/torch/hub/checkpoints/jx_vit_base_p16_384-83fb41ba.pth
149.4s
78
Traceback (most recent call last):
149.4s
79
  File "<string>", line 1, in <module>
149.4s
80
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
149.4s
81
    exitcode = _main(fd)
149.4s
82
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
149.4s
83
    self = reduction.pickle.load(from_parent)
149.4s
84
AttributeError: Can't get attribute '_mp_fn' on <module '__main__' (built-in)>
149.5s
85
Traceback (most recent call last):
149.5s
86
  File "<string>", line 1, in <module>
149.5s
87
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
149.5s
88
    exitcode = _main(fd)
149.5s
89
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
149.5s
90
    self = reduction.pickle.load(from_parent)
149.5s
91
AttributeError: Can't get attribute '_mp_fn' on <module '__main__' (built-in)>
149.5s
92
Traceback (most recent call last):
149.5s
93
  File "<string>", line 1, in <module>
149.5s
94
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
149.5s
95
    exitcode = _main(fd)
149.5s
96
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
149.5s
97
    self = reduction.pickle.load(from_parent)
149.5s
98
AttributeError: Can't get attribute '_mp_fn' on <module '__main__' (built-in)>
149.6s
99
Traceback (most recent call last):
149.6s
100
  File "<string>", line 1, in <module>
149.6s
101
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
149.6s
102
    exitcode = _main(fd)
149.6s
103
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
149.6s
104
    self = reduction.pickle.load(from_parent)
149.6s
105
AttributeError: Can't get attribute '_mp_fn' on <module '__main__' (built-in)>
149.6s
106
Traceback (most recent call last):
149.6s
107
  File "<string>", line 1, in <module>
149.6s
108
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
149.6s
109
    exitcode = _main(fd)
149.6s
110
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
149.6s
111
    self = reduction.pickle.load(from_parent)
149.6s
112
AttributeError: Can't get attribute '_mp_fn' on <module '__main__' (built-in)>
149.6s
113
Traceback (most recent call last):
149.6s
114
  File "<string>", line 1, in <module>
149.6s
115
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
149.6s
116
    exitcode = _main(fd)
149.6s
117
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
149.6s
118
    self = reduction.pickle.load(from_parent)
149.6s
119
AttributeError: Can't get attribute '_mp_fn' on <module '__main__' (built-in)>
149.7s
120
Traceback (most recent call last):
149.7s
121
  File "<string>", line 1, in <module>
149.7s
122
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
149.7s
123
    exitcode = _main(fd)
149.7s
124
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
149.7s
125
    self = reduction.pickle.load(from_parent)
149.7s
126
AttributeError: Can't get attribute '_mp_fn' on <module '__main__' (built-in)>
149.7s
127
Traceback (most recent call last):
149.7s
128
  File "<string>", line 1, in <module>
149.7s
129
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
149.7s
130
    exitcode = _main(fd)
149.7s
131
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
149.7s
132
    self = reduction.pickle.load(from_parent)
149.7s
133
AttributeError: Can't get attribute '_mp_fn' on <module '__main__' (built-in)>
151.4s
134
Traceback (most recent call last):
151.4s
135
  File "<string>", line 1, in <module>
151.4s
136
  File "/opt/conda/lib/python3.7/site-packages/papermill/execute.py", line 108, in execute_notebook
151.4s
137
    raise_for_execution_errors(nb, output_path)
151.4s
138
  File "/opt/conda/lib/python3.7/site-packages/papermill/execute.py", line 188, in raise_for_execution_errors
151.4s
139
    raise error
151.4s
140
papermill.exceptions.PapermillExecutionError: 
151.4s
141
---------------------------------------------------------------------------
151.4s
142
Exception encountered at "In [21]":
151.4s
143
---------------------------------------------------------------------------
151.4s
144
FileNotFoundError                         Traceback (most recent call last)
151.4s
145
<ipython-input-21-a56ab5941735> in <module>
151.4s
146
----> 1 f = open(f'./log.txt', "r")
151.4s
147
      2 
151.4s
148
      3 print(f.read())
151.4s
149

151.4s
150
FileNotFoundError: [Errno 2] No such file or directory: './log.txt'
151.4s
151

152.3s
152
[NbConvertApp] Converting notebook __notebook__.ipynb to notebook
152.8s
153
[NbConvertApp] Writing 296013 bytes to __notebook__.ipynb
153.5s
154
[NbConvertApp] Converting notebook __notebook__.ipynb to html
154.5s
155
[NbConvertApp] Support files will be in __results___files/
154.5s
156
[NbConvertApp] Making directory __results___files
154.5s
157
[NbConvertApp] Writing 429123 bytes to __results__.html
154.5s
158
154.5s
160
Complete. Exited with code 0.

```

you can find it here  : https://www.kaggle.com/mobassir/vit-pytorch-xla-tpu-for-leaf-disease?scriptVersionId=52711212 (at the bottom)

**Comment by taylanbil** [comment]
Can you try putting the spawn under `if __name__ == '__main__':` ?
```python
if __name__ == '__main__':
  xmp.spawn(_mp_fn, .....)
```

**Comment by taylanbil** [comment]
Wait so are you running on a v2-8 or a pod, which is v2-32 or higher ?

**Comment by mobassir94** [comment]
i am running on v2-32 pod

**Comment by taylanbil** [comment]
So, you must be using `xla_dist` as in [this tutorial](https://cloud.google.com/tpu/docs/tutorials/pytorch-pod), right?

**Comment by jysohn23** [comment]
Typically on TPU we have 1 VM per 8 TPU cores (1 TPU host): https://cloud.google.com/tpu/docs/tutorials/pytorch-pod

It looks like on Kaggle though you're not? We actually have never had anyone try that on Kaggle and don't really expect it to work. Would you mind checking the tutorial out?

**Comment by mobassir94** [comment]
i got tpu pod award from kaggle because i am kaggle tpu star,all tpu star using tpu pod for tf tpu but i wanted to try torch xla,your tutorial is not python friendly,hard for me to understand how to make it working on kaggle,a jupyter notebook would be great,anyway i am rechecking and trying to understand

**Comment by mobassir94** [comment]
sorry i failed,,don't know how to use xla_dist  and tpu pod v2 in kaggle,it was easy with tf tpu pod(i tried) but for torch xla no easy tutorial to follow for kaggle :(

for example i don't know how to use this command in kaggle : 

```
python -m torch_xla.distributed.xla_dist \
      --tpu=$TPU_NAME \
      --conda-env=torch-xla-1.7 \
      --env XLA_USE_BF16=1 \
      --env ANY_OTHER=ENV_VAR \
      -- python /usr/share/torch-xla-1.7/pytorch/xla/test/test_train_mp_imagenet.py \
      --fake_data
```

**Comment by jysohn23** [comment]
I'm currently checking with Kaggle team, but from what I can tell it unfortunately doesn't seem like Kaggle + TPU Pods + PyTorch/XLA isn't currently supported. As shown in that first diagram in the TPU Pods tutorial for PyTorch/XLA we have a 1-1 correspondence in VMs between TPU VM and GCE VM. In TF/TPU that's different and they have 1-N correspondence since they use a TF distributed server. FYI, this is about to change with TPU VM support for PT/XLA coming and they'll look more similar.

**Comment by mobassir94** [comment]
@djherbis please check this thread,thank you

**Comment by djherbis** [comment]
Hey @mobassir94, I spoke with @jysohn23 and checked our TPU docs. At this time, we can't support PyTorch/XLA on Kaggle due to our current VM architecture. There are future plans to try and get this working, but in the meantime this won't work on Kaggle. It should work on GCP directly though.

Thanks for your continued work with TPUs!
