### ISSUE TITLE
Multiprocessing with GPUs setup for workers has errors

### ISSUE THREAD

**Issue by aingo03304** [pytorch/xla#2758]
## 🐛 Bug

In `xla_multiprocessing.py`, `_parse_workers_config` returns OrderedDict.
https://github.com/pytorch/xla/blob/9917e41f60354ce96b3181acf30dff422d3c8716/torch_xla/distributed/xla_multiprocessing.py#L54-L63

However 
https://github.com/pytorch/xla/blob/9917e41f60354ce96b3181acf30dff422d3c8716/torch_xla/distributed/xla_multiprocessing.py#L156-L157
this code tries to access `worker.host_port` and this raises the error which can be fixed by replacing `worker.host_port` to `wcfg[worker].host_port`.

And, 
https://github.com/pytorch/xla/blob/9917e41f60354ce96b3181acf30dff422d3c8716/torch_xla/distributed/xla_multiprocessing.py#L163-L165

this code is appending `'{}:{};grpc://{}:{}'` but `'{}:{};{}:{}'` is correct based on the following configuration in CI, because `m.group(1)` includes 'grpc://'.
https://github.com/pytorch/xla/blob/3eaee46ef679cc6a0f1f694bd0a007dbfd09c51b/.circleci/test.sh#L11

## To Reproduce

1. With GPUs, run `test_train_mp_mnist.py`

## Environment

 - Reproducible on XLA backend [CPU/TPU]: GPUs
 - torch_xla version: master

**Comment by JackCaoG** [comment]
@aingo03304 Thanks for reporting, will take a look. Do you mind sharing the config you used to setup the multi-GPU?

**Comment by aingo03304** [comment]
@JackCaoG 
Thank you for the response. Here are my env variables I set.
```
export XRT_WORKERS="localservice:0;grpc://localhost:40934"
export XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0|GPU:0;/job:localservice/replica:0/task:0/device:XLA_GPU:0|GPU:1;/job:localservice/replica:0/task:0/device:XLA_GPU:1|GPU:2;/job:localservice/replica:0/task:0/device:XLA_GPU:2|GPU:3;/job:localservice/replica:0/task:0/device:XLA_GPU:3"
```

By the way, do you have any plan to officially support pytorch-xla for gpu?

**Comment by JackCaoG** [comment]
HI @aingo03304 , sorry for the late reply. I think I need more time to look into this. For me if only exporting 
```
export XRT_WORKERS="localservice:0;grpc://localhost:40934"
export XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0|GPU:0;/job:localservice/replica:0/task:0/device:XLA_GPU:0|GPU:1;/job:localservice/replica:0/task:0/device:XLA_GPU:1|GPU:2;/job:localservice/replica:0/task:0/device:XLA_GPU:2|GPU:3;/job:localservice/replica:0/task:0/device:XLA_GPU:3"
```

will hit https://github.com/pytorch/xla/blob/9917e41f60354ce96b3181acf30dff422d3c8716/torch_xla/distributed/xla_multiprocessing.py#L382 and everything seems fine.

If I use
```
export GPU_NUM_DEVICES=4
```
I will hit a different issue with my setup. I need to look into it a bit more. I don't think you need to setup `XRT_DEVICE_MAP` and `XRT_WORKERS` if you export the `GPU_NUM_DEVICES`. Those should be setup automatically.

**Comment by aingo03304** [comment]
@JackCaoG Yes, I can reproduce your comment. Thank you for the reply.
The actual situation I mentioned was 
```
export GPU_NUM_DEVICES=4
export XRT_WORKERS="localservice:0;grpc://localhost:40934"
export XRT_DEVICE_MAP="CPU:0;/job:localservice/replica:0/task:0/device:XLA_CPU:0|GPU:0;/job:localservice/replica:0/task:0/device:XLA_GPU:0|GPU:1;/job:localservice/replica:0/task:0/device:XLA_GPU:1|GPU:2;/job:localservice/replica:0/task:0/device:XLA_GPU:2|GPU:3;/job:localservice/replica:0/task:0/device:XLA_GPU:3"
```
Then you can reproduce the python error like this.
```
Traceback (most recent call last):
  File "test_train_mp_mnist.py", line 196, in <module>
    xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS.num_cores)
  File "/home/aingo03304/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-1.6-py3.6-linux-x86_64.egg/torch_xla/distributed/xla_multiprocessing.py", line 384, in spawn
    pf_cfg = _pre_fork_setup(nprocs)
  File "/home/aingo03304/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-1.6-py3.6-linux-x86_64.egg/torch_xla/distributed/xla_multiprocessing.py", line 210, in _pre_fork_setup
    _setup_workers(num_devices)
  File "/home/aingo03304/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-1.6-py3.6-linux-x86_64.egg/torch_xla/distributed/xla_multiprocessing.py", line 157, in _setup_workers
    m = re.match(r'(.*):(\d+)$', worker.host_port)
AttributeError: 'str' object has no attribute 'host_port'
```
Clearly, this is an error on the python side.

However, now I encounter an error like this and it seems something that is in XLA and/or NCCL.
```
2021-02-05 14:47:38.663029: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xrt_execute_op.cc:430 : Internal: tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc:105: NCCL operation ncclGroupEnd() failed: unhandled cuda error
2021-02-05 14:47:38.663211: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xrt_execute_op.cc:430 : Internal: tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc:105: NCCL operation ncclGroupEnd() failed: unhandled cuda error
2021-02-05 14:47:38.678277: E tensorflow/compiler/xla/xla_client/xla_util.cc:76] >>> Dumping Computation 0
```

Any thought on this? I think this error is in the TensorFlow code so I should move this issue to tensorflow repo.

**Comment by JackCaoG** [comment]
Hi @aingo03304 Sorry for the late reply, the last error seem to coming from the NCCL group config, in https://github.com/tensorflow/tensorflow/blob/b681785237799530623e94455751a02c43eca1d7/tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc#L164

I will try to repo this when I am a bit more free, but this error might not be directly related to pt/xla. 

@tyoc213 You were also looking into using XLA:GPU locally and made it work. Did you encounter this error before?

**Comment by aingo03304** [comment]
@JackCaoG I want to fix this and run my code using multiprocessing asap.
I am not that familiar with NCCL API though, can you elaborate on NCCL group config?
In GPU xla backend code you mentioned, I cannot find any reason to fail ncclGroupEnd.

Don't know what `ncclUnhandledCudaError` exactly means, but the documentation of NCCL describes it as `A call to a CUDA function failed.`. Is there any way to debug cudaError in tensorflow or pt/xla configuration?

**Comment by zcain117** [comment]
Is this a setup with multiple machines, each machine having a few GPUs?  Or is this 1 machine with 4 GPUs?

If it's single-node, multi GPU you can just use e.g.:
```
              unset XRT_TPU_CONFIG
              export GPU_NUM_DEVICES=4
              python3 pytorch/xla/test/test_train_mp_mnist.py
```

this will run multiprocessing with 4 processes

you would need CUDA installed, for example you could use our public docker image: `gcr.io/xl-ml-test/pytorch-xla:nightly_3.6_cuda`

**Comment by aingo03304** [comment]
@zcain117 Thank you for the response. My setup is on a single machine.
I'll try with the docker image and let you know the result. Probably my local CUDA setting is somehow improper for pt/xla.

**Comment by tyoc213** [comment]
> Hi @aingo03304 Sorry for the late reply, the last error seem to coming from the NCCL group config, in https://github.com/tensorflow/tensorflow/blob/b681785237799530623e94455751a02c43eca1d7/tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc#L164
> 
> I will try to repo this when I am a bit more free, but this error might not be directly related to pt/xla.
> 
> @tyoc213 You were also looking into using XLA:GPU locally and made it work. Did you encounter this error before?

Sorry for late answer have been a little busy, yeah I can work locally with pytorch/XLA on GPU, but I only have 1 GPU the nearest thing I found was this https://github.com/pytorch/xla/issues/2670

**Comment by aingo03304** [comment]
@zcain117 

> you would need CUDA installed, for example you could use our public docker image: gcr.io/xl-ml-test/pytorch-xla:nightly_3.6_cuda
It seems that the image is not public...

**Comment by aingo03304** [comment]
@tyoc213 Actually I fixed the code and can run `test_train_mnist.py`. And now I encounter NCCL related error above. 
(Thank you for the blog post. It really was really helpful!)

@zcain117 
> If it's single-node, multi GPU you can just use e.g.:
> ```
>               unset XRT_TPU_CONFIG
>               export GPU_NUM_DEVICES=4
>               python3 pytorch/xla/test/test_train_mp_mnist.py
> ```
> this will run multiprocessing with 4 processes

I encounter the same error: 
```
Recent warning and error logs:
  OP_REQUIRES failed at xrt_execute_op.cc:430 : Internal: tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc:105: NCCL operation ncclGroupEnd() failed: unhandled cuda error
```

Is there any information I should give you so you can figure out what the problem is?

**Comment by zcain117** [comment]
Sorry about that, I gave the wrong GCR image. The public one should be:

`gcr.io/tpu-pytorch/xla:nightly_3.6_cuda` ( or you can use `nightly_3.7_cuda` )

**Comment by aingo03304** [comment]
@zcain117 I can reproduce the same error on docker image you gave.
```
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
warning: Linking two modules of different target triples: '/usr/local/cuda-10.1/nvvm/libdevice/libdevice.10.bc' is 'nvptx64-nvidia-gpulibs' whereas '' is 'nvptx64-nvidia-cuda'

warning: Linking two modules of different target triples: '/usr/local/cuda-10.1/nvvm/libdevice/libdevice.10.bc' is 'nvptx64-nvidia-gpulibs' whereas '' is 'nvptx64-nvidia-cuda'

2021-02-16 06:25:11.307955: W     734 tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xrt_execute_op.cc:430 : Internal: tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc:105: NCCL operation ncclGroupEnd() failed: unhandled cuda error
2021-02-16 06:25:11.308034: W     733 tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xrt_execute_op.cc:430 : Internal: tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc:105: NCCL operation ncclGroupEnd() failed: unhandled cuda error
```
This result is reproduced on another machine with two TitanXp.

**Comment by aingo03304** [comment]
Here is my NCCL debug logs.
```
526ab2a8a16a:750:962 [0] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.2<0>
526ab2a8a16a:750:962 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

526ab2a8a16a:750:962 [0] external/nccl_archive/src/misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
526ab2a8a16a:750:962 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0>
526ab2a8a16a:750:962 [0] NCCL INFO Using network Socket
NCCL version 2.7.6+cudaCUDA_MAJOR.CUDA_MINOR
526ab2a8a16a:751:1444 [0] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.2<0>
526ab2a8a16a:751:1444 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

526ab2a8a16a:751:1444 [0] external/nccl_archive/src/misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
526ab2a8a16a:751:1444 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0>
526ab2a8a16a:751:1444 [0] NCCL INFO Using network Socket
526ab2a8a16a:751:1450 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
526ab2a8a16a:751:1450 [0] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
526ab2a8a16a:750:1449 [0] NCCL INFO Channel 00/02 :    0   1
526ab2a8a16a:750:1449 [0] NCCL INFO Channel 01/02 :    0   1
526ab2a8a16a:750:1449 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
526ab2a8a16a:750:1449 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
526ab2a8a16a:751:1450 [0] NCCL INFO Channel 00 : 1[2000] -> 0[1000] via P2P/IPC
526ab2a8a16a:750:1449 [0] NCCL INFO Channel 00 : 0[1000] -> 1[2000] via P2P/IPC
526ab2a8a16a:750:1449 [0] NCCL INFO Channel 01 : 0[1000] -> 1[2000] via P2P/IPC
526ab2a8a16a:751:1450 [0] NCCL INFO Channel 01 : 1[2000] -> 0[1000] via P2P/IPC
526ab2a8a16a:750:1449 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
526ab2a8a16a:750:1449 [0] NCCL INFO comm 0x7f386c0070f0 rank 0 nranks 2 cudaDev 0 busId 1000 - Init COMPLETE
526ab2a8a16a:751:1450 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
526ab2a8a16a:750:1445 [0] NCCL INFO Launch mode Parallel
526ab2a8a16a:751:1450 [0] NCCL INFO comm 0x7f5194006f50 rank 1 nranks 2 cudaDev 0 busId 2000 - Init COMPLETE

526ab2a8a16a:750:1445 [0] external/nccl_archive/src/enqueue.cc:215 NCCL WARN Cuda failure 'invalid device function'
526ab2a8a16a:750:1445 [0] NCCL INFO external/nccl_archive/src/group.cc:282 -> 1

526ab2a8a16a:751:1444 [0] external/nccl_archive/src/enqueue.cc:215 NCCL WARN Cuda failure 'invalid device function'
526ab2a8a16a:751:1444 [0] NCCL INFO external/nccl_archive/src/group.cc:282 -> 1
2021-02-16 06:29:02.387579: W    1445 tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xrt_execute_op.cc:430 : Internal: tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc:105: NCCL operation ncclGroupEnd() failed: unhandled cuda error
2021-02-16 06:29:02.387675: W    1444 tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xrt_execute_op.cc:430 : Internal: tensorflow/compiler/xla/service/gpu/nccl_all_reduce_thunk.cc:105: NCCL operation ncclGroupEnd() failed: unhandled cuda error
```

**Comment by aingo03304** [comment]
@zcain117 This is logs when I turn on `TF_CPP_MIN_LOG_LEVEL=0`.
```
2021-02-16 06:35:55.180435: I    2165 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:55.702444: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:55.705666: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:55.738096: I    2170 tensorflow/compiler/xla/xla_client/xrt_local_service.cc:40] Peer localservice 2 {526ab2a8a16a:47615, 526ab2a8a16a:33419}
2021-02-16 06:35:55.738150: I    2170 tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-16 06:35:55.739931: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-02-16 06:35:55.741041: I    2169 tensorflow/compiler/xla/xla_client/xrt_local_service.cc:40] Peer localservice 2 {526ab2a8a16a:47615, 526ab2a8a16a:33419}
2021-02-16 06:35:55.741092: I    2169 tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-16 06:35:55.742027: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-02-16 06:35:55.751821: I    2170 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.752695: I    2170 tensorflow/core/common_runtime/gpu/gpu_device.cc:1760] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2021-02-16 06:35:55.752715: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:55.753885: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-02-16 06:35:55.753942: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2021-02-16 06:35:55.755176: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-02-16 06:35:55.755390: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-02-16 06:35:55.756675: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-02-16 06:35:55.757406: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2021-02-16 06:35:55.758098: I    2169 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.758513: I    2169 tensorflow/core/common_runtime/gpu/gpu_device.cc:1760] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2021-02-16 06:35:55.758528: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:55.759568: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-02-16 06:35:55.759589: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2021-02-16 06:35:55.760208: I    2170 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-02-16 06:35:55.760267: I    2170 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.760582: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-02-16 06:35:55.760742: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-02-16 06:35:55.761017: I    2170 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.761527: I    2170 tensorflow/core/common_runtime/gpu/gpu_device.cc:1898] Adding visible gpu devices: 0
2021-02-16 06:35:55.762033: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-02-16 06:35:55.762670: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2021-02-16 06:35:55.765040: I    2169 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-02-16 06:35:55.765146: I    2169 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.769080: I    2169 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.776048: I    2169 tensorflow/core/common_runtime/gpu/gpu_device.cc:1898] Adding visible gpu devices: 0
2021-02-16 06:35:55.897150: I    2170 tensorflow/core/common_runtime/gpu/gpu_device.cc:1300] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-02-16 06:35:55.897171: I    2170 tensorflow/core/common_runtime/gpu/gpu_device.cc:1306]      0 
2021-02-16 06:35:55.897176: I    2170 tensorflow/core/common_runtime/gpu/gpu_device.cc:1319] 0:   N 
2021-02-16 06:35:55.909214: I    2170 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.910231: I    2170 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.910587: I    2170 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.910933: I    2170 tensorflow/core/common_runtime/gpu/gpu_device.cc:1446] Created TensorFlow device (/job:localservice/replica:0/task:1/device:GPU:0 with 11547 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:02:00.0, compute capability: 6.1)
2021-02-16 06:35:55.912973: I    2169 tensorflow/core/common_runtime/gpu/gpu_device.cc:1300] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-02-16 06:35:55.912986: I    2169 tensorflow/core/common_runtime/gpu/gpu_device.cc:1306]      0 
2021-02-16 06:35:55.912991: I    2169 tensorflow/core/common_runtime/gpu/gpu_device.cc:1319] 0:   N 
2021-02-16 06:35:55.913056: I    2169 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.913407: I    2169 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.913751: I    2169 tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-16 06:35:55.914090: I    2169 tensorflow/core/common_runtime/gpu/gpu_device.cc:1446] Created TensorFlow device (/job:localservice/replica:0/task:0/device:GPU:0 with 11543 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-02-16 06:35:55.924973: I    2220 tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3600000000 Hz
2021-02-16 06:35:55.926265: I    2170 tensorflow/compiler/xla/service/service.cc:169] XLA service 0x55df6798bae0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-16 06:35:55.926279: I    2170 tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Host, Default Version
2021-02-16 06:35:55.927535: I    2170 tensorflow/compiler/xla/service/service.cc:169] XLA service 0x55df67f39920 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-02-16 06:35:55.927547: I    2170 tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2021-02-16 06:35:55.928102: I    2245 tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3600000000 Hz
2021-02-16 06:35:55.928619: I    2169 tensorflow/compiler/xla/service/service.cc:169] XLA service 0x56011284ae40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-16 06:35:55.928631: I    2169 tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Host, Default Version
2021-02-16 06:35:55.929838: I    2169 tensorflow/compiler/xla/service/service.cc:169] XLA service 0x560112df1950 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-02-16 06:35:55.929854: I    2169 tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2021-02-16 06:35:55.930642: I    2170 tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localservice -> {0 -> 526ab2a8a16a:47615, 1 -> 526ab2a8a16a:33419}
2021-02-16 06:35:55.931006: I    2170 tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://526ab2a8a16a:33419
2021-02-16 06:35:55.933012: I    2169 tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localservice -> {0 -> 526ab2a8a16a:47615, 1 -> 526ab2a8a16a:33419}
2021-02-16 06:35:55.933462: I    2169 tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://526ab2a8a16a:47615
2021-02-16 06:35:55.983042: I    2369 tensorflow/compiler/jit/xla_device.cc:399] XLA_GPU and XLA_CPU devices are deprecated and will be removed in subsequent releases. Instead, use either @tf.function(jit_compile=True) for must-compile semantics, or run with TF_XLA_FLAGS=--tf_xla_auto_jit=2 for auto-clustering best-effort compilation.
2021-02-16 06:35:55.985847: I    2485 tensorflow/compiler/jit/xla_device.cc:399] XLA_GPU and XLA_CPU devices are deprecated and will be removed in subsequent releases. Instead, use either @tf.function(jit_compile=True) for must-compile semantics, or run with TF_XLA_FLAGS=--tf_xla_auto_jit=2 for auto-clustering best-effort compilation.
Epoch 1 train begin 06:35:56
2021-02-16 06:35:56.715265: I    2636 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:56.715264: I    2640 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:56.741381: I    2635 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:56.748459: I    2637 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:56.758029: I    2664 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:56.767478: I    2645 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:56.773033: I    2641 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:56.892889: I    2669 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-02-16 06:35:56.985643: I    2354 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-02-16 06:35:57.043440: I    2485 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-02-16 06:35:57.084767: I    2354 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-02-16 06:35:57.139150: I    2485 tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-02-16 06:35:57.426677: I    2354 tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Loaded cuDNN version 7605
2021-02-16 06:35:57.478994: I    2485 tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Loaded cuDNN version 7605
warning: Linking two modules of different target triples: '/usr/local/cuda-10.1/nvvm/libdevice/libdevice.10.bc' is 'nvptx64-nvidia-gpulibs' whereas '' is 'nvptx64-nvidia-cuda'

warning: Linking two modules of different target triples: '/usr/local/cuda-10.1/nvvm/libdevice/libdevice.10.bc' is 'nvptx64-nvidia-gpulibs' whereas '' is 'nvptx64-nvidia-cuda'

2021-02-16 06:35:58.277019: I    2878 tensorflow/compiler/xla/xla_client/mesh_service.cc:312] Waiting to connect to client mesh master (300 seconds) 526ab2a8a16a:44857
```

Because there is no issue on NCCL in tensorflow repo, I suspect `xla_client` is somehow wrong.

**Comment by aingo03304** [comment]
@JackCaoG Ping. Any progress on this?

**Comment by JackCaoG** [comment]
@aingo03304 Sorry for the very late replay. My hand is tight with the upcoming 1.8 release right now, will try to circle back when I am a bit more free. @ailzhang is looking at the currently nightly failure of mnist with 2 gpu in https://github.com/pytorch/xla/pull/2787. This might be related.
