### ISSUE TITLE
compile/install locally requires numpy and I have numpy

### ISSUE THREAD

**Issue by tyoc213** [pytorch/xla#2762]
## 🐛 Bug

When trying to compile or build lib, I got numpy not found even that if I open a python terminal and import it can do it without error

```
$ pip install -e .
Obtaining file:///home/tyoc213/Documents/github/pytorch/xla
    ERROR: Command errored out with exit status 1:
     command: /home/tyoc213/miniconda3/envs/xla/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/tyoc213/Documents/github/pytorch/xla/setup.py'"'"'; __file__='"'"'/home/tyoc213/Documents/github/pytorch/xla/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-65dhg99g
         cwd: /home/tyoc213/Documents/github/pytorch/xla/
    Complete output (100 lines):
    Extracted 1864 functions (0 errors) from /home/tyoc213/Documents/github/pytorch/xla/scripts/../../build/aten/src/ATen/RegistrationDeclarations.h
    365 function overrides in /home/tyoc213/Documents/github/pytorch/xla/scripts/../torch_xla/csrc/aten_xla_type.h
    Generated 1864 wrappers for /home/tyoc213/Documents/github/pytorch/xla/scripts/../../build/aten/src/ATen/RegistrationDeclarations.h
    + OPTS=()
    + getopts O: OPTION
    + case $OPTION in
    + for i in ${OPTARG}
    + OPTS+=("--cxxopt=${i}")
    + getopts O: OPTION
    + shift 2
    + CMD=egg_info
    ++ dirname /home/tyoc213/Documents/github/pytorch/xla/build_torch_xla_libs.sh
    + cd /home/tyoc213/Documents/github/pytorch/xla
    +++ pwd
    ++ printf '%q\n' /home/tyoc213/Documents/github/pytorch/xla
    + PWD=/home/tyoc213/Documents/github/pytorch/xla
    + BASE_DIR=/home/tyoc213/Documents/github/pytorch/xla
    + echo /home/tyoc213/Documents/github/pytorch/xla
    /home/tyoc213/Documents/github/pytorch/xla
    + THIRD_PARTY_DIR=/home/tyoc213/Documents/github/pytorch/xla/third_party
    + MODE=opt
    + [[ 1 == \1 ]]
    + MODE=dbg
    + VERBOSE=
    + [[ 0 == \1 ]]
    + MAX_JOBS=
    + [[ 1 == \1 ]]
    + [[ '' == \t\r\u\e ]]
    + OPTS+=(--cxxopt="-std=c++14")
    ++ basename -- clang-8
    + [[ clang-8 =~ ^clang ]]
    + OPTS+=(--cxxopt="-Wno-c++11-narrowing")
    + [[ 1 == \1 ]]
    + OPTS+=(--cxxopt="-DXLA_CUDA=1")
    + OPTS+=(--config=cuda)
    + '[' egg_info == clean ']'
    + cp -r -u -p /home/tyoc213/Documents/github/pytorch/xla/third_party/xla_client /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/tensorflow/compiler/xla/
    + pushd /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow
    ~/Documents/github/pytorch/xla/third_party/tensorflow ~/Documents/github/pytorch/xla
    + bazel build --define framework_shared_object=false -c dbg --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --cxxopt=-std=c++14 --cxxopt=-Wno-c++11-narrowing --cxxopt=-DXLA_CUDA=1 --config=cuda //tensorflow/compiler/xla/xla_client:libxla_computation_client.so
    INFO: Options provided by the client:
      Inherited 'common' options: --isatty=0 --terminal_columns=80
    INFO: Reading rc options for 'build' from /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/.bazelrc:
      Inherited 'common' options: --experimental_repo_remote_exec
    INFO: Reading rc options for 'build' from /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/.bazelrc:
      'build' options: --apple_platform_type=macos --define framework_shared_object=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
    INFO: Found applicable config definition build:short_logs in file /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
    INFO: Found applicable config definition build:v2 in file /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
    INFO: Found applicable config definition build:cuda in file /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
    INFO: Found applicable config definition build:using_cuda in file /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
    INFO: Found applicable config definition build:linux in file /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
    INFO: Found applicable config definition build:dynamic_kernels in file /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
    Loading:
    Loading: 0 packages loaded
    DEBUG: /home/tyoc213/.cache/bazel/_bazel_tyoc213/19011bf2b17a0b6da5215ad1a05b9611/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10:
    Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
    INFO: Build option --cxxopt has changed, discarding analysis cache.
    Analyzing: target //tensorflow/compiler/xla/xla_client:libxla_computation_client.so (0 packages loaded, 0 targets configured)
    INFO: Repository local_config_python instantiated at:
      /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/WORKSPACE:12:10: in <toplevel>
      /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/tensorflow/workspace2.bzl:13:20: in workspace
      /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/tensorflow/workspace.bzl:100:21: in tf_repositories
    Repository rule python_configure defined at:
      /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/third_party/py/python_configure.bzl:294:35: in <toplevel>
    ERROR: An error occurred during the fetch of repository 'local_config_python':
       Traceback (most recent call last):
    	File "/home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/third_party/py/python_configure.bzl", line 267, column 40, in _python_autoconf_impl
    		_create_local_python_repository(repository_ctx)
    	File "/home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
    		numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
    	File "/home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
    		return execute(
    	File "/home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
    		fail(
    Error in fail: Problem getting numpy include path.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'numpy'
    Is numpy installed?
    INFO: Repository go_sdk instantiated at:
      /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/WORKSPACE:16:10: in <toplevel>
      /home/tyoc213/Documents/github/pytorch/xla/third_party/tensorflow/tensorflow/workspace0.bzl:77:20: in workspace
      /home/tyoc213/.cache/bazel/_bazel_tyoc213/19011bf2b17a0b6da5215ad1a05b9611/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
      /home/tyoc213/.cache/bazel/_bazel_tyoc213/19011bf2b17a0b6da5215ad1a05b9611/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
      /home/tyoc213/.cache/bazel/_bazel_tyoc213/19011bf2b17a0b6da5215ad1a05b9611/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
    Repository rule _go_download_sdk defined at:
      /home/tyoc213/.cache/bazel/_bazel_tyoc213/19011bf2b17a0b6da5215ad1a05b9611/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
    ERROR: Analysis of target '//tensorflow/compiler/xla/xla_client:libxla_computation_client.so' failed; build aborted: Problem getting numpy include path.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'numpy'
    Is numpy installed?
    INFO: Elapsed time: 0.394s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded, 11 targets configured)
    FAILED: Build did NOT complete successfully (0 packages loaded, 11 targets configured)
    Failed to build external libraries: ['/home/tyoc213/Documents/github/pytorch/xla/build_torch_xla_libs.sh', '-O', '-D_GLIBCXX_USE_CXX11_ABI=0', 'egg_info']
    Building torch_xla version: 1.6
    XLA Commit ID: 8ff7d3fb2b5cd24d966a5eee38be7fd26e9638fe
    PyTorch Commit ID: 05c8cd748ddc241d663951c96a7afdf756006aa8
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

## Environment

 - torch_xla version: just cloned form the repo 
```
$ python ../torch/utils/collect_env.py 
Collecting environment information...
PyTorch version: 1.8.0a0+05c8cd7
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.19.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0a0+unknown
[pip3] torchvision==0.9.0a0+a3c0e67
[conda] blas                      1.0                         mkl  
[conda] magma-cuda112             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py36he8ac12f_0  
[conda] mkl_fft                   1.2.0            py36h23d657b_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] numpy                     1.19.2           py36h54aff64_0  
[conda] numpy-base                1.19.2           py36hfa32c7d_0  
[conda] torch                     1.8.0a0+unknown           dev_0    <develop>
[conda] torchvision               0.9.0a0+a3c0e67           dev_0    <develop>

```

## Additional context

Same prompt, can import numpy

```
$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.19.2'
```

**Comment by tyoc213** [comment]
seem it comes from this folder... which was modified 10 days a go https://github.com/tensorflow/tensorflow/tree/master/third_party/py

**Comment by tyoc213** [comment]
Found solution here https://github.com/google/mediapipe/issues/724#issuecomment-657189385

so I did `which python` to find the path, then

```
export PYTHON_BIN_PATH=/home/tyoc213/miniconda3/envs/xla/bin/python
```

Not so sure why I need now to set up PYTHON_BIN_PATH as the times I have compiled before, this wasn't a requeriment.

Will leave this open for the moment so that ppl can read it and maybe provide some feedback in why or why not for local installs under conda in this case.

**Comment by tyoc213** [comment]
Got again the error tracked here https://github.com/pytorch/xla/pull/2721#issuecomment-757013666 and need to apply same solution

```
 make[2]: *** No rule to make target '/home/tyoc213/Documents/github/pytorch/xla/build/lib.linux-x86_64-3.6/torch_xla/lib/libxla_computation_client.so', needed by 'test_ptxla'.  Stop.
    make[2]: *** Waiting for unfinished jobs....
```

**Comment by ailzhang** [comment]
@tyoc213 This sounds like an mismatch environment issue, maybe check:
1. `which pip` and see if matches your `python` from conda? 
2. Try `python setup.py install` instead of `pip install`?

**Comment by tyoc213** [comment]
Yeah, indeed it was (I can compile now), but before I didn't need that I have set `PYTHON_BIN_PATH`.

**Comment by ailzhang** [comment]
Cool I'll close this issue as resolved then, feel free to reopen if you have followup questions!
