### ISSUE TITLE
Error while lowering: f32[768]{0} xla::cast, location=build_fp32_params@fp16_optimizer.py:66, type=f32, dtype=Float, stype=Half

### ISSUE THREAD

**Issue by TaridaGeorge** [pytorch/xla#2774]
## 🐛 Bug

Error: torch_xla/csrc/convert_ops.cpp:84 : Unsupported XLA type 10

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly

## Additional context

```
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.6/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/hydra_train.py", line 91, in cli_main
    hydra_main()
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/distributed/utils.py", line 361, in call_main
    main(cfg, **kwargs)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/train.py", line 143, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/train.py", line 206, in train
    itr = utils.tpu_data_loader(itr)
  File "/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/utils.py", line 673, in tpu_data_loader
    xm.mark_step()
  File "/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Error while lowering: f32[768]{0} xla::cast, location=build_fp32_params@fp16_optimizer.py:66, type=f32, dtype=Float, stype=Half
Error: torch_xla/csrc/convert_ops.cpp:84 : Unsupported XLA type 10
Python Frames:
  build_fp32_params (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/optim/fp16_optimizer.py:66)
  build_optimizer (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/optim/fp16_optimizer.py:289)
  _build_optimizer (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/trainer.py:239)
  lr_scheduler (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/trainer.py:214)
  lr_step (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/trainer.py:849)
  load_checkpoint (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/trainer.py:401)
  load_checkpoint (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/checkpoint_utils.py:201)
  main (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/train.py:126)
  call_main (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq/distributed/utils.py:361)
  hydra_main (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/hydra_train.py:45)
  run_job (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/core/utils.py:127)
  run (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/hydra.py:112)
  <lambda> (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py:350)
  run_and_report (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py:198)
  _run_hydra (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/_internal/utils.py:347)
  decorated_main (/anaconda3/envs/torch-xla-1.6/lib/python3.6/site-packages/hydra/main.py:37)
  cli_main (/home/tarida_george/saa-asr/sssr/libs/fairseq/fairseq_cli/hydra_train.py:91)
  <module> (/anaconda3/envs/torch-xla-1.6/bin/fairseq-hydra-train:33)
```

**Comment by allenwang28** [comment]
My guess here is that `fp16` is being used in the optimizer and is being cast to `fp32` which is not supported in this code path: https://github.com/pytorch/xla/blob/master/torch_xla/csrc/convert_ops.cpp#L83

Maybe we need to set `XLA_USE_F16=1` (https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#environment-variables), but preferably use BF16 instead.

CC: @taylanbil, have you seen this before when working with fairseq?

**Comment by taylanbil** [comment]
Mixed precision is used in fairseq w/o issues in many settings. Can we get some more info on this? What's the dtype of input tensor? which model/task is being trained?
