### ISSUE TITLE
Fixing dataset and model loading 8 times in transformers library

### ISSUE THREAD

**Issue by DarshanDeshpande** [pytorch/xla#2792]
## ❓ Questions and Help
I am new to torch_xla. The current implementation of [run_mlm.py](https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_mlm.py) with [xla_spawn.py](https://github.com/huggingface/transformers/blob/master/examples/xla_spawn.py) from the transformers library loads the dataset for each tpu core which takes almost 10x the RAM required to load it once. Along with this, if a model is to be loaded for continuing the training, it loads the model 8 times as well (one for each core I assume). So I tried to write a custom piece of code to modify this and load the dataset and model only once and then pass it to the TPU cores. This is what I wrote till now

```
def map_fn(index):  
  print(index)

  config = DistilBertConfig(vocab_size=30000)
  model = DistilBertForMaskedLM(config)
  device = xm.xla_device()
  model.to(device)


  data_files = {"train": "/content/NewTrainingData/Combined.txt"}
  tokenized_datasets = ds.load_dataset('text', data_files=data_files)
  tokenizer = DistilBertTokenizerFast.from_pretrained("/content/Tokenizer", do_lower_case=False)
  def tokenize_function(examples):
    # Remove empty lines
    examples["text"] = [line for line in examples["text"] if len(line) > 0 and not line.isspace()]
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128,
        return_special_tokens_mask=True,
    )

  tokenized_datasets.set_transform(tokenize_function)
  

  args = TrainingArguments(output_dir="/content/Files", do_train=True, per_device_train_batch_size=180,weight_decay=0.01, 
                    num_train_epochs=3, save_total_limit=2, save_steps=500,
                    disable_tqdm=False, remove_unused_columns=False, tpu_num_cores=8)
  
  data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm_probability=0.15)
  trainer = Trainer(
      model=model,
      args=args,
      train_dataset=tokenized_datasets["train"],
      tokenizer=tokenizer,
      data_collator=data_collator,
  )
  trainer.train()

xmp.spawn(map_fn, args=(), nprocs=1, start_method='fork')
```
My problem here is that this code only works when nprocs=1. When I change nprocs to 8, it throws this error for each TPU core
```
Cannot replicate if number of devices (1) is different from 8
```

I would be very grateful if someone could help me with this implementation

**Comment by taylanbil** [comment]
This tool exists, see `xm.MpModelWrapper` as in https://www.github.com/pytorch/xla/tree/master/contrib%2Fcolab%2Fresnet18-training.ipynb

**Comment by DarshanDeshpande** [comment]
Hey @taylanbil I tried using `xm.MpModelWrapper` both inside and outside the `map_fn`. It still gives the `Cannot replicate if number of devices (1) is different from 8` error when the model is initialized outside (and assigned to the xla device inside) `map_fn` whereas it loads the dataset and model 8 times when it is initialized inside. Any idea what could be wrong?

**Comment by taylanbil** [comment]
This error will happen if you use an api from `xm`, including acquiring the device via `xm.xla_device`, outside of `map_fn`. If you eliminate all of those, do you still see it?

**Comment by DarshanDeshpande** [comment]
@taylanbil Unfortunately, yes. The code looks something like this
```
model = xmp.MpModelWrapper(DistilBertForMaskedLM.from_pretrained('...')

def map_fn(index):
  device = xm.xla_device()
  model.to(device)
  ....
  ....

xmp.spawn(map_fn, args=(), nprocs=8)
```
This still throws the error

**Comment by taylanbil** [comment]
This works for me:

```python
import torch
import torch.nn as nn
import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp


net = nn.Sequential(
    *[
        nn.Linear(100,100),
        nn.Linear(100,100),
        nn.Linear(100,100),
    ]
)
model = xmp.MpModelWrapper(net)

def map_fn(index):
  device = xm.xla_device()
  model.to(device)
  xm.rendezvous('hi')
  print('DONE', flush=True)


if __name__ == "__main__":
    xmp.spawn(map_fn, args=(), nprocs=8)
```

The differences I'm seeing b/w this and your code snippet are:
- I am using `if __name__...` and you are not, and if I delete that, torch.distributed.spawn throws for me, but it's a different error than "cannot replicate...". Could you try w/ adding this before `xmp.spawn`?
- I'm not using a Huggingface model. Maybe when you import the model they acquire an xla device? I highly highly doubt that it would be the case though.

The error comes from [this line.](https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L286), but it would be useful to see the call stack above that line, could you include it?

**Comment by DarshanDeshpande** [comment]
I am using Colab's TPU so I created a script and executed it through a cell and `if __name__ == "__main__"` does not seem to be working. I tried using MpSerialExecutor as was done in the example that you shared with me but that didn't work as well. What seemed weird to me was that if I initialize a model from scratch, the code does not give me any error but if I load it from a checkpoint, it starts throwing that error. My code, for reference, is as follows

```
import transformers
from transformers import DataCollatorForLanguageModeling, Trainer
import datasets as ds
from transformers import TrainingArguments
from transformers import DistilBertConfig, DistilBertForMaskedLM, DistilBertTokenizerFast

import nlp
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.debug.metrics as met
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_multiprocessing as xmp
import torch_xla.utils.utils as xu

config = DistilBertConfig(vocab_size=30000)
model = xmp.MpModelWrapper(DistilBertForMaskedLM.from_pretrained("/content/checkpoint-38000"))

SERIAL_EXEC = xmp.MpSerialExecutor()
tokenizer = DistilBertTokenizerFast.from_pretrained("/content/Tokenizer", do_lower_case=False)

def get_tok():
  data_files = {"train": "/content/drive/Combined.txt"}
  tokenized_datasets = ds.load_dataset('text', data_files=data_files)
  
  def tokenize_function(examples):
    # Remove empty lines
    examples["text"] = [line for line in examples["text"] if len(line) > 0 and not line.isspace()]
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128,
        return_special_tokens_mask=True,
    )
  return tokenized_datasets.with_transform(tokenize_function)

def get_col():
  return DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm_probability=0.15)


def map_fn(index):  
  device = xm.xla_device()
  model.to(device)
  xm.rendezvous("hi")
  args = TrainingArguments(output_dir="/content/TPUCheckpoints", do_train=True, per_device_train_batch_size=128,weight_decay=0.01, 
                    num_train_epochs=3, save_total_limit=2, save_steps=500,
                    disable_tqdm=False, remove_unused_columns=False, ignore_data_skip=False)
                    
  tokenized_datasets = SERIAL_EXEC.run(get_tok)
  # xm.rendezvous("tok")
  data_collator = SERIAL_EXEC.run(get_col)
  # xm.rendezvous("col")
  
  trainer = Trainer(
      model=model,
      args=args,
      train_dataset=tokenized_datasets["train"],
      tokenizer=tokenizer,
      data_collator=data_collator,
  )
  trainer.train()

if __name__ == "__main__":
  xmp.spawn(map_fn, args=(), nprocs=8, start_method='fork')
```
Here is the complete error log

```
2021-02-26 07:05:48.426095: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
WARNING:root:TPU has started up successfully with version pytorch-1.7
Exception in device=TPU:0: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _setup_replication
    xm.set_replication(device, [device])
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 315, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 287, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
Exception in device=TPU:1: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _setup_replication
    xm.set_replication(device, [device])
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 315, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 287, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
Exception in device=TPU:2: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _setup_replication
    xm.set_replication(device, [device])
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 315, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 287, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
Exception in device=TPU:3: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _setup_replication
    xm.set_replication(device, [device])
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 315, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 287, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
Exception in device=TPU:4: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _setup_replication
    xm.set_replication(device, [device])
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 315, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 287, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
Exception in device=TPU:5: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _setup_replication
    xm.set_replication(device, [device])
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 315, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 287, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
Exception in device=TPU:6: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _setup_replication
    xm.set_replication(device, [device])
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 315, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 287, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
Exception in device=TPU:7: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    _setup_replication()
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 316, in _setup_replication
    xm.set_replication(device, [device])
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 315, in set_replication
    replication_devices = xla_replication_devices(devices)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/core/xla_model.py", line 287, in xla_replication_devices
    format(len(local_devices), len(kind_devices)))
RuntimeError: Cannot replicate if number of devices (1) is different from 8
Traceback (most recent call last):
  File "mlm.py", line 90, in <module>
    xmp.spawn(map_fn, args=(), nprocs=8, start_method='fork')
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 395, in spawn
    start_method=start_method)
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 112, in join
    (error_index, exitcode)
Exception: process 0 terminated with exit code 17
```

Now, I know for a fact that the HuggingFace Trainer has its own implementation for TPUs and uses model.to(device). Do you think model.to(device) being called twice might be throwing this error? [This](https://github.com/huggingface/transformers/blob/master/src/transformers/trainer.py) the trainer I am talking about

**Comment by taylanbil** [comment]
I cloned the HF repo and it looks like they indeed send model to device in `from_pretrained`. see https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_utils.py#L1187

You could make a feature request to huggingface about this. In the current state, loading pretrained weights to a model seems to initialize xla apis, which conflicts with the usage of `xmp.MpModelWrapper` and thus requiring 8x the memory usage.

@jysohn23 fyi

**Comment by taylanbil** [comment]
To get around this issue, you could delete the if block https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_utils.py#L1184, use MpModelWrapper and then send model to device in the spawned processes.

**Comment by taylanbil** [comment]
Closing this as it seems to be an HuggingFace feature request rather than a torchxla issue. @DarshanDeshpande Please reopen if needed, if the suggested fix above doesn't work.

**Comment by DarshanDeshpande** [comment]
@taylanbil Yes that does fix the model issue but the dataset issue still exists. Inspite of using the MpSerialExecutor, the dataset is still loaded 8 times. The trainer has its own Parallel Loader [here](https://github.com/huggingface/transformers/blob/master/src/transformers/trainer.py#L1004) which I think is causing the issue but since the resnet example also uses ParallelLoader, I'm unsure if that is the main issue here

**Comment by taylanbil** [comment]
dataset being loaded many times is a general concept as well, all distributed workloads will have that. not a torchxla specific issue.

**Comment by DarshanDeshpande** [comment]
But is this not wasteful? What if my dataset is very large (about a TB in size)? I'm not going to want to fit the entirety of it in the memory right?

**Comment by taylanbil** [comment]
Have a look at https://discuss.pytorch.org/t/how-to-use-dataset-larger-than-memory/37785. This is a common problem, and there are tools and tricks you can use to address, which are discoverable via a google search.

**Comment by DarshanDeshpande** [comment]
Yes I understand the concept of lazy loading and datasets, it's just that I'm familiar with tensorflow's implementation for TPU strategy where it automatically lazy loads and splits the dataset for each core through the tf.data.Dataset pipeline without having to load the entire dataset in memory eight separate times. I was wondering if something similar can be achieved using torchxla since HuggingFace's support for tf is poor. Anyway, I guess this needs some more work from HuggingFace's side than torchxla's. Thank you so much for the help @taylanbil
