### ISSUE TITLE
`index_copy_` test fails on PyTorch/XLA

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#2818]
Mirror of https://github.com/pytorch/pytorch/issues/53256. `test_index_copy_scalars` added in https://github.com/pytorch/pytorch/pull/52203/files only fail on PT/XLA.

**Comment by JackCaoG** [comment]
Was able to repo after patching the pytorch pr, error looks like
```
======================================================================
ERROR: test_index_copy_scalars_xla_float32 (__main__.TestTorchDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/jackcao/anaconda3/envs/pytorch2/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
    raise rte
  File "/usr/local/google/home/jackcao/anaconda3/envs/pytorch2/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 287, in instantiated_test
    result = test_fn(self, *args)
  File "test/test_torch.py", line 4479, in test_index_copy_scalars
    target.index_copy_(0, idx, source)
RuntimeError: /usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/xla/torch_xla/csrc/helpers.cpp:97 : Check failed: min_shape_dim <= dim && dim <= max_shape_dim 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	torch_xla::XlaHelpers::GetCanonicalDimensionIndex(long, long)
	torch_xla::XLATensor::index_copy_(torch_xla::XLATensor&, long, torch_xla::XLATensor const&, torch_xla::XLATensor const&)
	torch_xla::AtenXlaType::index_copy_(at::Tensor&, long, at::Tensor const&, at::Tensor const&)
	c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor& (*)(at::Tensor&, long, at::Tensor const&, at::Tensor const&), at::Tensor&, c10::guts::typelist::typelist<at::Tensor&, long, at::Tensor const&, at::Tensor const&> >::operator()(at::Tensor&, long, at::Tensor const&, at::Tensor const&)
	c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<at::Tensor& (*)(at::Tensor&, long, at::Tensor const&, at::Tensor const&), at::Tensor&, c10::guts::typelist::typelist<at::Tensor&, long, at::Tensor const&, at::Tensor const&> >, at::Tensor& (at::Tensor&, long, at::Tensor const&, at::Tensor const&)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor&, long, at::Tensor const&, at::Tensor const&)
	

```
