### ISSUE TITLE
test demo amp error Unsupported XLA type 10

### ISSUE THREAD

**Issue by qshzh** [pytorch/xla#2917]
## 🐛 Bug

```shell
(pytorch) root@9548ee6eb3ba:/# python pytorch/xla/test/test_train_mp_mnist_amp.py
/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:179.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
Epoch 1 train begin 17:26:52
Exception in device=TPU:0: Error while lowering: f32[128,10]{1,0} xla::cast, type=f32, dtype=Float, stype=Half
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10
Python Frames:

Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "/pytorch/xla/test/test_train_mp_mnist_amp.py", line 184, in _mp_fn
    accuracy = train_mnist(flags)
  File "/pytorch/xla/test/test_train_mp_mnist_amp.py", line 162, in train_mnist
    train_loop_fn(train_device_loader)
  File "/pytorch/xla/test/test_train_mp_mnist_amp.py", line 135, in train_loop_fn
    scaler.step(optimizer)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_xla/amp/grad_scaler.py", line 9, in _maybe_opt_step
    xm.mark_step()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Error while lowering: f32[128,10]{1,0} xla::cast, type=f32, dtype=Float, stype=Half
Error: torch_xla/csrc/convert_ops.cpp:83 : Unsupported XLA type 10
Python Frames:

Traceback (most recent call last):
  File "pytorch/xla/test/test_train_mp_mnist_amp.py", line 194, in <module>
    xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS.num_cores)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 394, in spawn
    start_method=start_method)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 144, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 17
```

## To Reproduce

1. Follow the instructions in readme
2. run on container `gcr.io/tpu-pytorch/xla:nightly_3.7`
3. Container Image id: accc39d863bc

## Environment

 - Reproducible on XLA backend [CPU/TPU]: tpuv3-8
 - torch_xla version: 1.8.1

**Comment by JackCaoG** [comment]
Please check https://github.com/pytorch/xla/issues/2897#issuecomment-822970891. I will try to add a warning message of some sort to make it clear that amp does not work for TPU yet.

**Comment by JackCaoG** [comment]
submitted https://github.com/pytorch/xla/pull/2921 to make it explict

**Comment by byronyi** [comment]
If you only want to use bf16, there is an env var to enable it. PyTorch-native AMP support for bf16 is not there yet.
