### ISSUE TITLE
Code runs GCP v3-8 TPU but not on v3-64  |  torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 17

### ISSUE THREAD

**Issue by thepurpleowl** [pytorch/xla#3042]
## ❓ Questions and Help
I have followed the [official documentation](http://pytorch.org/xla/release/1.9/index.html#running-on-multiple-xla-devices-with-multi-processing) to implement a simple NN model to run on Multiple XLA Devices with Multi-processing. The code runs on a GCP v3-8 TPU node, doesn't run on GCP v3-64 TPU.   

pytorch version: 1.9.0
TPU node pytorch version: pytorch-1.9

I searched in official documentation and checked web; the only similar kinda issue I got is [Process 0 terminated with exit code 17](https://github.com/pytorch/fairseq/issues/2527)

As the code runs on v3-8 node, it should be an code issue. Any idea how to solve this or what to look for?  

---
Following is the error log
```
Exception in device=TPU:0: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1291 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Internal: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Internal: Invalid system configuration: 2x4 host topology with 0 missing hosts, but 1 hosts in total.
         [[{{node configure_distributed_tpu/_0}}]]
  (1) Internal: Invalid system configuration: 2x4 host topology with 0 missing hosts, but 1 hosts in total.
         [[{{node configure_distributed_tpu/_0}}]]
         [[ConfigureDistributedTPU_G3]]
0 successful operations.
0 derived errors ignored. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace()
        xla::XrtComputationClient::InitializeAndFetchTopology(std::string const&, int, std::string const&, tensorflow::ConfigProto const&)
        xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::ComputationClient::Create()


        xla::ComputationClient::Get()


        _PyMethodDef_RawFastCallKeywords

        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords

		_PyEval_EvalFrameDefault
        _PyFunction_FastCallDict
        PyObject_GetAttr
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallDict
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallDict
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords

		_PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        PyEval_EvalCodeEx
        PyEval_EvalCode
        PyRun_StringFlags
        PyRun_SimpleStringFlags
        _Py_UnixMain
        __libc_start_main
*** End stack trace ***
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 322, in _start_fn
    _setup_replication()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 314, in _setup_replication
    device = xm.xla_device()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 231, in xla_device
    devkind=devkind if devkind is not None else None)
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 136, in get_xla_supported_devices
    xla_devices = _DEVICES.value
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/utils/utils.py", line 32, in value
    self._value = self._gen_fn()
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 18, in <lambda>
    _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1291 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorf
low::Status::OK() (Internal: From /job:tpu_worker/replica:0/task:0:
2 root error(s) found.
  (0) Internal: Invalid system configuration: 2x4 host topology with 0 missing hosts, but 1 hosts in total.
         [[{{node configure_distributed_tpu/_0}}]]
  (1) Internal: Invalid system configuration: 2x4 host topology with 0 missing hosts, but 1 hosts in total.
         [[{{node configure_distributed_tpu/_0}}]]
         [[ConfigureDistributedTPU_G3]]
0 derived errors ignored. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace()
        xla::XrtComputationClient::InitializeAndFetchTopology(std::string const&, int, std::string const&, tensorflow::ConfigProto const&)
        xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::ComputationClient::Create()


        xla::ComputationClient::Get()


        _PyMethodDef_RawFastCallKeywords

        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords

        _PyEval_EvalFrameDefault
        _PyFunction_FastCallDict
        PyObject_GetAttr
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallDict
        _PyEval_EvalFrameDefault
		_PyFunction_FastCallDict
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_FastCallKeywords
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        PyEval_EvalCodeEx
        PyEval_EvalCode
        PyRun_StringFlags
        PyRun_SimpleStringFlags
        _Py_UnixMain
        __libc_start_main
*** End stack trace ***
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    xmp.spawn(run, args=())
  File "/opt/conda/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 394, in spawn
    start_method=start_method)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 144, in join
    exit_code=exitcode
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 17

```

**Comment by zcain117** [comment]
what was the command you used to kick off the training for v3-8 and what was the command for v3-64?

Take a look at this guide: https://cloud.google.com/tpu/docs/tutorials/pytorch-pod

That one is a better tutorial if you want to try using a TPU that is bigger than the v3-8. In particular note that the training command is a bit different for the v3-64 case - you have to use `torch_xla.distributed.xla_dist`

**Comment by thepurpleowl** [comment]
Yes. That seems to be the reason.

As per guide - 

> An instance group of VMs is connected to a TPU pod. **One VM is needed for each group of 8 TPU cores.** The VMs feed data to the TPU cores and all training occurs on the TPU Pod.

Which means there's a one-to-one correspondence between one VM-> 8 cores. So in pytorch_xla the batch size should be decided considering 8 cores or 64 cores, in case of v3-64 tpu?

For example- if batch size = 128, then [sharded TPU batch size](https://cloud.google.com/tpu/docs/performance-guide#model_processing_performance) will be 16 or 2?

**Comment by zcain117** [comment]
In case of v3-64 tpu, there will be 8 VMs driving 8 cores each. So I think each VM would receive 1/8th the dataset

Here is some example code from our team that works well on TPU pod slices such as v3-64: https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L155

`xm.xrt_world_size()` will return the number of VMs, or you can think of it as (number of total TPU cores / 8)

**Comment by thepurpleowl** [comment]
Ok. So if a batch size of 16 is not getting OOM on a v3-8, then a batchsize of 128 should not be getting OOM on a v3-64, correct?

**Comment by zcain117** [comment]
what do you mean by batch size?  If it's the `batch_size` arg to a torch data loader, then if you pass `batch_size=128` then I think there will be 128 images passed for each forward pass regardless of the TPU pod size. It's the dataset that gets sharded. So each VM will have a shard of the dataset ready to split into batches to pass into each training pass
