### ISSUE TITLE
How to concatenate all the predicted labels in XLA?

### ISSUE THREAD

**Issue by gabrielwong1991** [pytorch/xla#3090]
## ❓ Questions and Help
Hi does anyone knows how to get all predicted labels from all 8 cores of XLA and concatenate them together?

Say I have a model:
`outputs = model(ids, mask, token_type_ids)`
`_, pred_label = torch.max(outputs.data, dim = 1)`

If I do
`all_predictions_np = pred_label.cpu().detach().numpy().tolist()`

apparently, this only sends the result to CPU from TPU core:0. How can I get all 8 cores and concatenate them together in the same list? I am not sure if `xm.all_gather() ` is used in this case?

**Comment by JackCaoG** [comment]
`xm.all_gather` will do what you described. `all_reduce`, `all_gather` and `all_to_all` are cross core communication methods we have right now.

**Comment by JackCaoG** [comment]
[here](https://github.com/pytorch/xla/blob/08ae1044c2a7e314895f9946104cbe399e096515/test/test_mp_all_gather.py) is an simple example of `all_gather` in pt/xla.

**Comment by gabrielwong1991** [comment]
Hi, I try to follow the example of `all_gather` on `pred_label`:

`all_prediction_np = xm.all_gather(pred_label)`

It receives the following error:

`2021-08-19 18:10:26.491034: W   16036 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1629396626.490905199","description":"Error received from peer ipv4:10.70.101.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2021-08-19 18:10:26.491034: W   16152 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1629396626.490896256","description":"Error received from peer ipv4:10.70.101.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2021-08-19 18:10:26.491034: W   16075 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1629396626.490884027","description":"Error received from peer ipv4:10.70.101.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2021-08-19 18:10:26.491034: W   16018 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1629396626.490905324","description":"Error received from peer ipv4:10.70.101.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2021-08-19 18:10:26.491067: W   16175 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1629396626.490884213","description":"Error received from peer ipv4:10.70.101.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2021-08-19 18:10:26.491113: W   16144 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1629396626.491012119","description":"Error received from peer ipv4:10.70.101.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2021-08-19 18:10:26.491138: W   16191 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1629396626.490982298","description":"Error received from peer ipv4:10.70.101.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2021-08-19 18:10:26.491460: W   16066 tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "Unavailable: Socket closed" and grpc_error_string = "{"created":"@1629396626.491378050","description":"Error received from peer ipv4:10.70.101.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2021-08-19 18:10:44.020572: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88] StackTrace:
2021-08-19 18:10:44.020646: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** Begin stack trace ***
2021-08-19 18:10:44.020655: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        tensorflow::CurrentStackTrace()
2021-08-19 18:10:44.020663: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::ReportComputationError(tensorflow::Status const&, absl::lts_20210324::Span<xla::XlaComputation const* const>, absl::lts_20210324::Span<xla::Shape const* const>)
2021-08-19 18:10:44.020672: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::XrtComputationClient::CheckCompileStatus(tensorflow::Status const&, std::vector<xla::ComputationClient::CompileInstance, std::allocator<xla::ComputationClient::CompileInstance> > const&, xla::XrtComputationClient::SessionWork const&)
2021-08-19 18:10:44.020680: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.020697: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::MultiWait::Complete(std::function<void ()> const&)
2021-08-19 18:10:44.020708: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.020716: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.020761: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.020768: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        clone
2021-08-19 18:10:44.020776: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** End stack trace ***
2021-08-19 18:10:44.020785: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.020792: E   16066 tensorflow/compiler/xla/xla_client/xla_util.cc:88] Status: Aborted: Session 18695ce3691f4c2a is not found.
Exception in device=TPU:4: Aborted: Session 18695ce3691f4c2a is not found.
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "inference.py", line 194, in map_fn
    all_data_idx, all_predictions, all_predictions_prob = eval_loop_fn(para_eval_loader, model, device,   progress_bar=progress_bar)
  File "inference.py", line 78, in eval_loop_fn
    for bi, data in enumerate(eval_dataloader):
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 34, in __next__
    return self.next()
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 46, in next
    xm.mark_step()
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Aborted: Session 18695ce3691f4c2a is not found.
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
  what():  tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1172 : Check failed: session->session()->Run( feed_inputs, {}, {cached_node.operations[0]}, &outputs) == ::tensorflow::Status::OK() (Aborted: Session 18695ce3691f4c2a is not found. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace()
        xla::XrtComputationClient::ReleaseHandles(std::vector<xla::XrtComputationClient::DeviceHandle, std::allocator<xla::XrtComputationClient::DeviceHandle> >*, std::function<xla::XrtSession::CachedNode const& (xla::XrtSession*, tensorflow::Scope const&, std::string const&)> const&, xla::metrics::Metric*, xla::metrics::Counter*)
        xla::XrtComputationClient::HandleReleaser()
        xla::util::TriggeredTask::Runner()


        clone
*** End stack trace ***
2021-08-19 18:10:44.215543: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88] StackTrace:
2021-08-19 18:10:44.215613: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** Begin stack trace ***
2021-08-19 18:10:44.215622: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        tensorflow::CurrentStackTrace()
2021-08-19 18:10:44.215630: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::ReportComputationError(tensorflow::Status const&, absl::lts_20210324::Span<xla::XlaComputation const* const>, absl::lts_20210324::Span<xla::Shape const* const>)
2021-08-19 18:10:44.215645: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::XrtComputationClient::CheckCompileStatus(tensorflow::Status const&, std::vector<xla::ComputationClient::CompileInstance, std::allocator<xla::ComputationClient::CompileInstance> > const&, xla::XrtComputationClient::SessionWork const&)
2021-08-19 18:10:44.215653: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.215669: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        xla::util::MultiWait::Complete(std::function<void ()> const&)
2021-08-19 18:10:44.215716: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.215726: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.215736: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.215747: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]        clone
2021-08-19 18:10:44.215757: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88] *** End stack trace ***
2021-08-19 18:10:44.215768: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88]
2021-08-19 18:10:44.215778: E   16144 tensorflow/compiler/xla/xla_client/xla_util.cc:88] Status: Aborted: Session cdddf6a41076995c is not found.
Exception in device=TPU:7: Aborted: Session cdddf6a41076995c is not found.
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 329, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 323, in _start_fn
    fn(gindex, *args)
  File "inference.py", line 194, in map_fn
    all_data_idx, all_predictions, all_predictions_prob = eval_loop_fn(para_eval_loader, model, device,   progress_bar=progress_bar)
  File "inference.py", line 78, in eval_loop_fn
    for bi, data in enumerate(eval_dataloader):
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 34, in __next__
    return self.next()
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/parallel_loader.py", line 46, in next
    xm.mark_step()
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/core/xla_model.py", line 718, in mark_step
    wait=xu.getenv_as('XLA_SYNC_WAIT', bool, False))
RuntimeError: Aborted: Session cdddf6a41076995c is not found.
Traceback (most recent call last):
  File "inference.py", line 232, in <module>
    main()
  File "inference.py", line 229, in main
    xmp.spawn(map_fn, args=(flags,), nprocs=8, start_method='fork')
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 394, in spawn
    start_method=start_method)
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/anaconda3/envs/torch-xla-1.9/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 136, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 4 terminated with signal SIGABRT
`

Any ideas?

**Comment by gabrielwong1991** [comment]
I managed to use `xm.mesh_reduce("reduce", pred_label, torch.cat)` instead. Thanks

**Comment by JackCaoG** [comment]
hmm, yea the error seems like there is a remote crash on the server side, which is not expected. Glad that you find a solution that worked for you, feel free to reopen if you have any follow up question.
