### ISSUE TITLE
[PT_BREAK] Test crash after `torch.where` change

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3105]
Pytroch pr in https://github.com/pytorch/pytorch/pull/62084, failure log
```
Aug 30 13:03:21 ERROR [0.037s]: test_where_scalar_valid_combination_xla_uint8 (__main__.TestTorchDeviceTypeXLA)
Aug 30 13:03:21 ----------------------------------------------------------------------
Aug 30 13:03:21 Traceback (most recent call last):
Aug 30 13:03:21   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
Aug 30 13:03:21     raise rte
Aug 30 13:03:21   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 373, in instantiated_test
Aug 30 13:03:21     result = test(self, **param_kwargs)
Aug 30 13:03:21   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 7694, in test_where_scalar_valid_combination
Aug 30 13:03:21     self._test_where_scalar_template(device, dtype, checkResult)
Aug 30 13:03:21   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 7659, in _test_where_scalar_template
Aug 30 13:03:21     exec_fn(scalar_type, dtype, condition, x, scalar_1)
Aug 30 13:03:21   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 7683, in checkResult
Aug 30 13:03:21     self.assertEqual(scalar_out, tensor_out)
Aug 30 13:03:21   File "/var/lib/jenkins/workspace/xla/test/pytorch_test_base.py", line 606, in assertEqual
Aug 30 13:03:21     x, y = self.prepare_for_compare(x, y)
Aug 30 13:03:21   File "/var/lib/jenkins/workspace/xla/test/pytorch_test_base.py", line 549, in prepare_for_compare
Aug 30 13:03:21     x = tx.to(device='cpu')
Aug 30 13:03:21 RuntimeError: Error while lowering: u8[0]{0} aten::where
Aug 30 13:03:21 Error: /var/lib/jenkins/workspace/xla/torch_xla/csrc/helpers.cpp:584 : Check failed: xla::ShapeUtil::SameElementType(shape1, shape2) 
Aug 30 13:03:21 *** Begin stack trace ***
Aug 30 13:03:21 	tensorflow::CurrentStackTrace[abi:cxx11]()
Aug 30 13:03:21 	torch_xla::XlaHelpers::PromoteShapes(xla::XlaOp, xla::XlaOp)
Aug 30 13:03:21 	
Aug 30 13:03:21 	torch_xla::ir::ops::Generic::Lower(torch_xla::ir::LoweringContext*) const
Aug 30 13:03:21 	torch_xla::ir::LoweringContext::LowerNode(torch_xla::ir::Node const*)
Aug 30 13:03:21 	torch_xla::ir::LoweringContext::LoweringContext(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, torch_xla::Device, absl::lts_20210324::Span<torch_xla::ir::Node const* const>, std::unordered_map<torch_xla::ir::Node const*, torch_xla::ir::Util::EmitStatus, std::hash<torch_xla::ir::Node const*>, std::equal_to<torch_xla::ir::Node const*>, std::allocator<std::pair<torch_xla::ir::Node const* const, torch_xla::ir::Util::EmitStatus> > >)
Aug 30 13:03:21 	torch_xla::XLATensor::Compile(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> > const&, absl::lts_20210324::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch_xla::XLATensor::SyncTensorCollection const&, torch_xla::XLATensor::PostOrderData*)
Aug 30 13:03:21 	torch_xla::XLATensor::SyncTensorsGraphInternal(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*, absl::lts_20210324::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch_xla::XLATensor::SyncTensorsConfig const&)
Aug 30 13:03:21 	torch_xla::XLATensor::SyncTensorsGraph(std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >*, absl::lts_20210324::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, bool, bool)
Aug 30 13:03:21 	torch_xla::XLATensor::ApplyPendingGraph()
Aug 30 13:03:21 	torch_xla::XLATensor::GetXlaData()
```

**Comment by JackCaoG** [comment]
This seems to be introduced by the type promotion inconsistency between pt and pt/xla
```
(Pdb) torch.where(condition, x, scalar_1)
tensor([], device='xla:0', dtype=torch.uint8)
(Pdb) torch.where(condition.cpu(), x.cpu(), scalar_1)
tensor([], dtype=torch.int64)
(Pdb) x.dtype
torch.uint8
(Pdb) scalar_1
0
```

PyTorch/XLA where is defined like
```
at::Tensor XLANativeFunctions::_s_where(const at::Tensor& condition,
                                        const at::Tensor& self,
                                        const at::Tensor& other)
```
If I print `self` and `other` I see
```
[ XLAByteType{0} ]
[ XLALongType{0} ]
```

It seem like scalar integer is being converted to a int64. PyTorch will handle this kind of mismatch type by promoting both `input` and `other` to `at::result_type(self, other)` . Pytorch/XLA can follow this behavior.

**Comment by JackCaoG** [comment]
This turn out to be more complicated than I thought. I want to reuse the pytorch/xla type promotion logic instead of force a casting at aten level, but somehow it does not work.

**Comment by JackCaoG** [comment]
After pytorch side update, xla seems to be get the fix for free
```
t1 = torch.tensor([1], device=device).to(torch.uint8)
t2 = torch.tensor([True], device=device)

print(torch.where(t2, t1, 45))
```

```
self type unsigned char
other type unsigned char
```

scalar was correctly cast to uint8.

**Comment by JackCaoG** [comment]
was able to repo the error
```
======================================================================
ERROR: test_reference_eager_where_xla_int64 (__main__.TestOpInfoXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/jackcao/anaconda3/envs/pytorch2/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/usr/local/google/home/jackcao/anaconda3/envs/pytorch2/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/usr/local/google/home/jackcao/anaconda3/envs/pytorch2/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 411, in test_reference_eager
    self.compare_with_eager_reference(op, sample_input)
  File "test/test_ops.py", line 402, in compare_with_eager_reference
    self.assertEqual(actual, expected, exact_dtype=True, exact_device=False)
  File "/usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/xla/test/pytorch_test_base.py", line 609, in assertEqual
    x, y = self.prepare_for_compare(x, y)
  File "/usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/xla/test/pytorch_test_base.py", line 552, in prepare_for_compare
    x = tx.to(device='cpu')
RuntimeError: Error while lowering: s64[5,5]{1,0} aten::where, location=<lambda>@common_methods_invocations.py:11330
Error: /usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/xla/torch_xla/csrc/helpers.cpp:587 : Check failed: xla::ShapeUtil::SameElementType(shape1, shape2) 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	torch_xla::XlaHelpers::PromoteShapes(xla::XlaOp, xla::XlaOp)
```

**Comment by JackCaoG** [comment]
Seems like pytorch/xla can not handle mix of int64 and floating scalar 
```
bool_t = torch.tensor([True, False], device=device)
true_t = torch.tensor([10, 20], device=device)

t1 = torch.where(bool_t, true_t, 0.5)
```

error message
```
Error: /usr/local/google/home/jackcao/Desktop/gitProj2/pytorch/xla/torch_xla/csrc/helpers.cpp:587 : Check failed: xla::ShapeUtil::SameElementType(shape1, shape2) 
...
s64[2]{0} and f32[2]{0}
```
