### ISSUE TITLE
Support running PyTorch/XLA on docker on TPUVM

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3132]
## Motivation

This is to support running github CI on TPUVM

@sgugger @miaoshasha

**Comment by JackCaoG** [comment]
@miaoshasha has tried running
```
sudo docker pull gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm_20210827
sudo docker run -it --shm-size 16G gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm_20210827
export TPU_IP_ADDRESS=10.128.15.203
export XRT_TPU_CONFIG="localservice;0;localhost:51011"
python3
import torch_xla.core.xla_model as xm
dev = xm.xla_device()
-----------------------output------------------
2021-09-17 17:56:35.994077: E      13 tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2021-09-17 17:56:35.994154: E      13 tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 231, in xla_device
    devices = get_xla_supported_devices(
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 137, in get_xla_supported_devices
    xla_devices = _DEVICES.value
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_xla/utils/utils.py", line 32, in value
    self._value = self._gen_fn()
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 19, in <lambda>
    _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1291 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Invalid argument: No matching devices found for '/job:localservice/replica:0/task:0/device:TPU_SYSTEM:0' vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace()
        xla::XrtComputationClient::InitializeAndFetchTopology(std::string const&, int, std::string const&, tensorflow::ConfigProto const&)
        xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::ComputationClient::Create()


        xla::ComputationClient::Get()


        PyCFunction_Call
        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall


        _PyObject_GenericGetAttrWithDict
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall



        _PyEval_EvalCodeWithName
        PyEval_EvalCode



        PyRun_InteractiveLoopFlags
        PyRun_AnyFileExFlags

        Py_BytesMain
        __libc_start_main

*** End stack trace ***
```

**Comment by JackCaoG** [comment]
I suspect this is a related to `libtpu.so` is not visable from the docker, therefore I manually copy the library over with
```
sudo docker cp /lib/libtpu.so acb6c85eba44:/lib/
```

and I verified that libtpu is presented within the docker
```

(pytorch) root@acb6c85eba44:/# ls /lib
cpp  init  ld-linux.so.2  libtpu.so  lsb  systemd  terminfo  udev  x86_64-linux-gnu
```

However I still get 
```
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1291 : Check failed: session.Run({tensorflow::Output(result, 0)}, &outputs) == ::tensorflow::Status::OK() (Invalid argument: No matching devices found for '/job:localservice/replica:0/task:0/device:TPU_SYSTEM:0' vs. OK)
```

**Comment by JackCaoG** [comment]
One thing I noticed is that from the host, I can see the TPU chip under `/dev`
```
jackcao@t1v-n-7af0a8f9-w-0:/dev$ ls | grep accel
accel0
accel1
accel2
accel3
```

but these are not visible from the docker
```
(pytorch) root@acb6c85eba44:/# ls /dev/
console  core  fd  full  mqueue  null  ptmx  pts  random  shm  stderr  stdin  stdout  tty  urandom  zero
```

For GPU, we need to pass `--gpus all` when launching docker. Checking with infra folks regarding the device not found issue.

**Comment by JackCaoG** [comment]
It turned out that we need to pass `--privileged` to make `/dev` accesiable and use `-v "/lib/libtpu.so:/lib/libtpu.so"` to pass libtpu through. The whole process looks like
```
sudo docker pull gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm
jackcao@t1v-n-7af0a8f9-w-0:~$ sudo docker run --privileged -v "/lib/libtpu.so:/lib/libtpu.so" --shm-size 16G -it -d  gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm_20210827
33bbe269a7738af325b9aaacb27976c607f657f9bf40a986e6e35ad6a696f9ec
jackcao@t1v-n-7af0a8f9-w-0:~$ sudo docker ps | grep xla:nightly_3.8_tpuvm_20210827
33bbe269a773   gcr.io/tpu-pytorch/xla:nightly_3.8_tpuvm_20210827          "docker-entrypoint.s…"   11 seconds ago   Up 10 seconds             trusting_roentgen
jackcao@t1v-n-7af0a8f9-w-0:~$ sudo docker exec --privileged -it  33bbe269a773 /bin/bash
(pytorch) root@33bbe269a773:/# ls /dev | grep accel
accel0
accel1
accel2
accel3
(pytorch) root@33bbe269a773:/# ls /lib | grep tpu
libtpu.so
(pytorch) root@33bbe269a773:/# export XRT_TPU_CONFIG="localservice;0;localhost:51011"
(pytorch) root@33bbe269a773:/# python3 pytorch/xla/test/test_train_mp_mnist.py
```

Couple notes here
1. Pytorch/XLA publish docker image for tpuvm everyday, maybe it is easier to just use this docker image. If you want to use your own image, please build with `TPUVM_MODE=1`.
2. `libtpu.so`  on `v2-alpha` will not work with the current nightly. I cut a version of `v2-nightly` recently so user can create their TPUVM with
```
gcloud alpha compute tpus tpu-vm create your_tpu_vm --zone $ZONE --accelerator-type v3-8 --version v2-nightly20210914 --project $PROJECT
```

**Comment by sgugger** [comment]
Thanks for all the info (cc @LysandreJik)

**Comment by MrDavinci** [comment]
Hi, I'm using a TPU-v3 vm. The prebuilt enviroment is  tpu-vm-pt-1.11. It is OK to use tpu by the defult enviroment. But, the error happens when I start an xla container.  I have tried several docker images such as  nightly_3.7nightly_3.7_20220624,  r1.12_3.7_tpuvmr1.12_3.7_tpuvm_20220614, r1.12_3.8_tpuvmr1.12_3.8_tpuvm_20220614. They all output the same error you encountered.

**Comment by matanby** [comment]
Same thing here. Tried to follow @JackCaoG 's proposed solution, but without luck.
