### ISSUE TITLE
TPU fails to connect

### ISSUE THREAD

**Issue by MathieuTuli** [pytorch/xla#3163]
## 🐛 Bug

Unable to run ImageNet example [test/test_train_mp_imagenet.py](test/test_train_mp_imagenet.py), fails to connect to mesh master.

Currently running `toch-xla-1.9`.
Some other info:
```
conda activate torch-xla-1.9
gcloud compute tpus list --zone=us-central1-b
>>> result = COMPUTE-VM-NAME  us-central1-b  v2-8              default  10.40.209.96/29  READY
export TPU_IP_ADDRESS=ip-address;
export XRT_TPU_CONFIG="tpu_worker;0;$TPU_IP_ADDRESS:8470"
echo $XRT_TPU_CONFIG 
>>> result = tpu_worker;0;10.40.209.96:8470

python /usr/share/torch-xla-1.9/pytorch/xla/test/test_train_mp_imagenet.py --fake_data --model=resnet50 --num_epochs=2 --batch_size=128 --log_steps=20

```
## Error

*** End stack trace ***
Failed to connect to client mesh master: COMPUTE-VM-NAME.us-central1-a.cCOMPUTE-VM-NAME.internal:43781
Traceback (most recent call last):
  File "/usr/share/torch-xla-1.7/pytorch/xla/test/test_train_mp_imagenet.py", line 267, in <module>
    xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS.num_cores)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 395, in spawn
    start_method=start_method)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 112, in join
    (error_index, exitcode)
Exception: process 4 terminated with exit code 17

## Additional Context
In this instant, my compute vm is in zone us-central1-a, tpu instance is in us-central1-b. I have tried with both compute vm and tpu instance in the same zone, the issue persists.

Same issue from issue #2676 it seems, although change to torch-xla-1.7 did not resolve the issue.

**Comment by MathieuTuli** [comment]
Ah I see, yes you're right, when I use the proper IP address from the describe command, rather than the CIDR block, it works. The tutorial was a bit confusing on that point, and given only the last bits of the address were change I overlooked the slight various in CIDR block address vs. proper ip address, thanks! Closing now as this is resolved.
