### ISSUE TITLE
[PT_BREAK] test_advancedindex_mixed_cpu_devices_xla

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3206]
## 🐛 Bug

Got a bunch of email regarding this test failed on pytorch pr
```
Nov 09 19:27:49 ======================================================================

Nov 09 19:27:49 ERROR [0.051s]: test_advancedindex_mixed_cpu_devices_xla (__main__.TestDevicePrecisionXLA)

Nov 09 19:27:49 ----------------------------------------------------------------------

Nov 09 19:27:49 Traceback (most recent call last):

Nov 09 19:27:49   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test

Nov 09 19:27:49     raise rte

Nov 09 19:27:49   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test

Nov 09 19:27:49     result = test(self, **param_kwargs)

Nov 09 19:27:49   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 915, in multi_fn

Nov 09 19:27:49     return fn(slf, devices, *args, **kwargs)

Nov 09 19:27:49   File "/var/lib/jenkins/workspace/xla/test/../../test/test_torch.py", line 8203, in test_advancedindex_mixed_cpu_devices

Nov 09 19:27:49     test(x, ia, ib)
```

**Comment by JackCaoG** [comment]
I will go ahead and disable the test for now and do the investigation later.

**Comment by miladm** [comment]
@wonjoolee95 can you please take a pass at this issue?

**Comment by JackCaoG** [comment]
It is actually already fixed. Check https://github.com/pytorch/xla/pull/3213. I will close this issue.
