### ISSUE TITLE
GPU AMP syncfree optimizer test failure

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3322]
## 🐛 Bug

```
test_adam_optimizer (__main__.TestSyncFreeAdam) ... FAIL
test_optimizer (__main__.TestSyncFreeSGD) ... FAIL

======================================================================
FAIL: test_adam_optimizer (__main__.TestSyncFreeAdam)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_syncfree_optimizers.py", line 178, in test_adam_optimizer
    self._test_adam_optimizer_helper(syncfree.Adam, torch.optim.Adam)
  File "test/test_syncfree_optimizers.py", line 139, in _test_adam_optimizer_helper
    "betas": (0.9, 0.99),
  File "test/test_syncfree_optimizers.py", line 94, in _test_optimizer
    assert syncfree_loss.allclose(ref_loss, rtol=1e-3, atol=1e-3)
AssertionError

======================================================================
FAIL: test_optimizer (__main__.TestSyncFreeSGD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_syncfree_optimizers.py", line 106, in test_optimizer
    "momentum": 0.5,
  File "test/test_syncfree_optimizers.py", line 94, in _test_optimizer
    assert syncfree_loss.allclose(ref_loss, rtol=1e-3, atol=1e-3)
AssertionError
```
## To Reproduce

run GPU CI on pytorch/xla master. @ymwangg Could you take a look? I remembered this test passed on your CI. It might just be a glitch that we need to increate the tolerance.

**Comment by ymwangg** [comment]
@JackCaoG thanks for reporting, will take a look.
