### ISSUE TITLE
Head doc push breaks

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#3448]
## 🐛 Bug

currently doc push failed with message
```
Traceback (most recent call last):
  File "/opt/conda/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/opt/conda/lib/python3.7/site-packages/sphinx/cmd/build.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/opt/conda/lib/python3.7/site-packages/sphinx/application.py", line 42, in <module>
    from sphinx.highlighting import lexer_classes, lexers
  File "/opt/conda/lib/python3.7/site-packages/sphinx/highlighting.py", line 30, in <module>
    from sphinx.ext import doctest
  File "/opt/conda/lib/python3.7/site-packages/sphinx/ext/doctest.py", line 28, in <module>
    from sphinx.builders import Builder
  File "/opt/conda/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 24, in <module>
    from sphinx.io import read_doc
  File "/opt/conda/lib/python3.7/site-packages/sphinx/io.py", line 42, in <module>
    from sphinx.util.rst import append_epilog, docinfo_re, prepend_prolog
  File "/opt/conda/lib/python3.7/site-packages/sphinx/util/rst.py", line 22, in <module>
    from jinja2 import environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/opt/conda/lib/python3.7/site-packages/jinja2/__init__.py)
```

Seems like we need to update some dependency.

**Comment by JackCaoG** [comment]
Issue seems to be related to Jinja2 version, it used to be `Jinja2-3.0.3`, now it become `Jinja2-3.1.0`. This version seems to cause the issue. I will try to pin the  Jinja2
