### ISSUE TITLE
PT 1.11 Build Error  for GPU ; Error compiling objects for extension 

### ISSUE THREAD

**Issue by codeislife99** [pytorch/xla#3582]
## ❓ Questions and Help
I am getting an error building PT 1.11 XLA along with PT 1.11 with 

`

subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
--
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
File "setup.py", line 319, in <module>
setup(
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
return distutils.core.setup(**attrs)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
return run_commands(dist)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
dist.run_commands()
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
self.run_command(cmd)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
super().run_command(command)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
cmd_obj.run()
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
self.run_command('build')
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
super().run_command(command)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
cmd_obj.run()
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
self.run_command(cmd_name)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
super().run_command(command)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
cmd_obj.run()
File "setup.py", line 226, in run
BuildExtension.run(self)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
_build_ext.run(self)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
self.build_extensions()
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
build_ext.build_extensions(self)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
_build_ext.build_ext.build_extensions(self)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
self._build_extensions_serial()
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
self.build_extension(ext)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
_build_ext.build_extension(self, ext)
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
objects = self.compiler.compile(sources,
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
_write_ninja_file_and_compile_objects(
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
_run_ninja_build(
File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
[0mThe command '/bin/sh -c cd /pytorch && bash xla/scripts/build_torch_wheels.sh ${python_version} ${pt_xla_release_version}' returned a non-zero code: 1
`
I am using CUDA 11.2 and other standard versions which were used in the build. What could be the reason for this error and how would it be possible to reproduce your build ? I don't get this error when I move to the PT1.12 versions

[Longer Build Logs](https://logpaste.com/Qhsdlq4J)

**Comment by JackCaoG** [comment]
Hmm, I think build is passing our end. For 1.11 we have we have docker image
```
* `gcr.io/tpu-pytorch/xla:r1.11_3.7_cuda_11.2`: The current stable version.
```

If you can't resolve the build error you can try to build inside this docker which should have all of the build env ready.

**Comment by codeislife99** [comment]
Yeah, looking at the container I am seeing that I am using the correct PT and PT-XLA commits for my build. But do you think you or someone else has seen this error before or have an idea on why it might be happening

**Comment by codeislife99** [comment]
Okay, I found the reason for the error. The tag v1.11.0 is a bit different from the branch r1.11. The build for r1.11 works fine which is what you used to build the container whereas it doesn't work for the tag. I am using the branch now, but perhaps it might be useful to fix the bug.

**Comment by JackCaoG** [comment]
What is tag v1.11.0?

**Comment by JackCaoG** [comment]
Thanks, I just fix the v1.11.0 tag, now it should be aligned with r1.11 branch.
