### ISSUE TITLE
`sym_sizes` implementation breaks on non-dynamic ops

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#3816]
## 🐛 Bug

I get the following error when integrating dynamic shape for `sym_sizes` in `tensor_impl` class. The error occurs on `47` of the  seemingly [non-dynamic tests](https://github.com/pytorch/pytorch/blob/master/test/test_torch.py#L3314-L3323). 

**Sample ERROR**
```
======================================================================
ERROR: **test_put_xla_uint8** (__main__.TestTorchDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "../test/test_torch.py", line 3326, in test_put
    out = torch.put(dest, idx, source) #, accumulate=accumulate)
RuntimeError: bad optional access
```

Looks like the sym_sizes initialization is missing to handle a corner case.

**Comment by miladm** [comment]
Turns out empty tensors needed to be updated. This fix reduced the number of failures to `23`.
I will share a PR shortly.

**Comment by miladm** [comment]
More errors of similar signature appear. Looking into them. This might be due to how `is_symbolic` is initialized.

```
======================================================================
ERROR: test_index_reduce_reduce_amax_xla_bfloat16 (__main__.TestTorchDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "/workspace/pytorch/xla/test/../../test/test_torch.py", line 2997, in test_index_reduce
    torch.maximum(expected[idx[i]], src[i], out=expected[idx[i]])
RuntimeError: bad optional access
```

**Comment by miladm** [comment]
When `tensor_->GetIrValue().node->shape(0).dim() > 0 `, `tensor_->GetIrValue().node->shape(0).is_symbolic()` can be empty. Added a check to guard against updating `sym_sizes_` when `is_symbolic` returns empty.

**Comment by miladm** [comment]
I realized using `xla::shape` is the way to resolve the issue. These tests error are now resolved.
