### ISSUE TITLE
Shape mismatch due to shape replication while initializing `sym_sizes_` for dynamic shape

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#3839]
## 🐛 Bug

While debugging issues #https://github.com/pytorch/xla/issues/3828 I learnt the solution to address the problem is to replace initializing `sym_sizes_` in tensor_impl constructor with one that takes advantage of a method like [`SetupSizeProperties`](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/tensor_impl.cpp#L159-L179) for `SymInt` objects. In doing so, I am dealing with the following new error that appears to suggest a tensor updating its shape data structures more than once. This failure occurs across over 50 tests.

```
======================================================================
ERROR: test_Dropout_xla (__main__.TestNNDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
    raise rte
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "/workspace/pytorch/xla/test/../../test/test_nn.py", line 14397, in test_Dropout
    self._test_dropout(nn.Dropout, device, input)
  File "/workspace/pytorch/xla/test/../../test/test_nn.py", line 12997, in _test_dropout
    output.backward(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor.py", line 485, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 184, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 72, in _make_grads
    + str(out_shape) + ".")
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1000]) and output[0] has a shape of torch.Size([1000, 1000]).
```

**Comment by miladm** [comment]
My latest changes suggest we don't need to maintain a permanent [`sym_sizes_`](https://github.com/pytorch/xla/pull/3829/files#diff-1edb9f3bb5aa676852199f34cbb2fb731175df85e4bf59c0976df389d01386e3R63) class member variable in `tensor_impl`. Instead we want to fully take advantage of [`sizes_and_strides_`](https://github.com/pytorch/pytorch/blob/master/c10/core/TensorImpl.h#L2484) in  `c10/core/TensorImpl`.

@Krovatkin I think this observation may also apply to the upstream LTC implementation [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/lazy/core/tensor_impl.h#L62). Wdyt?

**Comment by miladm** [comment]
I was able to fix this issue on local tests via this https://github.com/pytorch/xla/commit/7da8d3b47e09332ac43c4c09ac78883c676d7594. Closing.
