### ISSUE TITLE
Simple NN model test with dynamic shape breaks `torch.nn.functional`

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#4075]
Looks like [this code](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L3081) breaks in pytorch when running the test in this [PR](https://github.com/pytorch/xla/pull/4074).

Error message:
```
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    before_train = criterion(y_pred.squeeze(), y_test)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 619, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 3081, in binary_cross_entropy
    if target.size() != input.size():
RuntimeError: NYI
```

CC @Krovatkin

**Comment by Krovatkin** [comment]
could you please paste the command and/or test you are running? @miladm

**Comment by Krovatkin** [comment]
Interesting! We actually failed on a different unimplemented function than I expected. 

```
Thread 1 "python" hit Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x55555b7b8160,
    tinfo=0x7fff4e324728 <typeinfo for c10::Error>, dest=0x7fffd54e0ba0 <c10::Error::~Error()>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/build/gcc-final/x86_64-conda-linux-gnu/libstdc++-v3/libsupc++/eh_throw.cc:77
77      in /opt/conda/conda-bld/gcc-compiler_1654084175708/work/build/gcc-final/x86_64-conda-linux-gnu/libstdc++-v3/libsupc++/eh_throw.cc
(gdb) where
#0  __cxxabiv1::__cxa_throw (obj=0x55555b7b8160, tinfo=0x7fff4e324728 <typeinfo for c10::Error>,
    dest=0x7fffd54e0ba0 <c10::Error::~Error()>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/build/gcc-final/x86_64-conda-linux-gnu/libstdc++-v3/libsupc++/eh_throw.cc:77
#1  0x00007fffd550b605 in c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) ()
   from /root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libc10.so
#2  0x00007fffc688b130 in c10::SymIntNodeImpl::wrap (this=<optimized out>, num=<optimized out>)
    at /home/pytorch/c10/core/SymIntNodeImpl.h:73
```

Initially, I was thinking we failed in a different spot in python, but then I ran py-spy to get the python stack trace and it showed the exact same spot that you hit:

```
Thread 0x7FFFF7FEB740 (active+gil): "MainThread"
    binary_cross_entropy (torch/nn/functional.py:3081)
    forward (torch/nn/modules/loss.py:619)
    _call_impl (torch/nn/modules/module.py:1190)
    <module> (dynamic_shape_model_test.py:74)
```



@vanbasten23 @miladm 

first fix in https://github.com/pytorch/xla/pull/4076
