### ISSUE TITLE
Need to handle randomization in the dynamic shape forward passing test script

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4113]
## 🐛 Bug

This [pr](https://github.com/pytorch/xla/pull/4074/files) created a testing script for testing dynamic shape. The randomization seems making it flaky. For example, I run this script consecutively twice on my docker container in cloudtop (CPU) and got different results:
```
(base) jenkins@c76438fd460f:/workspace$ python3 pytorch/xla/test/dynamic_shape_model_test.py
2022-10-20 23:25:39.431645: W  532017 tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-10-20 23:25:39.431766: W  532017 tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
tensor([[ -3,   4],
        [ -3,  -2],
        [ -3,  -8],
        [ -4,   4],
        [ -3,   3],
        [ -2,  -2],
        [ -5,  -8],
        [ -4,   2],
        [ -2,  -2],
        [ -3, -10]], device='xla:0', dtype=torch.int32)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [3., 0.],
        [3., 1.],
        [4., 0.],
        [4., 1.],
        [5., 0.],
        [5., 1.],
        [6., 0.],
        [6., 1.],
        [7., 0.],
        [7., 1.],
        [8., 0.],
        [8., 1.],
        [9., 0.],
        [9., 1.]], device='xla:0')
tensor([0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0.,
        1., 1.], device='xla:0')
2022-10-20 23:25:39.901710: E  532459 tensorflow/compiler/xla/service/dynamic_padder.cc:1864] Inserting PadToStatic for instruction: %p4.7 = f32[<=20,2]{1,0} parameter(4), metadata={op_type="xla__device_data" op_name="xla__device_data" source_file="@No Python Frames" source_line=-1}
2022-10-20 23:25:39.956433: E  532463 tensorflow/compiler/xla/service/dynamic_padder.cc:1864] Inserting PadToStatic for instruction: %p4.6 = f32[<=20,2]{1,0} parameter(4), metadata={op_type="xla__device_data" op_name="xla__device_data" source_file="@No Python Frames" source_line=-1}
Test loss before training 0.6884850263595581
(base) jenkins@c76438fd460f:/workspace$ python3 pytorch/xla/test/dynamic_shape_model_test.py
2022-10-20 23:25:47.688863: W  532955 tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-10-20 23:25:47.688914: W  532955 tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
tensor([[ 8,  0],
        [ 2,  5],
        [ 7,  2],
        [-5, -2],
        [-1, -3],
        [ 6,  2],
        [-2, -4],
        [ 2,  7],
        [-5, -1],
        [ 1, 10]], device='xla:0', dtype=torch.int32)
tensor([[0., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [3., 0.],
        [3., 1.],
        [4., 0.],
        [4., 1.],
        [5., 0.],
        [5., 1.],
        [6., 0.],
        [6., 1.],
        [7., 0.],
        [7., 1.],
        [8., 0.],
        [8., 1.],
        [9., 0.],
        [9., 1.]], device='xla:0')
tensor([1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
        0., 1.], device='xla:0')
2022-10-20 23:25:48.037353: E  533399 tensorflow/compiler/xla/service/dynamic_padder.cc:1864] Inserting PadToStatic for instruction: %p4.7 = f32[<=20,2]{1,0} parameter(4), metadata={op_type="xla__device_data" op_name="xla__device_data" source_file="@No Python Frames" source_line=-1}
Traceback (most recent call last):
  File "pytorch/xla/test/dynamic_shape_model_test.py", line 79, in <module>
    before_train = criterion(y_pred.squeeze(), y_test)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 619, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 3084, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size())
ValueError: Using a target size (torch.Size([20])) that is different to the input size (torch.Size([Static bound: 20])) is deprecated. Please ensure they have the same size.
```

Looking at the error, it seems expected because the input is generated randomly and the `nonzero` makes `x_test` also random.

**Comment by vanbasten23** [comment]
So I update the test script to make sure we don't have the above shape mismatch error: https://github.com/pytorch/xla/pull/4114/files#diff-744d9fc9b04d57e48ff50e72d9aa720132ad0c5f30368d537746dac1b45fa6e1
 (only the file test/dynamic_shape_model_test.py. Not sure how to show diff between 2 pending PRs.)

Then I run twice consecutively: the first run failed with the error below and the second run succeeded:
```
$ python3 pytorch/xla/test/dynamic_shape_model_test.py
2022-10-21 00:10:47.430105: W  559158 tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-10-21 00:10:47.430156: W  559158 tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
xw32 num_non_zero= 16
tensor([[  8,  -1],
        [  0,   1],
        [  5,   0],
        [ -1,   2],
        [  7,   0],
        [  1,  -7],
        [  1,   3],
        [  5, -10],
        [  3,  -8],
        [  0,   2]], device='xla:0', dtype=torch.int32)
xw32 y_test.size()= torch.Size([16])
tensor([[0., 0.],
        [0., 1.],
        [1., 1.],
        [2., 0.],
        [3., 0.],
        [3., 1.],
        [4., 0.],
        [5., 0.],
        [5., 1.],
        [6., 0.],
        [6., 1.],
        [7., 0.],
        [7., 1.],
        [8., 0.],
        [8., 1.],
        [9., 1.]], device='xla:0')
tensor([1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1.],
       device='xla:0')
2022-10-21 00:10:47.779834: E  559600 tensorflow/compiler/xla/service/dynamic_padder.cc:1864] Inserting PadToStatic for instruction: %p4.7 = f32[<=20,2]{1,0} parameter(4), metadata={op_type="xla__device_data" op_name="xla__device_data" source_file="@No Python Frames" source_line=-1}
2022-10-21 00:10:47.830590: F  559158 /workspace/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/xla_client/debug_macros.h:27] Non-OK-status: status.status() status: INVALID_ARGUMENT: Binary op multiply with incompatible shapes: f32[16] and f32[<=20].
*** Begin stack trace ***
	tsl::CurrentStackTrace[abi:cxx11]()
	xla::Shape const* ConsumeValue<xla::Shape const*>(tsl::StatusOr<xla::Shape const*>&&)
	torch_xla::XlaHelpers::ShapeOfXlaOp(xla::XlaOp)

	torch_xla::BuildBinaryCrossEntropy(xla::XlaOp, xla::XlaOp, std::optional<xla::XlaOp> const&, torch_xla::ReductionMode)

	torch_xla::InferOutputShape(absl::lts_20220623::Span<xla::Shape const>, std::function<xla::XlaOp (absl::lts_20220623::Span<xla::XlaOp const>)> const&)
	torch_xla::BinaryCrossEntropyOutputShape(torch::lazy::Value const&, torch::lazy::Value const&, c10::optional<torch::lazy::Value> const&, long)
	std::_Function_handler<xla::Shape (), torch_xla::BinaryCrossEntropy::BinaryCrossEntropy(torch::lazy::Value const&, torch::lazy::Value const&, c10::optional<torch::lazy::Value> const&, long const&, std::vector<torch::lazy::Shape, std::allocator<torch::lazy::Shape> >&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
	torch_xla::XlaNode::GetOpShape(std::function<xla::Shape ()> const&) const
	torch_xla::XlaNode::XlaNode(torch::lazy::OpKind, c10::ArrayRef<torch::lazy::Value>, std::vector<torch::lazy::Shape, std::allocator<torch::lazy::Shape> >&&, std::function<xla::Shape ()> const&, unsigned long, torch::lazy::hash_t)
	torch_xla::BinaryCrossEntropy::BinaryCrossEntropy(torch::lazy::Value const&, torch::lazy::Value const&, c10::optional<torch::lazy::Value> const&, long const&, std::vector<torch::lazy::Shape, std::allocator<torch::lazy::Shape> >&&)
	torch_xla::XLANativeFunctions::binary_cross_entropy(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long)




	at::_ops::binary_cross_entropy::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long)





	at::_ops::binary_cross_entropy::call(at::Tensor const&, at::Tensor const&, c10::optional<at::Tensor> const&, long)

	_PyMethodDef_RawFastCallKeywords

	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_FastCallKeywords

	_PyEval_EvalFrameDefault
	_PyObject_FastCallDict

	PyObject_Call
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyObject_FastCallDict

	_PyObject_FastCallKeywords
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	PyEval_EvalCode

	PyRun_FileExFlags
	PyRun_SimpleFileExFlags

	_Py_UnixMain
	__libc_start_main

*** End stack trace ***

Aborted (core dumped)
(base) jenkins@c76438fd460f:/workspace$ python3 pytorch/xla/test/dynamic_shape_model_test.py
2022-10-21 00:19:37.516127: W  564590 tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-10-21 00:19:37.516177: W  564590 tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
xw32 num_non_zero= 20
tensor([[  6,  -6],
        [  8,  -5],
        [ -2, -10],
        [  6,  -4],
        [  3,  -1],
        [ -3,  -6],
        [ 10,  -5],
        [  6,  -2],
        [  5,  -3],
        [ -2,  -6]], device='xla:0', dtype=torch.int32)
xw32 y_test.size()= torch.Size([20])
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [2., 1.],
        [3., 0.],
        [3., 1.],
        [4., 0.],
        [4., 1.],
        [5., 0.],
        [5., 1.],
        [6., 0.],
        [6., 1.],
        [7., 0.],
        [7., 1.],
        [8., 0.],
        [8., 1.],
        [9., 0.],
        [9., 1.]], device='xla:0')
tensor([0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
        1., 1.], device='xla:0')
2022-10-21 00:19:37.857297: E  565032 tensorflow/compiler/xla/service/dynamic_padder.cc:1864] Inserting PadToStatic for instruction: %p4.7 = f32[<=20,2]{1,0} parameter(4), metadata={op_type="xla__device_data" op_name="xla__device_data" source_file="@No Python Frames" source_line=-1}
2022-10-21 00:19:37.906632: E  565033 tensorflow/compiler/xla/service/dynamic_padder.cc:1864] Inserting PadToStatic for instruction: %p4.6 = f32[<=20,2]{1,0} parameter(4), metadata={op_type="xla__device_data" op_name="xla__device_data" source_file="@No Python Frames" source_line=-1}
Test loss before training 0.9669302105903625
```
The failure seems to be identical to https://github.com/pytorch/xla/issues/4097

**Comment by JackCaoG** [comment]
error is 
```
2022-10-21 00:10:47.830590: F  559158 /workspace/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/xla_client/debug_macros.h:27] Non-OK-status: status.status() status: INVALID_ARGUMENT: Binary op multiply with incompatible shapes: f32[16] and f32[<=20].
```

Seems like you are trying to multiply 
```
f32[16] and f32[<=20]
```

can you just add a small repo(<= 10 lines) and post it in this bug? Looking at the pr with random number generator is hard to debug.

**Comment by miladm** [comment]
I agree. @vanbasten23 can you replace the random number generation with a fixed input tensor? this will help stabalize our tests for now. we can turn on the random generator later when the base case works. wdyt?

**Comment by vanbasten23** [comment]
SG. I got rid of the random number in the test data and created a shorter version of test: https://github.com/pytorch/xla/pull/4114/files#diff-36fd0aa0804af43985345c71a17c6f03aca915d5497564ad132bf6905bf5a7d3.

Can you take a look and see if it's what you want?

**Comment by vanbasten23** [comment]
It's done with the [pr](https://github.com/pytorch/xla/pull/4114/files#diff-36fd0aa0804af43985345c71a17c6f03aca915d5497564ad132bf6905bf5a7d3.)
