### ISSUE TITLE
RuntimeError: XLA tensors do not have storage

### ISSUE THREAD

**Issue by heyoma** [pytorch/xla#4131]
## 🐛 Bug
RuntimeError: torch_xla/csrc/tensor_impl.cpp:159 : XLA tensors do not have storage

## To Reproduce

I'm trying to run [UIE](https://github.com/universal-ie/UIE) pretraining with TPU virtual machine. But it gave out such an error.
I didn't use provided dockers but I have tried pytorch 1.8.1 with corresponding torch_xla, the same error given out.
I saw a similar [issue](https://github.com/pytorch/xla/issues/2576), but I'm not sure if it is the same with this one and I got quite confused about how it is resolved.

1. git clone my [repo](https://github.com/heyoma/UIE) and prepare the environment by
```
sudo pip3 install torch==1.10.0
sudo pip3 install torchvision==0.11.1
sudo pip3 install torchaudio==0.10.0
sudo pip3 install https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-1.10-cp38-cp38-linux_x86_64.whl
pip3 install -r requirements.txt
```
2. execute "bash run_uie_pretrain_mine.bash"

## Expected behavior

Pretraining start with correct log that shows the progress bar.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU v3-8, pytorch 1.10.0
 - torch_xla version: 1.10

## Additional context
A more complete log is like this:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/site-packages/torch_xla/distributed/parallel_loader.py", line 135, in _loader_worker
    data_iter = enumerate(self._loader)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 138, in reduce_tensor
    storage = tensor.storage()
RuntimeError: torch_xla/csrc/tensor_impl.cpp:159 : XLA tensors do not have storage
```

**Comment by JackCaoG** [comment]
are you trying to use ddp on pytorch/xla? I saw
```
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 138, in reduce_tensor
    storage = tensor.storage()
```

**Comment by heyoma** [comment]
> are you trying to use ddp on pytorch/xla? I saw
> 
> ```
>   File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
>   File "/home/lhyricoh_gmail_com/miniconda3/envs/torch/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 138, in reduce_tensor
>     storage = tensor.storage()
> ```

I'm not sure. I was using huggface/Transformers package and try to make my code work well with TPU by [xla_spawn.py](https://github.com/huggingface/transformers/blob/main/examples/legacy/seq2seq/xla_spawn.py) .
The [description](https://github.com/huggingface/transformers/tree/main/examples/legacy/seq2seq#tpu-training) of script xla_spawn.py is like this:
```
We provide a very simple launcher script named xla_spawn.py that lets you run our example scripts on multiple TPU cores without any boilerplate.
Just pass a --num_cores flag to this script, then your regular training script with its arguments (this is similar to the torch.distributed.launch helper for torch.distributed).
```
Maybe there's somewhere conflict with TPU, but the Exception didn't point to any line of my code, so I don't know what's going wrong.

**Comment by Liyang90** [comment]
The latest torch_xla implements the `tensor.storage()` now: https://github.com/pytorch/xla/blob/e0dd3e08fe393fc64f769a1fc30861e7e793b019/torch_xla/csrc/tensor_impl.cpp#L208

The error seems to happen in the multi-worker dataloader. Could you try setting `dataloader_num_workers=0` to see if it runs correctly?

I will try to repro the error later.

**Comment by heyoma** [comment]
> The latest torch_xla implements the `tensor.storage()` now:
> 
> https://github.com/pytorch/xla/blob/e0dd3e08fe393fc64f769a1fc30861e7e793b019/torch_xla/csrc/tensor_impl.cpp#L208
> 
> The error seems to happen in the multi-worker dataloader. Could you try setting `dataloader_num_workers=0` to see if it runs correctly?
> 
> I will try to repro the error later.

Thank you!
I will try it soon.

**Comment by Liyang90** [comment]
I confirm I can reproduce the error on my side. The stack indicates the access to an XLA tensor's `tensor.storage()` method, which was not implemented in earlier versions of torch_xla, happened during the initialization of the multi-worker dataloader iterator.

Usually the data tensors from dataloader are only moved to XLA device *after* they are yielded from the dataloader iterator, so there should be no XLA tensor when multi-worker dataloader iterator is initialized. But in this case, the dataloader instance had a reference to the `model` in its `collate_fn`, and `model` contains parameters that have been moved to XLA device, leading to the error we see here.

Setting `dataloader_num_workers=0` should get around this issue.

**Comment by heyoma** [comment]
> I confirm I can reproduce the error on my side. The stack indicates the access to an XLA tensor's `tensor.storage()` method, which was not implemented in earlier versions of torch_xla, happened during the initialization of the multi-worker dataloader iterator.
> 
> Usually the data tensors from dataloader are only moved to XLA device _after_ they are yielded from the dataloader iterator, so there should be no XLA tensor when multi-worker dataloader iterator is initialized. But in this case, the dataloader instance had a reference to the `model` in its `collate_fn`, and `model` contains parameters that have been moved to XLA device, leading to the error we see here.
> 
> Setting `dataloader_num_workers=0` gets around this issue, and training would proceed correctly.

Thank you very much! That worked for me. I will close this issue.
