### ISSUE TITLE
How to wrap a model with dynamo

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/xla#4157]
## ❓ Questions and Help

I am trying to add a dynamo model test with
```
import torch
import torch_xla
import torch_xla.core.xla_model as xm
import torch_xla.utils.utils as xu
import torch_xla.debug.metrics as met
import torch._dynamo as dynamo
import torchvision
import unittest

class DynamoBasicTest(unittest.TestCase):

  @dynamo.optimize('torchxla_trace_once')
  def resetnet_18_dynamo(self, data):
    model = torchvision.models.resnet18()
    #model.eval()
    return model(data)

  def test_resnet18(self):
    batch_size = xu.getenv_as('BATCH_SIZE', int, defval=4)
    sample_count = xu.getenv_as('SAMPLE_COUNT', int, defval=10)
    loader = xu.SampleGenerator(
        data=(torch.zeros(batch_size, 3, 224,
                          224), torch.zeros(batch_size, dtype=torch.int64)),
        sample_count=sample_count)    
    for data, _ in loader:
      import pdb; pdb.set_trace()
      output = self.resetnet_18_dynamo(data)
```

I get an error
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_dynamo/optimizations/backends.py", line 53, in inner
    return fn(model, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_dynamo/optimizations/backends.py", line 823, in torchxla_trace_once
    return integration.extract_compiled_graph(model, example_inputs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_dynamo/optimizations/torchxla_integration.py", line 79, in extract_compiled_graph
    orig_device = example_inputs[0].device
IndexError: list index out of range
```

and I saw that `example_inputs` is empty. If I try with a simple example
```
  def fn_simple(self, x, y):
    a = torch.cos(x)
    b = torch.sin(y)
    return a + b

  @dynamo.optimize('torchxla_trace_once')
  def fn_simple_dynamo(self, x, y):
    return self.fn_simple(x, y)
```

it worked as expected. I am wondering what did I missed here.

@shunting314 @wconstab

**Comment by wconstab** [comment]
can you confirm what type(data) and len(data) is at the place you put pdb in the above snippet?

you could also try running with 'eager' backend instead of 'torchxla_trace_once' backend.  (you can also make your own compiler to debug what is getting passed to the compiler:
```
def my_compiler(graphmodule, example_inputs):
   return graphmodule
```

```
@dynamo.optimize(my_compiler)  <-- pass the actual fn instead of str name
```

**Comment by JackCaoG** [comment]
```
(Pdb) type(data)
<class 'torch.Tensor'>
(Pdb) data.size()
torch.Size([4, 3, 224, 224])
```

if I used the mycompiler trick I am able to see the computation go through without issue
```
(Pdb) output
tensor([[ 0.0264,  0.0299, -0.0337,  ...,  0.0101, -0.0403,  0.0125],
        [ 0.0264,  0.0299, -0.0337,  ...,  0.0101, -0.0403,  0.0125],
        [ 0.0264,  0.0299, -0.0337,  ...,  0.0101, -0.0403,  0.0125],
        [ 0.0264,  0.0299, -0.0337,  ...,  0.0101, -0.0403,  0.0125]],
       grad_fn=<AddmmBackward0>)
```

**Comment by shunting314** [comment]
@JackCaoG  Maybe it triggers some corner case in dynamo since I see both the graph and example inputs passed to the compiler are empty.

But there is a easy way to work around. Instead of creating the model within dynamo context, do that outside and pass in the model instance. The following version with the aforementioned change works:
```
  @dynamo.optimize('torchxla_trace_once')
  def resetnet_18_dynamo(self, model, data):
    #model.eval()
    return model(data)

  def test_resnet18(self):
    batch_size = xu.getenv_as('BATCH_SIZE', int, defval=4)
    sample_count = xu.getenv_as('SAMPLE_COUNT', int, defval=10)
    loader = xu.SampleGenerator(
        data=(torch.zeros(batch_size, 3, 224,
                          224), torch.zeros(batch_size, dtype=torch.int64)),
        sample_count=sample_count)
    model = torchvision.models.resnet18()
    for data, _ in loader:
      # import pdb; pdb.set_trace()
      output = self.resetnet_18_dynamo(model, data)
```

**Comment by JackCaoG** [comment]
Thanks WIll and Shunting, I am able to get it to work. open the https://github.com/pytorch/xla/pull/4159 for basic testing.
