### ISSUE TITLE
Fix dynamic shape test (xla/test/test_dynamic_shapes.py) and add it to pytorch/xla's CI.

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4171]
## 🐛 Bug

xla/test/test_dynamic_shapes.py is currently failing and not included in the CI.

## To Reproduce

```
$ export XLA_EXPERIMENTAL=nonzero:masked_select:masked_scatter
$ python3 test/test_dynamic_shapes.py
======================================================================
ERROR: test_wrap (__main__.TestDynamicShapes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dynamic_shapes.py", line 14, in test_wrap
    self.assertTrue(a2.shape[0] == 3)
RuntimeError: py_node INTERNAL ASSERT FAILED at "/workspace/pytorch/torch/csrc/utils/pybind.cpp":31, please report a bug to PyTorch
```
## Expected behavior

The test should pass and be included in the CI.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CPU
 - torch_xla version: latest

**Comment by vanbasten23** [comment]
Have some thought: the failure might be related to https://github.com/pytorch/xla/pull/4132. Need to investigate more.

**Comment by JackCaoG** [comment]
FYI @Krovatkin

**Comment by vanbasten23** [comment]
Nick kindly pointed out that 
```
Looks like we are triggering the following assert : https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/pybind.cpp#L30
since XlaSymNodeImpl doesn't extend PythonSymNodeImpl. https://github.com/pytorch/xla/blob/54f24e25edee95feabd7bf7e05dba6c616551ff7/torch_xla/csrc/tensor.h#L30 
```

So I made `XlaSymNodeImpl ` extend `PythonSymNodeImpl` in https://github.com/pytorch/xla/pull/4180. To make the PR compile, I'd need to add a default constructor to `PythonSymNodeImpl` (https://github.com/pytorch/pytorch/pull/88772).

Right now, running xla/test/test_dynamic_shapes.py fails with segfault:
```
(gdb) bt
#0  0x00007f7ba91c1d71 in c10::SafePyObject::ptr(c10::impl::PyInterpreter const*) const () from /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so
#1  0x00007f7bb6357cc4 in pybind11::detail::type_caster<c10::SymInt, void>::cast(c10::SymInt, pybind11::return_value_policy, pybind11::handle) ()
   from /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#2  0x00007f7bb58f5cc1 in pybind11::object pybind11::cast<c10::SymInt&, 0>(c10::SymInt&, pybind11::return_value_policy, pybind11::handle) ()
   from /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#3  0x00007f7bb5e8cdfa in THPSize_NewFromSymSizes(at::Tensor const&) () from /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#4  0x00007f7bb5f1ef01 in THPVariable_get_shape(THPVariable*, void*) () from /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so
#5  0x000055d3507719ec in getset_get () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/descrobject.c:156
#6  0x000055d350751844 in _PyObject_GenericGetAttrWithDict () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/object.c:1238
#7  0x000055d3507de71a in _PyEval_EvalFrameDefault () at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:2573
#8  0x000055d3507538d7 in PyEval_EvalFrameEx (throwflag=0, f=0x7f7c5cd6c620) at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:547
#9  function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>)
    at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:283
#10 _PyFunction_FastCallKeywords () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:408
#11 0x000055d3507de395 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:4616
#12 _PyEval_EvalFrameDefault () at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:3124
#13 0x000055d350733e85 in PyEval_EvalFrameEx (throwflag=0, f=0x55d356291820) at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:547
#14 _PyEval_EvalCodeWithName () at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:3930
#15 0x000055d350735592 in _PyFunction_FastCallDict (kwargs=<optimized out>, nargs=2, args=0x7ffc00753420, func=<optimized out>)
    at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:376
#16 _PyObject_FastCallDict () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:98
#17 0x000055d35074a141 in _PyObject_Call_Prepend (kwargs=0x7f7c5cd65dc0, args=0x7f7c5cd67310, obj=<optimized out>, callable=0x7f7c621ea560)
    at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:906
#18 method_call () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/classobject.c:309
#19 0x000055d350735b94 in PyObject_Call () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:245
#20 0x000055d3507dfc58 in do_call_core (kwdict=0x7f7c5cd65dc0, callargs=0x7f7c5cd67310, func=0x7f7c6016a5f0)
    at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:4645
#21 _PyEval_EvalFrameDefault () at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:3191
#22 0x000055d350733e85 in PyEval_EvalFrameEx (throwflag=0, f=0x7f7c5cd6a590) at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:547
#23 _PyEval_EvalCodeWithName () at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:3930
#24 0x000055d350735592 in _PyFunction_FastCallDict (kwargs=<optimized out>, nargs=2, args=0x7ffc007537b0, func=<optimized out>)
    at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:376
#25 _PyObject_FastCallDict () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:98
#26 0x000055d3507a14bc in _PyObject_Call_Prepend (kwargs=0x0, args=0x7f7c5cd67610, obj=<optimized out>, callable=0x7f7c621ea680)
    at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:906
#27 slot_tp_call () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/typeobject.c:6402
#28 0x000055d35079a16c in _PyObject_FastCallKeywords () at /home/builder/tkoch/workspace/python_1648536129212/work/Objects/call.c:199
#29 0x000055d3507e26b5 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:4619
#30 _PyEval_EvalFrameDefault () at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:3124
#31 0x000055d350733e85 in PyEval_EvalFrameEx (throwflag=0, f=0x7f7c5cd6c430) at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:547
#32 _PyEval_EvalCodeWithName () at /home/builder/tkoch/workspace/python_1648536129212/work/Python/ceval.c:3930
#33 0x000055d350735592 in _PyFunction_FastCallDict (kwargs=<optimized out>, nargs=2, args=0x7ffc00753b50, func=<optimized out>)
```

I think it failed probably because https://github.com/pytorch/pytorch/blob/c4a3aa8fe7306aa490959df35a5933187b170d56/torch/csrc/utils/python_symnode.h#L178 is null.
