### ISSUE TITLE
Master CI is failing

### ISSUE THREAD

**Issue by steventk-g** [pytorch/xla#4274]
CI failing with the following issue
```
======================================================================
ERROR: test_simple_model (__main__.DynamoBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pytorch/xla/test/dynamo/test_dynamo.py", line 41, in test_simple_model
    res_xla_dynamo_2 = self.fn_simple_dynamo(xla_x, xla_y)
  File "/opt/conda/lib/python3.7/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/tmp/pytorch/xla/test/dynamo/test_dynamo.py", line 21, in fn_simple_dynamo
    @dynamo.optimize('torchxla_trace_once')
  File "/opt/conda/lib/python3.7/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/_dynamo/optimizations/backends.py", line 755, in fwd
    model = subgraph.model
NameError: free variable 'subgraph' referenced before assignment in enclosing scope

----------------------------------------------------------------------
```
https://app.circleci.com/pipelines/github/pytorch/xla/14726/workflows/68042915-3e90-409b-8a44-5e4f5abee2c3/jobs/34053

**Comment by steventk-g** [comment]
According to Jack, this might be fixed by https://github.com/pytorch/pytorch/pull/90197

**Comment by JackCaoG** [comment]
I tried to compile with head and still see
```
======================================================================
ERROR: test_resnet18 (__main__.DynamoBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/dynamo/test_dynamo.py", line 62, in test_resnet18
    output = self.run_model_with_dynamo(xla_resnet18, data)
  File "/pytorch/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "test/dynamo/test_dynamo.py", line 25, in run_model_with_dynamo
    @dynamo.optimize('torchxla_trace_once')
  File "/pytorch/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/pytorch/torch/_dynamo/optimizations/backends.py", line 755, in fwd
    model = subgraph.model
NameError: free variable 'subgraph' referenced before assignment in enclosing scope

======================================================================
ERROR: test_simple_model (__main__.DynamoBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/dynamo/test_dynamo.py", line 41, in test_simple_model
    res_xla_dynamo_2 = self.fn_simple_dynamo(xla_x, xla_y)
  File "/pytorch/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "test/dynamo/test_dynamo.py", line 21, in fn_simple_dynamo
    @dynamo.optimize('torchxla_trace_once')
  File "/pytorch/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/pytorch/torch/_dynamo/optimizations/backends.py", line 755, in fwd
    model = subgraph.model
NameError: free variable 'subgraph' referenced before assignment in enclosing scope
```

**Comment by voznesenskym** [comment]
@JackCaoG commented elsewhere, but try removing the del, its an optimization anyway.
