### ISSUE TITLE
[Functionalizaton] test_index_reduce

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#4351]
Runngint `python test/test_torch.py TestTorchDeviceTypeXLA.test_index_reduce_reduce_prod_xla_int64` fails with
```
======================================================================
ERROR: test_index_reduce_reduce_prod_xla_int64 (__main__.TestTorchDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    result = test(self, **param_kwargs)
  File "/workspace/pytorch/xla/test/../../test/test_torch.py", line 2981, in test_index_reduce
    dest.index_reduce_(dim, idx, src, reduce, include_self=include_self)
IndexError: select(): index 0 out of range for tensor of size [3, 4, 0] at dimension 2
```

**Comment by miladm** [comment]
is this issue still relevant? if not, let's close.
