### ISSUE TITLE
[Functionalization] test_logcumsumexp_xla

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#4352]
Running `python test/test_torch.py TestTorchDeviceTypeXLA.test_logcumsumexp_xla` fails with
```
======================================================================
FAIL: test_logcumsumexp_xla (__main__.TestTorchDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 378, in instantiated_test
    result = test(self, **param_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1063, in wrapper
    fn(*args, **kwargs)
  File "/workspace/pytorch/xla/test/../../test/test_torch.py", line 2470, in test_logcumsumexp
    torch.logcumsumexp(b, axis, out=inplace_out)
AssertionError: RuntimeError not raised
```

**Comment by ysiraichi** [comment]
Discussion in this PyTorch issue: https://github.com/pytorch/pytorch/issues/92912

**Comment by ysiraichi** [comment]
Update: after discussing it with Brian ([details](https://github.com/pytorch/pytorch/issues/92912)), he pointed out that the benefits might not be worth the added infra to build/maintain.
