### ISSUE TITLE
`expand` returns incorrect result when dynamic shape is enabled

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4564]
## 🐛 Bug

`expand` returns incorrect result when dynamic shape is enabled.

I discovered the issue in the functionalization project when I tried to deprecate our c++ test `AtenXlaTensorTest.TestExpandSymIntDynamic` and `AtenXlaTensorTest.TestExpandSymIntSymbolic`. Since dynamic shape needs to enable python dispatcher by default, I create a equivalent python test (below) to replace the current c++ test.

## To Reproduce

I have a simple test:

```
  def test_expand_symint_correctness(self):
    size1 = 5
    size2 = 2
    t1 = torch.ones([size1, size2])
    expand_out_aten = t1.expand(2, size1, size2)

    t2 = torch.zeros([size1, size2], device=dev)
    t2[3][0] = 1
    t2[3][1] = 1
    # t2 has size [<=10, 2]
    t3 = torch.nonzero(t2)
    t4 = torch.ones([size1, size2], device=dev)
    expand_out_xla = t4.expand(t3.shape[0], size1, size2)
    self.assertEqual(t3.shape[0], 2)
    print(expand_out_xla)
    self.assertEqual(expand_out_aten.cpu(), expand_out_xla.cpu())
```

Running the script `XLA_EXPERIMENTAL="nonzero:masked_select" python3 pytorch/xla/test/test_dynamic_shapes.py TestDynamicShapes.test_expand_symint_correctness` would result in:
```
tensor([[[2.8026e-45, 1.0000e+00],
         [       nan, 1.0000e+00],
         [1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00]],

        [[7.0065e-45, 1.0000e+00],
         [       nan, 1.0000e+00],
         [1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00]]], device='xla:1')
```

But the correct result I expect is something like:
```
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
```

Same behavior has been observed in both master branch and functionalization branch.

If I disable dynamic shape feature, above script would return the correct output:
```
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
```

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU (v3 TPU VM)
 - torch_xla version: nightly

## Additional context

Because of this issue, I cannot remove the 2 `AtenXlaTensorTest.TestExpandSymIntSymbolic` and `AtenXlaTensorTest.TestExpandSymIntDynamic` cpp test for now in the functionalization branch. I'll investigate.

cc @miladm @alanwaketan @JackCaoG

**Comment by vanbasten23** [comment]
This issue seems to have been fixed by the recent tf pin update: https://github.com/pytorch/xla/pull/4554. Running the above script outputs:
```
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]], device='xla:1')
```

**Comment by vanbasten23** [comment]
Some interesting observations: without Jack's tf pin update, the above python script fails with error:
```
tensor([[[2.8026e-45, 1.0000e+00],
         [       nan, 1.0000e+00],
         [1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00]],

        [[7.0065e-45, 1.0000e+00],
         [       nan, 1.0000e+00],
         [1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00],
         [1.0000e+00, 1.0000e+00]]], device='xla:1')
======================================================================
FAIL: test_expand_symint_correctness (__main__.TestDynamicShape)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pytorch/xla/test/test_operations.py", line 755, in test_expand_symint_correctness
    self.assertEqual(expand_out_aten.cpu(), expand_out_xla.cpu())
  File "pytorch/xla/test/test_operations.py", line 358, in assertEqual
    assertTensorsEqual(x, y)
  File "pytorch/xla/test/test_operations.py", line 288, in assertTensorsEqual
    self.assertTrue(torch.equal(nan_mask, torch.isnan(b)), message)
AssertionError: False is not true : 
```
but the seemingly equivalent cpp test `AtenXlaTensorTest.TestExpandSymIntDynamic` and `AtenXlaTensorTest.TestExpandSymIntSymbolic` pass: 
```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AtenXlaTensorTest
[ RUN      ] AtenXlaTensorTest.TestExpandSymIntDynamic
```
