### ISSUE TITLE
Making backward NN model works with dynamic shaped input

### ISSUE THREAD

**Issue by vanbasten23** [pytorch/xla#4592]
## 🐛 Bug

Still trying to make the backward NN model [test](https://github.com/pytorch/xla/blob/76b34fb9957cd5e0f60c1a3a1461ba644231f013/test/test_dynamic_shape_models.py#L98-L125) works with dynamic shaped input. I ran the test on `functionalization` branch and it failed with 
```
root@t1v-n-5f93dd4b-w-0:/workspaces/work# TORCH_SHOW_CPP_STACKTRACES=1 XLA_EXPERIMENTAL="nonzero:masked_select" python3 pytorch/xla/test/test_dynamic_shape_models.py TestDynamicShapeModels.test_backward_pass_with_dynamic_input
test_backward_pass_with_dynamic_input (__main__.TestDynamicShapeModels) ... ERROR

======================================================================
ERROR: test_backward_pass_with_dynamic_input (__main__.TestDynamicShapeModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pytorch/xla/test/test_dynamic_shape_models.py", line 104, in test_backward_pass_with_dynamic_input
    loss.backward()
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides
Exception raised from sizes_default at /workspaces/work/pytorch/c10/core/TensorImpl.h:626 (most recent call first):
frame #0: <unknown function> + 0x9cdff (0x7fd2f1c01dff in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x4d (0x7fd24e3a490d in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x57 (0x7fd2f1c00e47 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #3: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0x9f (0x7fd2f1bfeb7f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x603a5 (0x7fd2f1bc53a5 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #5: c10::TensorImpl::sizes_custom() const + 0x6e (0x7fd2f1bbf6fe in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0x18cdba8 (0x7fd24846aba8 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x18c889d (0x7fd24846589d in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x2387b3e (0x7fd248f24b3e in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: at::native::unsqueeze(at::Tensor const&, long) + 0x72 (0x7fd248f24a42 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x3fb0914 (0x7fd24ab4d914 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x40b91f3 (0x7fd24ac561f3 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2c0dbc9 (0x7fd2497aabc9 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: at::_ops::unsqueeze::call(at::Tensor const&, long) + 0x5f1 (0x7fd24a538951 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x48f5aab (0x7fd24b492aab in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x499abb0 (0x7fd24b537bb0 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x2c0dbc9 (0x7fd2497aabc9 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x2c0e0a4 (0x7fd2497ab0a4 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: at::_ops::unsqueeze::redispatch(c10::DispatchKeySet, at::Tensor const&, long) + 0x18e (0x7fd24a538cce in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #19: <unknown function> + 0x739c713 (0x7fd24df39713 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #20: <unknown function> + 0x739c3f0 (0x7fd24df393f0 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #21: <unknown function> + 0x739cdd0 (0x7fd24df39dd0 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #22: <unknown function> + 0x2c0dbc9 (0x7fd2497aabc9 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #23: <unknown function> + 0x2c0e0a4 (0x7fd2497ab0a4 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #24: at::_ops::unsqueeze::redispatch(c10::DispatchKeySet, at::Tensor const&, long) + 0x18e (0x7fd24a538cce in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #25: <unknown function> + 0x68e6f54 (0x7fd24d483f54 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #26: <unknown function> + 0x687f6c3 (0x7fd24d41c6c3 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #27: <unknown function> + 0x687ec76 (0x7fd24d41bc76 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #28: <unknown function> + 0x687f970 (0x7fd24d41c970 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #29: <unknown function> + 0x2c0dbc9 (0x7fd2497aabc9 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #30: at::_ops::unsqueeze::call(at::Tensor const&, long) + 0x5f1 (0x7fd24a538951 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #31: <unknown function> + 0x19311c4 (0x7fd2484ce1c4 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #32: <unknown function> + 0x85b09bd (0x7fd24f14d9bd in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #33: torch::autograd::generated::SqueezeBackward0::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x178 (0x7fd24c90ea88 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #34: <unknown function> + 0x7697558 (0x7fd24e234558 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #35: <unknown function> + 0x768bd5f (0x7fd24e228d5f in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #36: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x52f (0x7fd24e2251ff in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #37: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x5a6 (0x7fd24e2247f6 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #38: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x9e (0x7fd24e22355e in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #39: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x63 (0x7fd2f88d9283 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #40: <unknown function> + 0x76ac259 (0x7fd24e249259 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #41: <unknown function> + 0x76ac091 (0x7fd24e249091 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #42: <unknown function> + 0x76ac00d (0x7fd24e24900d in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #43: <unknown function> + 0x76abf75 (0x7fd24e248f75 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #44: <unknown function> + 0x76ab9b9 (0x7fd24e2489b9 in /home/ptxla/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #45: <unknown function> + 0xbbb2f (0x7fd2f1a9cb2f in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #46: <unknown function> + 0x7fa3 (0x7fd2fcf47fa3 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #47: clone + 0x3f (0x7fd2fccea06f in /lib/x86_64-linux-gnu/libc.so.6)


----------------------------------------------------------------------
Ran 1 test in 0.460s

FAILED (errors=1)
```

Note, the above failure happened without python dispatcher.

## To Reproduce

see above

## Expected behavior

It shouldn't crash.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU within a docker container on TPU VM
 - torch_xla version: nightly on functionalization branch.

**Comment by vanbasten23** [comment]
If I enable python dispatcher, the script would fail with a different error:
```
root@t1v-n-5f93dd4b-w-0:/workspaces/work#  python3 pytorch/xla/test/test_dynamic_shape_models.py TestDynamicShapeModels.test_backward_pass_with_dynamic_input
test_backward_pass_with_dynamic_input (__main__.TestDynamicShapeModels) ... ERROR

======================================================================
ERROR: test_backward_pass_with_dynamic_input (__main__.TestDynamicShapeModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pytorch/xla/test/test_dynamic_shape_models.py", line 108, in test_backward_pass_with_dynamic_input
    loss.backward()
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/ptxla/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: /workspaces/work/pytorch/xla/torch_xla/csrc/helpers.cpp:273 : Check failed: out_size <= size_at_dyndim / input_shape.dimensions( input_dynamic_dimension) (2 vs. 1)
*** Begin stack trace ***
        tsl::CurrentStackTrace[abi:cxx11]()
        torch_xla::XlaHelpers::GetDynamicReshapeInfo(xla::Shape const&, absl::lts_20220623::Span<long const>)
        torch_xla::XlaHelpers::GetDynamicReshape(xla::Shape const&, absl::lts_20220623::Span<long const>)
        torch_xla::Permute::MakePermuteShape(xla::Shape const&, absl::lts_20220623::Span<long const>)
        torch_xla::ViewInfo::ViewInfo(torch_xla::ViewInfo::Type, xla::Shape, std::vector<long, std::allocator<long> >)
        torch_xla::tensor_methods::transpose(c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > const&, long, long)
        torch_xla::XLANativeFunctions::t_copy(at::Tensor const&)

        at::_ops::t_copy::call(at::Tensor const&)

        at::_ops::t::redispatch(c10::DispatchKeySet, at::Tensor const&)

        at::_ops::t::redispatch(c10::DispatchKeySet, at::Tensor const&)

        at::_ops::t::call(at::Tensor const&)

        torch::autograd::generated::AddmmBackward0::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&)

        torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&)
        torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&)
        torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool)
        torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool)

        clone
*** End stack trace ***
Unable to map dynamic dimension of shape f32[<=10,2]{1,0} to output sizes (2, 10)

----------------------------------------------------------------------
Ran 1 test in 0.951s

FAILED (errors=1)
```

So I'd like to confirm that we should enable python dispatcher and functionalization in order to run DS feature. wdyt? @JackCaoG @miladm
