### ISSUE TITLE
RuntimeError: dimensionality of sizes (2) must match dimensionality of strides (1)

### ISSUE THREAD

**Issue by cicirori** [pytorch/xla#4647]
## 🐛 Bug

Running the slightly modified test_train_mp_mnist_amp.py will report an error:

- RuntimeError: dimensionality of sizes (2) must match dimensionality of strides (1)

## To Reproduce

![image](https://user-images.githubusercontent.com/32845984/219533218-3e7091df-b3b8-4432-bef0-6ec32aa6b9b8.png)

wrap test_loop in no_grad context manager will cause this error:

```
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/opt/conda/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 58, in wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 213, in _run_thread_per_device
    replica_results = list(
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 206, in _thread_fn
    return fn()
  File "/opt/conda/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 315, in __call__
    self.fn(global_ordinal(), *self.args, **self.kwargs)
  File "/local_workspace/pt2_playground/pytorch/xla/test/test_train_mp_mnist_amp.py", line 204, in _mp_fn
    accuracy = train_mnist(flags)
  File "/local_workspace/pt2_playground/pytorch/xla/test/test_train_mp_mnist_amp.py", line 185, in train_mnist
    accuracy = test_loop_fn(test_device_loader)
  File "/local_workspace/pt2_playground/pytorch/xla/test/test_train_mp_mnist_amp.py", line 167, in test_loop_fn
    output = model(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/local_workspace/pt2_playground/pytorch/xla/test/test_train_mp_mnist_amp.py", line 67, in forward
    return F.log_softmax(x, dim=1)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1932, in log_softmax
    ret = input.log_softmax(dim)
RuntimeError: dimensionality of sizes (2) must match dimensionality of strides (1)
"""
```

1. GPU_NUM_DEVICES=1 CUDA_VISIBLE_DEVICES=0 PJRT_DEVICE=GPU python test_train_mp_mnist_amp.py --device xla

## Expected behavior

program will exit successfully on 1.12, but failed on 2.0

## Environment

 - Reproducible on XLA backend : PJRT_GPU
 - torch_xla version: bd6d2d3fe31e5b0d2e6e625ded3ea107d122d3e2

## Additional context

`print(x.shape)` before `return F.log_softmax(x, dim=1)` will fix this error. it it's maybe related to symbolic shape?

**Comment by JackCaoG** [comment]
seems to be a tracing time check failure. What's x's shape?

**Comment by cicirori** [comment]
torch.Size([128, 10]) and torch.Size([16, 10]) when testing.
stride seems different after insert `print(x.shape)`, from `(1,)` to `(10, 1)`

**Comment by JackCaoG** [comment]
hmm @ymwangg have you guys see the same issue? If it is a regression we want to fix it in 2.0. I am a bit worried that change has to happen in the upstream.

**Comment by ymwangg** [comment]
I tested using `gcr.io/tpu-pytorch/xla:nightly_3.8_cuda_11.7_20230217` and couldn't reproduce this issue. So maybe it has been fixed already?

**Comment by cicirori** [comment]
it's strange that code won't raise exceptions after rebuilding form source code...
