### ISSUE TITLE
Run Pytorch 2.0 benchmarks with XLA backend

### ISSUE THREAD

**Issue by vinayburugu** [pytorch/xla#4699]
I am having trouble in getting the benchmarks running with XLA backend. Used latest pytorch master/release2.0 branch.
Here is what I did

```bash
#!/bin/bash
set -x
# Setup the output directory
backend="torchxla_trace_once"
models="huggingface"
precision=amp
rm -rf ${models}_${backend}_logs/${backend}_${models}_${precision}_cuda_performance.csv
mkdir -p ${models}_${backend}_logs
# Commands for huggingface for device=cuda, dtype=${precision} for training and for performance testing
cd pytorch
GPU_NUM_DEVICES=1 python benchmarks/dynamo/${models}.py --performance --${precision} -dcuda --output=${models}_${backend}_logs/${backend}_${models}_${precision}_cuda_performance.csv --output-directory=./ --backend=${backend}   --no-skip --dashboard -x Reformer -x GPTNeoForCausalLM -x GPTJForQuestionAnswering -x BlenderbotForConditionalGeneration -x GPTJForCausalLM -x GPTNeoForSequenceClassification
gh gist create ${models}_${backend}_logs/${backend}_${models}_${precision}_cuda_performance.csv
```

## Error

```
WARNING:__main__:Running smaller batch size=4 for AlbertForMaskedLM, orig batch_size=8
cuda eval  AlbertForMaskedLM                   ERROR:common:Failed for dynamo All tensors should be on xla
Traceback (most recent call last):
  File "/home/ubuntu/pytorch/benchmarks/dynamo/common.py", line 1289, in warmup
    fn(model, example_inputs)
  File "/home/ubuntu/anaconda3/envs/xla/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/huggingface.py", line 485, in forward_pass
    return mod(**inputs)
  File "/home/ubuntu/anaconda3/envs/xla/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/transformers/src/transformers/models/albert/modeling_albert.py", line 939, in forward
    @add_start_docstrings_to_model_forward(ALBERT_INPUTS_DOCSTRING.format("batch_size, sequence_length"))
  File "/home/ubuntu/anaconda3/envs/xla/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/xla/lib/python3.8/site-packages/torch/_dynamo/backends/torchxla.py", line 24, in fwd
    compiled_graph = bridge.extract_compiled_graph(model, args)
  File "/home/ubuntu/anaconda3/envs/xla/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/torch_xla/core/dynamo_bridge.py", line 197, in extract_compiled_graph
    assert all(
AssertionError: All tensors should be on xla
ERROR
```

**Comment by JackCaoG** [comment]
I felt like this is a HF setup issue, we have not started the integration with HF benchmark with dynamo backend. We have been using torchbench to evulate the xla dynamo backend. it seems like some of the input tensor is either on cpu or CUDA device when feed to XLA backend. 

@Liyang90 Maybe HF benchmark is something we should also support?

**Comment by vinayburugu** [comment]
@JackCaoG which branch should I use for xla master or JackCao/update_to_2.0 ?

**Comment by JackCaoG** [comment]
you can just use the pytorch and xla master, however I suspect changes needs to be done on the HF benchmark code side. 

If you set a pdb in `/home/ubuntu/anaconda3/envs/xla/lib/python3.8/site-packages/torch_xla-2.0.0-py3.8-linux-x86_64.egg/torch_xla/core/dynamo_bridge.py` you will likley see some input tensor is not no xla device.

**Comment by vinayburugu** [comment]
@JackCaoG I only PT2.0+XLA results with CPU in this #4328. Can you point to the official benchmark results with cpu and gpu?

**Comment by JackCaoG** [comment]
That `cpu` is misleading, it is a UI thing in the torchbench we didn't fix. The torchbench will use the same XLA setup and first run lazy and then run dynamo. for example if you config

```
PJRT_DEVICE=CPU .....
```
then the benchmark will be on CPU. If you do 
```
PJRT_DEVICE=GPU ....
```
the benchmark will be done using GPU comparing lazy vs dynamo using xla:gpu. I don't know how you configure xla in your setup.

**Comment by JackCaoG** [comment]
benchmark in https://github.com/pytorch/xla/issues/4328 was done using TPU btw.

**Comment by vinayburugu** [comment]
@JackCaoG do you have a link with GPU benchmark results with XLA?

**Comment by JackCaoG** [comment]
there are some old data in https://dev-discuss.pytorch.org/t/torchdynamo-update-10-integrating-with-pytorch-xla-for-inference-and-training/935, it was being run ~2 month ago. I think speed on head now was improved but I didn't rerun it recently.

**Comment by ysiraichi** [comment]
As I understand it, you can run the benchmarks on XLA:GPU ([see this][1]).

[1]: https://github.com/pytorch/xla/blob/master/benchmarks/README.md
