### ISSUE TITLE
[Functionalization] Fix RNN tests

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/xla#4711]
Fix the following RNN tests that are broken by functionalizatoin:

- [ ] test_GRU_grad_and_gradgrad_xla_float64
- [ ] test_LSTM_grad_and_gradgrad_xla_float64

**Comment by alanwaketan** [comment]
It looks like these tests have been failing for TPU for the same reason for a long time. Not sure if it's worth making it work for CPU/GPU only. @wonjoolee95 Let me properly skip them.

```
root@t1v-n-307ffe96-w-0:/workspaces/work/pytorch/xla# PJRT_DEVICE=CPU python ../test/test_nn.py -v -k test_LSTM_grad_and_gradgrad_xla_float64
test_LSTM_grad_and_gradgrad_xla_float64 (__main__.TestNNDeviceTypeXLA) ... ERROR

======================================================================
ERROR: test_LSTM_grad_and_gradgrad_xla_float64 (__main__.TestNNDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/work/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    raise rte
  File "/workspaces/work/pytorch/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/workspaces/work/pytorch/torch/testing/_internal/common_device_type.py", line 888, in dep_fn
    return fn(slf, *args, **kwargs)
  File "../test/test_nn.py", line 10211, in test_LSTM_grad_and_gradgrad
    self._test_rnn_mod(mod, inp)
  File "../test/test_nn.py", line 10182, in _test_rnn_mod
    gradcheck(gradcheckfunc, inp, check_batched_grad=False)
  File "/workspaces/work/pytorch/torch/testing/_internal/common_utils.py", line 3861, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1536, in gradcheck
    return _gradcheck_helper(**args)
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1550, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1166, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1421, in _fast_gradcheck
    _check_analytical_numerical_equal(analytical_vJu, numerical_vJu, complex_indices,
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1389, in _check_analytical_numerical_equal
    raise GradcheckError(_get_notallclose_msg(a, n, j, i, complex_indices, test_imag, is_forward_ad) + jacobians_str)
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor(-0.0652, device='xla:0')
analytical:tensor(-0.0292, device='xla:0')

The above quantities relating the numerical and analytical jacobians are computed 
in fast mode. See: https://github.com/pytorch/pytorch/issues/53876 for more background 
about fast mode. Below, we recompute numerical and analytical jacobians in slow mode:

Numerical:
 tensor([[ 5.6120e-02, -1.2396e-01,  9.3075e-03,  1.4915e-02, -4.5219e-02,
         -1.2580e-01,  5.7343e-02, -7.3937e-02, -1.5926e-02, -1.9359e-02,
         -7.0362e-04,  3.4288e-03],
        [ 1.4472e-02, -9.4019e-02, -3.3356e-03,  2.8488e-03, -5.3529e-02,
          9.8919e-02,  1.0714e-02,  5.4732e-02,  3.4984e-03, -1.7364e-02,
         -5.2546e-03, -3.3021e-03],
        [-1.2331e-02, -5.6170e-03,  2.1576e-01, -1.4155e-02, -6.4145e-02,
          5.5453e-03,  2.2342e-02, -8.9278e-02,  9.2624e-03,  1.9976e-04,
          3.1741e-02,  2.6777e-03],
        [ 6.5057e-02, -7.7560e-02, -1.3836e-01,  3.1752e-02, -1.2877e-03,
         -1.3324e-01,  7.0962e-02,  5.3031e-02, -2.5754e-02, -1.0336e-02,
         -2.2568e-02,  3.7040e-03],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.9173e-02,
         -1.7328e-04, -1.3722e-02, -2.3430e-02, -3.8333e-02, -3.4701e-02,
         -6.8036e-02,  9.3992e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  3.0118e-02,
         -3.6434e-04,  2.4399e-02, -1.1483e-02, -5.9742e-02, -5.7301e-02,
          6.0106e-03,  4.2567e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  2.4019e-03,
         -4.7642e-04,  1.8433e-02,  2.2860e-02, -1.7039e-02, -6.9270e-02,
          3.5280e-02, -7.8312e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  6.1217e-03,
         -4.2041e-04, -2.7490e-02,  1.7183e-02, -2.1611e-02, -6.3542e-02,
         -7.3382e-02, -6.7944e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]], device='xla:0')
Analytical:
tensor([[ 0.0561, -0.1240,  0.0093,  0.0149,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0145, -0.0940, -0.0033,  0.0028,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [-0.0123, -0.0056,  0.2158, -0.0142,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0651, -0.0776, -0.1384,  0.0318,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0826, -0.1174,  0.0052,  0.0620,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0382, -0.1044,  0.0401, -0.0855,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -0.0015,  0.0006,  0.1336,  0.0880,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0771, -0.0635, -0.0864,  0.0369,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0815, -0.1160,  0.0293,  0.1084],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0301, -0.0682,  0.0433, -0.0998],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         -0.0131, -0.0121,  0.0913,  0.0778],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0871, -0.0847, -0.0315,  0.1212]], device='xla:0')

The max per-element difference (slow mode) is: 0.13324319768577042.


----------------------------------------------------------------------
Ran 1 test in 7.853s

FAILED (errors=1)
root@t1v-n-307ffe96-w-0:/workspaces/work/pytorch/xla# PJRT_DEVICE=TPU python ../test/test_nn.py -v -k test_LSTM_grad_and_gradgrad_xla_float64
test_LSTM_grad_and_gradgrad_xla_float64 (__main__.TestNNDeviceTypeXLA) ... ERROR

======================================================================
ERROR: test_LSTM_grad_and_gradgrad_xla_float64 (__main__.TestNNDeviceTypeXLA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/work/pytorch/torch/testing/_internal/common_device_type.py", line 414, in instantiated_test
    raise rte
  File "/workspaces/work/pytorch/torch/testing/_internal/common_device_type.py", line 401, in instantiated_test
    result = test(self, **param_kwargs)
  File "/workspaces/work/pytorch/torch/testing/_internal/common_device_type.py", line 888, in dep_fn
    return fn(slf, *args, **kwargs)
  File "../test/test_nn.py", line 10211, in test_LSTM_grad_and_gradgrad
    self._test_rnn_mod(mod, inp)
  File "../test/test_nn.py", line 10182, in _test_rnn_mod
    gradcheck(gradcheckfunc, inp, check_batched_grad=False)
  File "/workspaces/work/pytorch/torch/testing/_internal/common_utils.py", line 3861, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1536, in gradcheck
    return _gradcheck_helper(**args)
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1550, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1166, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1421, in _fast_gradcheck
    _check_analytical_numerical_equal(analytical_vJu, numerical_vJu, complex_indices,
  File "/workspaces/work/pytorch/torch/autograd/gradcheck.py", line 1389, in _check_analytical_numerical_equal
    raise GradcheckError(_get_notallclose_msg(a, n, j, i, complex_indices, test_imag, is_forward_ad) + jacobians_str)
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor(-0.0563, device='xla:0')
analytical:tensor(-0.0158, device='xla:0')

The above quantities relating the numerical and analytical jacobians are computed 
in fast mode. See: https://github.com/pytorch/pytorch/issues/53876 for more background 
about fast mode. Below, we recompute numerical and analytical jacobians in slow mode:

Numerical:
 tensor([[ 3.1237e-02, -7.2806e-02, -4.0885e-03,  5.7071e-03, -2.9758e-02,
         -6.7852e-02, -1.2957e-02, -7.7575e-02, -2.2389e-02, -3.3178e-03,
         -5.8115e-04,  2.0023e-03],
        [-1.5107e-02, -7.3656e-02, -3.0695e-02,  1.5985e-02, -3.4455e-02,
          7.0542e-02, -3.6731e-02,  5.9895e-02,  4.7758e-03, -2.9760e-03,
         -4.5821e-03, -1.9288e-03],
        [-2.4365e-02,  3.8063e-03,  2.3315e-01, -2.7783e-02, -4.6846e-02,
          9.6001e-03,  6.9365e-03, -9.3445e-02,  1.2919e-02,  3.4459e-05,
          2.7657e-02,  1.5581e-03],
        [ 5.8388e-02, -3.3581e-02, -1.6461e-01,  2.4941e-02, -2.3805e-03,
         -7.5828e-02,  1.5058e-02,  5.6215e-02, -3.6128e-02, -1.7709e-03,
         -1.9632e-02,  2.1588e-03],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.9994e-02,
          4.6119e-03, -1.5244e-02, -2.1890e-02, -2.1480e-02, -2.3501e-02,
         -5.2810e-02,  1.0866e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  3.1359e-02,
          9.6895e-03,  2.6993e-02, -1.0729e-02, -3.2507e-02, -4.6934e-02,
         -9.8646e-03,  5.1040e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  2.4773e-03,
          1.2666e-02,  2.0199e-02,  2.1338e-02, -2.4945e-02, -6.0482e-02,
          1.9960e-02, -9.7545e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  6.4075e-03,
          1.1180e-02, -3.0361e-02,  1.6049e-02, -2.4147e-02, -5.3752e-02,
         -4.8824e-02, -7.9057e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]], device='xla:0')
Analytical:
tensor([[ 0.0312, -0.0728, -0.0041,  0.0055,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [-0.0151, -0.0736, -0.0307,  0.0161,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [-0.0244,  0.0038,  0.2331, -0.0277,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0584, -0.0336, -0.1646,  0.0250,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0681, -0.0487,  0.0019,  0.0656,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0408, -0.0687,  0.0643, -0.0875,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0078,  0.0149,  0.0894,  0.0885,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0534, -0.0058, -0.0596,  0.0431,
          0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0890, -0.0865,  0.0273,  0.1302],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0578, -0.0720,  0.0412, -0.1227],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0071, -0.0014,  0.0634,  0.0976],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0696, -0.0499, -0.0144,  0.1435]], device='xla:0')

The max per-element difference (slow mode) is: 0.14352937042713165.


----------------------------------------------------------------------
Ran 1 test in 7.645s

FAILED (errors=1)
```
