### ISSUE TITLE
Simple addition fails on TPU v4-8 with legacy `XRT_TPU_CONFIG` but not `PJRT_DEVICE`

### ISSUE THREAD

**Issue by dinhanhx** [pytorch/xla#5258]
## 🐛 Bug

I was trying to run [the example](https://cloud.google.com/tpu/docs/run-calculation-pytorch) on TPU v4-8 with `export XRT_TPU_CONFIG="localservice;0;localhost:51011"`. But it got `RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1403 : Check failed: parsed_device.id <= topology_proto->num_tpu_devices_per_task() (5 vs. 4)`. 

```
Traceback (most recent call last):
  File "test_add.py", line 4, in <module>
    dev = xm.xla_device()
  File "/home/confidential/.virtualenvs/torch-tpu/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 245, in xla_device
    devices = get_xla_supported_devices(devkind=devkind)
  File "/home/confidential/.virtualenvs/torch-tpu/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 139, in get_xla_supported_devices
    xla_devices = _DEVICES.value
  File "/home/confidential/.virtualenvs/torch-tpu/lib/python3.8/site-packages/torch_xla/utils/utils.py", line 32, in value
    self._value = self._gen_fn()
  File "/home/confidential/.virtualenvs/torch-tpu/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 21, in <lambda>
    _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:1403 : Check failed: parsed_device.id <= topology_proto->num_tpu_devices_per_task() (5 vs. 4)
*** Begin stack trace ***
        tsl::CurrentStackTrace()
        xla::XrtComputationClient::InitializeDevices(std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::XrtComputationClient::XrtComputationClient(xla::XrtComputationClient::Options, std::unique_ptr<tensorflow::tpu::TopologyProto, std::default_delete<tensorflow::tpu::TopologyProto> >)
        xla::ComputationClient::Create()


        xla::ComputationClient::Get()


        PyCFunction_Call
        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        PyObject_GetAttr
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        PyEval_EvalCode



        PyRun_SimpleFileExFlags
        Py_RunMain
        Py_BytesMain
        __libc_start_main
        _start
*** End stack trace ***
```

## To Reproduce

```bash
export XRT_TPU_CONFIG="localservice;0;localhost:51011"
```

```python
import torch
import torch_xla.core.xla_model as xm

dev = xm.xla_device()
t1 = torch.randn(1024,1024,device=dev)
t2 = torch.randn(1024,1024,device=dev)
t3 = t1 + t2
print(t3.shape)
```

## Expected behavior

It works.

## Environment

Torch, xla, tpu related
```requirements.txt
cloud-tpu-client==0.10
libtpu-nightly @ https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20220930-py3-none-any.whl
pytorch-lightning==2.0.4
torch==1.13.0
torch-tb-profiler==0.4.1
torch-xla @ https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-1.13-cp38-cp38-linux_x86_64.whl
torchmetrics==0.11.4
torchvision==0.14.0
```

Full list
```requirements.txt
absl-py==1.4.0
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.7.0
arrow==1.2.3
asttokens==2.2.1
async-timeout==4.0.2
attrs==23.1.0
backcall==0.2.0
beautifulsoup4==4.12.2
blessed==1.20.0
cachetools==4.2.4
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
cloud-tpu-client==0.10
comm==0.1.3
croniter==1.3.15
dataclass-wizard==0.22.2
dateutils==0.6.12
debugpy==1.6.7
decorator==5.1.1
deepdiff==6.3.0
einops==0.6.1
exceptiongroup==1.1.1
executing==1.2.0
fastapi==0.98.0
filelock==3.12.2
frozenlist==1.3.3
fsspec==2023.6.0
google-api-core==1.31.5
google-api-python-client==1.8.0
google-auth==1.35.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.5.3
googleapis-common-protos==1.59.1
grpcio==1.56.0
h11==0.14.0
httplib2==0.22.0
huggingface-hub==0.15.1
idna==3.4
importlib-metadata==6.7.0
inquirer==3.1.3
ipykernel==6.23.3
ipython==8.12.2
itsdangerous==2.1.2
jedi==0.18.2
Jinja2==3.1.2
jupyter_client==8.3.0
jupyter_core==5.3.1
libtpu-nightly @ https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20220930-py3-none-any.whl
lightning==2.0.4
lightning-cloud==0.5.37
lightning-utilities==0.8.0
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
mdurl==0.1.2
multidict==6.0.4
nest-asyncio==1.5.6
numpy==1.24.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauth2client==4.1.3
oauthlib==3.2.2
ordered-set==4.1.0
packaging==23.1
pandas==2.0.2
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.5.0
platformdirs==3.8.0
polars==0.18.4
prompt-toolkit==3.0.38
protobuf==4.23.3
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydantic==1.10.9
Pygments==2.15.1
PyJWT==2.7.0
pyparsing==3.1.0
python-dateutil==2.8.2
python-editor==1.0.4
python-iso639==2023.6.15
python-multipart==0.0.6
pytorch-lightning==2.0.4
pytz==2023.3
PyYAML==6.0
pyzmq==25.1.0
readchar==4.0.5
regex==2023.6.3
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.4.2
rsa==4.9
safetensors==0.3.1
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
stack-data==0.6.2
starlette==0.27.0
starsessions==1.3.0
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorboardX==2.6.1
tokenizers==0.13.3
toml==0.10.2
torch==1.13.0
torch-tb-profiler==0.4.1
torch-xla @ https://storage.googleapis.com/tpu-pytorch/wheels/tpuvm/torch_xla-1.13-cp38-cp38-linux_x86_64.whl
torchmetrics==0.11.4
torchvision==0.14.0
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.30.2
typing_extensions==4.6.3
tzdata==2023.3
uritemplate==3.0.1
urllib3==1.26.16
uvicorn==0.22.0
wcwidth==0.2.6
websocket-client==1.6.1
websockets==11.0.3
Werkzeug==2.3.6
yarl==1.9.2
zipp==3.15.0
```

**Comment by ManfeiBai** [comment]
Hi, @will-cromar, is it ok to assign this issue to you?

**Comment by will-cromar** [comment]
Hey, this is an error in our documentation. For XRT on TPU v4, you must set `TPU_NUM_DEVICES=4` explicitly. I'll send a fix.

**Comment by will-cromar** [comment]
Added `TPU_NUM_DEVICES=4` to the documentation: https://cloud.google.com/tpu/docs/run-calculation-pytorch#set_tpu_runtime_configuration

Let me know if that doesn't fix the issue.

In general, I recommend starting new projects with PJRT, since it's quite a bit easier to use and configure.

**Comment by opooladz** [comment]
@will-cromar running into the same problem For some reason PJRT isnt working for me.  I am on a v4-8. On v3-8's I would use 
import os
os.environ['XRT_TPU_CONFIG'] = 'localservice;0;localhost:51011'

xmp.spawn(_mp_fn, args=(None,), nprocs=8, start_method='fork')

Now seems I need to set xmp.spawn(_mp_fn) and do TPU_NUM_DEVICES=4. I have 8 devices right? hence the training 8 in v4-8. Why cant I utilize them all? What am I missing here?

**Comment by will-cromar** [comment]
First, `XRT` is now deprecated. For current releases, use `PJRT_DEVICE=TPU`[^1] rather than `XRT_TPU_CONFIG=...`. You can also skip `TPU_NUM_DEVICES` with PJRT.

The drivers on TPU v3 and v4 work differently. Both VMs have 4 TPU chips with 2 cores each. The number at the end of the TPU name is the number of cores. On TPU v3, the driver treats each core as one device. On TPU v4, the driver treats each chip as one device and divides the work between cores automatically. If you take a profile of either one, you'll see 8 cores.

[^1]: We can also auto-detect the TPU most of the time if everything is installed properly.

**Comment by opooladz** [comment]
What is the proper image to use on the v4's? I am using tpu-pt-vm-2.0. Using PJRT_DEVICE=TPU did not work for me. A but puzzled. I was able to use PJRT on the v3's with no issue.

**Comment by JackCaoG** [comment]
Check https://cloud.google.com/tpu/docs/run-calculation-pytorch for the most up to date information, but currently we recommend `tpu-ubuntu2204-base` and manually install the pytorch and torch_xla from pip.

**Comment by will-cromar** [comment]
> What is the proper image to use on the v4's? I am using tpu-pt-vm-2.0. Using PJRT_DEVICE=TPU did not work for me. A but puzzled. I was able to use PJRT on the v3's with no issue.

Our old images unfortunately had separate version to TPU v4. The newer base image that Jack linked will work on both v3 and v4 though.

**Comment by elijahross** [comment]
Same problem here, on v4-32 even allocating the device fails (PJRT_DEVICE=TPU python3 -c "import torch_xla.core.xla_model as xm; print(xm.get_xla_supported_devices(\"TPU\"))") --> no repose, have to kill the process..
the most api methods for torch_xla have same behavior. 

on v3, everything works fine.. any suggestions? tested with installation from the documentary (https://cloud.google.com/tpu/docs/run-calculation-pytorch?hl=de#set_tpu_runtime_configuration)
