### ISSUE TITLE
Simple code runs with xla_multiprocessing but hangs with DistributedDataParallel

### ISSUE THREAD

**Issue by mako443** [pytorch/xla#5303]
## 🐛 Bug

I have almost identical, basic code to test Pytorch XLA on TPU nodes. The following block runs through without hanging or unexpected debug/profiling outputs.

```
import os
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from torch.optim import SGD
from torch_xla.core import xla_model
from torch_xla.distributed import parallel_loader
from torch_xla.distributed import xla_multiprocessing
import torch_xla.debug.metrics as xla_metrics
import time

from torchvision.models import resnet18, resnet152

os.environ["PJRT_DEVICE"]="TPU"

x_data = torch.rand(128,3,512,512)
y_data = torch.randint(0, 1000, size=[len(x_data)])
dataset = TensorDataset(x_data,y_data)
loader = DataLoader(dataset, batch_size=4)

def process_fn(index):
    rank = xla_model.get_ordinal()
    world_size = xla_model.xrt_world_size()
    print(f"Rank {rank} of {world_size}")

    device = xla_model.xla_device()
    mp_loader = parallel_loader.MpDeviceLoader(loader, device)

    model = resnet152().to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = SGD(model.parameters(), lr=1e-3)

    for x, y in mp_loader:
        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        xla_model.optimizer_step(optimizer)

    if xla_model.is_master_ordinal():
        print(xla_metrics.metrics_report())

    
if __name__ == "__main__":
    t0 = time.time()
    xla_multiprocessing.spawn(process_fn, args=(), start_method="fork") # NOTE: "spawn" hangs
    print("Ela:", time.time() - t0)
```

The following code has minimal changes to use DistributedDataParallel as detailed in the [tutorial](https://pytorch.org/xla/release/2.0/index.html#how-to-do-distributeddataparallel) and should run equally well, but it gets stuck and needs to be killed with `sudo kill XXX` to free up the TPU again.

```
import os
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from torch.optim import SGD

from torch.nn.parallel import DistributedDataParallel as DDP

from torch_xla.core import xla_model
from torch_xla.distributed import parallel_loader
from torch_xla.distributed import xla_multiprocessing
import torch_xla.debug.metrics as xla_metrics
import time

from torchvision.models import resnet18, resnet152

os.environ["PJRT_DEVICE"]="TPU"

x_data = torch.rand(128,3,512,512)
y_data = torch.randint(0, 1000, size=[len(x_data)])
dataset = TensorDataset(x_data,y_data)
loader = DataLoader(dataset, batch_size=4)

def process_fn(index):
    rank = xla_model.get_ordinal()
    world_size = xla_model.xrt_world_size()
    print(f"Rank {rank} of {world_size}")

    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    # initialize the xla process group
    torch.distributed.init_process_group("xla", rank=rank, world_size=world_size)    

    device = xla_model.xla_device()
    mp_loader = parallel_loader.MpDeviceLoader(loader, device)

    model = resnet152().to(device)
    model = DDP(model, gradient_as_bucket_view=True)

    criterion = nn.CrossEntropyLoss()
    optimizer = SGD(model.parameters(), lr=1e-3)

    for x, y in mp_loader:
        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
       # NOTE:  xla_model.optimizer_step(optimizer) hangs just the same
        optimizer.step()
        xla_model.mark_step()

    if xla_model.is_master_ordinal():
        print(xla_metrics.metrics_report())

    torch.distributed.destroy_process_group()   
    
if __name__ == "__main__":
    t0 = time.time()
    xla_multiprocessing.spawn(process_fn, args=(), start_method="fork", nprocs=None)
    print("Ela:", time.time() - t0)
```

## To Reproduce

1. Run the first script, simply with `python3 name_of_script.py`
2. Run the second script, simply with `python3 name_of_script.py`, be prepared for it to hang as it did for me

If it helps, cancelling the second script gives this stack trace (cropped to bottom part):
```
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 104, in _python_exit
Process ForkProcess-2:
Process ForkProcess-3:
Process ForkProcess-4:
    t.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 96, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 96, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 97, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
^C
```

## Expected behavior

The second script should finish without errors or getting stuck, just as the first one does, or give a clear error.

## Environment

 - Reproducible on XLA backend TPU: GCP `TPU VM` of type `v3-8` with software `tpu-vm-pt-2.0`
 - torch_xla version: `2.0` (pre-installed on the GCP machine)

Any help is appreciated, please let me know if any more information is needed!

**Comment by JackCaoG** [comment]
Took a quick look and didn't spot anything obvious, @alanwaketan any idea?

**Comment by alanwaketan** [comment]
Sorry for the late reply. Yea, you need to init_process_group.

**Comment by mako443** [comment]
Yes, specifically with the `pjrt://` init to make it work
