### ISSUE TITLE
PyTorch/XLA wheel for release branch build failed to find cudnn8.7.0

### ISSUE THREAD

**Issue by ManfeiBai** [pytorch/xla#5419]
Hi @mateuszlewko and @will-cromar,

I wonder how build process find specific cudnn version like `libcudnn8=8.7.0.84-1+cuda11.8`, do we installed it already and saved in a bucket or we could only access specific version with limitation?

now we want to build release branch(2.0) with cudnn8.7.0.84-1+cudnn11.8 like https://github.com/pytorch/xla/blob/r2.0/infra/ansible/config/cuda_deps.yaml, but failed with `msg: no available installation candidate for libcudnn8=8.7.0.84-1+cuda11.8`, we confirmed `libcudnn8=8.7.0.84-1+cuda11.8` according to [blog](https://stackoverflow.com/questions/76465821/how-to-modify-this-command-to-install-specific-cudnn-and-torch-version-apt-inst) due to no access to nvidia yet.

So my question is how to enable building system find and install this specific verison of cudnn(`libcudnn8=8.7.0.84-1+cuda11.8`)?

Thanks.

cc: @JackCaoG @miladm @will-cromar

**Comment by mateuszlewko** [comment]
Hey Manfei,

It seems that previous APT repo for CUDA didn't contain such package version. I slightly updated the config and the CUDA apt repo. I created https://github.com/pytorch/xla/pull/5425. Note that PR will only affect nightly builds. To change r2.0, you should push similar change to the r2.0 branch.

Thanks,
Mateusz

**Comment by ManfeiBai** [comment]
Thanks, will make a same PR for r2.0 too

**Comment by vanbasten23** [comment]
It seems we still have such issue:
```
2023-09-18 22:05:13.946634: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:435] Loaded runtime CuDNN library: 8.7.0 but source was compiled with: 8.8.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
```
in our nightly docker image.

To repro:
```
(base) xiowei@xiowei-gpu:~$ sudo docker pull us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.8_cuda_11.8

nightly_3.8_cuda_11.8: Pulling from tpu-pytorch-releases/docker/xla
Digest: sha256:34457afa44856c7d53940bc1094bbbe0f84bd2b38340c79fbe8c546a2df05b0b
Status: Image is up to date for us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.8_cuda_11.8
us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.8_cuda_11.8
(base) xiowei@xiowei-gpu:~$
(base) xiowei@xiowei-gpu:~$ sudo docker run --gpus all -it -d us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.8_cuda_11.8 bin/bash
63294ed9e7cc6a0da8b7a3cd9ae44a8a910056d978a1753919563a2ea591b984
(base) xiowei@xiowei-gpu:~$ sudo docker exec -it $(sudo docker ps | awk 'NR==2 { print $1 }') /bin/bash
root@63294ed9e7cc:/# git clone --recursive https://github.com/pytorch/xla.git
Cloning into 'xla'...
remote: Enumerating objects: 71234, done.
remote: Counting objects: 100% (3662/3662), done.
remote: Compressing objects: 100% (1335/1335), done.
remote: Total 71234 (delta 2728), reused 3064 (delta 2311), pack-reused 67572
Receiving objects: 100% (71234/71234), 34.33 MiB | 29.47 MiB/s, done.
Resolving deltas: 100% (54282/54282), done.
root@63294ed9e7cc:/# export GPU_NUM_DEVICES=1 PJRT_DEVICE=GPU
root@63294ed9e7cc:/# python xla/test/test_train_mp_imagenet.py --fake_data
/usr/local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.8/site-packages/torch/__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at /src/pytorch/torch/csrc/tensor/python_tensor.cpp:450.)
  _C._set_default_tensor_type(t)
==> Preparing data..
2023-09-18 22:05:13.946634: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:435] Loaded runtime CuDNN library: 8.7.0 but source was compiled with: 8.8.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2023-09-18 22:05:13.964045: F ./torch_xla/csrc/runtime/debug_macros.h:20] Non-OK-status: status.status() status: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
*** Begin stack trace ***
	tsl::CurrentStackTrace[abi:cxx11]()
	std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > ConsumeValue<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >(absl::lts_20230125::StatusOr<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >&&)
	torch_xla::runtime::PjRtComputationClient::Compile(std::vector<torch_xla::runtime::ComputationClient::CompileInstance, std::allocator<torch_xla::runtime::ComputationClient::CompileInstance> >)
	torch_xla::XLAGraphExecutor::Compile(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&, absl::lts_20230125::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch::lazy::LazyGraphExecutor::SyncTensorCollection const&, torch::lazy::LazyGraphExecutor::PostOrderData*, std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&)
	torch_xla::XLAGraphExecutor::SyncTensorsGraphInternal(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230125::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch::lazy::LazyGraphExecutor::SyncTensorsConfig const&, bool)
	torch_xla::XLAGraphExecutor::SyncTensorsGraph(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230125::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, bool, bool, bool)
	torch_xla::XLAGraphExecutor::SyncLiveTensorsGraph(torch::lazy::BackendDevice const*, c10::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, bool)




	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault

	_PyEval_EvalFrameDefault

	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault

	PyVectorcall_Call
	_PyEval_EvalFrameDefault

	_PyObject_FastCallDict
	_PyObject_Call_Prepend

	PyObject_Call

	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyVectorcall_Call
	_PyEval_EvalFrameDefault

	_PyEval_EvalFrameDefault

	PyVectorcall_Call
	_PyEval_EvalFrameDefault

	_PyEval_EvalFrameDefault

	_PyEval_EvalFrameDefault


	PyVectorcall_Call



	clone
*** End stack trace ***

Traceback (most recent call last):
  File "xla/test/test_train_mp_imagenet.py", line 377, in <module>
    xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS.num_cores)
  File "/usr/local/lib/python3.8/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 38, in spawn
    return pjrt.spawn(fn, nprocs, start_method, args)
  File "/usr/local/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 202, in spawn
    run_multiprocess(spawn_fn, start_method=start_method)
  File "/usr/local/lib/python3.8/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 159, in run_multiprocess
    replica_results = list(
  File "/usr/local/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 160, in <genexpr>
    itertools.chain.from_iterable(
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by vanbasten23** [comment]
hi @mateuszlewko, per the previous comment, iiuc, does this PR build PyTorch/XLA along with the dependency openXLA with cudnn=8.7 instead of 8.8?

**Comment by mateuszlewko** [comment]
Hey,

Yes, the dependency fo CUDA 11.8 is libcudnn 8.7, as deefined here: https://github.com/pytorch/xla/blob/master/infra/ansible/config/cuda_deps.yaml#L8 (same for `-dev` at L14).
If you need libcudnn 8.8 for CUDA 11.8, you need to check what version is available in NVIDIA's repo and update it in that config file.

**Comment by mateuszlewko** [comment]
I could be wrong, but AFAIU `Loaded runtime CuDNN library: 8.7.0 but source was compiled with: 8.8.0.` points that libcudnn has version 8.7 as expected.

**Comment by vanbasten23** [comment]
> I could be wrong, but AFAIU `Loaded runtime CuDNN library: 8.7.0 but source was compiled with: 8.8.0.` points that libcudnn has version 8.7 as expected.

I am mostly curious how we compile it with 8.8.0, probably a compilation flag

**Comment by mateuszlewko** [comment]
I pulled the latest cuda 11.8 nightly images and verified the following list of installed packages:
```
$ apt list --installed 

cuda-cccl-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-compiler-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-cudart-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-cudart-dev-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-cuobjdump-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-cuxxfilt-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-driver-dev-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-libraries-11-8/unknown,now 11.8.0-1 amd64 [installed]
cuda-minimal-build-11-8/unknown,now 11.8.0-1 amd64 [installed]
cuda-nvcc-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-nvprune-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-nvrtc-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-profiler-api-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-toolkit-11-8-config-common/unknown,now 11.8.89-1 all [installed,automatic]
cuda-toolkit-11-config-common/unknown,now 11.8.89-1 all [installed,automatic]
cuda-toolkit-config-common/unknown,now 12.2.140-1 all [installed,automatic]
libcudnn8/unknown,now 8.7.0.84-1+cuda11.8 amd64 [installed,upgradable to: 8.9.5.29-1+cuda12.2]
```

So libcudnn is correctly installed at 8.7. I'm not sure where 8.8 is coming from. Could it be some dependency?

**Comment by vanbasten23** [comment]
Yeah, it could be. Closing it for now. I'll find some detailed example in case I encounter the same problem. Thanks @mateuszlewko.
