### ISSUE TITLE
Query bazel deps of XLAC.so?

### ISSUE THREAD

**Issue by apivovarov** [pytorch/xla#5525]
## ❓ Questions and Help
I'm trying to see bazel dependencies of `//:_XLAC.so` target by running the following command (as described in [bazel guide](https://bazel.build/query/guide))
```
bazel query "deps(//:_XLAC.so)"
```
It shows me the following errors:
```bash
ERROR: An error occurred during the fetch of repository 'mkl_dnn_acl_compatible'
ERROR: no such package '@mkl_dnn_acl_compatible//': Unable to load package for @tsl//tensorflow/third_party/mkl_dnn:mkldnn_acl.BUILD: BUILD file not found in directory 'tensorflow/third_party/mkl_dnn' of external repository @tsl.
ERROR: Evaluation of query "deps(//:_XLAC.so)" failed
```
Full output:
```bash
root@dd45b88976fe:~/workspace/pytorch/xla# bazel query "deps(//:_XLAC.so)"
Starting local Bazel server and connecting to it...
DEBUG: /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/xla/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'tf_runtime' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/xla/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'llvm-raw' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository mkl_dnn_acl_compatible instantiated at:
  /root/workspace/pytorch/xla/WORKSPACE:76:15: in <toplevel>
  /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/xla/workspace2.bzl:90:19: in workspace
  /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/workspace2.bzl:636:21: in workspace
  /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/workspace2.bzl:165:20: in _tf_repositories
  /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/third_party/repo.bzl:136:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/third_party/repo.bzl:89:35: in <toplevel>
ERROR: An error occurred during the fetch of repository 'mkl_dnn_acl_compatible':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/third_party/repo.bzl", line 55, column 31, in _tf_http_archive_impl
                link_dict = _get_link_dict(ctx, ctx.attr.link_files, ctx.attr.build_file)
        File "/root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/third_party/repo.bzl", line 47, column 54, in _get_link_dict
                link_dict[ctx.path("BUILD.bazel")] = ctx.path(Label(build_file))
Error in path: Unable to load package for @tsl//tensorflow/third_party/mkl_dnn:mkldnn_acl.BUILD: BUILD file not found in directory 'tensorflow/third_party/mkl_dnn' of external repository @tsl. Add a BUILD file to a directory to mark it as a package.
ERROR: /root/workspace/pytorch/xla/WORKSPACE:76:15: fetching _tf_http_archive rule //external:mkl_dnn_acl_compatible: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/third_party/repo.bzl", line 55, column 31, in _tf_http_archive_impl
                link_dict = _get_link_dict(ctx, ctx.attr.link_files, ctx.attr.build_file)
        File "/root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/tsl/third_party/repo.bzl", line 47, column 54, in _get_link_dict
                link_dict[ctx.path("BUILD.bazel")] = ctx.path(Label(build_file))
Error in path: Unable to load package for @tsl//tensorflow/third_party/mkl_dnn:mkldnn_acl.BUILD: BUILD file not found in directory 'tensorflow/third_party/mkl_dnn' of external repository @tsl. Add a BUILD file to a directory to mark it as a package.
ERROR: /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/xla/xla/service/cpu/BUILD:1008:11: no such package '@mkl_dnn_acl_compatible//': Unable to load package for @tsl//tensorflow/third_party/mkl_dnn:mkldnn_acl.BUILD: BUILD file not found in directory 'tensorflow/third_party/mkl_dnn' of external repository @tsl. Add a BUILD file to a directory to mark it as a package. and referenced by '@xla//xla/service/cpu:runtime_matmul_mkl'
ERROR: /root/.cache/bazel/_bazel_root/346fc8b061ac3bdcc6b91de97c708483/external/xla/xla/service/cpu/BUILD:944:11: no such package '@mkl_dnn_acl_compatible//': Unable to load package for @tsl//tensorflow/third_party/mkl_dnn:mkldnn_acl.BUILD: BUILD file not found in directory 'tensorflow/third_party/mkl_dnn' of external repository @tsl. Add a BUILD file to a directory to mark it as a package. and referenced by '@xla//xla/service/cpu:runtime_conv2d_mkl'
ERROR: Evaluation of query "deps(//:_XLAC.so)" failed: errors were encountered while computing transitive closure
Loading: 186 packages loaded
```

**Comment by JackCaoG** [comment]
@stgpetrovic Goran do you have any idea for this?
