### ISSUE TITLE
Einsum is not captured with Dynamo

### ISSUE THREAD

**Issue by yeounoh** [pytorch/xla#5530]
## 🐛 Bug

The fake tensor input to Dynamo is not registered as XLATensor, which causes the following error running the `toch.compile`-ed `torch.einsum` on XLA tensors:
```
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <function einsum at 0x7f3f576c0f70>(*('ijkl,ijlm->ijkm', FakeTensor(..., device='xla:0', size=(4, 4, 4, 4)), FakeTensor(..., device='xla:0', size=(4, 4, 4, 4))), **{}):
torch_xla/csrc/aten_xla_bridge.cpp:84 : Check failed: xtensor 
*** Begin stack trace ***
	tsl::CurrentStackTrace[abi:cxx11]()
	torch_xla::bridge::GetXlaTensor(at::Tensor const&)
	torch_xla::bridge::GetXlaTensors(c10::IListRef<at::Tensor> const&)
	torch_xla::XLANativeFunctions::einsum(c10::basic_string_view<char>, c10::ArrayRef<at::Tensor>, c10::OptionalArrayRef<long>)
```

The XLA [implementation](https://github.com/pytorch/xla/blob/02c4aff4c399b06a31a452f02b612d5b8c89dddd/torch_xla/csrc/aten_xla_type.cpp#L1173) requires all the inputs to be XLATensors, and I am not sure how to resolve this. Creating this issue to solicit some inputs from Meta partners, cc @ezyang @bdhirsh @JackCaoG 

As the Dynamo is fake tensors, I can't force creating an XLATensor off of them (or can I?) since they don't have memory allocated, either:
```
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <function einsum at 0x7feb33547f70>(*('ijkl,ijlm->ijkm', FakeTensor(..., device='xla:0', size=(4, 4, 4, 4)), FakeTensor(..., device='xla:0', size=(4, 4, 4, 4))), **{}):
The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```

## To Reproduce
Here is my repro script:
```
import torch
import torch_xla
import torch_xla.core.xla_model as xm

def einsum_mm(a, b):
  output = torch.einsum('ijkl,ijlm->ijkm', a, b)
  return output

a = torch.randn(4,4,4,4).to(xm.xla_device())
b = torch.randn(4,4,4,4).to(xm.xla_device())

fn = torch.compile(einsum_mm,
                   backend="torchxla_trace_once",
                   fullgraph=True)

result = fn(a, b)
```

## Expected behavior

This should run without crashing. This works, without `torch.compile`.
## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly

**Comment by ezyang** [comment]
Can you post the full backtrace (Python and as much C++ as you can get too), not just the truncated one

**Comment by yeounoh** [comment]
Here is the full stacktrace @ezyang 
```
~/pytorch/xla$ TORCH_LOGS="+dynamo" TORCHDYNAMO_VERBOSE=1 python ~/test.py 
WARNING:root:PJRT is now the default runtime. For more information, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1693934196.807729  985512 tpu_initializer_framework_helper.cc:78] Libtpu path is: /home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch_xla-2.1.0-py3.9-linux-x86_64.egg/torch_xla/lib/libtpu.so
I0000 00:00:1693934199.657214  985512 pjrt_c_api_client.cc:110] PjRtCApiClient created.
[2023-09-05 17:16:39,667] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/contextlib.py
[2023-09-05 17:16:39,667] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/contextlib.py
[2023-09-05 17:16:39,667] torch._dynamo.eval_frame: [DEBUG] skipping helper /home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/contextlib.py
[2023-09-05 17:16:39,667] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/contextlib.py
[2023-09-05 17:16:39,667] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/contextlib.py
[2023-09-05 17:16:39,667] torch._dynamo.eval_frame: [DEBUG] skipping enable_dynamic /home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py
[2023-09-05 17:16:39,668] [0/0] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing einsum_mm /home/yeounoh/test.py:25
[2023-09-05 17:16:39,671] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line einsum_mm /home/yeounoh/test.py:25
[2023-09-05 17:16:39,671] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]     def einsum_mm(a, b):
[2023-09-05 17:16:39,695] [0/0] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['a'] (4, 4, 4, 4) [<DimDynamic.STATIC: 2>, <DimDynamic.STATIC: 2>, <DimDynamic.STATIC: 2>, <DimDynamic.STATIC: 2>] [None, None, None, None]
[2023-09-05 17:16:39,696] [0/0] torch._dynamo.variables.builder: [DEBUG] wrap_to_fake L['b'] (4, 4, 4, 4) [<DimDynamic.STATIC: 2>, <DimDynamic.STATIC: 2>, <DimDynamic.STATIC: 2>, <DimDynamic.STATIC: 2>] [None, None, None, None]
[2023-09-05 17:16:39,696] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG] TRACE starts_line einsum_mm /home/yeounoh/test.py:26
[2023-09-05 17:16:39,696] [0/0] torch._dynamo.symbolic_convert.__trace_source: [DEBUG]       output = torch.einsum('ijkl,ijlm->ijkm', a, b)
[2023-09-05 17:16:39,697] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL torch []
[2023-09-05 17:16:39,697] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR einsum [TorchVariable(<module 'torch' from '/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/__init__.py'>)]
[2023-09-05 17:16:39,697] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST ijkl,ijlm->ijkm [TorchVariable(<function einsum at 0x7ff829be6f70>)]
[2023-09-05 17:16:39,698] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST a [TorchVariable(<function einsum at 0x7ff829be6f70>), ConstantVariable(str)]
[2023-09-05 17:16:39,698] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST b [TorchVariable(<function einsum at 0x7ff829be6f70>), ConstantVariable(str), TensorVariable()]
[2023-09-05 17:16:39,698] [0/0] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION 3 [TorchVariable(<function einsum at 0x7ff829be6f70>), ConstantVariable(str), TensorVariable(), TensorVariable()]
Traceback (most recent call last):
  File "/home/yeounoh/test.py", line 52, in <module>
    result = fn(a, b)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 382, in _convert_frame_assert
    return _compile(
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 562, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 484, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 451, in transform
    tracer.run()
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2078, in run
    super().run()
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 728, in run
    and self.step()
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 691, in step
    getattr(self, inst.opname)(inst)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1119, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 565, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/variables/torch.py", line 732, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 1195, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 1282, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1377, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1338, in get_fake_value
    return wrap_fake_exception(
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 917, in wrap_fake_exception
    return fn()
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1339, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1411, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1398, in run_node
    return node.target(*args, **kwargs)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.9/site-packages/torch/functional.py", line 377, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <function einsum at 0x7ff829be6f70>(*('ijkl,ijlm->ijkm', FakeTensor(..., device='xla:0', size=(4, 4, 4, 4)), FakeTensor(..., device='xla:0', size=(4, 4, 4, 4))), **{}):
torch_xla/csrc/aten_xla_bridge.cpp:84 : Check failed: xtensor 
*** Begin stack trace ***
	tsl::CurrentStackTrace[abi:cxx11]()
	torch_xla::bridge::GetXlaTensor(at::Tensor const&)
	torch_xla::bridge::GetXlaTensors(c10::IListRef<at::Tensor> const&)
	torch_xla::XLANativeFunctions::einsum(c10::basic_string_view<char>, c10::ArrayRef<at::Tensor>, c10::OptionalArrayRef<long>)
	
	
	
	
	
	
	at::_ops::einsum::call(c10::basic_string_view<char>, c10::ArrayRef<at::Tensor>, c10::OptionalArrayRef<long>)
	
	
	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	PyObject_Call
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyEval_EvalFrameDefault
	
	
	
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	
	_PyFunction_Vectorcall
	
	_PyObject_CallFunction_SizeT
	
	
	_PyEval_EvalFrameDefault
	
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	
	
	PyRun_SimpleFileExFlags
	Py_RunMain
	Py_BytesMain
	__libc_start_main
	
*** End stack trace ***
Input tensor is not an XLA tensor: XLAFloatType

from user code:
   File "/home/yeounoh/test.py", line 26, in einsum_mm
    output = torch.einsum('ijkl,ijlm->ijkm', a, b)


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

[2023-09-05 17:16:39,738] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
[2023-09-05 17:16:39,738] torch._dynamo.utils: [INFO] Function, Runtimes (s)
[2023-09-05 17:16:39,738] torch._dynamo.utils: [INFO] _compile.<locals>.compile_inner, 0.0000
```

The above stacktrace is usign the normal code path, and if I patch and try creating an XLATensor off of the fake tensor input, then I see
```
The XLATensor check happens in our einsum implementation,  
```
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <function einsum at 0x7feb33547f70>(*('ijkl,ijlm->ijkm', FakeTensor(..., device='xla:0', size=(4, 4, 4, 4)), FakeTensor(..., device='xla:0', size=(4, 4, 4, 4))), **{}):
The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```
^ the rest of the stack is identical to the original one.

**Comment by JackCaoG** [comment]
Let me take this one, the failure is from pytorch/xla end trying to extract the XLATensor from the input tensor. I don't think fake tensor is enabled for torch/xla's dynamo in general..

**Comment by JackCaoG** [comment]
The error actually happens before reaching the xla's dynamo bridge, it is in 
```
        with tx.fake_mode, enable_python_dispatcher():
            return wrap_fake_exception(
                lambda: run_node(tx.output, node, args, kwargs, nnmodule)
            )
```
in https://github.com/pytorch/pytorch/blob/b1729d8bbe6e18bcaeb4586c04426280ff91d137/torch/_dynamo/utils.py#L1341-L1344

with argument
```
(Pdb) tx.output
<torch._dynamo.output_graph.OutputGraph object at 0x7efba86d3340>
(Pdb) args
node = einsum
tx = <torch._dynamo.symbolic_convert.InstructionTranslator object at 0x7efba86c5ee0>
(Pdb) node
einsum
```

The symptom is that we are trying to run the `einsum` function with fake XLATensor input which is not supported(since FakeTensor does not have the XLATensor impl and we can't trace it). This does seems to happen for most other ops, if I have to guess it is due to we overwrite the `einsum` implementation in 
https://github.com/pytorch/xla/blob/d757e85e620eb92ae5defafceae89e5f73746567/codegen/xla_native_functions.yaml#L408C1-L409

the above `fake_value` is caused by 
```
example_value = get_fake_value(proxy.node, tx)
```
in https://github.com/pytorch/pytorch/blob/b1729d8bbe6e18bcaeb4586c04426280ff91d137/torch/_dynamo/variables/builder.py#L1293C12-L1294. I am still tring to understand what `wrap_fx_proxy_cls` is trying to do

**Comment by JackCaoG** [comment]
I dig a bit further and replaced the `einsum` with the `add`, I found that although `wrap_fx_proxy_cls` is also being called
```
1203 	    return TupleVariable(items).add_options(obj)
1204 	
1205 	
1206 	def wrap_fx_proxy(tx, proxy, example_value=None, **options):
1207 	    import pdb; pdb.set_trace()
1208 ->	    return wrap_fx_proxy_cls(
1209 	        target_cls=TensorVariable,
1210 	        tx=tx,
1211 	        proxy=proxy,
1212 	        example_value=example_value,
1213 	        **options,
(Pdb) proxy
Proxy(add)
```

underlying `run_node(tx.output, node, args, kwargs, nnmodule)` does not trigger any XLA execution
```
Counter: xla::_copy_from
  Value: 2
Counter: xla::_to_copy
  Value: 2
Counter: xla::empty_symint
  Value: 2
```
(I didn't see `xla::add` here)

Based on 
```
(Pdb) node.target(*args, **kwargs)
FakeTensor(..., device='xla:0', size=(4, 4, 4, 4))
(Pdb) node
add
(Pdb) args
tracer = <torch._dynamo.output_graph.OutputGraph object at 0x7eed4854a370>
node = add
args = (FakeTensor(..., device='xla:0', size=(4, 4, 4, 4)), FakeTensor(..., device='xla:0', size=(4, 4, 4, 4)))
kwargs = {}
nnmodule = None
```

in https://github.com/pytorch/pytorch/blob/208fd1cb845ade433b8a113b6346a98684705f82/torch/_dynamo/utils.py#L1401-L1402

I think what happened is that dynamo trying to figure out the output shape of a given op, it first tries to use some pre-defined rule in pytorch to calculated it(which is why it doesn't invoke any XLA code for add since it knows how to infer the output shape). For the ops that it doesn't know how to infer the output shape(`einsum` for example), it fallback to running the op on the real backend(XLA in this case) to execute and get the output shape. However XLA does not really support fake tensor and it crashed. @ezyang Can you shed some light on whether my thinking is correct?

**Comment by JackCaoG** [comment]
for the `einsum` it is
```
(Pdb) node
einsum
(Pdb) node.target
<function einsum at 0x7fb8858b98b0>
(Pdb) args
tracer = <torch._dynamo.output_graph.OutputGraph object at 0x7f9db00282e0>
node = einsum
args = ('ijkl,ijlm->ijkm', FakeTensor(..., device='xla:0', size=(4, 4, 4, 4)), FakeTensor(..., device='xla:0', size=(4, 4, 4, 4)))
kwargs = {}
nnmodule = None
```

another thing I noticed is that for `add`, `node.target` is a `built-in method add` while for `einsum`, it is just a `function einsum`. and `einsum` will trigger the XLA execution and crashed.

**Comment by JackCaoG** [comment]
@ezyang How important is it to support FakeTensor for pytorch/xla. I think it is doable, when we see a fake tensor we can try to allocate a temp XLATensorImpl, let it trace, figured out the shape and drop the `XLATensorImpl`. It is easier to do it in a op by op basis, and harder to do for all ops. Trying to figure out the priority for this one.

**Comment by ezyang** [comment]
Ah this makes sense.

The simplest fix is to metafy einsum. I originally thought that einsum was a composite and this automatically should have meta support. All you need is some Python reference implementation of einsum and you are good.

While in principle fake tensor fallback should work, in the limit it shouldn't be necessary as all ops should have meta functions. OTOH xla is literally perfect for fake execution so who can tell. I would try metafying einsum first though

**Comment by JackCaoG** [comment]
Thanks Ed!

**Comment by JackCaoG** [comment]
should be workaround by https://github.com/pytorch/xla/pull/5597
