### ISSUE TITLE
Which version of PyTorch is compatible with master branch version's XLA?

### ISSUE THREAD

**Issue by Beomi** [pytorch/xla#5553]
Hi, I read article about SPMD using pytorch/xla.

So I wanted to try it out, using XLA 2.2(master, nightly.) and PyTorch (2.2, pre release, nightly release).

I thought since XLA nightly version is 2.2.0, so I should install PyTorch 2.2 which is nightly pre release version.

But after I setup clean venv using virtualenv and installed both PyTorch and XLA, it shows this err below:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/beomi/spmd_tester/venv/lib/python3.8/site-packages/torch_xla/__init__.py", line 114, in <module>
    import _XLAC
ImportError: /home/beomi/spmd_tester/venv/lib/python3.8/site-packages/_XLAC.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5torch4lazy13MetricFnValueB5cxx11Ed
```

This is full install/exec log:
```
(venv) ➜  spmd_tester git:(main) ✗ pip install https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-nightly-cp38-cp38-linux_x86_64.whl
Collecting torch-xla==nightly
  Using cached https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-nightly-cp38-cp38-linux_x86_64.whl (179.6 MB)
Collecting pyyaml
  Using cached PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (736 kB)
Collecting cloud-tpu-client>=0.10.0
  Using cached cloud_tpu_client-0.10-py3-none-any.whl (7.4 kB)
Collecting absl-py>=1.0.0
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting google-api-python-client==1.8.0
  Using cached google_api_python_client-1.8.0-py3-none-any.whl (57 kB)
Collecting oauth2client
  Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
Collecting google-auth>=1.4.1
  Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
Collecting uritemplate<4dev,>=3.0.0
  Using cached uritemplate-3.0.1-py2.py3-none-any.whl (15 kB)
Collecting httplib2<1dev,>=0.9.2
  Using cached httplib2-0.22.0-py3-none-any.whl (96 kB)
Collecting six<2dev,>=1.6.1
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting google-auth-httplib2>=0.0.3
  Using cached google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)
Collecting google-api-core<2dev,>=1.13.0
  Using cached google_api_core-1.34.0-py3-none-any.whl (120 kB)
Collecting rsa>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting pyasn1>=0.1.7
  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
Collecting pyasn1-modules>=0.0.5
  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
Collecting googleapis-common-protos<2.0dev,>=1.56.2
  Using cached googleapis_common_protos-1.60.0-py2.py3-none-any.whl (227 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<4.0.0dev,>=3.19.5
  Using cached protobuf-3.20.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Collecting requests<3.0.0dev,>=2.18.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Collecting urllib3<2.0
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Collecting pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2
  Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
Installing collected packages: urllib3, uritemplate, six, pyyaml, pyparsing, pyasn1, protobuf, idna, charset-normalizer, certifi, cachetools, absl-py, rsa, requests, pyasn1-modules, httplib2, googleapis-common-protos, oauth2client, google-auth, google-auth-httplib2, google-api-core, google-api-python-client, cloud-tpu-client, torch-xla
Successfully installed absl-py-1.4.0 cachetools-5.3.1 certifi-2023.7.22 charset-normalizer-3.2.0 cloud-tpu-client-0.10 google-api-core-1.34.0 google-api-python-client-1.8.0 google-auth-2.22.0 google-auth-httplib2-0.1.0 googleapis-common-protos-1.60.0 httplib2-0.22.0 idna-3.4 oauth2client-4.1.3 protobuf-3.20.3 pyasn1-0.5.0 pyasn1-modules-0.3.0 pyparsing-3.1.1 pyyaml-6.0.1 requests-2.31.0 rsa-4.9 six-1.16.0 torch-xla-2.2.0 uritemplate-3.0.1 urllib3-1.26.16
WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
You should consider upgrading via the '/home/beomi/spmd_tester/venv/bin/python -m pip install --upgrade pip' command.
(venv) ➜  spmd_tester git:(main) ✗ python
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_xla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/beomi/spmd_tester/venv/lib/python3.8/site-packages/torch_xla/__init__.py", line 110, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
>>> exit()
(venv) ➜  spmd_tester git:(main) ✗ pip3 install -U --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu

Looking in indexes: https://download.pytorch.org/whl/nightly/cpu
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cpu/torch-2.2.0.dev20230908%2Bcpu-cp38-cp38-linux_x86_64.whl (184.7 MB)
Collecting fsspec
  Using cached https://download.pytorch.org/whl/nightly/fsspec-2023.4.0-py3-none-any.whl (153 kB)
Collecting sympy
  Using cached https://download.pytorch.org/whl/nightly/sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/nightly/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting typing-extensions
  Using cached https://download.pytorch.org/whl/nightly/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting filelock
  Using cached https://download.pytorch.org/whl/nightly/filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting networkx
  Using cached https://download.pytorch.org/whl/nightly/networkx-3.0rc1-py3-none-any.whl (2.0 MB)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/nightly/MarkupSafe-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting mpmath>=0.19
  Using cached https://download.pytorch.org/whl/nightly/mpmath-1.2.1-py3-none-any.whl (532 kB)
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
Successfully installed MarkupSafe-2.1.2 filelock-3.9.0 fsspec-2023.4.0 jinja2-3.1.2 mpmath-1.2.1 networkx-3.0rc1 sympy-1.11.1 torch-2.2.0.dev20230908+cpu typing-extensions-4.4.0
WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
You should consider upgrading via the '/home/beomi/spmd_tester/venv/bin/python -m pip install --upgrade pip' command.
(venv) ➜  spmd_tester git:(main) ✗ python
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_xla
/home/beomi/spmd_tester/venv/lib/python3.8/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/beomi/spmd_tester/venv/lib/python3.8/site-packages/torch_xla/__init__.py", line 114, in <module>
    import _XLAC
ImportError: /home/beomi/spmd_tester/venv/lib/python3.8/site-packages/_XLAC.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN5torch4lazy13MetricFnValueB5cxx11Ed
>>> exit()
(venv) ➜  spmd_tester git:(main) ✗ 
```

**Comment by JackCaoG** [comment]
we publish nightly whl at https://github.com/pytorch/xla#available-docker-images-and-wheels. For TPUVM you can use
```
https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch-nightly-cp310-cp310-linux_x86_64.whl
https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-nightly-cp310-cp310-linux_x86_64.whl
```
If you are using python 3.8 you can replace `310` with `38`. If you want to build nightly yourself, checkout https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md#building-manually

**Comment by Beomi** [comment]
After I installed with above wheel and installed `libopenblas` via apt,

```bash
sudo apt-get update
sudo apt-get install -y libopenblas-base

# I installed this wheel with the new virtualenv
pip install https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch-nightly-cp38-cp38-linux_x86_64.whl
pip install https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-nightly-cp38-cp38-linux_x86_64.whl
```

I was able to use this code:
```python
# check_mesh.py
import torch

print(torch.__version__)
import torch_xla

print(torch_xla.__version__)

import torch_xla.core.xla_model as xm

import torch_xla.runtime as xr
from torch_xla.experimental.xla_sharding import Mesh
import numpy as np

# Assuming you are running on a TPU host that has 8 devices attached
num_devices = xr.global_runtime_device_count()
# mesh shape will be (4,2) in this example
mesh_shape = (num_devices // 2, 2)
device_ids = np.array(range(num_devices))
# axis_names 'x' nad 'y' are optional
mesh = Mesh(device_ids, mesh_shape, ("x", "y"))
print(mesh)
print(mesh.get_logical_mesh())
```

and the output was:

```
(venv) ➜  spmd_tester git:(main) ✗ python check_mesh.py
2.2.0
2.2.0
WARNING:root:PJRT is now the default runtime. For more information, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1694479636.606322  502858 tpu_initializer_framework_helper.cc:78] Libtpu path is: /home/beomi/spmd_tester/venv/lib/python3.8/site-packages/torch_xla/lib/libtpu.so
I0000 00:00:1694479639.973694  502858 pjrt_c_api_client.cc:110] PjRtCApiClient created.
<torch_xla.experimental.xla_sharding.Mesh object at 0x7f762b5653d0>
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
```

Thanks for your reply! :)
