### ISSUE TITLE
Check failed: pjrt_device == pjrt_data->buffer->device in kaggle Tpu

### ISSUE THREAD

**Issue by level14taken** [pytorch/xla#5686]
## ❓ Questions and Help
Hi, I was trying to use a wav2vec2 model in kaggle, it was working fine with single core tpu, trynig to use multiprocessing is giving me this error, I feel that wrapping the model with the  xmp.MpModelWrapper is causing this.
````python 
*** SIGSEGV (@(nil)), see gl__________46#s15 received by PID 29436 (TID 30881) on cpu 66; stack trace: ***
PC: @     0x7c50703289e6  (unknown)  torch::lazy::Util::ComputePostOrder()
    @     0x7c4f47328a1a       1152  (unknown)
    @     0x7c518fa16f90       3368  (unknown)
    @     0x7c4e4bffc9c0  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7c50703289e6,7c4f47328a19,7c518fa16f8f,7c4e4bffc9bf&map=ceee8fa20ddf9c34af43f587221e91de:7c4f3a400000-7c4f4753f840 
E1009 03:55:24.113791   30881 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E1009 03:55:24.113848   30881 client.cc:278] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E1009 03:55:24.113874   30881 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E1009 03:55:24.113887   30881 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E1009 03:55:24.113897   30881 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E1009 03:55:24.113904   30881 coredump_hook.cc:580] RAW: Dumping core locally.
E1009 03:56:58.864850   30881 process_state.cc:784] RAW: Raising signal 11 with default behavior
https://symbolize.stripped_domain/r/?trace=7c518fad307c,7c518fa16f8f&map=https://symbolize.stripped_domain/r/?trace=7c518fa60d36,7c518fa16f8f&map= 
*** SIGTERM received by PID 29437 (TID 29437) on cpu 64 from PID 29187; stack trace: ***
 
*** SIGTERM received by PID 29435 (TID 29435) on cpu 48 from PID 29187; stack trace: ***
PC: @     0x7c518fad307c  (unknown)  __read
PC: @     0x7c518fa60d36  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7c518fa60d36,7c518fa16f8f&map= 
*** SIGTERM received by PID 29438 (TID 29438) on cpu 22 from PID 29187; stack trace: ***
PC: @     0x7c518fa60d36  (unknown)  (unknown)
    @     0x7c4f47328a1a       1152  (unknown)
    @     0x7c518fa16f90  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7c518fa60d36,7c4f47328a19,7c518fa16f8f&map=ceee8fa20ddf9c34af43f587221e91de:7c4f3a400000-7c4f4753f840 
E1009 03:56:59.844315   29438 coredump_hook.cc:360] RAW: Remote crash gathering disabled for SIGTERM.
    @     0x7c4f47328a1a       1152  (unknown)
    @     0x7c4f47328a1a       1152  (unknown)
    @     0x7c518fa16f90  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7c518fad307c,7c4f47328a19,7c518fa16f8f&map=ceee8fa20ddf9c34af43f587221e91de:7c4f3a400000-7c4f4753f840 
    @     0x7c518fa16f90  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7c518fa60d36,7c4f47328a19,7c518fa16f8f&map=E1009 03:56:59.847661   29437 coredump_hook.cc:360] RAW: Remote crash gathering disabled for SIGTERM.
ceee8fa20ddf9c34af43f587221e91de:7c4f3a400000-7c4f4753f840 
E1009 03:56:59.847693   29435 coredump_hook.cc:360] RAW: Remote crash gathering disabled for SIGTERM.
E1009 03:57:00.297948   29437 process_state.cc:784] RAW: Raising signal 15 with default behavior
E1009 03:57:00.305354   29435 process_state.cc:784] RAW: Raising signal 15 with default behavior
E1009 03:57:00.328240   29438 process_state.cc:784] RAW: Raising signal 15 with default behavior

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 92, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 245, in _run_thread_per_device
    replica_results = list(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 238, in _thread_fn
    return fn()
  File "/usr/local/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py", line 341, in __call__
    self.fn(global_ordinal(), *self.args, **self.kwargs)
  File "/tmp/ipykernel_29187/2260900140.py", line 105, in finetune
    train_loop_fn(train_device_loader, epoch)
  File "/tmp/ipykernel_29187/2260900140.py", line 61, in train_loop_fn
    outputs = model(i)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/ipykernel_29187/2825197491.py", line 24, in forward
    x= self.model(x)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchaudio/pipelines/_wav2vec2/impl.py", line 28, in forward
    return self.model(waveforms, lengths)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchaudio/models/wav2vec2/model.py", line 117, in forward
    x = self.encoder(x, lengths)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchaudio/models/wav2vec2/components.py", line 515, in forward
    x = self.transformer(x, attention_mask=mask)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchaudio/models/wav2vec2/components.py", line 452, in forward
    x = self._preprocess(x)
  File "/usr/local/lib/python3.8/site-packages/torchaudio/models/wav2vec2/components.py", line 438, in _preprocess
    x = x + self.pos_conv_embed(x)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchaudio/models/wav2vec2/components.py", line 234, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/utils/weight_norm.py", line 65, in __call__
    setattr(module, self.name, self.compute_weight(module))
  File "/usr/local/lib/python3.8/site-packages/torch/nn/utils/weight_norm.py", line 25, in compute_weight
    return _weight_norm(v, g, self.dim)
RuntimeError: tensorflow/compiler/xla/xla_client/pjrt_computation_client.cc:407 : Check failed: pjrt_device == pjrt_data->buffer->device() 
*** Begin stack trace ***
	tsl::CurrentStackTrace()
	xla::PjRtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20220623::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
	torch_xla::XlaBackendImpl::ExecuteComputation(std::shared_ptr<torch::lazy::Computation>, c10::ArrayRef<std::shared_ptr<torch::lazy::BackendData> >, torch::lazy::BackendDevice const&) const
	
	torch::lazy::MultiWait::Complete(std::function<void ()> const&)
	
	
	
	__clone
*** End stack trace ***
TPU_0(process=0,(0,0,0,0)) vs TPU_1(process=0,(0,0,0,1))
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[4], line 1
----> 1 xmp.spawn(finetune, args=(),start_method='fork')

File /usr/local/lib/python3.8/site-packages/torch_xla/distributed/xla_multiprocessing.py:386, in spawn(fn, args, nprocs, join, daemon, start_method)
    360 """Enables multi processing based replication.
    361 
    362 Args:
   (...)
    383   return None.
    384 """
    385 if pjrt.using_pjrt():
--> 386   return pjrt.spawn(fn, nprocs, start_method, args)
    388 if not _is_xla_config():
    389   # If this is not an XLA setup, jump to normal multi-processing.
    390   return _run_direct(fn, args, nprocs, join, daemon, start_method)

File /usr/local/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py:365, in spawn(fn, nprocs, start_method, args)
    362 elif nprocs is not None:
    363   logging.warning('Unsupported nprocs (%d), ignoring...' % nprocs)
--> 365 _run_multiprocess(spawn_fn, start_method=start_method)

File /usr/local/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py:92, in requires_pjrt.<locals>.wrapper(*args, **kwargs)
     88 if not using_pjrt():
     89   raise NotImplementedError('`{}` not implemented for XRT'.format(
     90       fn.__name__))
---> 92 return fn(*args, **kwargs)

File /usr/local/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py:322, in _run_multiprocess(fn, start_method, *args, **kwargs)
    316   mp_fn = functools.partial(
    317       _run_thread_per_device,
    318       local_world_size=num_processes,
    319       fn=functools.partial(fn, *args, **kwargs),
    320       initializer_fn=_initialize_multiprocess)
    321   process_results = executor.map(mp_fn, range(num_processes))
--> 322   replica_results = list(
    323       itertools.chain.from_iterable(
    324           result.items() for result in process_results))
    326 if device_type() == 'GPU':
    327   gpu.shutdown_distributed_runtime()

File /usr/local/lib/python3.8/site-packages/torch_xla/experimental/pjrt.py:323, in <genexpr>(.0)
    316   mp_fn = functools.partial(
    317       _run_thread_per_device,
    318       local_world_size=num_processes,
    319       fn=functools.partial(fn, *args, **kwargs),
    320       initializer_fn=_initialize_multiprocess)
    321   process_results = executor.map(mp_fn, range(num_processes))
    322   replica_results = list(
--> 323       itertools.chain.from_iterable(
    324           result.items() for result in process_results))
    326 if device_type() == 'GPU':
    327   gpu.shutdown_distributed_runtime()

File /usr/local/lib/python3.8/concurrent/futures/process.py:484, in _chain_from_iterable_of_lists(iterable)
    478 def _chain_from_iterable_of_lists(iterable):
    479     """
    480     Specialized implementation of itertools.chain.from_iterable.
    481     Each item in *iterable* should be a list.  This function is
    482     careful not to keep references to yielded objects.
    483     """
--> 484     for element in iterable:
    485         element.reverse()
    486         while element:

File /usr/local/lib/python3.8/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield fs.pop().result()
    620     else:
    621         yield fs.pop().result(end_time - time.monotonic())

File /usr/local/lib/python3.8/concurrent/futures/_base.py:444, in Future.result(self, timeout)
    442     raise CancelledError()
    443 elif self._state == FINISHED:
--> 444     return self.__get_result()
    445 else:
    446     raise TimeoutError()

File /usr/local/lib/python3.8/concurrent/futures/_base.py:389, in Future.__get_result(self)
    387 if self._exception:
    388     try:
--> 389         raise self._exception
    390     finally:
    391         # Break a reference cycle with the exception in self._exception
    392         self = None

RuntimeError: tensorflow/compiler/xla/xla_client/pjrt_computation_client.cc:407 : Check failed: pjrt_device == pjrt_data->buffer->device() 
*** Begin stack trace ***
	tsl::CurrentStackTrace()
	xla::PjRtComputationClient::ExecuteComputation(xla::ComputationClient::Computation const&, absl::lts_20220623::Span<std::shared_ptr<xla::ComputationClient::Data> const>, std::string const&, xla::ComputationClient::ExecuteComputationOptions const&)
	torch_xla::XlaBackendImpl::ExecuteComputation(std::shared_ptr<torch::lazy::Computation>, c10::ArrayRef<std::shared_ptr<torch::lazy::BackendData> >, torch::lazy::BackendDevice const&) const
	
	torch::lazy::MultiWait::Complete(std::function<void ()> const&)
	
	
	
	__clone
*** End stack trace ***
TPU_0(process=0,(0,0,0,0)) vs TPU_1(process=0,(0,0,0,1))
````
I have tried it without wrapping the model then for  every iteration ram memory keeps leaking till it consumes all 300GB ram and the model has around 1B parameter  .

**Comment by JackCaoG** [comment]
@will-cromar can you help take a look?

**Comment by level14taken** [comment]
Hi, @will-cromar can you help on this.

**Comment by will-cromar** [comment]
Is it possible to provide the full notebook for us to look at? I'm especially interested to see why memory usage grows over multiple iterations when it's unwrapped.

To be honest, we should have probably retired `xmp.MpSerialExecutor` and `xmp.MpModelWrapper` with our legacy runtime XRT. These well predate my time on PyTorch/XLA, and I'm not even sure if they can work with the current runtime (PJRT). For sure, they only can do _anything_ when `start_method='fork'`, which is not the default (although it is required in notebooks). Instead, I recommend loading datasets and potentially parameters in the parent process and passing them to `xmp.spawn`. One of our examples shows an example with data loaders: https://github.com/pytorch/xla/blob/994f9fb6dcaddf22546402b4b5059e7972895c82/test/pjrt/test_train_hf_transformer.py#L163-L172

High host memory usage is unfortunately not avoidable with multiprocessing. But, if you can run a few steps and then the model OOMs, there is likely a memory leak. Even four copies of 1B parameters (`1B * 4 bytes = 4gb` assuming `float32`) should fit fine.

**Comment by level14taken** [comment]
Hi @will-cromar ,[here](https://www.kaggle.com/code/level14taken/bengali-main-pytorch/notebook) is the notebook with the data, try increasing dataset size,currently only 64 rows.
