### ISSUE TITLE
Our JIT passes barks with with PT JIT changes

### ISSUE THREAD

**Issue by dlibenzi** [pytorch/xla#570]
After https://github.com/pytorch/xla/pull/569 is in, we build, but now we have issues when running tests.

```
======================================================================
ERROR: test (__main__.TestMNIST)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_operations.py", line 607, in test
    self.compareModel(model, x)
  File "test/test_operations.py", line 209, in compareModel
    xla_model = xm.XlaModel(model, [input], full_conv_precision=True)
  File "/usr/local/google/home/dlibenzi/google-git/pytorch/xla/torch_xla_py/xla_model.py", line 599, in __init__
    self._model_fn, inputs, num_cores=self._num_cores, devices=devices)
  File "/usr/local/google/home/dlibenzi/google-git/pytorch/xla/torch_xla_py/xla_model.py", line 291, in create_xla_model
    xla_model(*inputs_xla)
RuntimeError: torch_xla/csrc/passes/remove_unused_forward_outputs.cpp:121 : Check failed: df_input_vjps_it != gradient->df_input_vjps.end() 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	torch::jit::RemoveUnusedForwardOutputs(torch::jit::Gradient*)
	torch_xla::XlaModule::ComputeGradient(std::shared_ptr<torch::jit::Graph> const&)
	torch_xla::XlaModule::Initialize(std::vector<std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >, std::allocator<std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> > > > const&)
	torch_xla::XlaModule::forward(std::vector<std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> >, std::allocator<std::vector<torch_xla::XLATensor, std::allocator<torch_xla::XLATensor> > > > const&)
```

After exporting TF_CPP_VMODULE we get:

```
Before RemoveUnusedForwardOutputs:
Forward:
graph(%input.2 : Float(32, 1, 28, 28),
      %1 : Float(10, 1, 5, 5),
      %2 : Float(10),
      %3 : Float(20, 10, 5, 5),
      %4 : Float(20),
      %weight.1 : Float(50, 320),
      %bias.1 : Float(50),
      %weight.2 : Float(10, 50),
      %bias : Float(10)):
  %9 : int[] = prim::Constant[value=[5, 5]]()
  %10 : int[] = prim::Constant[value=[1, 1]]()
  %11 : int[] = prim::Constant[value=[0, 0]]()
  %12 : Float(32, 10, 24, 24), %13 : Tensor, %14 : Tensor = aten::thnn_conv2d_forward(%input.2, %1, %9, %2, %10, %11)
  %15 : int[] = prim::Constant[value=[2, 2]]()
  %16 : int[] = prim::Constant[value=[]]()
  %19 : bool = prim::Constant[value=0](), scope: XlaMNIST
  %input.3 : Float(32, 10, 12, 12), %21 : Long(32, 10, 12, 12) = aten::max_pool2d_with_indices(%12, %15, %16, %11, %10, %19), scope: XlaMNIST
  %input.5 : Float(32, 10, 12, 12) = aten::relu(%input.3), scope: XlaMNIST
  %26 : Float(32, 20, 8, 8), %27 : Tensor, %28 : Tensor = aten::thnn_conv2d_forward(%input.5, %3, %9, %4, %10, %11)
  %input.6 : Float(32, 20, 4, 4), %35 : Long(32, 20, 4, 4) = aten::max_pool2d_with_indices(%26, %15, %16, %11, %10, %19), scope: XlaMNIST
  %x.1 : Float(32, 20, 4, 4) = aten::relu(%input.6), scope: XlaMNIST
  %37 : int[] = prim::Constant[value=[-1, 320]]()
  %input.8 : Float(32, 320) = aten::view(%x.1, %37), scope: XlaMNIST
  %self_size.2 : int[] = aten::size(%x.1)
  %39 : Float(320!, 50!) = aten::t(%weight.1), scope: XlaMNIST/Linear[fc1]
  %40 : Float(32, 50) = aten::mm(%input.8, %39), scope: XlaMNIST/Linear[fc1]
  %41 : int = prim::Constant[value=1]()
  %103 : int[] = aten::size(%bias.1)
  %106 : int[] = aten::size(%40)
  %42 : Float(32, 50) = aten::add(%bias.1, %40, %41), scope: XlaMNIST/Linear[fc1]
  %input.10 : Float(32, 50) = aten::relu(%42), scope: XlaMNIST
  %44 : Float(50!, 10!) = aten::t(%weight.2), scope: XlaMNIST/Linear[fc2]
  %45 : Float(32, 10) = aten::mm(%input.10, %44), scope: XlaMNIST/Linear[fc2]
  %63 : int[] = aten::size(%bias)
  %66 : int[] = aten::size(%45)
  %47 : Float(32, 10) = aten::add(%bias, %45, %41), scope: XlaMNIST/Linear[fc2]
  %49 : Float(32, 10) = aten::log_softmax(%47, %41), scope: XlaMNIST
  return (%49, %12, %13, %14, %21, %input.5, %26, %27, %28, %35, %x.1, %input.8, %self_size.2, %39, %103, %106, %input.10, %44, %63, %66, %47)

Backward:
graph(%0 : Float(32, 10),
      %1 : Float(32, 10, 24, 24),
      %2 : Float(32, 10, 12, 12),
      %3 : Float(32, 20, 8, 8),
      %4 : Float(32, 20, 4, 4),
      %5 : Float(32, 320),
      %6 : Float(320!, 50!),
      %7 : Float(32, 50),
      %8 : Float(50!, 10!),
      %9 : Float(32, 10),
      %input.1 : Float(32, 1, 28, 28),
      %11 : Float(10, 1, 5, 5),
      %12 : Float(20, 10, 5, 5),
      %13 : Float(32, 10, 24, 24),
      %14 : Tensor,
      %15 : Tensor,
      %16 : Long(32, 10, 12, 12),
      %input.4 : Float(32, 10, 12, 12),
      %18 : Float(32, 20, 8, 8),
      %19 : Tensor,
      %20 : Tensor,
      %21 : Long(32, 20, 4, 4),
      %x : Float(32, 20, 4, 4),
      %input.7 : Float(32, 320),
      %self_size.1 : int[],
      %25 : Float(320!, 50!),
      %26 : int[],
      %27 : int[],
      %input.9 : Float(32, 50),
      %29 : Float(50!, 10!),
      %30 : int[],
      %31 : int[],
      %32 : Float(32, 10),
      %33 : Float(32, 10)):
  %52 : int = prim::Constant[value=1]()
  %42 : int = prim::Constant[value=0]()
  %41 : int[] = prim::Constant[value=[2, 2]]()
  %40 : int[] = prim::Constant[value=[]]()
  %37 : bool = prim::Constant[value=0](), scope: XlaMNIST
  %36 : int[] = prim::Constant[value=[5, 5]]()
  %35 : int[] = prim::Constant[value=[1, 1]]()
  %34 : int[] = prim::Constant[value=[0, 0]]()
  %grad_self.1 : Tensor = aten::_log_softmax_backward_data(%0, %33, %52, %32)
  %126 : int = prim::Constant[value=1]()
  %127 : Float(32, 10) = aten::add(%9, %grad_self.1, %126)
  %61 : Tensor = aten::_grad_sum_to_size(%127, %30)
  %62 : Tensor = aten::mul(%127, %52)
  %63 : Tensor = aten::_grad_sum_to_size(%62, %31)
  %66 : Tensor = aten::t(%29)
  %grad_self.3 : Tensor = aten::mm(%63, %66)
  %68 : Tensor = aten::t(%input.9)
  %grad_mat2.1 : Tensor = aten::mm(%68, %63)
  %128 : int = prim::Constant[value=1]()
  %129 : Float(50, 10) = aten::add(%8, %grad_mat2.1, %128)
  %130 : int = prim::Constant[value=1]()
  %131 : Float(32, 50) = aten::add(%7, %grad_self.3, %130)
  %73 : Tensor = aten::t(%129)
  %146 : Tensor = aten::threshold_backward(%131, %input.9, %42)
  %80 : Tensor = aten::_grad_sum_to_size(%146, %26)
  %81 : Tensor = aten::mul(%146, %52)
  %82 : Tensor = aten::_grad_sum_to_size(%81, %27)
  %85 : Tensor = aten::t(%25)
  %grad_self.5 : Tensor = aten::mm(%82, %85)
  %87 : Tensor = aten::t(%input.7)
  %grad_mat2.3 : Tensor = aten::mm(%87, %82)
  %132 : int = prim::Constant[value=1]()
  %133 : Float(320, 50) = aten::add(%6, %grad_mat2.3, %132)
  %134 : int = prim::Constant[value=1]()
  %135 : Float(32, 320) = aten::add(%5, %grad_self.5, %134)
  %92 : Tensor = aten::t(%133)
  %94 : Tensor = aten::reshape(%135, %self_size.1)
  %136 : int = prim::Constant[value=1]()
  %137 : Float(32, 20, 4, 4) = aten::add(%4, %94, %136)
  %147 : Tensor = aten::threshold_backward(%137, %x, %42)
  %grad_self.7 : Tensor = aten::max_pool2d_with_indices_backward(%147, %18, %41, %40, %34, %35, %37, %21)
  %138 : int = prim::Constant[value=1]()
  %139 : Float(32, 20, 8, 8) = aten::add(%3, %grad_self.7, %138)
  %144 : bool[] = prim::Constant[value=[1, 1, 1]]()
  %grad_self.9 : Tensor, %grad_weight.1 : Tensor, %grad_bias.1 : Tensor = aten::thnn_conv2d_backward(%139, %input.4, %12, %36, %35, %34, %19, %20, %144)
  %140 : int = prim::Constant[value=1]()
  %141 : Float(32, 10, 12, 12) = aten::add(%2, %grad_self.9, %140)
  %148 : Tensor = aten::threshold_backward(%141, %input.4, %42)
  %grad_self.11 : Tensor = aten::max_pool2d_with_indices_backward(%148, %13, %41, %40, %34, %35, %37, %16)
  %142 : int = prim::Constant[value=1]()
  %143 : Float(32, 10, 24, 24) = aten::add(%1, %grad_self.11, %142)
  %145 : bool[] = prim::Constant[value=[1, 1, 1]]()
  %grad_self.13 : Tensor, %grad_weight.3 : Tensor, %grad_bias.3 : Tensor = aten::thnn_conv2d_backward(%143, %input.1, %11, %36, %35, %34, %14, %15, %145)
  return (%grad_weight.3, %grad_bias.3, %grad_weight.1, %grad_bias.1, %92, %80, %73, %61)

Removing output at index 3 from the forward graph
Removing output at index 2 from %12 : Float(32, 10, 24, 24), %13 : Tensor, %14 : Tensor = aten::thnn_conv2d_forward(%input.2, %1, %9, %2, %10, %11)

2019-04-06 02:50:37.040656: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: df_input_vjps_it != gradient->df_input_vjps.end() 
```

**Comment by dlibenzi** [comment]
This is fixed on the PT side. Closing.
