### ISSUE TITLE
Torchbench `speech_transformer` fails when calling `_get_graph_hash`.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/xla#5746]
## 🐛 Bug

Running the `speech_transformer` benchmark of Torchbench fails with the following error: 

```python
  File "torch/_dynamo/backends/torchxla.py", line 49, in fwd
    compiled_graph = bridge.extract_compiled_graph(model, args)
  File "xla/torch_xla/core/dynamo_bridge.py", line 552, in extract_compiled_graph
    extract_internal(fused_module), node.args, None)
  File "xla/torch_xla/core/dynamo_bridge.py", line 354, in extract_internal
    dumb_return_handler, xla_args_need_update) = extract_graph_helper(xla_model)
  File "xla/torch_xla/core/dynamo_bridge.py", line 285, in extract_graph_helper
    graph_hash = torch_xla._XLAC._get_graph_hash(args_and_out)
RuntimeError: ./torch_xla/csrc/runtime/pjrt_computation_client.h:134 : Check failed: HasValue()
*** Begin stack trace ***
        tsl::CurrentStackTrace[abi:cxx11]()
        torch_xla::runtime::PjRtComputationClient::PjRtData::GetHandle()
        torch::lazy::LazyGraphExecutor::RunPostOrder(std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&, torch::lazy::LazyGraphExecutor::SyncTensorCollection*)
        torch_xla::XLAGraphExecutor::RunPostOrder(std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&, torch::lazy::LazyGraphExecutor::SyncTensorCollection*)
        torch_xla::XLAGraphExecutor::GetGraphHash(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&)
```

<details>
<summary>Raw Output</summary>

```
ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "benchmarks/dynamo/common.py", line 2462, in warmup
    fn(model, example_inputs)
  File "torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/torchbench.py", line 508, in forward_pass
    return mod(*inputs)
  File "torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "torchbenchmark/models/speech_transformer/speech_transformer/transformer/transformer.py", line 28, in forward
    encoder_padded_outputs, *_ = self.encoder(padded_input, input_lengths)
  File "torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "torchbenchmark/models/speech_transformer/speech_transformer/transformer/encoder.py", line 48, in forward
    non_pad_mask = get_non_pad_mask(padded_input, input_lengths=input_lengths)
  File "torchbenchmark/models/speech_transformer/speech_transformer/transformer/encoder.py", line 50, in <resume in forward>
    slf_attn_mask = get_attn_pad_mask(padded_input, input_lengths, length)
  File "torchbenchmark/models/speech_transformer/speech_transformer/utils/utils.py", line 140, in get_attn_pad_mask
    non_pad_mask = get_non_pad_mask(padded_input, input_lengths=input_lengths)
  File "torchbenchmark/models/speech_transformer/speech_transformer/utils/utils.py", line 140, in <resume in get_attn_pad_mask>
    non_pad_mask = get_non_pad_mask(padded_input, input_lengths=input_lengths)
  File "torch/_dynamo/eval_frame.py", line 401, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3921, in forward
    return compiled_fn(full_args)
  File "torch/_functorch/aot_autograd.py", line 1498, in g
    return f(*args)
  File "torch/_functorch/aot_autograd.py", line 2549, in runtime_wrapper
    all_outs = call_func_with_args(
  File "torch/_functorch/aot_autograd.py", line 1522, in call_func_with_args
    out = normalize_as_list(f(args))
  File "torch/_functorch/aot_autograd.py", line 1610, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "torch/_functorch/aot_autograd.py", line 1498, in g
    return f(*args)
  File "torch/_dynamo/backends/torchxla.py", line 49, in fwd
    compiled_graph = bridge.extract_compiled_graph(model, args)
  File "xla/torch_xla/core/dynamo_bridge.py", line 552, in extract_compiled_graph
    extract_internal(fused_module), node.args, None)
  File "xla/torch_xla/core/dynamo_bridge.py", line 354, in extract_internal
    dumb_return_handler, xla_args_need_update) = extract_graph_helper(xla_model)
  File "xla/torch_xla/core/dynamo_bridge.py", line 285, in extract_graph_helper
    graph_hash = torch_xla._XLAC._get_graph_hash(args_and_out)
RuntimeError: ./torch_xla/csrc/runtime/pjrt_computation_client.h:134 : Check failed: HasValue()
*** Begin stack trace ***
        tsl::CurrentStackTrace[abi:cxx11]()
        torch_xla::runtime::PjRtComputationClient::PjRtData::GetHandle()
        torch::lazy::LazyGraphExecutor::RunPostOrder(std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&, torch::lazy::LazyGraphExecutor::SyncTensorCollection*)
        torch_xla::XLAGraphExecutor::RunPostOrder(std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&, torch::lazy::LazyGraphExecutor::SyncTensorCollection*)
        torch_xla::XLAGraphExecutor::GetGraphHash(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&)







        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault



        PyObject_Call
        _PyEval_EvalFrameDefault


        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyObject_FastCallDictTstate
        _PyObject_Call_Prepend

        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault



        PyObject_Call
        _PyEval_EvalFrameDefault


        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyObject_FastCallDictTstate
        _PyObject_Call_Prepend

        PyObject_Call
        _PyEval_EvalFrameDefault



        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        PyEval_EvalCode



        _PyRun_SimpleFileObject
        _PyRun_AnyFileObject
        Py_RunMain
        Py_BytesMain

        __libc_start_main

*** End stack trace ***
buffer with shape f32[10,204] on device CPU:0 is null
```

</details>

## To Reproduce

Run the `speech_transformer` benchmark with `openxla` backend:

```bash
$ PJRT_DEVICE=CPU python benchmarks/dynamo/torchbench.py --performance --trace-on-xla --backend=openxla --inference --only speech_transformer
```

## Environment

 - PyTorch: 2bf3ca1be759460cf9fbf011d96d3246001361e9 (Oct 4)
 - PyTorch/XLA: 5dfcec90ca2dd33d2361adf981677cc0978186fa (Oct 21)
 - PyTorch/benchmark: bb5275f819d479baacd24fe96000474355586096 (Oct 4)

**Comment by ysiraichi** [comment]
While investigating this issue, I ended up in [this part of `LazyGraphExecutor::RunPostOrder`](https://github.com/pytorch/pytorch/blob/b165abaa3b5b2f81fcd69c1060e651aabe38e574/torch/csrc/lazy/core/lazy_graph_executor.cpp#L719-L722). The conditional `TensorCollectionBarrier` doesn't make the result of `backend_data->HasValue()` change.

**Comment by JackCaoG** [comment]
yea.. this is one of the most common failure of the dynamo.. it pretty much complains that one of the value requested by dynamo is null and it can't trace through it. I fixed a similar issue in https://github.com/pytorch/xla/issues/5410.

One thing you can try is to replace the 
https://github.com/pytorch/xla/blob/595ebcf05c08b842050757d628033b104ed3c98f/torch_xla/core/dynamo_bridge.py#L503
with a 
```
xm.mark_step()
```
This will produce incorrect output but might help you naivgate the issue. The idea is that while we are dry running the model to generate the trace, we created a bunch of IRs and assign them to tensors. We don't want to execute these IRs since real model code hasn't happen yet. Hence we call `clear_pending_irs` to remove all of the IRs. We saved the old values of inputs and perform a clone after tracing is done, so ideally input of the model was restored and IR cleaning wouldn't impact them.

**Comment by ysiraichi** [comment]
Interesting... After the change you suggested, we seemed to hit the same [storage bug](https://github.com/pytorch/pytorch/issues/111506). Applying the fix for that one, this one starts working. But, if we revert the change you suggested, it stops working with the same error.

**Comment by JackCaoG** [comment]
Hmm ok I think you can refer to https://github.com/pytorch/xla/issues/5410#issuecomment-1666284519 for how to debug this issue(you can turn on debugging message by 
```
alias cpplog="TF_CPP_MIN_LOG_LEVEL=0 TF_CPP_VMODULE=\"xla_graph_executor=5,pjrt_computation_client=3\""
```
)

I think what happened is that `ClearPendingIr` clear the tensor it shouldn't have, and the reason is that tensor that's suppose to have no IR(one of the input tensor) somehow still carries a non-DeviceData IR after `clone` before the `ClearPendingIr`. The key is to find that tensor and what ir does it carry. I can provide more debugging tips if you run into any problems.

**Comment by ysiraichi** [comment]
Got it. Thanks for the tips. I will see if I can find the issue.

**Comment by JackCaoG** [comment]
one tip, you can use 
```
print(torch_xla._XLAC._get_xla_tensors_text([tensor]))
```
to inspect the IR attached to the current Tensor. for example after `y = x + 1`, you should see a `add` IR attached to the `y`

**Comment by ysiraichi** [comment]
Yes. I was doing that, but I don't think I was able to extract any meaningful information from there:

```
IR {
  %0 = s64[] prim::Constant(), xla_shape=s64[], value=1
  %1 = f32[10,204]{1,0} xla::device_data(), xla_shape=f32[10,204]{1,0}, device=CPU:0
  %2 = f32[10,204,1]{2,1,0} aten::view(%1), xla_shape=f32[10,204,1]{2,1,0}, output_size=(10, 204, 1)
  %3 = f32[10,204]{1,0} aten::view(%2), xla_shape=f32[10,204]{1,0}, output_size=(10, 204)
  %4 = pred[10,204]{1,0} aten::lt(%3, %0), xla_shape=pred[10,204]{1,0}
  %5 = pred[10,1,204]{2,1,0} aten::view(%4), xla_shape=pred[10,1,204]{2,1,0}, output_size=(10, 1, 204)
  %6 = pred[10,204,204]{2,1,0} aten::expand(%5), xla_shape=pred[10,204,204]{2,1,0}, size=(10, 204, 204), ROOT=0
}
```

I believe `%1` is the one that's null.

**Comment by JackCaoG** [comment]
you want to read this as a sequence of ops happened, the final IR got attached to this tensor is a `expand` IR with shape `[10,204,204]` and the type `pred` means boolean.

**Comment by JackCaoG** [comment]
There is another api you can used that give you more info
https://github.com/pytorch/xla/blob/944136faf6bbb7022da957fc3ac637d583d13ed6/torch_xla/csrc/init_python_bindings.cpp#L942-L945
