### ISSUE TITLE
Error with simple Linear GSPMD example

### ISSUE THREAD

**Issue by aws-murandoo** [pytorch/xla#5798]
## 🐛 Bug

We see the following error when running a simple linear example. We loosely follow: https://pytorch.org/blog/pytorch-xla-spmd/ but simplify it further.
```
Traceback (most recent call last):
  File "test2.py", line 55, in <module>
    print(t3)
  File "/shared_2/murandoo/aws_neuron_venv_pytorch/lib/python3.8/site-packages/torch_xla/experimental/xla_sharded_tensor.py", line 134, in __repr__
    return f"XLAShardedTensor({self.global_tensor})"
AttributeError: global_tensor
```

## To Reproduce

test.py:
```
import numpy as np
import os
os.environ["XLA_FLAGS"]="--xla_force_host_platform_device_count=32"
import torch
import torch_xla
import torch_xla.runtime as xr
# Enable XLA SPMD execution mode.
xr.use_spmd()

import torch_xla.experimental.xla_sharding as xs
from torch_xla.experimental.xla_sharding import Mesh
from torch_xla.experimental.xla_sharded_tensor import XLAShardedTensor
import torch_xla.core.xla_model as xm
import torch_xla.experimental.pjrt_backend
import torch_xla.experimental.pjrt as pjrt

num_devices = xr.global_runtime_device_count()
print(f'num device: {num_devices}')
mesh_shape = (32, 1)
device_ids = np.array(range(num_devices))
# axis_names 'x' and 'y' are optional
mesh = Mesh(device_ids, mesh_shape, ('x', 'y'))
partition_spec = (1, 0)
lin = torch.nn.Linear(32, 32).to(xm.xla_device())
xs.mark_sharding(lin.weight, mesh, partition_spec)
lin.train()

print(mesh.get_logical_mesh(), mesh.shape())

t1 = torch.randn(64, 32).to(xm.xla_device())
t2 = torch.randn(64, 32).to(xm.xla_device())

m1_sharded = xs.mark_sharding(t1, mesh, partition_spec)
m2_sharded = xs.mark_sharding(t2, mesh, partition_spec)

assert isinstance(m1_sharded, XLAShardedTensor) == True
assert isinstance(m2_sharded, XLAShardedTensor) == True

t3 = (m1_sharded + m2_sharded)
t3 = lin(m1_sharded)

print(t3)
```

1. Create `test.py` above
2. Run `CPU_NUM_DEVICES=32 python test.py`

## Expected behavior

Linear sharding works without errors.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CPU
 - torch_xla version: 2.1.0

**Comment by JackCaoG** [comment]
@yeounoh can you take a look?

**Comment by yeounoh** [comment]
Thanks @aws-murandoo , will take a look.

**Comment by yeounoh** [comment]
This is a bug, 
```
# WORKS
lin(t1)= tensor([[-0.1627,  0.1749, -0.8895,  ..., -0.1114,  0.3500, -0.7123],
        [-0.2934, -0.2865,  1.6864,  ...,  0.0766, -1.6279,  0.2955],
        [-0.4232, -0.5505,  0.7643,  ...,  0.5106,  0.0519, -0.3720],
        ...,
        [-0.4711,  0.3183,  0.6648,  ...,  0.2909,  0.1764,  0.5686],
        [-0.9641, -0.0448, -1.0625,  ..., -0.5837, -0.4017,  0.4089],
        [-0.5841,  0.0312, -0.4924,  ..., -0.7154, -0.7351, -0.0622]],
       device='xla:0', grad_fn=<AddmmBackward0>)

# WORKS
lin(m1_sharded.global_tensor)= tensor([[-0.1627,  0.1749, -0.8895,  ..., -0.1114,  0.3500, -0.7123],
        [-0.2934, -0.2865,  1.6864,  ...,  0.0766, -1.6279,  0.2955],
        [-0.4232, -0.5505,  0.7643,  ...,  0.5106,  0.0519, -0.3720],
        ...,
        [-0.4711,  0.3183,  0.6648,  ...,  0.2909,  0.1764,  0.5686],
        [-0.9641, -0.0448, -1.0625,  ..., -0.5837, -0.4017,  0.4089],
        [-0.5841,  0.0312, -0.4924,  ..., -0.7154, -0.7351, -0.0622]],
       device='xla:0', grad_fn=<AddmmBackward0>)

# DOESN'T WORK (BUG)
lin(m1_sharded)= Traceback (most recent call last):
  File "aws_test.py", line 49, in <module>
    print('lin(m1_sharded)=',t6)
  File "/home/yeounoh/anaconda3/envs/ptxla/lib/python3.8/site-packages/torch_xla-2.2.0+gitf94549b-py3.8-linux-x86_64.egg/torch_xla/distributed/spmd/xla_sharded_tensor.py", line 145, in __repr__
    return f"XLAShardedTensor({self.global_tensor})"
AttributeError: global_tensor
```

I will start debugging..

**Comment by aws-murandoo** [comment]
Thanks @yeounoh!

**Comment by yeounoh** [comment]
Hi @aws-murandoo I raised a fix, I was able to verify locally -- you can verify & close this issue after we land the patch. Thank you!
```
(base) yeounoh@t1v-n-2a0f41b4-w-0:~/dev/tmp$ PJRT_DEVICE=CPU python aws_test.py 
/home/yeounoh/dev/tmp/aws_test.py:10: DeprecationWarning: Importing from `torch_xla.experimental.xla_sharding` will be deprecated after 2.2 release. Please use `torch_xla.distributed.spmd` instead.
  import torch_xla.experimental.xla_sharding as xs
/home/yeounoh/dev/tmp/aws_test.py:12: DeprecationWarning: Importing from `torch_xla.experimental.xla_sharded_tensor` will be deprecated after 2.2 release. Please use `torch_xla.distributed.spmd` instead.
  from torch_xla.experimental.xla_sharded_tensor import XLAShardedTensor
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1700083416.458859   32426 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
num device: 1
mesh:
 [0] OrderedDict([('x', 1)])
(m1_sharded + m2_sharded)= XLAShardedTensor(tensor([[ 2.6601, -1.9906, -1.3094,  ...,  2.0952, -0.6005,  2.5800],
        [-0.1253,  0.5206,  0.2982,  ...,  0.7766,  0.0412,  1.3814],
        [-3.6001,  1.3288,  2.3647,  ..., -0.4499, -2.8891,  0.7890],
        ...,
        [-1.5495, -0.3257,  0.4832,  ..., -0.6085, -0.3236, -0.0455],
        [-1.9271,  2.5754, -1.2992,  ..., -0.1672,  2.1612, -0.1506],
        [ 1.1939,  2.8743,  0.4919,  ..., -0.0972, -3.0733,  0.8859]],
       device='xla:0'))
lin(m1_sharded.global_tensor)= tensor([[ 0.4747, -0.5474,  0.1255,  ..., -0.4364,  0.9692, -1.0440],
        [ 0.1968, -1.1348, -0.5825,  ..., -0.5679,  0.7670, -0.3792],
        [ 0.4564,  0.0344, -0.7997,  ..., -0.0427,  0.5244,  1.0804],
        ...,
        [ 0.0116,  0.1621, -0.2571,  ..., -0.3676, -0.8315,  0.6257],
        [-0.3139, -0.4784, -0.5908,  ..., -0.1554,  0.5359,  1.3356],
        [ 0.2534,  0.0584, -0.0604,  ...,  0.5093, -0.2703,  1.2010]],
       device='xla:0', grad_fn=<AddmmBackward0>)
lin(m1_sharded)= XLAShardedTensor(tensor([[ 0.4747, -0.5474,  0.1255,  ..., -0.4364,  0.9692, -1.0440],
        [ 0.1968, -1.1348, -0.5825,  ..., -0.5679,  0.7670, -0.3792],
        [ 0.4564,  0.0344, -0.7997,  ..., -0.0427,  0.5244,  1.0804],
        ...,
        [ 0.0116,  0.1621, -0.2571,  ..., -0.3676, -0.8315,  0.6257],
        [-0.3139, -0.4784, -0.5908,  ..., -0.1554,  0.5359,  1.3356],
        [ 0.2534,  0.0584, -0.0604,  ...,  0.5093, -0.2703,  1.2010]]))
I0000 00:00:1700083416.753091   32426 tfrt_cpu_pjrt_client.cc:352] TfrtCpuClient destroyed.

```

**Comment by aws-murandoo** [comment]
Thanks for the quick turnaround @yeounoh!

**Comment by aws-murandoo** [comment]
Works when patched locally, closing.
