### ISSUE TITLE
No support for overlapped tensors.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/xla#5835]
## 🐛 Bug

The following code tries to create an overlapped tensor with 6 elements out of a tensor with 5 elements. e.g. Given the tensor `[1, 2, 3, 4, 5]`, it tries to create a 2D tensor `[[1, 2, 3], [3, 4, 5]]`, where the element `3` is overlapped.

```python
import torch
import torch_xla.core.xla_model as xm

device = xm.xla_device()
x = torch.arange(5, device=device)
r = x.as_strided((2, 3), (2, 1), 0)

print(r)
```

```python
Traceback (most recent call last):
  File "examples/bug-longformer.py", line 10, in <module>
    print(foo(x))
  File "torch/_tensor.py", line 442, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "torch/_tensor_str.py", line 664, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "torch/_tensor_str.py", line 430, in _str_intern
    self = self.to("cpu")
RuntimeError: Error while lowering: [] aten::as_strided, xla_shape=s64[2,3]{1,0}, size=(2, 3), stride=(2, 1), storage_offset=0
Error: torch_xla/csrc/ops/as_strided.cpp:26 : Check failed: storage_offset + slice_size <= input_element_count (6 vs. 5)
```

<details>
<summary>Full Error Dump</summary>

```python
Traceback (most recent call last):
  File "examples/bug-longformer.py", line 10, in <module>
    print(foo(x))
  File "torch/_tensor.py", line 442, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "torch/_tensor_str.py", line 664, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "torch/_tensor_str.py", line 430, in _str_intern
    self = self.to("cpu")
RuntimeError: Error while lowering: [] aten::as_strided, xla_shape=s64[2,3]{1,0}, size=(2, 3), stride=(2, 1), storage_offset=0
Error: torch_xla/csrc/ops/as_strided.cpp:26 : Check failed: storage_offset + slice_size <= input_element_count (6 vs. 5)
*** Begin stack trace ***
        tsl::CurrentStackTrace[abi:cxx11]()

        torch_xla::AsStrided::Lower(torch_xla::LoweringContext*) const
        torch_xla::LoweringContext::LowerNode(torch::lazy::Node const*)
        torch_xla::LoweringContext::LoweringContext(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, torch::lazy::BackendDevice, c10::ArrayRef<torch::lazy::Node const*>, std::unordered_map<torch::lazy::Node const*, torch::lazy::Util::EmitStatus, std::hash<torch::lazy::Node const*>, std::equal_to<torch::lazy::Node const*>, std::allocator<std::pair<torch::lazy::Node const* const, torch::lazy::Util::EmitStatus> > >)
        torch_xla::XLAGraphExecutor::Compile(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&, absl::lts_20230125::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch::lazy::LazyGraphExecutor::SyncTensorCollection const&, torch::lazy::LazyGraphExecutor::PostOrderData*, std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&)
        torch_xla::XLAGraphExecutor::SyncTensorsGraphInternal(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230125::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, torch::lazy::LazyGraphExecutor::SyncTensorsConfig const&, bool)
        torch_xla::XLAGraphExecutor::SyncTensorsGraph(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230125::Span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, bool, bool, bool)
        torch_xla::XLATensor::ApplyPendingGraph()
        torch_xla::XLATensor::GetXlaData()
        torch_xla::XLATensor::ToTensor(bool)
        torch_xla::XLANativeFunctions::_to_copy(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>)


        at::_ops::_to_copy::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>)

        at::_ops::_to_copy::call(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>)


        at::_ops::_to_copy::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>)


        at::_ops::_to_copy::call(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, c10::optional<c10::MemoryFormat>)
        at::native::to(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, bool, c10::optional<c10::MemoryFormat>)

        at::_ops::to_dtype_layout::call(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, bool, c10::optional<c10::MemoryFormat>)
        at::Tensor::to(c10::TensorOptions, bool, bool, c10::optional<c10::MemoryFormat>) const



        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall


        PyObject_Str
        PyFile_WriteObject


        _PyEval_EvalFrameDefault

        PyEval_EvalCode



        _PyRun_SimpleFileObject
        _PyRun_AnyFileObject
        Py_RunMain
        Py_BytesMain

        __libc_start_main

*** End stack trace ***
```

</details>

If we replace `x` by a tensor with 6 elements (storage with capacity for 6 elements), PyTorch/XLA no longer breaks. However, it does give an incorrect result:

```python
# CPU
tensor([[0, 1, 2],
        [2, 3, 4]])

# Eager
tensor([[0, 1, 2],
        [3, 4, 5]], device='xla:0')
```

Dynamo also has the same problem.

## Affected Benchmark

`hf_Longformer` 

## Environment

 - PyTorch version: `63fc48257a02f8e28b79d13def7a7139589d4176` (Nov 2)
 - PyTorch/XLA version: `d5d023063bfa8ecb4629f621f9b5890bc8396f58` (Nov 9)

## Additional context

This issue gets to the same error as #5719. However, the cause seems to be different.

**Comment by ysiraichi** [comment]
cc @JackCaoG @miladm

**Comment by JackCaoG** [comment]
can you print the IR for the `r`? I suspect reshape and slicing  is being done incorrectly.

**Comment by ysiraichi** [comment]
This is the IR when the source tensor has 6 elements:

```python
IR {
  %0 = s64[6]{0} xla::device_data(), xla_shape=s64[6]{0}, device=CPU:0
  %1 = s64[2,3]{1,0} aten::as_strided(%0), xla_shape=s64[2,3]{1,0}, size=(2, 3), stride=(2, 1), storage_offset=0, ROOT=0
}
```

Looks fine to me. But, I don't think we actually use the stride's value when lowering, do we? As far as I can see, we only use them to find a permutation where the strides will be in increasing order. Does XLA itself support overlapped tensors?

**Comment by JackCaoG** [comment]
more ever, I think pytorch using the overlapping storget to achieve 2 things
1. save memory space
2. storage can be updated multiple times 

for 1 it doesn't really applied to XLA, we won't save any memory. For 2 I think it should be taking care of by the functionization.

**Comment by ysiraichi** [comment]
```python
HloModule IrToHlo.4, entry_computation_layout={()->(s64[2,3]{1,0})}

ENTRY %IrToHlo.4 () -> (s64[2,3]) {
  %constant.1 = s64[6]{0} constant({0, 1, 2, 3, 4, 5})
  %reshape.2 = s64[2,3]{1,0} reshape(s64[6]{0} %constant.1)
  ROOT %tuple.3 = (s64[2,3]{1,0}) tuple(s64[2,3]{1,0} %reshape.2)
}
```

> Overlapping storage is possible, we can do something like clone the input x times and then slice the intended part and then concat them.

Yes. I was thinking this could be a solution.

**Comment by JackCaoG** [comment]
yea lol, it pretty much just reshape `s64[6]` to `s64[2,3]`.. I guess current lowering does not support compilcated slice and concat.

**Comment by JackCaoG** [comment]
let's debug a bit https://github.com/pytorch/xla/blob/2b04794a95d9e2be360e2ff6dea83c87e98b892e/torch_xla/csrc/ops/as_strided.cpp#L20-L42

Worse case we should throw a error instead of return an incorrect tensor.

**Comment by ysiraichi** [comment]
I was thinking, as you suggested, we could create a new tensor of the size requested [2, 3] and gather the values as needed when building the IR (instead of lowering).

**Comment by JackCaoG** [comment]
it is better to do that in the lowering, that way at least IR is clean(just a as_stride), otherwise when we try to understand the IR it becomes confusing. You can try your idea first and see how it turn out.
