### ISSUE TITLE
[Core ATen Opset] Lower aten__native_batch_norm_legit

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#5880]
In order for PyTorch/XLA to support the PyTorch core ATen opset, it requires lowering each core ATen op in PyTorch/XLA. This issue is used to track the PyTorch/XLA lowering for **aten__native_batch_norm_legit**.

Here are some general guidelines to lowering this op:
  - Uncomment `@unittest.skip` or `@unittest.expectFailure` and run the unit test at [test_core_aten_ops.py](https://github.com/pytorch/xla/blob/master/test/test_core_aten_ops.py). Eg: `pytest test/test_core_aten_ops.py -k test_aten__native_batch_norm_legit_0`
  - Make code changes until the test passes. Read and follow [fix_lowering_for_core_aten_ops.md](https://github.com/pytorch/xla/blob/master/FIX_LOWERING_FOR_CORE_ATEN_OPS.md) for ideas to fix.
    - There may be multiple unit tests for a single op. For this op, the corresponding unit tests are:
      - test_aten__native_batch_norm_legit_0
      - test_aten__native_batch_norm_legit_1
    - Please also uncomment the skips for all these tests and ensure all tests are fixed.
    - Note that sometimes the fix may be to fix the unit tests itself. Please take a look at the corresponding unit tests to make sure the tests are valid.
  - Submit the PR!

For any questions, feel free to leave a comment in this PR.

**Comment by wonjoolee95** [comment]
The `aten__native_batch_norm_legit ` tests are failing due to:
```
======================================================================
ERROR: test_aten__native_batch_norm_legit_0 (__main__.AtenOpTest) [stablehlo_can_run]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wonjoo/pytorch/xla/test/test_core_aten_ops.py", line 68, in run_export_and_compare
    res2 = shlo(*args, **kwargs)
  File "/home/wonjoo/pytorch/xla/torch_xla/stablehlo.py", line 110, in __call__
    return self.evaluate(self._default_method, args)
  File "/home/wonjoo/pytorch/xla/torch_xla/stablehlo.py", line 86, in evaluate
    res = pytree.tree_unflatten(res, out_spec)
  File "/home/wonjoo/miniconda3/lib/python3.10/site-packages/torch/utils/_pytree.py", line 818, in tree_unflatten
    return treespec.unflatten(leaves)
  File "/home/wonjoo/miniconda3/lib/python3.10/site-packages/torch/utils/_pytree.py", line 736, in unflatten
    raise ValueError(
ValueError: treespec.unflatten(leaves): `leaves` has length 5 but the spec refers to a pytree that holds 3 items (TreeSpec(tuple, None, [*,
  *,
  *])).
```
According to https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml#L4264, the return type should be `<Tensor, Tensor, Tensor>`. However, the `res` in stablehlo.py (at https://github.com/pytorch/xla/blob/master/torch_xla/stablehlo.py#L80C27-L80C41) returns an output of 5 tensors, hence, the error.

cc @qihqi, do you know why the stablehlo behavior thinks that the output contains 5 tensors?

**Comment by wonjoolee95** [comment]
Closed with https://github.com/pytorch/xla/pull/6580
