### ISSUE TITLE
[Core ATen Opset] Lower aten_topk

### ISSUE THREAD

**Issue by wonjoolee95** [pytorch/xla#5904]
In order for PyTorch/XLA to support the PyTorch core ATen opset, it requires lowering each core ATen op in PyTorch/XLA. This issue is used to track the PyTorch/XLA lowering for **aten_topk**.

Here are some general guidelines to lowering this op:
  - Uncomment `@unittest.skip` or `@unittest.expectFailure` and run the unit test at [test_core_aten_ops.py](https://github.com/pytorch/xla/blob/master/test/test_core_aten_ops.py). Eg: `pytest test/test_core_aten_ops.py -k test_aten_topk_0`
  - Make code changes until the test passes. Read and follow [fix_lowering_for_core_aten_ops.md](https://github.com/pytorch/xla/blob/master/FIX_LOWERING_FOR_CORE_ATEN_OPS.md) for ideas to fix.
    - There may be multiple unit tests for a single op. For this op, the corresponding unit tests are:
      - test_aten_topk_3
    - Please also uncomment the skips for all these tests and ensure all tests are fixed.
    - Note that sometimes the fix may be to fix the unit tests itself. Please take a look at the corresponding unit tests to make sure the tests are valid.
  - Submit the PR!

For any questions, feel free to leave a comment in this PR.

**Comment by wonjoolee95** [comment]
Had a sync with @ManfeiBai, to make the `aten::topk` core aten op test succeed:
1. Run the core_aten_op unit test and put the failure here. My guess is that native PyTorch converts the output into floating type even when input type if integer, but PyTorch/XLA doesn't do that.
2. If our guess from 1) is correct, then we have to add a manual dtype conversion. However, this op is not codegened, so it might be little tricky. You can probably do a manual dtype conversion here: https://github.com/pytorch/xla/blob/master/torch_xla/csrc/xla_lower_util.cpp#L358. Or maybe even a layer above. You can take a look and decide which layer to do it.

**Comment by ManfeiBai** [comment]
Thanks, @wonjoolee95,

- tested locally for failure:
```
(torch310) root@cb1bb455239f:~/pytorch/xla# pytest test/test_core_aten_ops.py -k test_aten_topk_0
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/pytorch
configfile: pytest.ini
plugins: hypothesis-6.92.2
collected 522 items / 521 deselected / 1 selected                              

test/test_core_aten_ops.py .                                             [100%]

====================== 1 passed, 521 deselected in 7.87s =======================
(torch310) root@cb1bb455239f:~/pytorch/xla# pytest test/test_core_aten_ops.py -k test_aten_topk_1
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/pytorch
configfile: pytest.ini
plugins: hypothesis-6.92.2
collected 522 items / 521 deselected / 1 selected                              

test/test_core_aten_ops.py .                                             [100%]

====================== 1 passed, 521 deselected in 6.89s =======================
(torch310) root@cb1bb455239f:~/pytorch/xla# pytest test/test_core_aten_ops.py -k test_aten_topk_2
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/pytorch
configfile: pytest.ini
plugins: hypothesis-6.92.2
collected 522 items / 521 deselected / 1 selected                              

test/test_core_aten_ops.py F                                             [100%]

=================================== FAILURES ===================================
_________________________ AtenOpTest.test_aten_topk_2 __________________________
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 4466, in test_aten_topk_2
    run_export_and_compare(self, torch.ops.aten.topk, args, kwargs)
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 72, in run_export_and_compare
    diff_output(
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 40, in diff_output
    diff_output(testcase, o1, o2, rtol, atol)
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 33, in diff_output
    testcase.assertTrue(
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
------------------------------ Captured log call -------------------------------
WARNING  root:runtime.py:41 PJRT is now the default runtime. For more information, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING  root:runtime.py:45 libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
=========================== short test summary info ============================
FAILED test/test_core_aten_ops.py::AtenOpTest::test_aten_topk_2 - AssertionError: False is not true
====================== 1 failed, 521 deselected in 6.42s =======================
(torch310) root@cb1bb455239f:~/pytorch/xla# 
```

**Comment by ManfeiBai** [comment]
capatured output are:
```
(torch310) root@cb1bb455239f:~/pytorch/xla# pytest test/test_core_aten_ops.py -k test_aten_topk_2
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/pytorch
configfile: pytest.ini
plugins: hypothesis-6.92.2
collected 522 items / 521 deselected / 1 selected                              

test/test_core_aten_ops.py F                                             [100%]

=================================== FAILURES ===================================
_________________________ AtenOpTest.test_aten_topk_2 __________________________
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 4468, in test_aten_topk_2
    run_export_and_compare(self, torch.ops.aten.topk, args, kwargs)
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 74, in run_export_and_compare
    diff_output(
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 42, in diff_output
    diff_output(testcase, o1, o2, rtol, atol)
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 35, in diff_output
    testcase.assertTrue(
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
----------------------------- Captured stdout call -----------------------------
output1:  tensor([[0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [2],
        [2]], dtype=torch.int32)
output2:  tensor([[0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [2],
        [2]], device='xla:0', dtype=torch.int32)
output1:  tensor([[3],
        [0],
        [9],
        [3],
        [9],
        [0],
        [5],
        [9],
        [0],
        [9]])
output2:  tensor([[3],
        [0],
        [9],
        [3],
        [4],
        [0],
        [5],
        [3],
        [0],
        [2]], device='xla:0')
------------------------------ Captured log call -------------------------------
WARNING  root:runtime.py:41 PJRT is now the default runtime. For more information, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING  root:runtime.py:45 libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
=========================== short test summary info ============================
FAILED test/test_core_aten_ops.py::AtenOpTest::test_aten_topk_2 - AssertionError: False is not true
====================== 1 failed, 521 deselected in 6.57s =======================
(torch310) root@cb1bb455239f:~/pytorch/xla# 
```

**Comment by ManfeiBai** [comment]
modify successed test to test with int32, failed with the same error:
```
(torch310) root@cb1bb455239f:~/pytorch/xla# pytest test/test_core_aten_ops.py -k test_aten_topk_1
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/pytorch
configfile: pytest.ini
plugins: hypothesis-6.92.2
collected 522 items / 521 deselected / 1 selected                              

test/test_core_aten_ops.py F                                             [100%]

=================================== FAILURES ===================================
_________________________ AtenOpTest.test_aten_topk_1 __________________________
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 4457, in test_aten_topk_1
    run_export_and_compare(self, torch.ops.aten.topk, args, kwargs)
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 74, in run_export_and_compare
    diff_output(
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 42, in diff_output
    diff_output(testcase, o1, o2, rtol, atol)
  File "/root/pytorch/xla/test/test_core_aten_ops.py", line 35, in diff_output
    testcase.assertTrue(
  File "/root/miniconda3/envs/torch310/lib/python3.10/unittest/case.py", line 687, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
----------------------------- Captured stdout call -----------------------------
output1:  tensor([[-2],
        [-1],
        [-1],
        [ 0],
        [-1],
        [ 0],
        [-1],
        [-1],
        [-2],
        [ 0]], dtype=torch.int32)
output2:  tensor([[-2],
        [-1],
        [-1],
        [ 0],
        [-1],
        [ 0],
        [-1],
        [-1],
        [-2],
        [ 0]], device='xla:0', dtype=torch.int32)
output1:  tensor([[7],
        [6],
        [1],
        [8],
        [6],
        [6],
        [8],
        [2],
        [4],
        [8]])
output2:  tensor([[7],
        [6],
        [1],
        [0],
        [6],
        [1],
        [0],
        [2],
        [4],
        [0]], device='xla:0')
------------------------------ Captured log call -------------------------------
WARNING  root:runtime.py:41 PJRT is now the default runtime. For more information, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING  root:runtime.py:45 libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
=========================== short test summary info ============================
FAILED test/test_core_aten_ops.py::AtenOpTest::test_aten_topk_1 - AssertionError: False is not true
====================== 1 failed, 521 deselected in 6.56s =======================
(torch310) root@cb1bb455239f:~/pytorch/xla# git diff
diff --git a/test/test_core_aten_ops.py b/test/test_core_aten_ops.py
index 0e7e665f2..fb214940f 100644
--- a/test/test_core_aten_ops.py
+++ b/test/test_core_aten_ops.py
@@ -30,6 +30,8 @@ def diff_output(testcase, output1, output2, rtol, atol
, equal_nan=True):
     if output2_cpu.dtype != output1.dtype:
       output2_cpu = output2_cpu.to(output1.dtype)
     # import pdb; pdb.set_trace()
+    print("output1: ", output1)
+    print("output2: ", output2)
     testcase.assertTrue(
         torch.allclose(
             output1, output2_cpu, atol=atol, rtol=rtol, equal_nan=equal_nan))
@@ -4445,7 +4447,7 @@ class AtenOpTest(unittest.TestCase):
 
   def test_aten_topk_1(self):
     args = (
-        torch.randn((10, 10)).to(torch.float16),
+        torch.randn((10, 10)).to(torch.int32), #float16),
         1,
         1,
         False,
@@ -4454,7 +4456,6 @@ class AtenOpTest(unittest.TestCase):
     kwargs = dict()
     run_export_and_compare(self, torch.ops.aten.topk, args, kwargs)
 
-  @unittest.skip
   def test_aten_topk_2(self):
     args = (

...skipping 1 line
(torch310) root@cb1bb455239f:~/pytorch/xla# 
```

**Comment by wonjoolee95** [comment]
Oh ok I think I know what's the problem. We want the `sorted` parameter to be set to true here in the unit test. Btw, the `stable` in our (PyToroch/XLA) implementation is the `sorted` parameter here.

**Comment by ManfeiBai** [comment]
Thanks, @wonjoolee95, and the local torch test result is:
- torch:
```
>>> aaa = torch.tensor([[0, 0, 2, 3, 3], [1, 2, 3, 3, 3], [4, 4, 4, 0, 0]])
>>> 
>>> 
>>> bbb = torch.topk(aaa, 1)
>>> ccc = aaa.to((torch.float16))
>>> ddd = torch.topk(ccc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: topk() missing 1 required positional arguments: "k"
>>> ddd = torch.topk(ccc, 1)
>>> ddd
torch.return_types.topk(
values=tensor([[3.],
        [3.],
        [4.]], dtype=torch.float16),
indices=tensor([[4],
        [2],
        [1]]))
>>> bbb
torch.return_types.topk(
values=tensor([[3],
        [3],
        [4]]),
indices=tensor([[4],
        [2],
        [1]]))
>>> eee = aaa.to(torch.int32)
>>> fff = torch.topk(eee, 1)
>>> eee
tensor([[0, 0, 2, 3, 3],
        [1, 2, 3, 3, 3],
        [4, 4, 4, 0, 0]], dtype=torch.int32)
>>> fff
torch.return_types.topk(
values=tensor([[3],
        [3],
        [4]], dtype=torch.int32),
indices=tensor([[4],
        [2],
        [1]]))
>>> exit()
```
- torch_xla:
```
>>> import torch
>>> aaa = torch.tensor([[0, 0, 2, 3, 3], [1, 2, 3, 3, 3], [4, 4, 4, 0, 0]])
>>> import torch_xla.core.xla_model as xm
>>> device = xm.xla_device()
>>> bbb = aaa.to(device)
>>> ccc = torch.topk(bbb, 1)
>>> ddd = aaa.to((torch.float16)).to(device)
>>> eee = torch.topk(ddd)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: topk() missing 1 required positional arguments: "k"
>>> eee = torch.topk(ddd, 1)
>>> fff = aaa.to((torch.float16)).to(device)
>>> ggg = torch.topk(.
  File "<stdin>", line 1
    ggg = torch.topk(.
                     ^
SyntaxError: invalid syntax
>>> asd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'asd' is not defined
>>> ggg = torch.topk(fff, 1)
>>> aaa
tensor([[0, 0, 2, 3, 3],
        [1, 2, 3, 3, 3],
        [4, 4, 4, 0, 0]])
>>> bbbb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'bbbb' is not defined. Did you mean: 'bbb'?
>>> bbb
tensor([[0, 0, 2, 3, 3],
        [1, 2, 3, 3, 3],
        [4, 4, 4, 0, 0]], device='xla:0')
>>> ccc
torch.return_types.topk(
values=tensor([[3],
        [3],
        [4]], device='xla:0'),
indices=tensor([[3],
        [3],
        [0]], device='xla:0'))
>>> ddd
tensor([[0., 0., 2., 3., 3.],
        [1., 2., 3., 3., 3.],
        [4., 4., 4., 0., 0.]], device='xla:0', dtype=torch.float16)
>>> eee
torch.return_types.topk(
values=tensor([[3.],
        [3.],
        [4.]], device='xla:0', dtype=torch.float16),
indices=tensor([[3],
        [3],
        [0]], device='xla:0'))
>>> fff
tensor([[0., 0., 2., 3., 3.],
        [1., 2., 3., 3., 3.],
        [4., 4., 4., 0., 0.]], device='xla:0', dtype=torch.float16)
>>> ggg
torch.return_types.topk(
values=tensor([[3.],
        [3.],
        [4.]], device='xla:0', dtype=torch.float16),
indices=tensor([[3],
        [3],
        [0]], device='xla:0'))
>>> exit()
(torch310) root@cb1bb455239f
```

**Comment by wonjoolee95** [comment]
I believe you just need to set the `sorted` param to `True` in our core aten unit tests.

**Comment by wonjoolee95** [comment]
@ManfeiBai, I can take this over.
