### ISSUE TITLE
Failed to run all test files in xla/test

### ISSUE THREAD

**Issue by marsggbo** [pytorch/xla#602]
After I install pytorch and xla, and set the ip of TPU node, I tried to run the test code provided in xla/test, but none of them can run successfully. The error informations of two sample codes are as follows:

```
~/pytorch/xla/test$ python test_operations.py
2019-04-14 14:33:57.371620: I tensorflow/compiler/xla/xla_client/computation_client.cc:125] Loading XRT configuration from /home/hkbuautoml/.pytorch_tpu.conf
2019-04-14 14:33:57.371773: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device CPU:0 -> /job:tpu_worker/replica:0/task:0/device:XLA_CPU:0
2019-04-14 14:33:57.371791: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:0 -> /job:tpu_worker/replica:0/task:0/device:TPU:0
2019-04-14 14:33:57.371813: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:1 -> /job:tpu_worker/replica:0/task:0/device:TPU:1
2019-04-14 14:33:57.371822: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:2 -> /job:tpu_worker/replica:0/task:0/device:TPU:2
2019-04-14 14:33:57.371832: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:3 -> /job:tpu_worker/replica:0/task:0/device:TPU:3
2019-04-14 14:33:57.371842: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:4 -> /job:tpu_worker/replica:0/task:0/device:TPU:4
2019-04-14 14:33:57.371851: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:5 -> /job:tpu_worker/replica:0/task:0/device:TPU:5
2019-04-14 14:33:57.371859: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:6 -> /job:tpu_worker/replica:0/task:0/device:TPU:6
2019-04-14 14:33:57.371867: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:7 -> /job:tpu_worker/replica:0/task:0/device:TPU:7
2019-04-14 14:33:57.371876: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:51] XRT default device: TPU:0
2019-04-14 14:33:57.371917: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:731] Initializing TPU system for worker tpu_worker:0 at grpc://10.240.1.10:8470
2019-04-14 14:34:03.636433: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:774] TPU topology: mesh_shape: 2
mesh_shape: 2
mesh_shape: 2
num_tasks: 1
num_tpu_devices_per_task: 8
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1

2019-04-14 14:34:03.753129: W tensorflow/compiler/xla/shape.cc:41] Malformed shape proto: is_dynamic_dimension is empty
2019-04-14 14:34:03.753212: W tensorflow/compiler/xla/shape.cc:41] Malformed shape proto: is_dynamic_dimension is empty
2019-04-14 14:34:03.759877: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: session_work.first->session()->Run( session_work.second.feed_inputs, session_work.second.outputs_handles, &outputs) == ::tensorflow::Status::OK() (Not found: Op type not registered 'XRTAllocateFromTensor' in binary running on n-8d59f3db-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        xla::XrtComputationClient::TransferToServer(absl::Span<xla::ComputationClient::TensorSource const>)
        torch_xla::TensorToXlaData(at::Tensor const&, torch_xla::Device const&)

        torch_xla::XLATensor::GetIrValueForScalar(c10::Scalar, xla::PrimitiveType, torch_xla::Device const&)
        torch_xla::XLATensor::GetIrValueForScalar(c10::Scalar, xla::Shape const&, torch_xla::Device const&)
        torch_xla::XLATensor::add(torch_xla::XLATensor const&, torch_xla::XLATensor const&, c10::Scalar)
        torch_xla::AtenXlaType::add(at::Tensor const&, at::Tensor const&, c10::Scalar) const
        torch::autograd::VariableType::add(at::Tensor const&, at::Tensor const&, c10::Scalar) const

        PyCFunction_Call
        PyObject_Call


        PyNumber_Add
        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        PyObject_Call
        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        PyObject_Call

        _PyObject_FastCallDict

        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        PyObject_Call

        _PyObject_FastCallDict

        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        PyObject_Call
        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        PyObject_Call

        _PyObject_FastCallDict

        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        PyObject_Call


        _PyObject_FastCallDict
        _PyObject_FastCallKeywords

        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault
        PyEval_EvalCodeEx
        PyEval_EvalCode

        PyRun_FileExFlags
        PyRun_SimpleFileExFlags
        Py_Main
        main
        __libc_start_main

*** End stack trace ***

E2019-04-14 14:34:03.780553: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: session->session()->Run( feed_inputs, {}, {cached_node.operations[0]}, &outputs) == ::tensorflow::Status::OK() (Internal: handle input should be an int64 scalar
         [[{{node XRTReleaseAllocationHandle}}]] vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        xla::XrtComputationClient::ReleaseHandles(std::vector<xla::XrtComputationClient::DeviceHandle, std::allocator<xla::XrtComputationClient::DeviceHandle> >*, std::function<xla::XrtSession::CachedNode const& (xla::XrtSession*, tensorflow::Scope const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&, xla::metrics::Metric*, xla::metrics::Counter*)
        xla::XrtComputationClient::HandleReleaser()
        xla::xla_util::TriggeredTask::Runner()


        clone
*** End stack trace ***

terminate called after throwing an instance of 'std::runtime_error'
  what():  tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:629 : Check failed: session->session()->Run( feed_inputs, {}, {cached_node.operations[0]}, &outputs) == ::tensorflow::Status::OK() (Internal: handle input should be an int64 scalar
         [[{{node XRTReleaseAllocationHandle}}]] vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        xla::XrtComputationClient::ReleaseHandles(std::vector<xla::XrtComputationClient::DeviceHandle, std::allocator<xla::XrtComputationClient::DeviceHandle> >*, std::function<xla::XrtSession::CachedNode const& (xla::XrtSession*, tensorflow::Scope const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&, xla::metrics::Metric*, xla::metrics::Counter*)
        xla::XrtComputationClient::HandleReleaser()
        xla::xla_util::TriggeredTask::Runner()


        clone
*** End stack trace ***

Aborted
```

```python
(py36) hkbuautoml@tputest:~/pytorch/xla/test$ python test_train_cifar.py 
2019-04-14 14:38:35.400546: I tensorflow/compiler/xla/xla_client/computation_client.cc:125] Loading XRT configuration from /home/hkbuautoml/.pytorch_tpu.conf
2019-04-14 14:38:35.400697: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device CPU:0 -> /job:tpu_worker/replica:0/task:0/device:XLA_CPU:0
2019-04-14 14:38:35.400714: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:0 -> /job:tpu_worker/replica:0/task:0/device:TPU:0
2019-04-14 14:38:35.400725: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:1 -> /job:tpu_worker/replica:0/task:0/device:TPU:1
2019-04-14 14:38:35.400736: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:2 -> /job:tpu_worker/replica:0/task:0/device:TPU:2
2019-04-14 14:38:35.400746: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:3 -> /job:tpu_worker/replica:0/task:0/device:TPU:3
2019-04-14 14:38:35.400755: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:4 -> /job:tpu_worker/replica:0/task:0/device:TPU:4
2019-04-14 14:38:35.400765: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:5 -> /job:tpu_worker/replica:0/task:0/device:TPU:5
2019-04-14 14:38:35.400776: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:6 -> /job:tpu_worker/replica:0/task:0/device:TPU:6
2019-04-14 14:38:35.400785: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:48] XRT device TPU:7 -> /job:tpu_worker/replica:0/task:0/device:TPU:7
2019-04-14 14:38:35.400795: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:51] XRT default device: TPU:0
2019-04-14 14:38:35.400825: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:731] Initializing TPU system for worker tpu_worker:0 at grpc://10.240.1.10:8470
2019-04-14 14:38:42.846154: I tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:774] TPU topology: mesh_shape: 2
mesh_shape: 2
mesh_shape: 2
num_tasks: 1
num_tpu_devices_per_task: 8
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1
device_coordinates: 0
device_coordinates: 0
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1
device_coordinates: 0
device_coordinates: 1
device_coordinates: 1
device_coordinates: 1

==> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
==> Building model..
[':0']
torch.Size([128, 3, 32, 32])
2019-04-14 14:39:10.685305: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: session_work.first->session()->Run( session_work.second.feed_inputs, session_work.second.outputs_handles, &outputs) == ::tensorflow::Status::OK() (Not found: Op type not registered 'XRTAllocateFromTensor' in binary running on n-8d59f3db-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        xla::XrtComputationClient::TransferToServer(absl::Span<xla::ComputationClient::TensorSource const>)
        torch_xla::CreateTensorsData(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
        torch_xla::XLATensor::CreateTensors(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)


        _PyCFunction_FastCallDict

        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        _PyObject_Call


        _PyObject_FastCallDict
        _PyObject_FastCallKeywords

        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault
        PyEval_EvalCodeEx
        PyEval_EvalCode

        PyRun_FileExFlags
        PyRun_SimpleFileExFlags
        Py_Main
        main
        __libc_start_main

*** End stack trace ***

Traceback (most recent call last):
  File "test_train_cifar.py", line 184, in <module>
    acc =  train_cifar()
  File "test_train_cifar.py", line 152, in train_cifar
    devices=devices)
  File "/home/hkbuautoml/pytorch/xla/torch_xla_py/xla_model.py", line 595, in __init__
    input_gradients=loss_output_grads)
  File "/home/hkbuautoml/pytorch/xla/torch_xla_py/xla_model.py", line 288, in create_xla_model
    inputs_xla = convert_to_xla_tensors(replica_inputs, devices=devices)
  File "/home/hkbuautoml/pytorch/xla/torch_xla_py/xla_model.py", line 259, in convert_to_xla_tensors
    arena.convert()
  File "/home/hkbuautoml/pytorch/xla/torch_xla_py/xla_model.py", line 176, in convert
    self._converted_tensors = self.convert_fn(self._tensors, self._devices)
  File "/home/hkbuautoml/pytorch/xla/torch_xla_py/xla_model.py", line 255, in convert
    return torch_xla._XLAC._xla_create_tensors(tensors, devices)
RuntimeError: tensorflow/compiler/xla/xla_client/xrt_computation_client.cc:109 : Check failed: session_work.first->session()->Run( session_work.second.feed_inputs, session_work.second.outputs_handles, &outputs) == ::tensorflow::Status::OK() (Not found: Op type not registered 'XRTAllocateFromTensor' in binary running on n-8d59f3db-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. vs. OK)
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()
        xla::XrtComputationClient::TransferToServer(absl::Span<xla::ComputationClient::TensorSource const>)
        torch_xla::CreateTensorsData(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
        torch_xla::XLATensor::CreateTensors(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)


        _PyCFunction_FastCallDict

        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault


        _PyCFunction_FastCallDict

        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault



        _PyEval_EvalFrameDefault

        _PyFunction_FastCallDict
        _PyObject_FastCallDict
        _PyObject_Call_Prepend
        PyObject_Call


        _PyObject_FastCallDict
        _PyObject_FastCallKeywords

        _PyEval_EvalFrameDefault


        _PyEval_EvalFrameDefault
        PyEval_EvalCodeEx
        PyEval_EvalCode

        PyRun_FileExFlags
        PyRun_SimpleFileExFlags
        Py_Main
        main
        __libc_start_main

```

**Comment by asuhan** [comment]
You'll need TF 1.14 for TPUs, which is going to be released very soon.

**Comment by a-runner** [comment]
I have the same problem,and I have not found a useful solution.
