### ISSUE TITLE
`test_autocast_torch_bf16` fails if PyTorch is compiled with CUDA support.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/xla#6085]
## 🐛 Bug

Running `test_autocast_torch_bf16` test produces the following error, if PyTorch was compiled with CUDA support:

```bash
$ python test/test_autocast.py -v -k test_autocast_torch_bf16
test_autocast_torch_bf16 (__main__.TestAutocastCuda) ... ERROR

======================================================================
ERROR: test_autocast_torch_bf16 (__main__.TestAutocastCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autocast.py", line 391, in test_autocast_torch_bf16
    self._run_autocast_outofplace(
  File "test/test_autocast.py", line 278, in _run_autocast_outofplace
    with autocast(xm.xla_device(), dtype=autocast_dtype):
  File "xla/torch_xla/amp/autocast_mode.py", line 45, in __init__
    super().__init__(
  File "torch/amp/autocast_mode.py", line 306, in __init__
    raise RuntimeError(
RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.

----------------------------------------------------------------------
Ran 1 test in 0.140s

FAILED (errors=1)
```

## Environment

- PyTorch/XLA: 402166bec712eaea1d2db9095db4f7e048e70f4a

## Additional Context

Blocking: #6070

**Comment by ysiraichi** [comment]
The main problem here is that `torch.cuda.is_bf16_supported()` returns false, while `torch.tensor([1.], dtype=torch.bfloat16, device=xm.xla_device())` works.

**Comment by JackCaoG** [comment]
@yeounoh FYI
