### ISSUE TITLE
bug for train magvit2

### ISSUE THREAD

**Issue by syyxsxx** [pytorch/xla#6090]
## ❓ Questions and Help
code：https://github.com/lucidrains/magvit2-pytorch
train script：
`
#import torch

from magvit2_pytorch import (
    VideoTokenizer,
    VideoTokenizerTrainer
)
#torch.set_default_dtype(torch.float32)
tokenizer = VideoTokenizer(
    image_size = 128,
    codebook_size=1024,
    init_dim = 64,
    max_dim = 512,
    layers = (
        'residual',
        'compress_space',
        ('consecutive_residual', 2),
        'compress_space',
        ('consecutive_residual', 2),
        'linear_attend_space',
        'compress_space',
        ('consecutive_residual', 2),
        'attend_space',
        'compress_time',
        ('consecutive_residual', 2),
        'compress_time',
        ('consecutive_residual', 2),
        'attend_time',
    )
)

trainer = VideoTokenizerTrainer(
    tokenizer,
    dataset_folder = '/workspace/magvit2-pytorch/data',     # folder of either videos or images, depending on setting below
    dataset_type = 'videos',                        # 'videos' or 'images', prior papers have shown pretraining on images to be effective for video synthesis
    batch_size = 1,
    grad_accum_every = 8,
    learning_rate = 2e-5,
    num_train_steps = 1_000_000
)

trainer.train()

# after a lot of training ...
# can use the EMA of the tokenizer

ema_tokenizer = trainer.ema_tokenizer

# mock video

video = torch.randn(1, 3, 17, 128, 128)

# tokenizing video to discrete codes

codes = ema_tokenizer.tokenize(video) # (1, 9, 16, 16) <- in this example, time downsampled by 4x and space downsampled by 8x. flatten token ids for (non)-autoregressive training

# sanity check

decoded_video = ema_tokenizer.decode_from_code_indices(codes)

assert torch.allclose(
    decoded_video,
    ema_tokenizer(video, return_recon = True)
)
`
tpu:tpuv2-8,
os:tpu-ubuntu2204-base
torch_xla:2.1.0

**I am training magvit2 on TPU got some error:**
2023-12-11 05:55:35.981364: F ./torch_xla/csrc/runtime/debug_macros.h:20] Non-OK-status: status.status() status: INTERNAL: during context [post-optimization]: Expected instruction to have shape equal to f32[20,64]{1,0}, actual shape is f32[64,20]{1,0:T(8,128)}:
%reduce.1107.clone.1 = f32[64,20]{1,0:T(8,128)} reduce(f32[20,128,8,17,64]{4,2,3,1,0:T(8,128)} %select.2131.clone.1, f32[]{:T(256)} %constant.13192.clone.1), dimensions={2,1,3}, to_apply=%AddComputation.13944
*** Begin stack trace ***
        tsl::CurrentStackTrace()
        std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > ConsumeValue<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >(absl::lts_20230125::StatusOr<std::unique_ptr<xla::PjRtLoadedExecutable, std::default_delete<xla::PjRtLoadedExecutable> > >&&)
        torch_xla::runtime::PjRtComputationClient::Compile(std::vector<torch_xla::runtime::ComputationClient::CompileInstance, std::allocator<torch_xla::runtime::ComputationClient::CompileInstance> >)
        torch_xla::XLAGraphExecutor::Compile(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > > const&, absl::lts_20230125::Span<std::string const>, torch::lazy::LazyGraphExecutor::SyncTensorCollection const&, torch::lazy::LazyGraphExecutor::PostOrderData*, std::vector<torch::lazy::Value, std::allocator<torch::lazy::Value> > const&)
        torch_xla::XLAGraphExecutor::SyncTensorsGraphInternal(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230125::Span<std::string const>, torch::lazy::LazyGraphExecutor::SyncTensorsConfig const&, bool)
        torch_xla::XLAGraphExecutor::SyncTensorsGraph(std::vector<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> >, std::allocator<c10::intrusive_ptr<torch_xla::XLATensor, c10::detail::intrusive_target_default_null_type<torch_xla::XLATensor> > > >*, absl::lts_20230125::Span<std::string const>, bool, bool, bool)
        torch_xla::XLAGraphExecutor::SyncLiveTensorsGraph(torch::lazy::BackendDevice const*, c10::ArrayRef<std::string>, bool)

        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault

        PyEval_EvalCode

        _PyRun_SimpleFileObject
        _PyRun_AnyFileObject
        Py_RunMain
        Py_BytesMain

        __libc_start_main
        _start
*** End stack trace ***

https://symbolize.stripped_domain/r/?trace=7fc22de969fc,7fc22de4251f&map= 
*** SIGABRT received by PID 495957 (TID 495957) on cpu 24 from PID 495957; stack trace: ***
PC: @     0x7fc22de969fc  (unknown)  pthread_kill
    @     0x7fc0ac7aa53a       1152  (unknown)
    @     0x7fc22de42520  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7fc22de969fc,7fc0ac7aa539,7fc22de4251f&map=abbd016d9542b8098892badc0b19ea68:7fc09f600000-7fc0ac9becf0 
E1211 05:55:35.986512  495957 coredump_hook.cc:447] RAW: Remote crash data gathering hook invoked.
E1211 05:55:35.986530  495957 coredump_hook.cc:486] RAW: Skipping coredump since rlimit was 0 at process start.
E1211 05:55:35.986542  495957 client.cc:272] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E1211 05:55:35.986550  495957 coredump_hook.cc:542] RAW: Sending fingerprint to remote end.
E1211 05:55:35.986578  495957 coredump_hook.cc:551] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] stat failed on crash reporting socket /var/google/services/logmanagerd/remote_coredump.socket (Is the listener running?): No such file or directory
E1211 05:55:35.986587  495957 coredump_hook.cc:603] RAW: Dumping core locally.
E1211 05:55:36.658551  495957 process_state.cc:783] RAW: Raising signal 6 with default behavior

**My questions：**
1、Do I need to modify the training code when I use xla，this code works well when training on GPU using CUDNN
2、How can I solve or debug the above problem

**Comment by JackCaoG** [comment]
hmm error is
```
2023-12-11 05:55:35.981364: F ./torch_xla/csrc/runtime/debug_macros.h:20] Non-OK-status: status.status() status: INTERNAL: during context [post-optimization]: Expected instruction to have shape equal to f32[20,64]{1,0}, actual shape is f32[64,20]{1,0:T(8,128)}:
%reduce.1107.clone.1 = f32[64,20]{1,0:T(8,128)} reduce(f32[20,128,8,17,64]{4,2,3,1,0:T(8,128)} %select.2131.clone.1, f32[]{:T(256)} %constant.13192.clone.1), dimensions={2,1,3}, to_apply=%AddComputation.13944
```

seem like it is expecting shapes `f32[20,64]` but get shape `f32[64,20]`. Not sure if this is an issue on the compiler side or pytorch/xla side. What version of PyTorch/XLA you are using?

**Comment by syyxsxx** [comment]
PyTorch/XLA: 2.1.0
install instructions : pip install torch~=2.1.0 torch_xla[tpu]~=2.1.0 torchvision -f https://storage.googleapis.com/libtpu-releases/index.html
It seems that when converting a dynamic graph into a static graph, some ops shape is wrong
How do I locate this problem?
@JackCaoG

**Comment by JackCaoG** [comment]
This seem like a bug on lowering code on our end. Can you follow https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#common-debugging-environment-variables-combinations to dump a IR and share the file. I guess the last IR graph dump will tell us where that `f32[64,20]` is from then we should have a better idea how to fix it.

**Comment by syyxsxx** [comment]
@JackCaoG 
here is ir file: https://storage.googleapis.com/mlserver-environment/save1.ir.0

**Comment by JackCaoG** [comment]
ok it does seem like a bug on the XLA compiler side, I can't find `[20,64]` in the IR, which usually means it is generate by one of the compiler's optimization pass. I will see if I can repo this. The IR is huge through ~20k lines of IR, which will make it really hard to figure out what happened. Any chance you can provide a smaller repo?

**Comment by syyxsxx** [comment]
hi i make a small repo, you can train magvit2 on tpu and found the error above
https://github.com/syyxsxx/magvit2-pytorch/tree/dev

**Comment by JackCaoG** [comment]
I tried your repo and run into some issues on dataloader
```
/repo/magvit2-pytorch# PT_XLA_DEBUG=1 python test.py
/usr/local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
50 training samples found at data
training with dataset of 47 samples and validating with randomly splitted 3 samples
step 0
recon loss: 0.318
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    trainer.train()
  File "/workspaces/dk2/repo/magvit2-pytorch/magvit2_pytorch/trainer.py", line 517, in train
    self.train_step(dl_iter)
  File "/workspaces/dk2/repo/magvit2-pytorch/magvit2_pytorch/trainer.py", line 408, in train_step
    data, *_ = next(dl_iter)
  File "/workspaces/dk2/repo/magvit2-pytorch/magvit2_pytorch/trainer.py", line 53, in cycle
    for data in dl:
  File "/usr/local/lib/python3.8/site-packages/accelerate-0.25.0-py3.8.egg/accelerate/data_loader.py", line 458, in __iter__
    next_batch = next(dataloader_iter)
  File "/workspaces/dk2/pytorch/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/workspaces/dk2/pytorch/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/workspaces/dk2/pytorch/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/workspaces/dk2/pytorch/torch/utils/data/dataset.py", line 399, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/workspaces/dk2/pytorch/torch/utils/data/dataset.py", line 399, in <listcomp>
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/workspaces/dk2/repo/magvit2-pytorch/magvit2_pytorch/data.py", line 278, in __getitem__
    tensor = self.mp4_to_tensor(path_str)
  File "/workspaces/dk2/repo/magvit2-pytorch/magvit2_pytorch/data.py", line 183, in video_to_tensor
    frames = np.array(np.concatenate(frames[:-1], axis = 0))  # convert list of frames to numpy array
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
WARNING:pt-xla-profiler:================================================================================
WARNING:pt-xla-profiler:Unlowered Op usage summary (more of these ops, lower performance)
WARNING:pt-xla-profiler:Note: _local_scalar_dense typically indicates CPU context access
WARNING:pt-xla-profiler:--------------------------------------------------------------------------------
WARNING:pt-xla-profiler:================================================================================
```

**Comment by syyxsxx** [comment]
@JackCaoG
Sorry for the late reply
I updated the code and raised incorrect data
you can pull the dev branch and you will get the shape error

**Comment by syyxsxx** [comment]
@JackCaoG 
hi, Is there any problem with running the demo

**Comment by JackCaoG** [comment]
Sorry was busy with some other issues. @will-cromar do you have cycle to repo this one?

**Comment by mgyong** [comment]
@JackCaoG @will-cromar Hoping to follow up on this problem. Thanks

**Comment by JackCaoG** [comment]
I am able to repo the issue.. Trying to extract the HLO and open a bug to the XLA team.

**Comment by JackCaoG** [comment]
Ok open the bug to XLA team. We need to wait for XLA team to triage the bug, fix them and we update our OpenXLA pin to resolve this issue.

**Comment by ManfeiBai** [comment]
According to XLA team, suggest to add these two flags (`xla_tpu_run_space_to_batch=false` and `xla_tpu_run_space_to_batch_on_new_platforms=false`) like this commit to retry: https://github.com/pytorch/xla/pull/6548/commits/6123022766109bff3a5e1803c1934638e80c1636

**Comment by JackCaoG** [comment]
@ManfeiBai can you provide the command to run it using env var?

**Comment by ManfeiBai** [comment]
Thanks, suggest to try command with flag like this:
```
XLA_FLAGS='  --xla_tpu_run_space_to_batch=false --xla_tpu_run_space_to_batch_on_new_platforms=false' PJRT_DEVICE=TPU python test.py
```
