### ISSUE TITLE
Nightmare Setting Up Distributed Training with TPU VM 3.8 on Kaggle

### ISSUE THREAD

**Issue by AlekKCode** [pytorch/xla#6305]
## ❓ Questions and Help
The resources available for distributed training on TPUs are frankly abysmal. 
Of the available resources, most only explain how to perform basic tensor operations with TPUs.
The remaining resources that actually showcase distributed training of models, don't work. 
Google Clouds example: https://www.youtube.com/watch?v=iwtpwQRdb3Y&t=430s doesn't work.
Kaggles Torchvision example: https://www.kaggle.com/discussions/product-feedback/369338 doesn't work.
The readme for this repo includes an example that only shows a couple lines of a distributed training script.
Can someone please show me a full, working example of distributed training with TPU VM 3.8, that works on Kaggle?
Or tell me why my code below doesn't work?

```
import os
import multiprocessing as mp

import torch
import torch.nn as nn
import torch.optim as optim

import torch.distributed as dist
from torch.distributed import init_process_group, destroy_process_group
from torch.nn.parallel import DistributedDataParallel as DDP

import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_backend # Registers `xla://` init_method
import torch_xla.experimental.pjrt_backend # Required for torch.distributed on TPU v2 and v3

import torchvision
import torchvision.transforms as transforms 


class Toy_Model(nn.Module):
    def __init__(self):
        super(Toy_Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, 5)
        self.mp1 = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(1440, 10)
    def forward(self, x):
        conv_outs = nn.ReLU()(self.conv1(x))
        mp_outs = torch.flatten(self.mp1(conv_outs), 1)
        fc1_outs = self.fc1(mp_outs)
        outs = nn.Softmax(dim=-1)(fc1_outs)
        return outs


# os.environ["MASTER_ADDR"] = "localhost"
# os.environ["MASTER_PORT"] = "12355" 
transform = transforms.Compose(
    [
        transforms.ToTensor(),
        transforms.Normalize((1307,), (3081,))
    ]
)
train_dataset = torchvision.datasets.MNIST(
    '/tmp/', train=True, download=True, transform=transform)

def train_loop(rank):

    device = xm.xla_device()
    init_process_group('xla', init_method='xla://')
    train_sampler = torch.utils.data.distributed.DistributedSampler(
        train_dataset)
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=32, pin_memory=True, shuffle=False, sampler=train_sampler)
    model = Toy_Model().to(device)
    xm.broadcast_master_param(model)
    model = DDP(model, gradient_as_bucket_view=True)

    loss_fn = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=.001)
    mp_device_loader = pl.MpDeviceLoader(train_loader, device)
    model.train()
    for epoch in range(10):
        train_sampler.set_epoch(epoch)
        for i, (X, y) in enumerate(mp_device_loader):
            X, y = X.to(device), y.to(device)
            optimizer.zero_grad()
            output = model(X)
            loss = loss_fn(output, y)
            loss.backward()
            xm.optimizer_step(optimizer)
    
#             if i % 1000 == 0:
#                 print(f"epoch: {epoch}, loss: {loss}")
    destroy_process_group()

if __name__ == '__main__':
    xmp.spawn(train_loop, args=(), start_method='fork')
```

**Comment by JackCaoG** [comment]
https://github.com/pytorch/xla/blob/master/contrib/kaggle/distributed-pytorch-xla-basics-with-pjrt.ipynb is tested on kaggle v3-8 on 2.1 release I think.

**Comment by AlekKCode** [comment]
How would I fit a real dataset with DistributedSampler and parallel_loader into this? And why isn't the example using xm.optimizer_step(optimizer) instead of optimizer.step() ?

**Comment by JackCaoG** [comment]
@yeounoh Do you have cycle for this one?

**Comment by yeounoh** [comment]
Hi @AlekKCode, thanks for reporting. Let me also start looking.

**Comment by yeounoh** [comment]
> How would I fit a real dataset with DistributedSampler and parallel_loader into this? And why isn't the example using xm.optimizer_step(optimizer) instead of optimizer.step() ?

I see that you are using `DDP` and `xm.optimizer_step` in your example. You don't need to call `xm.optimizer_step` because you are using `DDP` which should synchronizes the gradients for you.  If you look at our example, we also make this distinction,
```python
if flags.ddp:
  optimizer.step()
else:
  xm.optimizer_step(optimizer)
```

Regarding using the real-data, this section of the example could be helpful to you https://github.com/pytorch/xla/blob/master/test/test_train_mp_mnist.py#L96C5-L129, which I think you've already figured out... I also see `mp_device_loader = pl.MpDeviceLoader(train_loader, device)` in your example.

Hope this helps.

**Comment by AlekKCode** [comment]
Thanks for the clarification. I have updated my code by including the the data loader and sampler from the example you provided, and I have updated to optimizer.step(). However, now I get an equally frustrating error : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 240, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'train_loop' on <module '__main__' (built-in)>
```
I still have the question about why so many examples that are online don't work? Is this because xla went from 1.x to 2.x?
Also, the nprocs param seems to be deprecated as whenever I include it in xmp.spawn() it gives me a warning. 

```
import os
import multiprocessing as mp

import torch
import torch.nn as nn
import torch.optim as optim

import torch.distributed as dist
from torch.distributed import init_process_group, destroy_process_group
from torch.nn.parallel import DistributedDataParallel as DDP

import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_backend # Registers `xla://` init_method
import torch_xla.experimental.pjrt_backend # Required for torch.distributed on TPU v2 and v3

import torchvision
import torchvision.transforms as transforms 

class Toy_Model(nn.Module):
    def __init__(self):
        super(Toy_Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, 5)
        self.mp1 = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(1440, 10)
    def forward(self, x):
        conv_outs = nn.ReLU()(self.conv1(x))
        mp_outs = torch.flatten(self.mp1(conv_outs), 1)
        fc1_outs = self.fc1(mp_outs)
        outs = nn.Softmax(dim=-1)(fc1_outs)
        return outs


# os.environ["MASTER_ADDR"] = "localhost"
# os.environ["MASTER_PORT"] = "12355" 

def train_loop(rank):

    device = xm.xla_device()
    init_process_group('xla', init_method='xla://')
    model = Toy_Model().to(device)
    xm.broadcast_master_param(model)
    model = DDP(model, gradient_as_bucket_view=True)
    loss_fn = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=.001)
    
    train_dataset = datasets.MNIST(
        train=True,
        download=True,
        transform=transforms.Compose(
            [transforms.ToTensor(),
             transforms.Normalize((0.1307,), (0.3081,))]))
    train_sampler = None
    if xm.xrt_world_size() > 1:
        train_sampler = torch.utils.data.distributed.DistributedSampler(
          train_dataset,
          num_replicas=xm.xrt_world_size(),
          rank=xm.get_ordinal(),
          shuffle=True)
    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=32,
        sampler=train_sampler,
        shuffle=False if train_sampler else True,)
    mp_device_loader = pl.MpDeviceLoader(train_loader, device)
    model.train()
    for epoch in range(10):
        train_sampler.set_epoch(epoch)
        for i, (X, y) in enumerate(mp_device_loader):
            optimizer.zero_grad()
            output = model(X)
            loss = loss_fn(output, y)
            loss.backward()
            optimizer.step()
    
    destroy_process_group()

if __name__ == '__main__':
    xmp.spawn(train_loop, args=())
```

**Comment by AlekKCode** [comment]
Thanks for the clarification. I have finally managed to get it working after implementing your changes and debugging some errors. 

I still have the question about why so many examples that are online don't work? Is this because xla went from 1.x to 2.x?
Also, the nprocs param seems to be deprecated as whenever I include it in xmp.spawn() it gives me a warning.

I will tune up my code, try to get inference working, and share it because I know it will help someone that doesn't have time to figure it out for themselves by debugging and looking at tests just to implement basic distributed training.

**Comment by yeounoh** [comment]
@AlekKCode thank you, let me know how i can help -- also once you share your example, raise a PR (feel free to add me as a reviewer) so we can merge to the repo :)
