### ISSUE TITLE
[BUG] Cannot find libpython3.11.so.1.0 when using XLA on TPU device with conda environment

### ISSUE THREAD

**Issue by Mon-ius** [pytorch/xla#6372]
Device: Google TPU V4-8 Pod
Platform: GCP

Howto:

```bash
gcloud alpha compute tpus queued-resources create $V4_INSTANCE \
    --project $PROJECT \
    --zone $V4_ZONE \
    --node-id $V4_NODE \
    --accelerator-type $V4_TYPE \
    --runtime-version $TORCH \
    --best-effort 
```

```bash
mini_url_linux="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
curl -fsSL $mini_url_linux -o conda.sh
sudo mkdir -p /opt/dev && sudo chown -R "$USER:$USER" /opt/dev
chmod +x conda.sh && bash conda.sh -b -p /opt/dev/conda

cat >~/.bashrc <<-'EOF'
if [ -f "/opt/dev/conda/etc/profile.d/conda.sh" ]; then
    . "/opt/dev/conda/etc/profile.d/conda.sh"
else
    export PATH="/opt/dev/conda/bin:$PATH"
fi
EOF

source "$HOME"/.bashrc

conda -y create -n xla python=3.11 pytorch torchvision torchaudio transformers bitsandbytes diffusers segment-anything imageio scipy numpy pyglet trimesh gradio fire -c conda-forge -c pytorch

conda activate xla
pip install torch_xla[tpu]~=2.1.0 -f https://storage.googleapis.com/libtpu-releases/index.html

```

`import torch` works fine, but `import torch_xla.core.xla_model as xm`, more concrete, `import _XLAC` cannot detect the related `dlib` on correct path.

Error shows that:
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
> ImportError: libpython3.11.so.1.0: cannot open shared object file: No such file or directory

In fact, when execute `find $conda_path -name libpython3.11.so.1.0 `, it is just there,
> $conda_path/python-3.11.5-h955ad1f_0/lib/libpython3.11.so.1.0
> $conda_path/python-3.11.7-hab00c5b_1_cpython/lib/libpython3.11.so.1.0

It should be a design defect while finding correct path to load related lib of `_XLAC` package

**Comment by JackCaoG** [comment]
Can you try `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(python3-config --prefix)/lib"`?

**Comment by Mon-ius** [comment]
It turns out lack of `libc10.so` of `ImportError: libc10.so: cannot open shared object file: No such file or directory`

**Comment by Mon-ius** [comment]
And keep trying`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(python3-config --prefix)/lib: $(python3-config --prefix)/lib/python3.11/site-packages/torch/lib"`, right? 🤗

**Comment by Mon-ius** [comment]
r u from google? I think it's the bazel problem from the BUILD file for pybind11 here, https://github1s.com/pytorch/xla/blob/main/torch_xla/csrc/init_python_bindings.cpp#L2018

**Comment by Mon-ius** [comment]
New challenge here,

```bash
echo $LD_LIBRARY_PATH
```
> :/usr/local/lib:/opt/dev/conda/envs/xla/lib

```python
import torch
import torch_xla.core.xla_model as xm
```

> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> File "/opt/dev/conda/envs/xla/lib/python3.11/site-packages/torch_xla/__init__.py", line 114, in <module>
>    import _XLAC
> ImportError: /opt/dev/conda/envs/xla/lib/python3.11/site-packages/_XLAC.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN5torch4lazy13MetricFnValueEd

**Comment by Mon-ius** [comment]
Sure, believe me, it's not just that problem.

For another env setup, I tried:
```bash
mini_url_linux="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
curl -fsSL $mini_url_linux -o conda.sh
sudo mkdir -p /opt/dev && sudo chown -R "$USER:$USER" /opt/dev
chmod +x conda.sh && bash conda.sh -b -p /opt/dev/conda && rm conda.sh

cat >~/.bashrc <<-'EOF'
if [ -f "/opt/dev/conda/etc/profile.d/conda.sh" ]; then
    . "/opt/dev/conda/etc/profile.d/conda.sh"
else
    export PATH="/opt/dev/conda/bin:$PATH"
fi
EOF
source "$HOME"/.bashrc
conda create -n xla python=3.11 -c conda-forge -y
conda activate xla && pip install torch~=2.1.0 torch_xla[tpu]~=2.1.0 -f https://storage.googleapis.com/libtpu-releases/index.html
```
Then, you can follow:

```python
import torch
import torch_xla.core.xla_model as xm
```

>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/opt/dev/conda/envs/xla/lib/python3.11/site-packages/torch_xla/__init__.py", line 114, in <module>
>    import _XLAC
> ImportError: libpython3.11.so.1.0: cannot open shared object file: No such file or directory

Again, For `import _XLAC` only,
> ImportError: libc10.so: cannot open shared object file: No such file or directory

current $LD_LIBRARY_PATH,
```bash
echo $LD_LIBRARY_PATH
```
> :/usr/local/lib

And after, execute,
```bash
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(python3-config --prefix)/lib"
echo $LD_LIBRARY_PATH
```
> :/usr/local/lib:/opt/dev/conda/envs/xla/lib

Again, 

```python
import torch
import torch_xla.core.xla_model as xm
import _XLAC
```

Okay, it works. But sucks 🤗

**Comment by Mon-ius** [comment]
All right, I will email TRC team, it was just temporarily fixed while installing `pytorch` and `xla` together.

**Comment by Mon-ius** [comment]
@talumbau  You are definitely right! But I trace the [source](https://github.com/pytorch/xla/blob/master/torch_xla/csrc/BUILD#L157) that the root cause is the bazel build system problem
