### ISSUE TITLE
all_to_all NotImplementedError during back-propagating loss while training with xmp.spawn on v2-8

### ISSUE THREAD

**Issue by krmayankb** [pytorch/xla#6415]
## ❓ Questions and Help
I am training on: 
TPU VM: V2-8 
launched using: `xmp.spawn(main, args=(args,), start_method="fork")`
```
>>> import torch 
>>> import torch_xla
>>> torch.__version__
'2.1.2+cu121'
>>> torch_xla.__version__
'2.1.0'
```

I am getting the following error for which the trace is given below. 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 75, in _run_thread_per_device
    replica_results = list(
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 68, in _thread_fn
    return fn()
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 178, in __call__
    self.fn(runtime.global_ordinal(), *self.args, **self.kwargs)
  File "/home/krmayank/code/src/training/main.py", line 434, in main
    train_one_epoch(model, data, loss, epoch, optimizer, scaler, scheduler, dist_model, args, tb_writer=writer)
  File "/home/krmayank/code/src/training/train.py", line 127, in train_one_epoch
    backward(total_loss, scaler)
  File "/home/krmayank/code/src/training/train.py", line 65, in backward
    total_loss.backward()
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch/distributed/nn/functional.py", line 340, in backward
    gxs = _AlltoAll.apply(ctx.group, tensor_list, *grad_outputs)
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch/distributed/nn/functional.py", line 385, in forward
    dist.all_to_all(
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3652, in all_to_all
    work = default_pg.alltoall(output_tensor_list, input_tensor_list, opts)
  File "/home/krmayank/.local/lib/python3.8/site-packages/torch_xla/distributed/xla_backend.py", line 135, in alltoall
    raise NotImplementedError
NotImplementedError
"""

```

**Comment by JackCaoG** [comment]
yea we need to implement XlaBackend's https://github.com/pytorch/xla/blob/master/torch_xla/distributed/xla_backend.py#L173-L174. Can you use https://github.com/pytorch/xla/blob/master/torch_xla/core/xla_model.py#L623 in the meantime?

**Comment by krmayankb** [comment]
Thanks for the reply. It would be really helpful if you could provide an example snippet.

**Comment by JackCaoG** [comment]
maybe https://github.com/pytorch/xla/blob/90d9dd1d5da691a0f0713a4743e4c0dec293d5ef/test/test_mp_all_to_all.py#L8-L34

**Comment by YUE-FAN** [comment]
@krmayankb Hi, I also got the same error when using openclip training code. Have you figured out how to call `total_loss.backward()` without getting into this `NotImplementedError`? Many thanks!

**Comment by ysiraichi** [comment]
I see that there's an implementation to [`alltoall_base`](https://github.com/pytorch/xla/blob/1b7422d09d8509373d5094dcce153269b041d6b4/torch_xla/distributed/xla_backend.py#L218-L230). @krmayankb @YUE-FAN Could you confirm whether this issue is solved?
