### ISSUE TITLE
Torchbench run terminated whenever a model  failed due to package issue.

### ISSUE THREAD

**Issue by zpcore** [pytorch/xla#6438]
We saw torchbench model success rate jump due to benchmark run termination at 27%. Here is the error log:
```
Running benchmark configs by model:  27%|███████████████████████████████████████████████████████▎                                                                                                                                                   | 27/99 [3:23:03<12:35:51, 629.88s/it]
INFO:__main__:Run with --model-config={"model_name": "doctr_det_predictor"} --experiment-config={"accelerator": "tpu", "xla": "PJRT", "xla_flags": null, "dynamo": null, "test": "eval"}
Running benchmark configs by model:  27%|███████████████████████████████████████████████████████▋                                                                                                                                                    | 27/99 [3:23:03<9:01:29, 451.25s/it]
Traceback (most recent call last):
  File "/home/piz/pytorch/xla/benchmarks/torchbench_model.py", line 317, in benchmark_cls
    module = importlib.import_module(
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/piz/benchmark/torchbenchmark/models/doctr_det_predictor/__init__.py", line 2, in <module>
    from doctr.models import ocr_predictor
ModuleNotFoundError: No module named 'doctr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piz/pytorch/xla/benchmarks/experiment_runner.py", line 908, in <module>
    main()
  File "/home/piz/pytorch/xla/benchmarks/experiment_runner.py", line 904, in main
    runner.run()
  File "/home/piz/pytorch/xla/benchmarks/experiment_runner.py", line 55, in run
    self.generate_and_run_all_configs()
  File "/home/piz/pytorch/xla/benchmarks/experiment_runner.py", line 127, in generate_and_run_all_configs
    benchmark_model.update_process_env(process_env)
  File "/home/piz/pytorch/xla/benchmarks/torchbench_model.py", line 404, in update_process_env
    precision_flag = self.default_precision_flag
  File "/home/piz/pytorch/xla/benchmarks/torchbench_model.py", line 384, in default_precision_flag
    if self.get_cuda_precision() is None:
  File "/home/piz/pytorch/xla/benchmarks/torchbench_model.py", line 357, in get_cuda_precision
    return getattr(self.benchmark_cls(), attr, None)
  File "/home/piz/pytorch/xla/benchmarks/torchbench_model.py", line 320, in benchmark_cls
    module = importlib.import_module(
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'torchbenchmark.models.fb'
```
Previously benchmark will continue to the next model if one model fail due to such package issue.

**Comment by zpcore** [comment]
@ysiraichi , @miladm
