### ISSUE TITLE
`XLA_REGISTER_INSTALLED_PLUGINS=1` crashes torch_xla 

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#6547]
## 🐛 Bug
After setting `XLA_REGISTER_INSTALLED_PLUGINS` env variable, `import torch_xla` breaks for me. @will-cromar did you see the same behavior when trying https://github.com/pytorch/xla/pull/6533?

cc @lsy323 

```
$ export XLA_REGISTER_INSTALLED_PLUGINS=1
$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_xla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miladmo/pytorch/xla/torch_xla/__init__.py", line 184, in <module>
    plugins.register_installed_plugins()
  File "/home/miladmo/pytorch/xla/torch_xla/experimental/plugins.py", line 92, in register_installed_plugins
    pjrt_entry_points = importlib_metadata.entry_points(group='torch_xla.plugins')
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1018, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 943, in _normalized_name
    or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Comment by will-cromar** [comment]
This isn't reproducible on our latest nightly image:

```
docker run -it --rm --privileged -e PJRT_DEVICE=TPU -e XLA_REGISTER_INSTALLED_PLUGINS=1 -e TF_CPP_MIN_LOG_LEVEL=0 -e TF_CPP_VMODULE=pjrt_registry=5 us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.10_tpuvm
Python 3.10.13 (main, Feb 13 2024, 10:45:10) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_xla
INFO:torch_xla:Using bundled libtpu.so (/usr/local/lib/python3.10/site-packages/torch_xla/lib/libtpu.so)
2024-02-16 17:20:00.602676: I torch_xla/csrc/runtime/pjrt_registry.cc:53] Registering PjRt plugin TPU
>>> torch_xla.__version__
'2.3.0+gitb7c760d'
>>> torch_xla.core.xla_model.get_xla_supported_devices()
...
['xla:0', 'xla:1', 'xla:2', 'xla:3']
```

The error comes internally from `importlib.metadata`, so I expect this is an issue with your environment:

```
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

Try uninstalling `importlib_metadata`. This contains some backports that are not needed for python 3.10 in our case.

**Comment by miladm** [comment]
Had an offline chat with @will-cromar
Tried it on a the same TPU machine with a docker image + python 3.8. The error disappears. Looks like this issue is limited to our bare VM image.
