### ISSUE TITLE
KeyError: _ResumeIteration  in dataloader

### ISSUE THREAD

**Issue by nom** [pytorch/xla#6633]
## 🐛 Bug

I'm using HF's accelerate which uses torch_xla's dataloader under the hood, as follows:

```
train_set = wds.WebDataset(f"{dataset_config['location']}").shuffle(1000).decode("pil")
train_dl = data.DataLoader(train_set, args.batch_size, shuffle=False drop_last=True, num_workers=args.num_workers, persistent_workers=True, pin_memory=False, prefetch_factor=args.prefetch_factor)
train_dl = accelerator.prepare(train_dl)

for step, batch in enumerate(train_dl):
     train_step(...)
```
Typical values I use are `num_workers=8, prefetch_factor=8`.
After an epoch, I get the following error:

```
 File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/redacted/.local/lib/python3.10/site-packages/torch_xla/distributed/parallel_loader.py", line 152, in _loader_worker
    _, data = next(data_iter)
  File "/redacted/.local/lib/python3.10/site-packages/accelerate/data_loader.py", line 449, in __iter__
    dataloader_iter = super().__iter__()
  File "/redacted/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 436, in __iter__
    self._iterator._reset(self)
  File "/redacted/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1118, in _reset
    self._try_put_index()
  File "/redacted/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1349, in _try_put_index
    assert self._tasks_outstanding < self._prefetch_factor * self._num_workers
AssertionError
Begin new epoch
Exception in thread Thread-7 (_loader_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/redacted/.local/lib/python3.10/site-packages/torch_xla/distributed/parallel_loader.py", line 152, in _loader_worker
    _, data = next(data_iter)
  File "/redacted/.local/lib/python3.10/site-packages/accelerate/data_loader.py", line 452, in __iter__
    current_batch = next(dataloader_iter)
  File "/redacted/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/redacted/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1343, in _next_data
    self._task_info[idx] += (data,)
KeyError: _ResumeIteration(seed=None)
```

I wonder if this is because of persistent_workers set to True? 

## Expected behavior

No error, just moving onto a new epoch.

## Environment

 - Reproducible on XLA backend [CPU/TPU/CUDA]: TPU
 - torch_xla version: torch-xla==2.2.0

**Comment by nom** [comment]
Related to https://github.com/pytorch/pytorch/issues/13246
