### ISSUE TITLE
V2.2 failed with Huggingface `Accelerator` on TPUv4-8

### ISSUE THREAD

**Issue by Mon-ius** [pytorch/xla#6765]
## ENV setup
```bash
curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o conda.sh
sudo mkdir -p $DEV_PREFIX && sudo chown -R "$USER:$USER" $DEV_PREFIX
sudo chmod +x conda.sh && bash conda.sh -b -p $CONDA_ROOT_PREFIX && rm conda.sh

. "$CONDA_ROOT_PREFIX/etc/profile.d/conda.sh"

conda create -n xla python=3.11 datasets accelerate evaluate scikit-learn torchvision torchaudio transformers bitsandbytes diffusers segment-anything imageio scipy numpy pyglet trimesh gradio fire -c conda-forge -c pytorch -y
conda activate xla
conda env config vars set LD_LIBRARY_PATH="$CONDA_PREFIX/lib"
conda env config vars set PJRT_DEVICE=TPU
conda env config vars set XLA_USE_BF16=1
conda deactivate && conda activate xla

pip install torch 'torch_xla[tpu]' -f https://storage.googleapis.com/libtpu-releases/index.html

python -c "import torch; import torch_xla.core.xla_model as xm;"
python -c "import torch_xla; print(torch_xla.__version__);"
```

torch version
```bash
python -c "import torch; print(torch.__version__);"
2.2.1
```

xla version
```bash
python -c "import torch_xla; print(torch_xla.__version__);"
2.2.0
```

accelerate version
```bash
python -c "import accelerate; print(accelerate.__version__);"
0.28.0
```

## BUG

```
❯ python
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from accelerate import Accelerator
>>> accelerator = Accelerator()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/dev/conda/envs/xla/lib/python3.11/site-packages/accelerate/accelerator.py", line 371, in __init__
    self.state = AcceleratorState(
                 ^^^^^^^^^^^^^^^^^
  File "/opt/dev/conda/envs/xla/lib/python3.11/site-packages/accelerate/state.py", line 777, in __init__
    PartialState(cpu, **kwargs)
  File "/opt/dev/conda/envs/xla/lib/python3.11/site-packages/accelerate/state.py", line 163, in __init__
    xm.set_replication(self.device, [self.device])
  File "/opt/dev/conda/envs/xla/lib/python3.11/site-packages/torch_xla/core/xla_model.py", line 284, in set_replication
    replication_devices = xla_replication_devices(devices)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dev/conda/envs/xla/lib/python3.11/site-packages/torch_xla/core/xla_model.py", line 252, in xla_replication_devices
    raise RuntimeError(
RuntimeError: Cannot replicate if number of devices (1) is different from 4
>>>
```

**Comment by JackCaoG** [comment]
@vanbasten23 I think you fixed the accelerate recently, any insight on this issue?

**Comment by vanbasten23** [comment]
Can you double check if you are on v2/v3 or v4? IIRC, I have seen similar error on v2/v3 but not on v4.
We have fixed a similar issue on v2/v3 in HF accelerate last week. So, could you install the HF accelerate from source: https://huggingface.co/docs/accelerate/en/basic_tutorials/install#source?

**Comment by Mon-ius** [comment]
Hi @vanbasten23

It's `TPUv4-8`, and I used this to create environment, 

```bash
curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o conda.sh
sudo mkdir -p $DEV_PREFIX && sudo chown -R "$USER:$USER" $DEV_PREFIX
sudo chmod +x conda.sh && bash conda.sh -b -p $CONDA_ROOT_PREFIX && rm conda.sh

. "$CONDA_ROOT_PREFIX/etc/profile.d/conda.sh"

conda create -n xla python=3.11 datasets accelerate evaluate scikit-learn torchvision torchaudio transformers bitsandbytes diffusers segment-anything imageio scipy numpy pyglet trimesh gradio fire -c conda-forge -c pytorch -y
conda activate xla
conda env config vars set LD_LIBRARY_PATH="$CONDA_PREFIX/lib"
conda env config vars set PJRT_DEVICE=TPU
conda env config vars set XLA_USE_BF16=1
conda deactivate && conda activate xla

pip install torch 'torch_xla[tpu]' -f https://storage.googleapis.com/libtpu-releases/index.html

python -c "import torch; import torch_xla.core.xla_model as xm;"
python -c "import torch_xla; print(torch_xla.__version__);"
```
Will compile `accelerate` now 🤗

**Comment by Mon-ius** [comment]
cool~ at least can import 🤗 The `HF` guys action fast, 
```bash
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>     # Run the model in parallel
KeyboardInterrupt
>>> from accelerate import Accelerator
>>> accelerator = Accelerator()
>>>
```
