### ISSUE TITLE
[BUG] GPU/CUDA, V2.3 BrokenProcessPool: process was terminated abruptly

### ISSUE THREAD

**Issue by Mon-ius** [pytorch/xla#6779]
```bash
conda create -n x3 python=3.10 cuda -c nvidia -y
conda activate x3

conda env config vars set LD_LIBRARY_PATH="$CONDA_PREFIX/lib"
conda env config vars set HF_HOME=/dev/shm
conda env config vars set PJRT_DEVICE=CUDA
conda env config vars set CUDA_NUM_DEVICES=4
conda env config vars set GPU_NUM_DEVICES=4

pip install torch==2.3.0.dev20240315+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
pip install https://storage.googleapis.com/pytorch-xla-releases/wheels/cuda/12.1/torch_xla-2.3.0rc2-cp310-cp310-linux_x86_64.whl

python -c "import torch; print(torch.__version__, torch.version.cuda);"
python -c "import torch_xla; print(torch_xla.__version__);"
python -c "import torch; import torch_xla.core.xla_model as xm;"

echo 'import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr
num_devices = xr.global_runtime_device_count()
print(num_devices)

dev = xm.xla_device()
t1 = torch.randn(3,3,device=dev)
t2 = torch.randn(3,3,device=dev)
print(t1 + t2)' | tee /tmp/run.py

PJRT_DEVICE=CUDA GPU_NUM_DEVICES=4 python /tmp/run.py
git clone -j8 --depth 1 --branch main https://github.com/pytorch/xla.git
PJRT_DEVICE=CUDA GPU_NUM_DEVICES=4 python xla/test/test_train_mp_imagenet.py --fake_data
```

Version:
```bash
❯ python -c "import torch; print(torch.__version__, torch.version.cuda);"                                                                  (x5)
  python -c "import torch_xla; print(torch_xla.__version__);"
  python -c "import torch; import torch_xla.core.xla_model as xm;"
2.3.0.dev20240315+cu121 12.1
2.3.0-rc2
```

Simple dev num test:
```bash

echo 'import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr
num_devices = xr.global_runtime_device_count()
print(num_devices)

dev = xm.xla_device()
t1 = torch.randn(3,3,device=dev)
t2 = torch.randn(3,3,device=dev)
print(t1 + t2)' | tee /tmp/run.py

PJRT_DEVICE=CUDA GPU_NUM_DEVICES=4 python /tmp/run.py

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1710914446.889451  872685 service.cc:145] XLA service 0x65bb140 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1710914446.892681  872685 se_gpu_pjrt_client.cc:853] Using BFC allocator.
I0000 00:00:1710914446.892785  872685 gpu_helpers.cc:107] XLA backend allocating 19078594560 bytes on device 0 for BFCAllocator.
I0000 00:00:1710914446.892850  872685 gpu_helpers.cc:107] XLA backend allocating 19076825088 bytes on device 1 for BFCAllocator.
I0000 00:00:1710914446.892916  872685 gpu_helpers.cc:107] XLA backend allocating 19078594560 bytes on device 2 for BFCAllocator.
I0000 00:00:1710914446.892959  872685 gpu_helpers.cc:107] XLA backend allocating 19078594560 bytes on device 3 for BFCAllocator.
I0000 00:00:1710914446.893025  872685 gpu_helpers.cc:147] XLA backend will use up to 6359531520 bytes on device 0 for CollectiveBFCAllocator.
I0000 00:00:1710914446.893075  872685 gpu_helpers.cc:147] XLA backend will use up to 6358941696 bytes on device 1 for CollectiveBFCAllocator.
I0000 00:00:1710914446.893123  872685 gpu_helpers.cc:147] XLA backend will use up to 6359531520 bytes on device 2 for CollectiveBFCAllocator.
I0000 00:00:1710914446.893164  872685 gpu_helpers.cc:147] XLA backend will use up to 6359531520 bytes on device 3 for CollectiveBFCAllocator.
4
tensor([[-0.2121,  1.5588, -0.6952],
        [-0.7885, -0.2022,  0.9242],
        [ 0.8555, -1.8699,  1.4333]], device='xla:0')
```

MP error Log:
```bash
git clone -j8 --depth 1 --branch main https://github.com/pytorch/xla.git
PJRT_DEVICE=CUDA GPU_NUM_DEVICES=4 python xla/test/test_train_mp_imagenet.py --fake_data

I0000 00:00:1710914256.418632  870291 se_gpu_pjrt_client.cc:853] Using BFC allocator.
I0000 00:00:1710914256.418725  870291 gpu_helpers.cc:107] XLA backend allocating 19076825088 bytes on device 1 for BFCAllocator.
I0000 00:00:1710914256.418756  870291 gpu_helpers.cc:147] XLA backend will use up to 6358941696 bytes on device 1 for CollectiveBFCAllocator.
I0000 00:00:1710914256.419108  870289 se_gpu_pjrt_client.cc:853] Using BFC allocator.
I0000 00:00:1710914256.419206  870289 gpu_helpers.cc:107] XLA backend allocating 19078594560 bytes on device 3 for BFCAllocator.
I0000 00:00:1710914256.419273  870289 gpu_helpers.cc:147] XLA backend will use up to 6359531520 bytes on device 3 for CollectiveBFCAllocator.
/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/core/xla_model.py:104: UserWarning: `devkind` argument is deprecated and will be removed in a future release.
  warnings.warn("`devkind` argument is deprecated and will be removed in a "
/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
==> Preparing data..
/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/core/xla_model.py:104: UserWarning: `devkind` argument is deprecated and will be removed in a future release.
  warnings.warn("`devkind` argument is deprecated and will be removed in a "
/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/core/xla_model.py:104: UserWarning: `devkind` argument is deprecated and will be removed in a future release.
  warnings.warn("`devkind` argument is deprecated and will be removed in a "
/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
==> Preparing data..
/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
==> Preparing data..
/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/core/xla_model.py:104: UserWarning: `devkind` argument is deprecated and will be removed in a future release.
  warnings.warn("`devkind` argument is deprecated and will be removed in a "
/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)
==> Preparing data..
I0000 00:00:1710914259.379369  871415 asm_compiler.cc:379] ptxas warning : Registers are spilled to local memory in function 'loop_multiply_fusion_35', 164 bytes spill stores, 164 bytes spill loads

Epoch 1 train begin 13:57:39
I0000 00:00:1710914259.538069  871486 asm_compiler.cc:379] ptxas warning : Registers are spilled to local memory in function 'loop_multiply_fusion_35', 164 bytes spill stores, 164 bytes spill loads

I0000 00:00:1710914259.547065  871505 asm_compiler.cc:379] ptxas warning : Registers are spilled to local memory in function 'loop_multiply_fusion_35', 164 bytes spill stores, 164 bytes spill loads

I0000 00:00:1710914259.556020  871626 asm_compiler.cc:379] ptxas warning : Registers are spilled to local memory in function 'loop_multiply_fusion_35', 164 bytes spill stores, 164 bytes spill loads

double free or corruption (out)
double free or corruption (!prev)
double free or corruption (!prev)
I0000 00:00:1710914261.790868  872191 asm_compiler.cc:379] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_2180', 660 bytes spill stores, 368 bytes spill loads

I0000 00:00:1710914261.830193  872189 asm_compiler.cc:379] ptxas warning : Registers are spilled to local memory in function 'triton_gemm_dot_2180', 8 bytes spill stores, 8 bytes spill loads

Traceback (most recent call last):
  File "/data/xla/test/test_train_mp_imagenet.py", line 377, in <module>
    xmp.spawn(_mp_fn, args=(FLAGS,), nprocs=FLAGS.num_cores)
  File "/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/runtime.py", line 95, in wrapper
    return fn(*args, **kwargs)
  File "/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 38, in spawn
    return pjrt.spawn(fn, nprocs, start_method, args)
  File "/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 211, in spawn
    run_multiprocess(spawn_fn, start_method=start_method)
  File "/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/runtime.py", line 95, in wrapper
    return fn(*args, **kwargs)
  File "/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 171, in run_multiprocess
    replica_results = list(
  File "/data/.dev/conda/envs/x5/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 172, in <genexpr>
    itertools.chain.from_iterable(
  File "/data/.dev/conda/envs/x5/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/data/.dev/conda/envs/x5/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/data/.dev/conda/envs/x5/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/data/.dev/conda/envs/x5/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/data/.dev/conda/envs/x5/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by JackCaoG** [comment]
Seems like it is caused by `double free or corruption (out)`. I know that recent OpenXLA pin update has caused us some issues on GPU. @zpcore and @vanbasten23 are looking into that right now.

**Comment by Mon-ius** [comment]
Glad to learn that, saw a PR to fixed it 🤗
