### ISSUE TITLE
[torchbench] `hf_Reformer` fails to run training on dynamo.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/xla#6830]
## 🐛 Bug

Running the upstreamed benchmarking scripts with the following command results in an unexpected error.

```bash
python xla/benchmarks/experiment_runner.py \
       --suite-name torchbench \
       --accelerator cuda \
       --xla PJRT \
       --dynamo openxla \
       --test train \
       --repeat 8 --iterations-per-run 1 \
       --print-subprocess \
       --no-resume -k hf_Reformer
```

```python
Traceback (most recent call last):
  File "xla/benchmarks/experiment_runner.py", line 945, in <module>
    main()
  File "xla/benchmarks/experiment_runner.py", line 941, in main
    runner.run()
  File "xla/benchmarks/experiment_runner.py", line 61, in run
    self.run_single_config()
  File "xla/benchmarks/experiment_runner.py", line 256, in run_single_config
    metrics, last_output = self.run_once_and_gather_metrics(
  File "xla/benchmarks/experiment_runner.py", line 345, in run_once_and_gather_metrics
    output, _ = loop(iter_fn=self._default_iter_fn)
  File "xla/benchmarks/experiment_runner.py", line 302, in loop
    output, timing, trace = iter_fn(benchmark_experiment, benchmark_model,
  File "xla/benchmarks/experiment_runner.py", line 218, in _default_iter_fn
    output = benchmark_model.model_iter_fn(
  File "torch/_dynamo/eval_frame.py", line 390, in _fn
    return fn(*args, **kwargs)
  File "xla/benchmarks/torchbench_model.py", line 418, in train
    super().train(inputs, collect_full_output=collect_full_output)
  File "xla/benchmarks/benchmark_model.py", line 156, in train
    self._optimizer_zero_grad()
  File "xla/benchmarks/benchmark_model.py", line 158, in torch_dynamo_resume_in_train_at_156
    pred = self.module(*inputs)
  File "torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 2404, in forward
    reformer_outputs = self.reformer(
  File "torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 2004, in forward
    @add_start_docstrings_to_model_forward(REFORMER_INPUTS_DOCSTRING)
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 2061, in torch_dynamo_resume_in_forward_at_2061
    input_shape[-1] % least_common_mult_chunk_length != 0
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 2101, in torch_dynamo_resume_in_forward_at_2066
    encoder_outputs = self.encoder(
  File "torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 1727, in forward
    hidden_states = _ReversibleFunction.apply(
  File "torch/autograd/function.py", line 606, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 1615, in forward
    layer_outputs = layer(
  File "torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 1478, in forward
    self._init_attention_seed()
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 1503, in torch_dynamo_resume_in_forward_at_1478
    self._init_feed_forward_seed()
  File "/lib/python3.8/site-packages/transformers/models/reformer/modeling_reformer.py", line 1503, in torch_dynamo_resume_in_forward_at_1503
    self._init_feed_forward_seed()
  File "torch/_dynamo/eval_frame.py", line 390, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 917, in forward
    return compiled_fn(full_args)
  File "torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 107, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 181, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "torch/_dynamo/backends/torchxla.py", line 36, in fwd
    compiled_graph = bridge.extract_compiled_graph(model, args)
  File "xla/torch_xla/core/dynamo_bridge.py", line 617, in extract_compiled_graph
    xm.mark_step()
  File "xla/torch_xla/core/xla_model.py", line 1056, in mark_step
    torch_xla._XLAC._xla_step_marker(
RuntimeError: Bad StatusOr access: INVALID_ARGUMENT: Executable expected shape f16[4,12,4096,64]{3,2,1,0} for argum
ent 4 but got incompatible shape f64[4,12,4096,64]{3,2,1,0}
```

## Environment

- PyTorch Commit: a52b4e22571507abc35c2d47de138497190d2e0a
- PyTorch/XLA Commit: 84e7feb302374f9f9916869129e72c698bdee5bf
- PyTorch/benchmark Commit: d6015d42d9a1834bc7595c4bd6852562fb80b30b

cc @miladm @JackCaoG @vanbasten23 @zpcore @frgossen @golechwierowicz @cota

**Comment by zpcore** [comment]
Same cause of https://github.com/pytorch/xla/issues/6831, close for now.
