### ISSUE TITLE
[torchbench] `hf_GPT2` and `hf_GPT2_large` training fails to run on dynamo.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/xla#6900]
## 🐛 Bug

`hf_GPT2` and `hf_GPT2_large` training fails to run on dynamo. See the error below:

```bash
python xla/benchmarks/experiment_runner.py \
    --suite-name torchbench --accelerator cuda --repeat 8 --iterations-per-run 1 \
    --xla PJRT --dynamo None --test train \
    -k hf_GPT2
```

```python
Traceback (most recent call last):
  File "xla/benchmarks/experiment_runner.py", line 945, in <module>
    main()
  File "xla/benchmarks/experiment_runner.py", line 941, in main
    runner.run()
  File "xla/benchmarks/experiment_runner.py", line 61, in run
    self.run_single_config()
  File "xla/benchmarks/experiment_runner.py", line 256, in run_single_config
    metrics, last_output = self.run_once_and_gather_metrics(
  File "xla/benchmarks/experiment_runner.py", line 345, in run_once_and_gather_metrics
    output, _ = loop(iter_fn=self._default_iter_fn)
  File "xla/benchmarks/experiment_runner.py", line 302, in loop
    output, timing, trace = iter_fn(benchmark_experiment, benchmark_model,
  File "xla/benchmarks/experiment_runner.py", line 218, in _default_iter_fn
    output = benchmark_model.model_iter_fn(
  File "torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "xla/benchmarks/torchbench_model.py", line 400, in train
    super().train(inputs, collect_full_output=collect_full_output)
  File "xla/benchmarks/benchmark_model.py", line 156, in train
    self._optimizer_zero_grad()
  File "xla/benchmarks/benchmark_model.py", line 156, in torch_dynamo_resume_in_train_at_156
    self._optimizer_zero_grad()
  File "torch/_dynamo/eval_frame.py", line 410, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 917, in forward
    return compiled_fn(full_args)
  File "torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "torch/_functorch/_aot_autograd/runtime_wrappers.py", line 89, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "torch/autograd/function.py", line 569, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 560, in forward
    fw_outs = call_func_at_runtime_with_args(
  File "torch/_functorch/_aot_autograd/utils.py", line 113, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "torch/_functorch/_aot_autograd/utils.py", line 89, in g
    return f(*args)
  File "torch/_dynamo/backends/torchxla.py", line 38, in fwd
    return compiled_graph(*args)
  File "torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/fx/_lazy_graph_module.py", line 123, in _lazy_forward
    return self(*args, **kwargs)
  File "torch/fx/graph_module.py", line 737, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "torch/fx/graph_module.py", line 317, in __call__
    raise e
  File "torch/fx/graph_module.py", line 304, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "<eval_with_key>.1", line 5, in forward
  File "xla/torch_xla/core/dynamo_bridge.py", line 498, in optimized_mod
    res = dumb_return_handler.addDumbReturn(args, res)
  File "xla/torch_xla/core/dynamo_bridge.py", line 245, in addDumbReturn
    ret = self.deduper.recover(real_outputs)
  File "xla/torch_xla/core/dynamo_bridge.py", line 196, in recover
    return [deduped_list[i] for i in self.permute_for_orig]
  File "xla/torch_xla/core/dynamo_bridge.py", line 196, in <listcomp>
    return [deduped_list[i] for i in self.permute_for_orig]
IndexError: list index out of range
ERROR:root:Caught an exception when exiting the process. Exception:
Traceback (most recent call last):
  File "xla/torch_xla/__init__.py", line 162, in _prepare_to_exit
    _XLAC._prepare_to_exit()
RuntimeError: Bad StatusOr access: INVALID_ARGUMENT: Executable expected shape f32[768,3072]{1,0} for argument 5 but got incompatible shape f16[]
```

## Affected Configurations

- Training+Dynamo

## Environment

 - Reproducible on XLA backend [CPU/TPU]: CUDA
 - torch_xla version: 5c48be19e6ded305bb524b3d1231fd4ce4d46208

cc @miladm @JackCaoG @vanbasten23 @cota @golechwierowicz @frgossen @zpcore

**Comment by ysiraichi** [comment]
Closing, since I can't seem to reproduce this.

**Comment by ysiraichi** [comment]
Oops. Actually, I can.
