### ISSUE TITLE
[torchbench] `drq` training fails to run on non-dynamo.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/xla#7247]
## 🐛 Bug

Running the upstreamed benchmarking scripts with the following command results in an unexpected error.

```bash
python xla/benchmarks/experiment_runner.py \
       --suite-name torchbench \
       --accelerator cuda \
       --xla PJRT \
       --dynamo None \
       --test train \
       --repeat 30 --iterations-per-run 5 \
       --print-subprocess \
       --no-resume -k drq
```

```python
Traceback (most recent call last):
  File "xla/benchmarks/experiment_runner.py", line 963, in <module>
    main()
  File "xla/benchmarks/experiment_runner.py", line 959, in main
    runner.run()
  File "xla/benchmarks/experiment_runner.py", line 61, in run
    self.run_single_config()
  File "xla/benchmarks/experiment_runner.py", line 257, in run_single_config
    metrics, last_output = self.run_once_and_gather_metrics(
  File "xla/benchmarks/experiment_runner.py", line 349, in run_once_and_gather_metrics
    output, _ = loop(iter_fn=self._default_iter_fn)
  File "xla/benchmarks/experiment_runner.py", line 306, in loop
    output, timing, trace = iter_fn(benchmark_experiment, benchmark_model,
  File "xla/benchmarks/experiment_runner.py", line 219, in _default_iter_fn
    output = benchmark_model.model_iter_fn(
  File "xla/benchmarks/torchbench_model.py", line 413, in train
    super().train(inputs, collect_full_output=collect_full_output)
  File "xla/benchmarks/benchmark_model.py", line 181, in train
    pred = self.module(*inputs)
  File "torch/nn/modules/module.py", line 1558, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1567, in _call_impl
    return forward_call(*args, **kwargs)
  File "benchmark/torchbenchmark/models/drq/drq.py", line 109, in forward
    dist = drqutils.SquashedNormal(mu, std)
  File "benchmark/torchbenchmark/models/drq/drqutils.py", line 160, in __init__
    self.base_dist = pyd.Normal(loc, scale)
  File "torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "torch/distributions/distribution.py", line 69, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (1, 1)) of distribution Normal(loc: tensor([[nan]], device='xla:0', dtype=torch.float16, grad_fn=<SplitBackward0>), scale: tensor([[nan]], device='xla:0', grad_fn=<ExpBackward0>)) to satisfy the constraint Real(), but found invalid values:
tensor([[nan]], device='xla:0', dtype=torch.float16, grad_fn=<SplitBackward0>)
```

## Environment

 - Reproducible on XLA backend [CPU/TPU/CUDA]: CUDA
 - torch_xla version: aec273056a95d8119279c15d36c0f48f739fb810

cc @miladm @lezcano

**Comment by miladm** [comment]
DRQ Paper: https://ieeexplore.ieee.org/document/9138970

**Comment by ysiraichi** [comment]
Closing, since I can't reproduce it.
