### ISSUE TITLE
Op info test for `linalg.tensorsolve .. log_normal`

### ISSUE THREAD

**Issue by qihqi** [pytorch/xla#7505]
## Fix the Op info test for `linalg.tensorsolve .. log_normal`

1. Find the lines 143 to 147 of [test_ops.py](test/test_ops.py) and remove
   `linalg.tensorsolve` .. `log_normal` from `skip_list`
2. Run op_info test with `pytest test/test_ops.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/fixing_op_info_test.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7343
* https://github.com/pytorch/xla/pull/7312
* https://github.com/pytorch/xla/pull/7325

**Comment by barney-s** [comment]
@ManfeiBai - Iam working on this

**Comment by barney-s** [comment]
## trying linspace:

One of the failing test logs:
```
testcase = <test.test_ops.TestOpInfoCPU testMethod=test_reference_eager_linspace_tensor_overload_cpu_float32>, output1 = tensor([-2.]), output2 = tensor(-2.)
rtol = 1e-05, atol = 0.001, equal_nan = True, check_output = True


E         AssertionError: The values for attribute 'shape' do not match: torch.Size([]) != torch.Size([1]).
E         To execute this test, run the following from the base repo dir:
E              python test/test_ops.py -k TestOpInfoCPU.test_reference_eager_linspace_tensor_overload_cpu_float32
E         This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------
[DEBUG] sample_input:  SampleInput(input=-2.0, args=(tensor(-3), 0), kwargs={'dtype': torch.int64, 'device': 'cpu'}, broadcasts_input=False, name='')
[DEBUG] sample_input:  SampleInput(input=-2.0, args=(-3, 0), kwargs={'dtype': torch.int64, 'device': 'cpu'}, broadcasts_input=False, name='')
[DEBUG] sample_input:  SampleInput(input=-2.0, args=(tensor(-3), 0), kwargs={'dtype': torch.int64, 'device': 'cpu'}, broadcasts_input=False, name='')
[DEBUG] sample_input:  SampleInput(input=-2.0, args=(tensor(-3), 1), kwargs={'dtype': torch.int64, 'device': 'cpu'}, broadcasts_input=False, name='')

```

The `output2` is a `tensor(-2)` ? Is this a scalar ? vs `output1` being `tensor([-2])`

Taking the last sample input and calling in a test script:

```
import torch
import torch_xla2

env = torch_xla2.default_env()
env.config.debug_print_each_op = True
#env.config.debug_accuracy_for_each_op = True

with env:
  print(torch.linspace(-2, -3, 1))

--------------------- [output]:
 % python test_logspace.py   
/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:270: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
FUNCTION: linspace
 DISPATCH: aten::linspace
  FUNCTION: full
XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [-2.])
```

The call is returning a Jax array of len 1.

**Comment by barney-s** [comment]
Investigating further, the testcases that are failing is using `tensor(int)` as input to the `linspace`. Pytorch linspace allows using 0D tensor (scalar). But passing that to the xla env, fails:

```
import torch
import torch_xla2

env = torch_xla2.default_env()
env.config.debug_print_each_op = True
#env.config.debug_accuracy_for_each_op = True

with env:
  print("torch_xla2.linspace:", torch.linspace(-2, -3, 1))
  print("\n")
  print("torch_xla2.linspace:", torch.linspace(torch.Tensor(-2), torch.Tensor(-3), 1))
print("native torch:", torch.linspace(-2, -3, 1))


---------------------------[output]:
 % python test_logspace.py
/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:270: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
FUNCTION: linspace
 DISPATCH: aten::linspace
  FUNCTION: full
torch_xla2.linspace: XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [-2.])

DISPATCH: aten::empty.memory_format
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/test_logspace.py", line 14, in <module>
    print("torch_xla2.linspace:", torch.linspace(torch.Tensor(-2), torch.Tensor(-3), 1))
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/tensor.py", line 227, in __torch_dispatch__
    return self.env.dispatch(func, types, args, kwargs)
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/tensor.py", line 430, in dispatch
    res = op.func(*args, **kwargs)
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/ops/op_base.py", line 63, in wrapper
    return func(*args, dtype=jax_dtype, **kwargs)
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/ops/jaten.py", line 502, in _aten_empty
    return jnp.empty(size, dtype=dtype)
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 3271, in empty
    return zeros(shape, dtype, device=device)
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 3252, in zeros
    return lax.full(shape, 0, _jnp_dtype(dtype), sharding=_normalize_to_sharding(device))
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 1284, in full
    return broadcast(fill_value, shape)
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 829, in broadcast
    return broadcast_in_dim(operand, tuple(sizes) + np.shape(operand), dims)
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 858, in broadcast_in_dim
    return broadcast_in_dim_p.bind(
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/core.py", line 416, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/core.py", line 420, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/core.py", line 909, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
    outs = fun(*args)
TypeError: broadcast_in_dim shape must have every element be nonnegative, got (-2,).
barni@barni ~/workspace/pytorch/xla/experimental/torch_xla2
```

**Comment by barney-s** [comment]
Investigating `torch.empty` and `torch.full` further.  using torch.empty and copying in a 0D tensor, results in a return tensor that is not a 0D tensor.  All other cases returns a 0D tensor.

```
import torch
import torch_xla2

env = torch_xla2.default_env()
env.config.debug_print_each_op = True
#env.config.debug_accuracy_for_each_op = True

with env:
  print("torch.empty:", torch.empty((1,)).copy_(torch.tensor(-2)))
  print("torch.full:", torch.full((1,), torch.tensor(-2)))

print("torch.empty:", torch.empty((1,)).copy_(torch.tensor(-2)))
print("torch.full:", torch.full((1,), torch.tensor(-2)))


-------------------[output]:
% python test_logspace.py
/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:270: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
FUNCTION: empty
FUNCTION: tensor
/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/ops/jtorch.py:48: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in array is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  return jnp.array(
FUNCTION: copy_
 DISPATCH: aten::copy_
torch.empty: XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> -2.0)
FUNCTION: tensor
/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/ops/jtorch.py:48: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in array is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  return jnp.array(
FUNCTION: full
torch.full: XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [-2.])
torch.empty: tensor([-2.])
torch.full: tensor([-2])
```

**Comment by ManfeiBai** [comment]
Thanks for the investigation here, is it possible to modify [`_aten_copy`](https://github.com/pytorch/xla/blob/14d14aec5ed5e972de1ade1f5d91b10eeab97685/experimental/torch_xla2/torch_xla2/ops/jaten.py#L103) implementation to wrap it with array or increase dimension? if I understand correct

**Comment by barney-s** [comment]
Trying this patch, some of the failure go away for `linspace`.
```
@op(torch.ops.aten.copy_, is_jax_function=False)
def _aten_copy(x, y, memory_format=None):
  x._elem = y._elem.astype(x._elem.dtype)
  if x.ndim == 1 and y.ndim == 0:
    # case of torch.empty((1,)).copy_(tensor(N))
    # we need to return 0D tensor([N]) and not scalar tensor(N)
    # ref: https://github.com/pytorch/xla/issues/7505#issuecomment-2395319131
    x._elem = jnp.array([y._elem.astype(x._elem.dtype)])
  else:
    x._elem = y._elem.astype(x._elem.dtype)
  return x
```

But it introduces failures for `nanquantile`. Investigating that found that `squeeze_` behavior is changed:

```
def squeeze(): 
  with env:
    t1 = torch.tensor([-3.5])
    r1 = t1.squeeze_(-1)
    print("xla   | torch.squeeze :", r1)
  t1 = torch.tensor([-3.5])
  r1 = t1.squeeze_(-1)
  print("native| torch.squeeze :", r1)
```

output:
```
FUNCTION: tensor
FUNCTION: squeeze_
 DISPATCH: aten::squeeze_.dim
  FUNCTION: squeeze
  FUNCTION: copy_
   DISPATCH: aten::copy_
xla   | torch.squeeze : XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [-3.5])
native| torch.squeeze : tensor(-3.5000)
```

**Comment by qihqi** [comment]
copy_ should behave identically as original torch.copy_ should behave.

From here: https://pytorch.org/docs/stable/generated/torch.Tensor.copy_.html it's not about scaler vs rank 1; but about src's shape is perserving.

So `torch.empty((2,2)).copy(1)` should be a `2 x 2` tensor of all 1s etc.

So something along the lines of:

```
def _aten_copy(x, y, memory_format=None):
  orig_shape = x._elem.shape
  orig_dtype = x._elem.dtype
  x._elem = y._elem.expand_dims(orig_shape).astype(orig_dtype)

  return x
```
should work

**Comment by barney-s** [comment]
With fixes in #8236 , most tests are passing:
1. fix _copy to handle self shape=(1) and copy src shape=0
2. for squeeze where we expect the self's shape to change, dont use copy_ instead replace.

Remaining failure can be reduced to behavior  similar to this input:
```
xla   | torch_xla2.linspace(4.9, 3, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 4 3 3 3])
native| torch_xla2.linspace(4.9, 3, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
```

**Comment by ManfeiBai** [comment]
> linspace(4.9, 3, 5, dtype=torch.int64)

tried locally too with `barney-s:linspace` branch, it looks like round calculation might be one of the reason: for `end-start` < -1, and end with `x.1` ~ `x.3` will met issue like this

```
# mismatched
xla   | torch_xla2.linspace(4.9, 3, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4, 4, 3, 3, 3])
native| torch_xla2.linspace(4.9, 3, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# mismatched
xla   | torch_xla2.linspace(4.4, 3, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4, 4, 3, 3, 3])
native| torch_xla2.linspace(4.4, 3, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(4.3, 3, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 3 3])
native| torch_xla2.linspace(4.3, 3, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(4.0, 3, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 3 3])
native| torch_xla2.linspace(4.0, 3, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(4, 3.0, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 3 3])
native| torch_xla2.linspace(4, 3.0, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(4, 3.3, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 3 3])
native| torch_xla2.linspace(4, 3.3, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(4, 3.4, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 3 3])
native| torch_xla2.linspace(4, 3.4, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(4, 3.5, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 3 3])
native| torch_xla2.linspace(4, 3.5, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(4, 3.6, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 3 3])
native| torch_xla2.linspace(4, 3.6, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(4, 3.8, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 3 3])
native| torch_xla2.linspace(4, 3.8, 5, dtype=torch.int64):  tensor([4, 3, 3, 3, 3])
---
# mismatched
xla   | torch_xla2.linspace(4, 2.9, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4, 3, 3, 3, 2])
native| torch_xla2.linspace(4, 2.9, 5, dtype=torch.int64):  tensor([4, 3, 3, 2, 2])
---
# MATCHED
xla   | torch_xla2.linspace(4, 2.5, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 2 2])
native| torch_xla2.linspace(4, 2.5, 5, dtype=torch.int64):  tensor([4, 3, 3, 2, 2])
---
# mismatched
xla   | torch_xla2.linspace(4, 2.7, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4, 3, 3, 3, 2])
native| torch_xla2.linspace(4, 2.7, 5, dtype=torch.int64):  tensor([4, 3, 3, 2, 2])
---
# MATCHED
xla   | torch_xla2.linspace(4, 2.6, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4 3 3 2 2])
native| torch_xla2.linspace(4, 2.6, 5, dtype=torch.int64):  tensor([4, 3, 3, 2, 2])
---
# mismatched
xla   | torch_xla2.linspace(4, 1.9, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [4, 3, 2, 2, 1])
native| torch_xla2.linspace(4, 1.9, 5, dtype=torch.int64):  tensor([4, 3, 2, 1, 1])
---
# missmatched
xla   | torch_xla2.linspace(5, 3.9, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [5, 4, 4, 4, 3])
native| torch_xla2.linspace(5, 3.9, 5, dtype=torch.int64):  tensor([5, 4, 4, 3, 3])
---
# MATCHED
xla   | torch_xla2.linspace(5, 6.1, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [5 5 5 5 6])
native| torch_xla2.linspace(5, 6.1, 5, dtype=torch.int64):  tensor([5, 5, 5, 5, 6])
---
# MATCHED
xla   | torch_xla2.linspace(5, 2.0, 5, dtype=torch.int64):  XLATensor2(<class 'jaxlib.xla_extension.ArrayImpl'> [5 4 3 2 2])
native| torch_xla2.linspace(5, 2.0, 5, dtype=torch.int64):  tensor([5, 4, 3, 2, 2])
```

**Comment by qihqi** [comment]
Looks like there is a bug in torch's linspace: https://github.com/pytorch/pytorch/issues/137546

**Comment by barney-s** [comment]
tested jaten.py implementation as well xla's pytorch decomposition.

For the float dtype output matches.
For the int64 dtype the output dont match for both jax as well as pytorch decomposition when compared with native. !! 

So its to do with rounding logic when converting from float to int !! And it should be done after the initial generation.

xla override (jax implementation):
```
@register_function(torch.linspace)
def linspace(start, end=None, steps=None, 
  out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False):
  new_start = start
  new_end = end
  #new_start = jax.lax.convert_element_type(start, mappings.t2j_dtype(dtype))
  #new_end = jax.lax.convert_element_type(end, mappings.t2j_dtype(dtype))
  if dtype is not None:
    dtype=mappings.t2j_dtype(dtype)
  ret = jnp.linspace(new_start, new_end, steps,
                      endpoint=True,
                      #dtype=dtype,
                      )
  return jnp.astype(ret, dtype)def linspace(): 
```

test script:
```
  dtype=torch.float
  with env:
    print("xla   | torch.linspace(): ", torch.linspace(4.9, 3, 5, dtype=dtype))
  print("native| torch.linspace(): ", torch.linspace(4.9, 3, 5, dtype=dtype))
  with env:
    print("xla   | torch.linspace(): ", torch.linspace(-2, -3, 50, dtype=dtype))
  print("native| torch.linspace(): ", torch.linspace(-2, -3, 50, dtype=dtype))
  with env:
    print("xla   | torch.linspace(): ", torch.linspace(4.3, -3, 50, dtype=dtype))
  print("native| torch.linspace(): ", torch.linspace(4.3, -3, 50, dtype=dtype))
```

**Comment by barney-s** [comment]
## Working on log_normal.

log_normal has a pytroch decomposition: https://github.com/pytorch/pytorch/pull/91674 
So registering it with xla: https://github.com/pytorch/xla/pull/8247/
Since the nature of the api is non-deterministic, regular test methodology of diffing xla and native output wont work (https://github.com/pytorch/xla/blob/07d0823f2c33e83673787d53dc4c3e5bdf292449/experimental/torch_xla2/test/test_ops.py#L211).

Ref: 
* pytorch test library annotation for log_normal: https://github.com/pytorch/pytorch/blob/5516ac5c218dc05928860c91563c6f01ceac4808/torch/testing/_internal/common_methods_invocations.py#L11954

**Comment by barney-s** [comment]
### Working on `linalg.vector_norm`

#### attempt 0

tests failing:
```
[DEBUG] op:  linalg.vector_norm , sample_input:  SampleInput(input=-0.06738138198852539, args=(), kwargs={'ord': 0}, broadcasts_input=False, name='')
[DEBUG] input: torch.float32
output2 tensor(1., dtype=torch.float64)  , output1 tensor(1.)

...

FAILED test/test_ops.py::TestOpInfoCPU::test_reference_eager_linalg_vector_norm_cpu_float32 - AssertionError: The values for attribute 'dtype' do not match: torch.float64 != torch.float32.
```

Trying out in a script:
```python
import torch
import torch_xla2
import jax.numpy as jnp

env = torch_xla2.default_env()
env.config.debug_print_each_op = True

def linalg_vector_norm():
  with env:
    t = torch.tensor(-0.06738138198852539)
    print("xla   | linalg.vector_norm()", torch.linalg.vector_norm(t, ord=0).dtype)
  t = torch.tensor(-0.06738138198852539)
  print("native| linalg.vector_norm()", torch.linalg.vector_norm(t, ord=0).dtype)
  
linalg_vector_norm()
```

output:

```
FUNCTION: tensor
FUNCTION: linalg_vector_norm
 DISPATCH: aten::linalg_vector_norm
xla   | linalg.vector_norm() torch.float32
native| linalg.vector_norm() torch.float32
```

#### attempt 1

**Comment by barney-s** [comment]
### working on `linalg.vectorsolve`

#### attempt 1

Test Failure seen
```
FAILED test/test_ops.py::TestOpInfoCPU::test_reference_eager_linalg_tensorsolve_cpu_float32 - RuntimeError: Expected Tensor but got None
```

debug script:
```python
import torch
import torch_xla2
import jax.numpy as jnp

env = torch_xla2.default_env()
env.config.debug_print_each_op = True

def linalg_vector_norm():
  with env:
    t = torch.tensor(-0.06738138198852539)
    print("xla   | linalg.vector_norm()", torch.linalg.vector_norm(t, ord=0).dtype)
  t = torch.tensor(-0.06738138198852539)
  print("native| linalg.vector_norm()", torch.linalg.vector_norm(t, ord=0).dtype)
  
def linalg_tensorsolve():
  with env:
    A = torch.tensor([[[-0.0674,  4.8280, -7.4074, -6.6235, -3.4664,  2.4134],
         [-0.1783,  7.1360, -0.7987,  2.3815, -2.7199, -1.7691],
         [-8.5981, -5.9605, -3.7100,  0.3334,  3.5580,  5.4002]],
        [[-6.1015, -3.9192,  3.2690,  7.4735, -1.8522,  6.7348],
         [-1.4507,  0.9523,  8.1493, -8.3490, -5.6658, -2.2785],
         [-3.5082,  7.7760, -5.8336, -4.1430, -6.2878, -8.4290]]])
    B = torch.tensor([[-5.2537,  7.7364,  4.0160],
        [ 4.3621,  0.4733, -4.6142]])
    print("xla   | linalg.vectorsolve()", torch.linalg.tensorsolve(A, B))
  A = torch.tensor([[[-0.0674,  4.8280, -7.4074, -6.6235, -3.4664,  2.4134],
         [-0.1783,  7.1360, -0.7987,  2.3815, -2.7199, -1.7691],
         [-8.5981, -5.9605, -3.7100,  0.3334,  3.5580,  5.4002]],
        [[-6.1015, -3.9192,  3.2690,  7.4735, -1.8522,  6.7348],
         [-1.4507,  0.9523,  8.1493, -8.3490, -5.6658, -2.2785],
         [-3.5082,  7.7760, -5.8336, -4.1430, -6.2878, -8.4290]]])
  B = torch.tensor([[-5.2537,  7.7364,  4.0160],
        [ 4.3621,  0.4733, -4.6142]])
  print("native| linalg.vectorsolve()", torch.linalg.tensorsolve(A, B))
  
linalg_tensorsolve()
```

debug script output:
```
%      python test_logspace.py
/usr/local/google/home/barni/miniconda3/envs/torch_xla2/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:270: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
WARNING:root:Duplicate op registration for aten.trunc
FUNCTION: tensor
FUNCTION: tensor
FUNCTION: linalg_tensorsolve
 DISPATCH: aten::view
 DISPATCH: aten::view
 DISPATCH: aten::_linalg_solve_ex
[DEBUG]: linalg_solve_ex ret: [-1.2417108   2.068498    1.2399809   0.08891661  2.002629    0.576693  ]
Traceback (most recent call last):
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/test_logspace.py", line 125, in <module>
    linalg_tensorsolve()
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/test_logspace.py", line 108, in linalg_tensorsolve
    print("xla   | linalg.vectorsolve()", torch.linalg.tensorsolve(A, B))
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/tensor.py", line 212, in __torch_function__
    return func(*args, **(kwargs or {}))
RuntimeError: Expected Tensor but got None
```

Refs:
https://github.com/pytorch/pytorch/blob/575f260229a1e691b70d4aff9bd2d919b902c395/aten/src/ATen/native/LinearAlgebra.cpp#L3319
