### ISSUE TITLE
Make `tpu-info` more visible to the community

### ISSUE THREAD

**Issue by miladm** [pytorch/xla#7837]
## 📚 Documentation

We highlighted tpu-info in the [PyTorch/XLA 2.4 release](https://cloud.google.com/blog/products/ai-machine-learning/pytorch-xla-2-4-improves-pallas-and-adds-eager-mode?e=13802955). I understand we have a [CoLab demo page](https://colab.sandbox.google.com/drive/1aMYTONPE4f3BtZpRq1_jPcRcIiSKtoY9?usp=drive_open#scrollTo=ZqjPdg3XlTnG) to help users set up and use `tpu-info`. 

A quick search on the web, however, shows no pointer to the instructions on how to set up `tpu-info`. I suggest we publish a guide that brings this feature to the forefront. cc @duncantech 

Similarly, PyTorchXLA docker images benefit from having this feature built-in. Can we add it to our docker nightly/release setup flow?

Do we have plans to make `tpu-info` a standalong installation package?

**Comment by miladm** [comment]
Try before calling `tpu-info` on your terminal.

```
pip install git+https://github.com/google/cloud-accelerator-diagnostics/#subdirectory=tpu_info
```

**Comment by radna0** [comment]
@miladm I got this error when installing the package

```
Defaulting to user installation because normal site-packages is not writeable
WARNING: Ignoring invalid distribution -orch (/home/kojoe/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/kojoe/.local/lib/python3.10/site-packages)
Collecting git+https://github.com/google/cloud-accelerator-diagnostics/#subdirectory=tpu_info
  Cloning https://github.com/google/cloud-accelerator-diagnostics/ to /tmp/pip-req-build-b1q6c0ep
  Running command git clone --filter=blob:none --quiet https://github.com/google/cloud-accelerator-diagnostics/ /tmp/pip-req-build-b1q6c0ep
  Resolved https://github.com/google/cloud-accelerator-diagnostics/ to commit 6439522892666f9a50ce3bfad7f9a12d4c7e136b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Error processing line 1 of /tmp/pip-build-env-xqv01jqa/overlay/local/lib/python3.10/dist-packages/distutils-precedence.pth:

        Traceback (most recent call last):
          File "/usr/lib/python2.7/site.py", line 158, in addpackage
            exec line
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-env-xqv01jqa/overlay/local/lib/python3.10/dist-packages/_distutils_hack/__init__.py", line 36
            f"Register concerns at {report_url}"
            ^
        SyntaxError: invalid syntax

      Remainder of file ignored
      Traceback (most recent call last):
        File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
          mod_name, _Error)
        File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
          code = loader.get_code(mod_name)
        File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
          self.code = compile(source, self.filename, 'exec')
        File "/tmp/pip-build-env-xqv01jqa/overlay/local/lib/python3.10/dist-packages/grpc_tools/protoc.py", line 45
          package_or_requirement: str, resource_name: str
                                ^
      SyntaxError: invalid syntax
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-xqv01jqa/overlay/local/lib/python3.10/dist-packages/hatchling/build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
        File "/tmp/pip-build-env-xqv01jqa/overlay/local/lib/python3.10/dist-packages/hatchling/builders/plugin/interface.py", line 147, in build
          build_hook.initialize(version, build_data)
        File "/tmp/pip-build-env-xqv01jqa/overlay/local/lib/python3.10/dist-packages/hatch_build_scripts/plugin.py", line 51, in initialize
          run(cmd, cwd=str(work_dir), check=True, shell=True)  # noqa: S602
        File "/usr/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'python -m grpc_tools.protoc -I. tpu_info/proto/tpu_metric_service.proto --python_out=. --pyi_out=. --grpc_python_out=.' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution -orch (/home/kojoe/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -orch (/home/kojoe/.local/lib/python3.10/site-packages)
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by miladm** [comment]
what's your python version?

**Comment by radna0** [comment]
@miladm it's python 3.10.14 I believe
