### ISSUE TITLE
SPMD Checkpointing Error

### ISSUE THREAD

**Issue by alexanderswerdlow** [pytorch/xla#7935]
## 🐛 Bug

Timeout or error when using SPMD checkpointing. Adding a `xm.mark_step()` (following HF accelerate) produces the result below. Otherwise, I sometimes get a timeout error. The error does not seem to occur on rank zero, but on all other ranks. I have had some success checkpointing during earlier steps <10 but it seems to not be reproducible.

Using HF accelerate's save_state function, I can save a checkpoint, however this causes OOM after checkpointing. Using CheckpointManager causes a hang before the first training step.

## To Reproduce

```
Traceback (most recent call last):
  File "/home/aswerdlow/decoupled_utils.py", line 938, in inner
    return f(*args, **kwargs)
  File "/home/aswerdlow/model_setup.py", line 815, in checkpoint
    dist_cp.save(
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/logger.py", line 66, in wrapper
    result = func(*args, **kwargs)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 434, in inner_func
    return func(*args, **kwargs)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 152, in save
    return _save_state_dict(
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 316, in _save_state_dict
    central_plan: SavePlan = distW.reduce_scatter("plan", local_step, global_step)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 192, in reduce_scatter
    raise result
torch.distributed.checkpoint.api.CheckpointException: CheckpointException ranks:dict_keys([2, 7])
Traceback (most recent call last): (RANK 2)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 165, in reduce_scatter
    local_data = map_fun()
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/logger.py", line 66, in wrapper
    result = func(*args, **kwargs)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 303, in local_step
    local_plan = planner.create_local_plan()
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch_xla/experimental/distributed_checkpoint/planners.py", line 103, in create_local_plan
    xla_write_items = _create_xla_write_items(self.sharded_state_dict)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch_xla/experimental/distributed_checkpoint/planners.py", line 355, in _create_xla_write_items
    items.extend(_create_write_items_for_xla_sharded_tensor(fqn, v))
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch_xla/experimental/distributed_checkpoint/planners.py", line 326, in _create_write_items_for_xla_sharded_tensor
    replica_and_indices = torch_xla._XLAC._get_local_shard_replica_and_indices(
RuntimeError: torch_xla/csrc/tensor.cpp:217 : Check failed: handle->HasValue()
*** Begin stack trace ***
    tsl::CurrentStackTrace()
    torch_xla::XLATensor::GetXlaData()

    _PyObject_MakeTpCall
    _PyEval_EvalFrameDefault
 ...
    PyEval_EvalCode

    _PyRun_SimpleFileObject
    _PyRun_AnyFileObject
    Py_RunMain
    Py_BytesMain

    __libc_start_main
    _start
*** End stack trace ***
Trying to access XLA data for tensor with ID 1589632 while an async operation is in flight: UNKNOWN_SCALAR[]
Traceback (most recent call last): (RANK 7)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/utils.py", line 165, in reduce_scatter
    local_data = map_fun()
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/logger.py", line 66, in wrapper
    result = func(*args, **kwargs)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch/distributed/checkpoint/state_dict_saver.py", line 303, in local_step
    local_plan = planner.create_local_plan()
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch_xla/experimental/distributed_checkpoint/planners.py", line 103, in create_local_plan
    xla_write_items = _create_xla_write_items(self.sharded_state_dict)
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch_xla/experimental/distributed_checkpoint/planners.py", line 355, in _create_xla_write_items
    items.extend(_create_write_items_for_xla_sharded_tensor(fqn, v))
  File "/home/aswerdlow/venv/lib/python3.10/site-packages/torch_xla/experimental/distributed_checkpoint/planners.py", line 326, in _create_write_items_for_xla_sha
rded_tensor
    replica_and_indices = torch_xla._XLAC._get_local_shard_replica_and_indices(
RuntimeError: torch_xla/csrc/tensor.cpp:217 : Check failed: handle->HasValue()
*** Begin stack trace ***
    tsl::CurrentStackTrace()
    torch_xla::XLATensor::GetXlaData()

    _PyObject_MakeTpCall
    _PyEval_EvalFrameDefault
    _PyFunction_Vectorcall
    _PyEval_EvalFrameDefault
    _PyFunction_Vectorcall
    _PyEval_EvalFrameDefault
    _PyFunction_Vectorcall
...
    _PyRun_SimpleFileObject
    _PyRun_AnyFileObject
    Py_RunMain
    Py_BytesMain

    __libc_start_main
    _start
*** End stack trace ***
Trying to access XLA data for tensor with ID 1589632 while an async operation is in flight: UNKNOWN_SCALAR[]
```

1. Train w/SPMD sharding w/mesh [4, 8, 1]. 4 Replicas, FSDP within 2 nodes, DP across all chips. Model is ~1B params.
2. Checkpoint after ~50 steps.

## Environment

 - Reproducible on XLA backend [CPU/TPU/CUDA]: TPUv4-64
 - Versions:
torch                        2.4.0
torch-fidelity               0.3.0
torch-xla                    2.5.0+gitf0bbaeb

**Comment by JackCaoG** [comment]
@jonb377 is it the same issue the other use reported yesterday?

**Comment by jonb377** [comment]
This looks different. The error means that the tensor data has not been resolved before being accessed.

@alexanderswerdlow You may need an additional `xm.wait_device_ops` before attempting the checkpoint.

Also if you're able to share a repro for the CheckpointManager hang, I can take a look at that.

**Comment by alexanderswerdlow** [comment]
@jonb377 Ah got it thanks, will try that.

Can't repro it right now but my code looked like:

```
from torch_xla.experimental.distributed_checkpoint import CheckpointManager, prime_optimizer
self.chkpt_mgr = CheckpointManager(self.config.checkpointing.save_dir, self.config.trainer.ckpt_steps)
....
for i in steps:
   ...
   loss.backward()
   state_dict = {'model': self.backbone.state_dict(), 'optim': self.optimizer.state_dict()}
    if self.chkpt_mgr.save_async(self.global_step, state_dict):
        print(f'Checkpoint taken at step {self.global_step}')
```

**Comment by jonb377** [comment]
That looks like appropriate usage, do you know if it hung before or after step 0? Trying to get a sense of whether the hang was in initialization or the `save_async` call.

**Comment by alexanderswerdlow** [comment]
@jonb377 Yep, right after the first save_async call [which is after my first loss.backward/optimizer.step]. I think I figured it out though!—if I wait to call `save_async` after 10 steps, the hang goes away.

Not sure if this is expected behavior or not, but if it is, it seems odd given that the design encourages the user to call it after each step.

I'll also say that after adding the `xm.wait_device_ops()`, the probability of crashing after a checkpoint is far lower [not using checkpoint manager], so it seems that it's required, at least in my case :)

**Comment by jonb377** [comment]
Interesting findings, thank you for following up! This is not intended behavior, you should be able to call `save_async` every step starting at step 0.

It could be that there's some additional uninitialized state at step 0 that causes issues. There's been some interest in skipping the initial checkpoint previously, maybe we should adopt that approach instead.
