### ISSUE TITLE
tensor.expand(...) XLATensor behavior different than PyTorch Tensor

### ISSUE THREAD

**Issue by dlibenzi** [pytorch/xla#799]
From @jysohn23 

When expanding dimensions for a tensor a case which works fine on PyTorch tensor on CPU, errors on when executing on XLATensor.

Repro is here script available at script expand_dimensions.py [1]. And the stack trace dumped using gdb [2].

From the stack trace it looks somewhere around `xla::ShapeUtil::MakeShape` in XLA land they do not handle negative indexes well. Whereas in PyTorch tensors with ATen it looks like `reshape((1, 1, -1, -1))` gets well translated to `reshape((1, 1, 30, 30))` in repro script it errors with XLA.

We probably should either have XLA handle this more gracefully or do the translations ourselves.

```
import torch
import torch_xla
import torch_xla_py.xla_model as xm


def cpu_ok():
    mask = torch.zeros([30, 30])
    expanded_mask = mask.expand((1, 1, -1, -1))  # expand to [1, 1, 30, 30]
    print("cpu_ok - expanded_mask.shape: {}".format(expanded_mask.shape))

def tpu_ok():
    # tpu device bootstrap
    device = xm.xla_device()
    torch_xla._XLAC._xla_set_default_device(str(device))

    # For XLA tensor we get:
    # Invalid argument: shape's dimensions must not be < 0; dimension at index 2 was -1
    # wrong --> should be:

    # Debug steps:
    # $ gdb python
    # ... few other breaks
    # (gdb) b torch_xla::XYZ::ABC
    # (gdb) run expand_dimensions.py

    mask = torch.zeros([30, 30]).to(device)
    expanded_mask = mask.expand((1, 1, -1, -1))  # expand to [1, 1, 30, 30]
    print("tpu_ok - expanded_mask.shape: {}".format(expanded_mask.shape))

def main():
    print("cpu_ok repro start")
    cpu_ok()
    print("cpu_ok repro end")

    print("\n---------------------------------------------------------\n")

    print("tpu_ok repro start")
    tpu_ok()
    print("tpu_ok repro end")

if __name__ == "__main__":
    main()
```

```

Thread 1 "python" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff785142a in __GI_abort () at abort.c:89
#2  0x00007fff3fb0cab0 in tensorflow::internal::LogMessageFatal::~LogMessageFatal() ()
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#3  0x00007fff3fb0cac0 in tensorflow::internal::LogMessageFatal::~LogMessageFatal() ()
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#4  0x00007fff3f1a89eb in stream_executor::port::internal_statusor::Helper::Crash(tensorflow::Status const&) ()
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#5  0x00007fff3f199bc2 in xla::ShapeUtil::MakeShape(xla::PrimitiveType, absl::Span<long long const>) ()
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#6  0x00007fff3f017c3c in ?? () from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#7  0x00007fff3effdb9e in xla::XlaBuilder::ReportErrorOrReturn(std::function<stream_executor::port::StatusOr<xla::XlaOp> ()> const&) ()
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#8  0x00007fff3f004298 in xla::XlaBuilder::BroadcastInDim(xla::XlaOp const&, absl::Span<long long const>, absl::Span<long long const>) ()
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#9  0x00007fff3f00bd0e in xla::BroadcastInDim(xla::XlaOp, absl::Span<long long const>, absl::Span<long long const>) ()
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#10 0x00007fff422a98b1 in torch_xla::BuildExpand (input=..., output_sizes=...) at torch_xla/csrc/data_ops.cpp:87
#11 0x00007fff427bdea1 in std::function<xla::XlaOp (absl::Span<xla::XlaOp const>)>::operator()(absl::Span<xla::XlaOp const>) const (this=<optimized out>, __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:2127
#12 torch_xla::ir::ops::InferOutputShape(absl::Span<xla::Shape const>, std::function<xla::XlaOp (absl::Span<xla::XlaOp const>)> const&) (input_shapes=..., core_lowering_fn=...)
    at torch_xla/csrc/ops/infer_output_shape.cpp:19
#13 0x00007fff427bbdf7 in torch_xla::ir::ops::(anonymous namespace)::NodeOutputShape (input=..., size=...) at torch_xla/csrc/ops/expand.cpp:20
#14 torch_xla::ir::ops::Expand::Expand(torch_xla::ir::Value const&, std::vector<long long, std::allocator<long long> >)::$_0::operator()() const (this=<optimized out>)
    at torch_xla/csrc/ops/expand.cpp:28
#15 std::_Function_handler<xla::Shape (), torch_xla::ir::ops::Expand::Expand(torch_xla::ir::Value const&, std::vector<long long, std::allocator<long long> >)::$_0>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:1716
#16 0x00007fff4227b5c5 in std::function<xla::Shape ()>::operator()() const (this=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/functional:2127
#17 torch_xla::ir::Node::GetOpShape(std::function<xla::Shape ()> const&) const (this=0x555556fad550, shape_fn=...) at torch_xla/csrc/ir.cpp:207
#18 0x00007fff4227b4fd in torch_xla::ir::Node::Node(torch_xla::ir::OpKind, absl::Span<torch_xla::ir::Value const>, std::function<xla::Shape ()> const&, unsigned long, unsigned long) (this=0x555556fad550, op=..., operands=..., shape_fn=..., num_outputs=<optimized out>, hash_seed=14241834936821907571) at torch_xla/csrc/ir.cpp:111
#19 0x00007fff427bb7e0 in torch_xla::ir::ops::Expand::Expand (this=0x555556fad550, input=..., size=...) at torch_xla/csrc/ops/expand.cpp:26
#20 0x00007fff42300b26 in __gnu_cxx::new_allocator<torch_xla::ir::ops::Expand>::construct<torch_xla::ir::ops::Expand, torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(torch_xla::ir::ops::Expand*, torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (this=<optimized out>, __p=0x2,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x681632>,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x681632>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/ext/new_allocator.h:120
#21 std::allocator_traits<std::allocator<torch_xla::ir::ops::Expand> >::construct<torch_xla::ir::ops::Expand, torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(std::allocator<torch_xla::ir::ops::Expand>&, torch_xla::ir::ops::Expand*, torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (__a=...,
    __p=0x2, __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x681601>,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x681601>)
---Type <return> to continue, or q <return> to quit---
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/alloc_traits.h:475
#22 std::_Sp_counted_ptr_inplace<torch_xla::ir::ops::Expand, std::allocator<torch_xla::ir::ops::Expand>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(std::allocator<torch_xla::ir::ops::Expand>, torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (this=0x555556fad540, __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x681590>,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x681590>, __a=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/shared_ptr_base.h:520
#23 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<torch_xla::ir::ops::Expand, std::allocator<torch_xla::ir::ops::Expand>, torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(std::_Sp_make_shared_tag, torch_xla::ir::ops::Expand*, std::allocator<torch_xla::ir::ops::Expand> const&, torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (this=0x7fffffffd720, __a=...,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x6814ce>,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x6814ce>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/shared_ptr_base.h:615
#24 0x00007fff422d40ef in std::__shared_ptr<torch_xla::ir::ops::Expand, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<torch_xla::ir::ops::Expand>, torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(std::_Sp_make_shared_tag, std::allocator<torch_xla::ir::ops::Expand> const&, torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (__a=...,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb4bc>,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb4bc>,
    this=<optimized out>, __tag=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/shared_ptr_base.h:1099
#25 std::shared_ptr<torch_xla::ir::ops::Expand>::shared_ptr<std::allocator<torch_xla::ir::ops::Expand>, torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(std::_Sp_make_shared_tag, std::allocator<torch_xla::ir::ops::Expand> const&, torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (__a=...,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb489>,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb489>,
    this=<optimized out>, __tag=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/shared_ptr.h:319
#26 std::allocate_shared<torch_xla::ir::ops::Expand, std::allocator<torch_xla::ir::ops::Expand>, torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(std::allocator<torch_xla::ir::ops::Expand> const&, torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (__a=...,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb456>,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb456>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/shared_ptr.h:619
#27 std::make_shared<torch_xla::ir::ops::Expand, torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb423>,
    __args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb423>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/shared_ptr.h:635
#28 torch_xla::ir::MakeNode<torch_xla::ir::ops::Expand, torch_xla::ir::Value, std::vector<long long, std::allocator<long long> > >(torch_xla::ir::Value&&, std::vector<long long, std::allocator<long long> >&&) (
    args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb3fa>,
    args=<unknown type in /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/_XLAC.cpython-36m-x86_64-linux-gnu.so, CU 0x515ce9, DIE 0x5eb3fa>)
    at /pytorch/xla/torch_xla/csrc/ir.h:282
#29 torch_xla::XLATensor::expand (input=..., size=<error reading variable: Cannot access memory at address 0x0>) at torch_xla/csrc/tensor_methods.cpp:920
#30 0x00007fff4231e73f in torch_xla::AtenXlaType::expand (self=..., size=..., implicit=<optimized out>) at torch_xla/csrc/aten_xla_type.cpp:1152
#31 0x00007fffe3cb8381 in at::Tensor::expand(c10::ArrayRef<long>, bool) const () from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch/lib/libtorch.so
#32 0x00007fffe5c2cd1a in torch::autograd::VariableType::expand(at::Tensor const&, c10::ArrayRef<long>, bool) ()
---Type <return> to continue, or q <return> to quit---
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch/lib/libtorch.so
#33 0x00007fffe7f46511 in at::Tensor::expand(c10::ArrayRef<long>, bool) const () from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#34 0x00007fffe7eb9749 in torch::autograd::THPVariable_expand(_object*, _object*, _object*) ()
   from /anaconda3/envs/pytorch-nightly/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#35 0x0000555555665744 in _PyCFunction_FastCallDict () at /tmp/build/80754af9/python_1546130271559/work/Objects/methodobject.c:231
#36 0x00005555556ec42c in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4851
#37 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#38 0x00005555556e653b in _PyFunction_FastCall (globals=<optimized out>, nargs=0, args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4933
#39 fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4968
#40 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#41 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#42 0x00005555556e653b in _PyFunction_FastCall (globals=<optimized out>, nargs=0, args=<optimized out>, co=<optimized out>)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4933
#43 fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4968
#44 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#45 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#46 0x00005555556e7289 in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwstep=2, kwcount=<optimized out>,
    kwargs=0x0, kwnames=0x0, argcount=0, args=0x0, locals=0x7ffff6ec00d8, globals=0x7ffff6ec00d8, _co=0x7ffff6d41e40)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#47 PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4187
#48 0x00005555556e801c in PyEval_EvalCode (co=co@entry=0x7ffff6d41e40, globals=globals@entry=0x7ffff6ec00d8, locals=locals@entry=0x7ffff6ec00d8)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:731
#49 0x000055555576a3c4 in run_mod () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:1025
#50 0x000055555576a7c1 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:978
#51 0x000055555576a9c3 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:419
#52 0x000055555576aacd in PyRun_AnyFileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:81
#53 0x000055555576e4b3 in run_file (p_cf=0x7fffffffe2cc, filename=0x5555558a92f0 L"expand_dimensions.py", fp=0x555555936f00)
    at /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:340
#54 Py_Main () at /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:811
#55 0x000055555563702e in main () at /tmp/build/80754af9/python_1546130271559/work/Programs/python.c:69
#56 0x00007ffff783d2e1 in __libc_start_main (main=0x555555636f40 <main>, argc=2, argv=0x7fffffffe4d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe4c8) at ../csu/libc-start.c:291
#57 0x0000555555717e0e in _start () at ../sysdeps/x86_64/elf/start.S:103
```

**Comment by dlibenzi** [comment]
https://github.com/pytorch/xla/pull/801
