### ISSUE TITLE
PjRtComputationClient::ExecuteReplicated core dump when encountering a scalar

### ISSUE THREAD

**Issue by mars1248** [pytorch/xla#8057]
## ❓ Questions and Help
In my test code, I found that there might be PjRtData as the type argument(the argument is a scalar), and then the core dump.
https://github.com/pytorch/xla/blob/master/torch_xla/csrc/runtime/pjrt_computation_client.cc#L806
I wrote a test function earlier that tried to transform all arguments manually, but core dumped.
![image](https://github.com/user-attachments/assets/982c4200-f708-42c4-9865-3c4f5f4b3488)
![image](https://github.com/user-attachments/assets/19f0b9a1-f3b5-406b-a87e-fe3b4d610442)

**Comment by JackCaoG** [comment]
hmmm why is the last data's device is `CUDA:0` instead of `SPMD:0`, under SPMD mode all tensor should be in SPMD:0 device. Do you have a small repo?

**Comment by mars1248** [comment]
This can be replicated with the following ut, the 8*a100 environment I used
```
from transformers import AutoModel
import torch
import torch.optim as optim
import torch_xla
import torch_xla.runtime as xr
import torch_xla.core.xla_model as xm
import torch_xla.experimental.xla_sharding as xs
from torch_xla.experimental.xla_sharding import Mesh
from torch_xla.amp import autocast, GradScaler
from torch_xla.experimental.spmd_fully_sharded_data_parallel import SpmdFullyShardedDataParallel as FSDPv2

import numpy as np
import torch_xla.debug.profiler as xp
import time
import os
# Setup profiler env var
os.environ['XLA_HLO_DEBUG'] = '1'
server = xp.start_server(9012)
# Enable XLA SPMD execution mode.
xr.use_spmd()
model = AutoModel.from_pretrained("/root/OpenGVLab__InternViT-6B-448px-V1-5", low_cpu_mem_usage=True, device_map="cpu", trust_remote_code=True, torch_dtype=torch.bfloat16)
model = model.to(xm.xla_device())
num_devices = xr.global_runtime_device_count()
mesh_shape = (num_devices // 1, 1)
device_ids = np.array(range(num_devices))
mesh = Mesh(device_ids, mesh_shape, ('fsdp', 'replica'))
def shard_output(output, mesh):
    xs.mark_sharding(output.last_hidden_state[:,1:], mesh, ('fsdp', None, None))
model = FSDPv2(model, mesh, shard_output)
image = torch.rand([8, 3, 448, 448]).to(xm.xla_device(), torch.bfloat16)
xs.mark_sharding(image, mesh, (('fsdp', 'replica'), ) + (None, None, None))
with autocast(xm.xla_device(), dtype=torch.bfloat16):
    output = model(image)
    loss = output.last_hidden_state[:,1:].sum()
xm.unlazy([loss])
print("ans is ", loss)
```

**Comment by zjjott** [comment]
@JackCaoG

**Comment by JackCaoG** [comment]
busy this week, will try to find some time to take a look

**Comment by zjjott** [comment]
I have a more easy code @JackCaoG ,pure torch/torch_xla
```
import torch
import torch.optim as optim
import torch_xla
import torch_xla.runtime as xr
import torch_xla.core.xla_model as xm
import torch_xla.distributed.spmd.xla_sharding as xs
from torch_xla.distributed.spmd.xla_sharding import Mesh
from torch_xla.amp import autocast, GradScaler
from torch_xla.experimental.spmd_fully_sharded_data_parallel import SpmdFullyShardedDataParallel as FSDPv2
from torch import nn
import numpy as np
import torch_xla.debug.profiler as xp
import time
import os
class InternRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon) # cause here + self.variance_epsilon
        return self.weight * hidden_states.to(input_dtype)
os.environ['XLA_HLO_DEBUG'] = '1'
server = xp.start_server(9012)
# Enable XLA SPMD execution mode.
xr.use_spmd()
model = InternRMSNorm(448)
model = model.to(xm.xla_device())
num_devices = xr.global_runtime_device_count()
mesh_shape = (num_devices // 1, 1)
device_ids = np.array(range(num_devices))
mesh = Mesh(device_ids, mesh_shape, ('fsdp', 'replica'))
def shard_output(output, mesh):
    xs.mark_sharding(output, mesh, ('fsdp', None, None))
model = FSDPv2(model, mesh=mesh, shard_output=shard_output)
image = torch.rand([64, 448, 448]).to(xm.xla_device(), torch.bfloat16)
xs.mark_sharding(image, mesh, (('fsdp', 'replica'), ) + (None, None))
with autocast(xm.xla_device(), dtype=torch.bfloat16):
    output = model(image)
    loss = output.sum()#output.last_hidden_state[:,1:].sum()
xm.unlazy([loss])
print("ans is ", loss)
```

**Comment by zjjott** [comment]
`server = xp.start_server(9012) ` cause segmantfault,when quote this line, this code work fine

**Comment by ysiraichi** [comment]
@mars1248 Were you able to resolve your issue by implementing @zjjott suggestion?

**Comment by tengyifei** [comment]
The underlying issue still reproduces as of Mar 31, 2025. I got this stack trace:

```
0x00007ffcf481f90a in std::vector<std::shared_ptr<torch_xla::runtime::PjRtComputationClient::PjRtData>, std::allocator<std::shared_ptr<torch_xla::runtime::PjRtComputationClient::PjRtData> > >::size (this=0x218) at /usr/include/c++/10/bits/stl_vector.h:919
919           { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
(gdb) bt

   #0  0x00007ffcf481f90a in std::vector<std::shared_ptr<torch_xla::runtime::PjRtComputationClient::PjRtData>, std::allocator<std::shared_ptr<torch_xla::runtime::PjRtComputationClient::PjRtData> > >::size (this=0x218)
    at /usr/include/c++/10/bits/stl_vector.h:919
#1  0x00007ffcf4816678 in operator() (__closure=0x7fc974005a70, start=0, end=3)
    at torch_xla/csrc/runtime/pjrt_computation_client.cc:817
#2  0x00007ffcf481bf68 in std::__invoke_impl<void, torch_xla::runtime::PjRtComputationClient::ExecuteReplicated(const torch_xla::runtime::ComputationClient::Computation&, absl::lts_20230802::Span<const std::shared_ptr<torch_xla::runtime::ComputationClient::Data> >, absl::lts_20230802::Span<const std::__cxx11::basic_string<char> >, const torch_xla::runtime::ComputationClient::ExecuteReplicatedOptions&)::<lambda(int64_t, int64_t)>&, long int, long int>(std::__invoke_other, struct {...} &)
    (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#3  0x00007ffcf481b7df in std::__invoke_r<void, torch_xla::runtime::PjRtComputationClient::ExecuteReplicated(const torch_xla::runtime::ComputationClient::Computation&, absl::lts_20230802::Span<const std::shared_ptr<torch_xla::runtime::ComputationClient::Data> >, absl::lts_20230802::Span<const std::__cxx11::basic_string<char> >, const torch_xla::runtime::ComputationClient::ExecuteReplicatedOptions&)::<lambda(int64_t, int64_t)>&, long int, long int>(struct {...} &) (__fn=...)
    at /usr/include/c++/10/bits/invoke.h:110
#4  0x00007ffcf481b114 in std::_Function_handler<void(long int, long int), torch_xla::runtime::PjRtComputationClient::ExecuteReplicated(const torch_xla::runtime::ComputationClient::Computation&, absl::lts_20230802::Span<const std::shared_ptr<torch_xla::runtime::ComputationClient::Data> >, absl::lts_20230802::Span<const std::__cxx11::basic_string<char> >, const torch_xla::runtime::ComputationClient::ExecuteReplicatedOptions&)::<lambda(int64_t, int64_t)> >::_M_invoke(const std::_Any_data &, long &&, long &&) (__functor=..., __args#0=@0x7ff6529fed20: 0, __args#1=@0x7ff6529fed18: 3)
    at /usr/include/c++/10/bits/std_function.h:291
#5  0x00007ffcf4ac4f7f in std::function<void (long, long)>::operator()(long, long) const ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#6  0x00007ffd05359708 in tsl::thread::ThreadPool::ParallelFor(long, long, std::function<void (long, long)> const&)::{lambda(long, long)#1}::operator()(long, long) const () from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#7  0x00007ffd0535b342 in void std::__invoke_impl<void, tsl::thread::ThreadPool::ParallelFor(long, long, std::function<void (long, long)> const&)::{lambda(long, long)#1}&, long, long>(std::__invoke_other, tsl::thread::ThreadPool::ParallelFor(long, long, std::function<void (long, long)> const&)::{lambda(long, long)#1}&, long&&, long&&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#8  0x00007ffd0535ac1c in std::enable_if<is_invocable_r_v<void, tsl::thread::ThreadPool::ParallelFor(long, long, std::function<void (long, long)> const&)::{lambda(long, long)#1}&, long, long>, void>::type std::__invoke_r<void, tsl::thread::ThreadPool::ParallelFor(long, long, std::function<void (long, long)> const&)::{lambda(long, long)#1}&, long, long>(tsl::thread::ThreadPool::ParallelFor(long, long, std::function<void (long, long)> const&)::{lambda(long, long)#1}&, long&&, long&&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#9  0x00007ffd0535a44c in std::_Function_handler<void (long, long), tsl::thread::ThreadPool::ParallelFor(long, long, std::function<void (long, long)> const&)::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, long&&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#10 0x00007ffcf4ac4f7f in std::function<void (long, long)>::operator()(long, long) const ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#11 0x00007ffcf4ac4558 in Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const () from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#12 0x00007ffcf5302e7e in Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<void (long, long)>) const () from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#13 0x00007ffd05359928 in tsl::thread::ThreadPool::ParallelFor(long, long, std::function<void (long, long)> const&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#14 0x00007ffcf481775c in torch_xla::runtime::PjRtComputationClient::ExecuteReplicated (this=0x55555b635230, 
    computation=..., arguments=..., devices=..., options=...) at torch_xla/csrc/runtime/pjrt_computation_client.cc:811
#15 0x00007ffcf4268987 in operator() (__closure=0x55555d1160e0) at torch_xla/csrc/xla_graph_executor.cpp:1121
#16 0x00007ffcf4270ba0 in std::__invoke_impl<void, torch_xla::XLAGraphExecutor::ScheduleSyncTensorsGraph(torch::lazy::LazyGraphExecutor::SyncTensorCollection*, std::vector<std::shared_ptr<torch::lazy::BackendData> >, std::vector<std::shared_ptr<torch::lazy::BackendData> >, std::vector<std::shared_ptr<torch_xla::XLATensor::ShardingSpec> >, torch_xla::runtime::util::AbstractCache<torch::lazy::hash_t, torch_xla::XLAGraphExecutor::CachedComputation, torch::lazy::HashReducer>::TypePtr)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#17 0x00007ffcf427040f in std::__invoke_r<void, torch_xla::XLAGraphExecutor::ScheduleSyncTensorsGraph(torch::lazy::LazyGraphExecutor::SyncTensorCollection*, std::vector<std::shared_ptr<torch::lazy::BackendData> >, std::vector<std::shared_ptr<torch::lazy::BackendData> >, std::vector<std::shared_ptr<torch_xla::XLATensor::ShardingSpec> >, torch_xla::runtime::util::AbstractCache<torch::lazy::hash_t, torch_xla::XLAGraphExecutor::CachedComputation, torch::lazy::HashReducer>::TypePtr)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/10/bits/invoke.h:110
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00007ffcf426fc7b in std::_Function_handler<void(), torch_xla::XLAGraphExecutor::ScheduleSyncTensorsGraph(torch::lazy::LazyGraphExecutor::SyncTensorCollection*, std::vector<std::shared_ptr<torch::lazy::BackendData> >, std::vector<std::shared_ptr<torch::lazy::BackendData> >, std::vector<std::shared_ptr<torch_xla::XLATensor::ShardingSpec> >, torch_xla::runtime::util::AbstractCache<torch::lazy::hash_t, torch_xla::XLAGraphExecutor::CachedComputation, torch::lazy::HashReducer>::TypePtr)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/10/bits/std_function.h:291
#19 0x00007ffff5ab9f8c in std::function<void ()>::operator()() const (this=0x55555d14a918)
    at /usr/include/c++/10/bits/std_function.h:622
#20 0x00007fffe40b94f9 in torch::lazy::MultiWait::Complete(std::function<void ()> const&) (this=0x55555d178f18, func=...)
    at /workspaces/torch/pytorch/torch/csrc/lazy/core/multi_wait.cpp:64
#21 0x00007fffe40b9256 in operator() (__closure=0x55555d14a910)
    at /workspaces/torch/pytorch/torch/csrc/lazy/core/multi_wait.cpp:49
#22 0x00007fffe40b9c8e in std::__invoke_impl<void, torch::lazy::MultiWait::Completer(std::function<void()>)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#23 0x00007fffe40b9a45 in std::__invoke_r<void, torch::lazy::MultiWait::Completer(std::function<void()>)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/10/bits/invoke.h:110
#24 0x00007fffe40b984b in std::_Function_handler<void(), torch::lazy::MultiWait::Completer(std::function<void()>)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/10/bits/std_function.h:291
#25 0x00007ffcf3db661a in std::function<void ()>::operator()() const (this=0x7ff6529ffcb0)
    at /usr/include/c++/10/bits/std_function.h:622
#26 0x00007ffd0535bf16 in tsl::thread::EigenEnvironment::ExecuteTask(tsl::thread::EigenEnvironment::Task const&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#27 0x00007ffd0535cd3e in Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#28 0x00007ffd0535c1c4 in Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::ThreadPoolTempl(int, bool, tsl::thread::EigenEnvironment)::{lambda()#1}::operator()() const ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#29 0x00007ffd0535eeb6 in void std::__invoke_impl<void, Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::ThreadPoolTempl(int, bool, tsl::thread::EigenEnvironment)::{lambda()#1}&>(std::__invoke_other, Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::ThreadPoolTempl(int, bool, tsl::thread::EigenEnvironment)::{lambda()#1}&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#30 0x00007ffd0535e84e in std::enable_if<is_invocable_r_v<void, Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::ThreadPoolTempl(int, bool, tsl::thread::EigenEnvironment)::{lambda()#1}&>, void>::type std::__invoke_r<void, Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::ThreadPoolTempl(int, bool, tsl::thread::EigenEnvironment)::{lambda()#1}&>(Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::ThreadPoolTempl(int, bool, tsl::thread::EigenEnvironment)::{lambda()#1}&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#31 0x00007ffd0535d8c9 in std::_Function_handler<void (), Eigen::ThreadPoolTempl<tsl::thread::EigenEnvironment>::ThreadPoolTempl(int, bool, tsl::thread::EigenEnvironment)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#32 0x00007ffcf3db661a in std::function<void ()>::operator()() const (this=0x55555d1b9ce8)
    at /usr/include/c++/10/bits/std_function.h:622
#33 0x00007ffd0535bcc7 in tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}::operator()() const () from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#34 0x00007ffd0535f277 in void std::__invoke_impl<void, tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&>(std::__invoke_other, tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&)
    () from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#35 0x00007ffd0535f254 in std::__invoke_result<tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&>::type std::__invoke<tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&>(tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#36 0x00007ffd0535f231 in std::invoke_result<tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&>::type std::invoke<tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&>(tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#37 0x00007ffd0535f1f2 in void absl::lts_20230802::internal_any_invocable::InvokeR<void, tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&, , void>(tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&) () from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#38 0x00007ffd0535eff9 in void absl::lts_20230802::internal_any_invocable::RemoteInvoker<false, void, tsl::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}&>(absl::lts_20230802::internal_any_invocable::TypeErasedState*) () from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
--Type <RET> for more, q to quit, c to continue without paging--
#39 0x00007ffcf486749d in absl::lts_20230802::internal_any_invocable::Impl<void ()>::operator()() ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#40 0x00007ffd0533a148 in tsl::(anonymous namespace)::PThread::ThreadFn(void*) ()
   from /workspaces/torch/pytorch/xla/_XLAC.cpython-310-x86_64-linux-gnu.so
#41 0x00007ffff7a80ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#42 0x00007ffff7b96acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

So we're dealing with a corruption C++ `PjrtData` object.
