### ISSUE TITLE
DataParallel doesn't work with torch.jit.ScriptModule

### ISSUE THREAD

**Issue by jysohn23** [pytorch/xla#809]
We added a change to have models initialized only a single time and instead copying that model with [deepcopy](https://github.com/pytorch/xla/blob/master/torch_xla_py/data_parallel.py#L193) to each of the devices to have same initialization (`model.to(device)` looked like it was making modification to the existing object).

However, this doesn't work with models that have layers such as `torch.jit.ScriptModule` as it looks like they don't serialize well ([example](https://github.com/pytorch/vision/blob/master/torchvision/ops/misc.py#L135)). Stack trace:

```
Traceback (most recent call last):
  File "/pytorch/vision/references/detection/train_tpu.py", line 162, in <module>
    main()
  File "/pytorch/vision/references/detection/train_tpu.py", line 156, in main
    do_train(FLAGS.num_cores)
  File "/pytorch/vision/references/detection/train_tpu.py", line 135, in do_train
    dp.DataParallel(model, device_ids=devices)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla_py/data_parallel.py", line 179, in __init__
    device_module = deepcopy(module).to(device=torch.device(device))
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1644, in __getstate__
    "For purely script modules use my_script_module.save(<filename>) instead.")
_pickle.PickleError: ScriptModules cannot be deepcopied using copy.deepcopy or saved using torch.save. Mixed serialization of script and non-script modules is not supported. For purely script modules use my_script_module.save(<filename>) instead.
```

**Comment by dlibenzi** [comment]
@jysohn23 The `deepcopy()` change was not done for saving initialization time. It was done for correctness, as otherwise model would start from a different parameter values set.
That was a real bugfix.

**Comment by jysohn23** [comment]
? Did I mention saving initialization time? I think you might have misread same -> save? Yes, it was for correctness.

**Comment by dlibenzi** [comment]
Duh! You're right! BeforeCoffee answer :)

I think this is more of a PyTorch ScriptModule+deepcopy issue.
How did you encounter this issue?
IMHO we can leave this very low priority.

**Comment by jysohn23** [comment]
No worries!

Yes, this is a PyTorch ScriptModule + deepcopy issue, which arises in models that have layers that are instances of `ScriptModule` instead of `torch.nn.module` and MaskRCNN under `torchvision` is one of these that uses `FrozenBatchNorm2d` (https://github.com/pytorch/vision/blob/master/torchvision/ops/misc.py#L135). Not familiar enough with `ScriptModule` on to tell whether this could be re-written to be a `torch.nn.module` instance, but it'll block `DataParallel` usage. For now I'm just sending to single XLA device so that deepcopy doesn't get called.

**Comment by dlibenzi** [comment]
https://github.com/pytorch/pytorch/issues/18106

**Comment by dlibenzi** [comment]
I think we can close this.
For two reasons. It is a pytorch bug (one already exist on that side), and this is MT based replication, which is on its way to be deprecated.

**Comment by mattans** [comment]
@jysohn23 can you suggest a non-XLA workaround?
I try to torch.save or pickle.dump my MaskRCNN, but getting this traceback.

**Comment by jysohn23** [comment]
Are you having problems with saving regular (non-XLA) PyTorch mixed script/non-script (https://github.com/pytorch/pytorch/issues/15116)? We PyTorch/XLA don't have a solution to that and should be something requested to PyTorch/PyTorch.
