### ISSUE TITLE
Model support for `hf_BigBird` with Torch_XLA2

### ISSUE THREAD

**Issue by ManfeiBai** [pytorch/xla#8133]
## Fix the model test for `hf_BigBird.py`

1. setup env according to [Run a model under torch_xla2](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/support_a_new_model.md)
2. Run model test under `run_torchbench/` with `python models/your_target_model_name.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/support_a_new_model.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7583

**Comment by barney-s** [comment]
with script changes the test is still failing. 
```
% JAX_PLATFORMS=cpu python models/hf_BigBird.py
/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:337: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
Input ids are automatically padded from 819 to 832 to be a multiple of `config.block_size`: 64
Traceback (most recent call last):
  File "/usr/local/google/home/barni/workspace/pytorch-tpu/run_torchbench/models/hf_BigBird.py", line 61, in <module>
    sys.exit(main())
  File "/usr/local/google/home/barni/workspace/pytorch-tpu/run_torchbench/models/hf_BigBird.py", line 39, in main
    xla2_ans = model(**example)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2446, in forward
    outputs = self.bert(
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2083, in forward
    blocked_encoder_mask, band_mask, from_mask, to_mask = self.create_masks_for_block_sparse_attn(
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2195, in create_masks_for_block_sparse_attn
    band_mask = create_band_mask_from_inputs(blocked_encoder_mask, blocked_encoder_mask)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2190, in create_band_mask_from_inputs
    band_mask = torch.einsum("blq,blk->blqk", from_blocked_mask[:, 2:-2], exp_blocked_to_pad)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/torch/functional.py", line 395, in einsum
    return handle_torch_function(einsum, operands, equation, *operands)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/torch/overrides.py", line 1719, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/tensor.py", line 208, in __torch_function__
    return self.env.dispatch(func, types, args, kwargs)
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/tensor.py", line 435, in dispatch
    res = op.func(*args, **kwargs)
  File "/usr/local/google/home/barni/workspace/pytorch/xla/experimental/torch_xla2/torch_xla2/ops/jtorch.py", line 99, in _einsum
    return jnp.einsum(equation, *filtered_operands)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 9335, in einsum
    operands, contractions = contract_path(
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/opt_einsum/contract.py", line 294, in contract_path
    input_subscripts, output_subscript, operands_prepped = parser.parse_einsum_input(operands_, shapes=shapes)
  File "/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/opt_einsum/parser.py", line 410, in parse_einsum_input
    raise ValueError(
ValueError: Number of einsum subscripts, 2, must be equal to the number of operands, 1.
```
