### ISSUE TITLE
Model support for `simple_gpt` with Torch_XLA2

### ISSUE THREAD

**Issue by ManfeiBai** [pytorch/xla#8178]
## Fix the model test for `simple_gpt.py`

1. setup env according to [Run a model under torch_xla2](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/support_a_new_model.md)
2. Run model test under `run_torchbench/` with `python models/your_target_model_name.py`
3. Fix the failure.

Please refer to 
[this guide](https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/docs/support_a_new_model.md) as guide to fix:

Also refer to these PRs:
* https://github.com/pytorch/xla/pull/7583

**Comment by barney-s** [comment]
Model requires CUDA ? 

```
 % JAX_ENABLE_X64=true JAX_PLATFORMS=cpu python models/simple_gpt.py 
/usr/local/google/home/barni/miniconda3/envs/diffusion-models-2/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:337: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/google/home/barni/workspace/pytorch-tpu/run_torchbench/models/simple_gpt.py", line 61, in <module>
    sys.exit(main())
  File "/usr/local/google/home/barni/workspace/pytorch-tpu/run_torchbench/models/simple_gpt.py", line 21, in main
    benchmark = benchmark_cls(test="eval", device = "cpu")
  File "/usr/local/google/home/barni/workspace/pytorch-tpu/run_torchbench/benchmark/torchbenchmark/util/model.py", line 43, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/usr/local/google/home/barni/workspace/pytorch-tpu/run_torchbench/benchmark/torchbenchmark/models/simple_gpt/__init__.py", line 44, in __init__
    raise error
NotImplementedError: Model requires CUDA
```
