### ISSUE TITLE
XLA2 does not support maxpool

### ISSUE THREAD

**Issue by Chaosruler972** [pytorch/xla#8241]
## 🐛 Bug

Maxpool operator from xla2 crashes

## To Reproduce

1. download a mnist toy example I prepared from [here](https://gist.githubusercontent.com/Chaosruler972/c8d34310b4a9d892443f81dd5bf8ee89/raw/f645486709e33b79fbc588660c82f57f5cc87a9f/mnist_with_maxpool.py)
2. move it to Trillium machine
3. run it

Traceback:
Traceback (most recent call last):
  File "/home/zmelumian/xla2_trainer_poc//google_bugs/mnist_with_maxpool.py", line 174, in <module>
    jax_weights, opt_state, loss = training_step(jax_weights, jax_buffers, opt_state, x_j, target_j)
  File "/home/zmelumian/xla2_trainer_poc//google_bugs/mnist_with_maxpool.py", line 102, in training_step
    loss, grads = jax.value_and_grad(forward)(jax_weights, buffers, x, target)
  File "/home/zmelumian/xla2_trainer_poc//google_bugs/mnist_with_maxpool.py", line 89, in forward
    pred = jittable_model.functional_call('forward', weights, buffers, x)
  File "/home/zmelumian/xla/experimental/torch_xla2/torch_xla2/interop.py", line 73, in functional_call
    res = getattr(self._model, method_name)(*args, **kwargs)
  File "/home/zmelumian/xla2_trainer_poc//google_bugs/mnist_with_maxpool.py", line 68, in forward
    x = F.max_pool2d(x, 2, stride=2, return_indices=False)
  File "/home/zmelumian/venv/lib/python3.10/site-packages/torch/_jit_internal.py", line 503, in fn
    return if_false(*args, **kwargs)
  File "/home/zmelumian/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 783, in _max_pool2d
    return handle_torch_function(
  File "/home/zmelumian/venv/lib/python3.10/site-packages/torch/overrides.py", line 1630, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
  File "/home/zmelumian/xla/experimental/torch_xla2/torch_xla2/tensor.py", line 212, in __torch_function__
    return func(*args, **(kwargs or {}))
  File "/home/zmelumian/venv/lib/python3.10/site-packages/torch/_jit_internal.py", line 503, in fn
    return if_false(*args, **kwargs)
  File "/home/zmelumian/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 796, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
  File "/home/zmelumian/xla/experimental/torch_xla2/torch_xla2/tensor.py", line 227, in __torch_dispatch__
    return self.env.dispatch(func, types, args, kwargs)
  File "/home/zmelumian/xla/experimental/torch_xla2/torch_xla2/tensor.py", line 430, in dispatch
    res = op.func(*args, **kwargs)
  File "/home/zmelumian/xla/experimental/torch_xla2/torch_xla2/ops/jaten.py", line 1136, in _aten_max_pool2d_with_indices
    indices, _ = jax.lax.reduce_window(
ValueError: Operands must have the same tree structure as init_values: PyTreeDef([*, *, CustomNode(Zero[ShapedArray(float0[1024,64,24,24])], []), *]) vs. PyTreeDef([*, *, *, *])
(venv) zmelumian@t1v-n-41085a1d-w-0:~$ 

## Expected behavior

Maxpool to have exact behavior between xla2 and pytorch and be completely wrapped

## Environment

 - Reproducible on XLA backend TPU
 - Jax version 0.4.43
 - Trillium machine
 - torch_xla2 version: 0.0.1

## Additional context

after digging in, I noticed that the operator written in xla2 has two trees, one where it will compute the maxpool values, and one where it computes both values and indices

it is done so, to let the case of the indices unused in the operator to be ignored in the XLA compiler - which will lead better performence due to the skip of the unused indexes prediction, unless they were used

a custom kernel was written to the window function in jax that gets a value that contains a tuple which is the index and value per grid on the window map

the logic in the kernel is accurate and should work, however the windowing function is not supported in Jax, which has some odd internal states per input to better understand it's relationship across devices

**Comment by ManfeiBai** [comment]
Thanks, sry for the late reply, start looking at this issue, and reproduced locally now: https://gist.github.com/ManfeiBai/ab11a866f6cb8bac70edc2e0dc7aab32

**Comment by ManfeiBai** [comment]
was busy with release, did a local investigation with `pdb` for trace: https://gist.github.com/ManfeiBai/9154dc6487502f22e49eae2602102541

found code crashed at `if operand_tree != init_value_tree:`: [code](https://github.com/jax-ml/jax/blob/d38da5d1b4be5167c25ead8e6b1a6de04e531870/jax/_src/lax/windowed_reductions.py#L63C1-L67C6), `operand_tree` and `init_value_tree` was flatten from `operand` and `init_value`;

from [log](https://gist.github.com/ManfeiBai/9154dc6487502f22e49eae2602102541), `operand_tree != init_value_tree` happen after several stacks:
- the formal stack:
   ```
    # operand
   (Traced<ShapedArray(int32[1024,64,24,24])>with<DynamicJaxprTrace(level=1/0)>,
    Traced<ShapedArray(float32[1024,64,24,24])>with<JVPTrace(level=3/0)> with primal = Traced<ShapedArray(float32[1024,64,24,24])>with<DynamicJaxprTrace(level=1/0)> tangent = Traced<ShapedArray(float32[1024,64,24,24])>with<JaxprTrace(level=2/0)> with pval = (ShapedArray(float32[1024,64,24,24]), None) recipe = JaxprEqnRecipe(eqn_id=<object object at 0x7fba935fe690>, in_tracers=(Traced<ShapedArray(bool[1024,64,24,24]):JaxprTrace(level=2/0)>, Traced<ShapedArray(float32[1024,64,24,24]):JaxprTrace(level=2/0)>, Traced<ShapedArray(float32[1024,64,24,24]):JaxprTrace(level=2/0)>), out_tracer_refs=[<weakref at 0x7fbb4af6e0c0; to 'JaxprTracer' at 0x7fbb4af6e070>], out_avals=[ShapedArray(float32[1024,64,24,24])], primitive=select_n, params={}, effects=frozenset(), source_info=<jax._src.source_info_util.SourceInfo object at 0x7fbb4af80e80>, ctx=JaxprEqnContext(compute_type=None, threefry_partitionable=False, xla_metadata={})))
    # init_value
    (0, 
     Traced<ShapedArray(float32[])>with<DynamicJaxprTrace(level=1/0)>)
   ```
- the crashed stack:
   ```
    # operand
    [Traced<ShapedArray(int32[1024,64,24,24])>with<DynamicJaxprTrace(level=1/0)>, 
     Traced<ShapedArray(float32[1024,64,24,24])>with<DynamicJaxprTrace(level=1/0)>,      
     Zero(ShapedArray(float0[1024,64,24,24])), 
     Traced<ShapedArray(float32[1024,64,24,24]):JaxprTrace(level=2/0)>]
  
    # init_value
    [0, 
     Traced<ShapedArray(float32[])>with<DynamicJaxprTrace(level=1/0)>, 
     Traced<ShapedArray(float0[])>with<DynamicJaxprTrace(level=1/0)>, 
     Traced<ShapedArray(float32[])>with<DynamicJaxprTrace(level=1/0)>]
   ```

so agree with the above `Additional context`, this might caused by `  indices, _ = jax.lax.reduce_window((indices, inputs), (0, init_val), reduce_fn, dims, strides, padding)`: [code](https://github.com/pytorch/xla/blob/7c7ad4e7889b3e7680c4ea63a517def8fcbaf15b/experimental/torch_xla2/torch_xla2/ops/jaten.py#L1193C1-L1198C4)

this line code use `0` to conbine with `init_val`, and conbine `indices = jnp.arange(np.prod(inputs.shape)).reshape(inputs.shape)` with `inputs` directly

so our next step will be:
- find out why the operand have `ZERO(ShAapedArray)` and not match `init_value` after flatten to tree
- find other solutions to get indices, due to [formal line code](https://github.com/pytorch/xla/blob/7c7ad4e7889b3e7680c4ea63a517def8fcbaf15b/experimental/torch_xla2/torch_xla2/ops/jaten.py#L1193C3-L1195C4) passed without combination
