### ISSUE TITLE
Instructions in CONTRIBUTING.md for using VS Code don't seem to work

### ISSUE THREAD

**Issue by mikegre-google** [pytorch/xla#8342]
## 📚 Documentation
I've followed the instructions in CONTRIBUTING.md to set up a dev environment using VS Code. Next I run python and then tried to import torch_xla as xla and I get an error:

```
>>> import torch_xla as xla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/xla_vs_files/pytorch/xla/torch_xla/__init__.py", line 259, in <module>
    from .stablehlo import save_as_stablehlo, save_torch_model_as_stablehlo
  File "/workspaces/xla_vs_files/pytorch/xla/torch_xla/stablehlo.py", line 18, in <module>
    from torch_xla._dynamo import dynamo_bridge
  File "/workspaces/xla_vs_files/pytorch/xla/torch_xla/_dynamo/dynamo_bridge.py", line 20, in <module>
    from torch._inductor.fx_passes.post_grad import ConstructorMoverPass
  File "/usr/local/lib/python3.10/site-packages/torch/_inductor/fx_passes/post_grad.py", line 22, in <module>
    from .. import config, ir, pattern_matcher
  File "/usr/local/lib/python3.10/site-packages/torch/_inductor/pattern_matcher.py", line 96, in <module>
    from .lowering import fallback_node_due_to_unsupported_type
  File "/usr/local/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 6639, in <module>
    from . import kernel
  File "/usr/local/lib/python3.10/site-packages/torch/_inductor/kernel/__init__.py", line 1, in <module>
    from . import mm, mm_common, mm_plus_mm, unpack_mixed_mm
  File "/usr/local/lib/python3.10/site-packages/torch/_inductor/kernel/mm.py", line 16, in <module>
    from torch._inductor.codegen.cpp_gemm_template import CppPackedGemmTemplate
  File "/usr/local/lib/python3.10/site-packages/torch/_inductor/codegen/cpp_gemm_template.py", line 14, in <module>
    from ..kernel.mm_common import mm_args
  File "/usr/local/lib/python3.10/site-packages/torch/_inductor/kernel/mm_common.py", line 10, in <module>
    from torch._inductor.select_algorithm import realize_inputs
  File "/usr/local/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 22, in <module>
    from filelock import FileLock
ModuleNotFoundError: No module named 'filelock'
```
So it appears something isn't configured correctly. If I follow the instructions for directly using a container, everything works as expected.

**Comment by mikegre-google** [comment]
If I manually `pip install filelock` I'm able to import torch_xla.
