### ISSUE TITLE
Duplicate registration issue with torch_xla2

### ISSUE THREAD

**Issue by aboubezari** [pytorch/xla#8517]
## 🐛 Bug

When importing torch_xla2, I get a duplicate registration issue.

## To Reproduce

Follow the instructions here, install torch 2.3.0, and try to import torch_xla2.
https://github.com/pytorch/xla/tree/master/experimental/torch_xla2

## Expected behavior

Should import properly, but get a crash:
```
Traceback (most recent call last):
  File "/tmp/openxla/xla-2.3.0/experimental/torch_xla2/test.py", line 1, in <module>
    import torch_xla2
  File "/tmp/openxla/xla-2.3.0/experimental/torch_xla2/torch_xla2/__init__.py", line 5, in <module>
    from torch_xla2 import tensor
  File "/tmp/openxla/xla-2.3.0/experimental/torch_xla2/torch_xla2/tensor.py", line 9, in <module>
    from torch_xla2 import ops_registry
  File "/tmp/openxla/xla-2.3.0/experimental/torch_xla2/torch_xla2/ops_registry.py", line 3, in <module>
    import torch_xla2.decompositions
  File "/tmp/openxla/xla-2.3.0/experimental/torch_xla2/torch_xla2/decompositions.py", line 30, in <module>
    @register_decomposition(aten.reflection_pad3d)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aboubezari/miniconda3/lib/python3.12/site-packages/torch/_decomp/__init__.py", line 186, in decomposition_decorator
    pytree.tree_map_(register, aten_op)
  File "/home/aboubezari/miniconda3/lib/python3.12/site-packages/torch/utils/_pytree.py", line 933, in tree_map_
    tuple(map(func, *flat_args))  # consume and exhaust the iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aboubezari/miniconda3/lib/python3.12/site-packages/torch/_decomp/__init__.py", line 183, in register
    _add_op_to_registry(registry, op, fn)
  File "/home/aboubezari/miniconda3/lib/python3.12/site-packages/torch/_decomp/__init__.py", line 55, in _add_op_to_registry
    raise RuntimeError(f"duplicate registrations for {op_overload}")
RuntimeError: duplicate registrations for aten.reflection_pad3d.default
```

## Environment

Torch version: 2.3.0

**Comment by qihqi** [comment]
Hi,

I believe this is fixed at HEAD: https://github.com/pytorch/xla/blob/master/experimental/torch_xla2/torch_xla2/decompositions.py#L50
