### ISSUE TITLE
`tensor.gather` causes all kind of weird behaviors

### ISSUE THREAD

**Issue by ibeltagy** [pytorch/xla#873]
To get around this issue https://github.com/pytorch/xla/issues/859, I used `tensor.gather` to only keep the relevant entries (https://github.com/ibeltagy/pytorch-transformers/blob/tpu/pytorch_transformers/modeling_bert.py#L795-L797). Using `gather` resulted into many weird behaviors. 
1- Training takes half an hour (instead of the usual 30 seconds) even though no trips to the CPU are needed. The time is probably spent in some compilation step. Running training for the second time (some computation graphs are cached in the TPU), it takes 300 seconds to train (still, 10x slower than without `gather`). Below is the metric report for the first slow run, then the second faster (but still slow) run. Is this expected from `gather` or is this a bug? Any way to address that?
```
Metric: CompileTime
  TotalSamples: 26
  Counter: 08h12m02s071ms528.125us
  ValueRate: 07s861ms806.565us / second
  Rate: 0.0165136 / second
  Percentiles: 1%=001ms195.944us; 5%=07m06s302ms581.579us; 10%=07m06s306ms28.908us; 20%=07m06s369ms81.446us; 50%=07m15s248ms283.490us; 80%=07m15s302ms850.564us; 90%=07m15s315ms485.2$
4us; 95%=07m15s333ms523.452us; 99%=07m15s334ms416.878us
Metric: ExecuteTime
  TotalSamples: 96
  Counter: 04h16m26s947ms249.514us
  ValueRate: 03s467ms108.130us / second
  Rate: 0.0627301 / second
  Percentiles: 1%=003ms394.870us; 5%=004ms901.986us; 10%=07s689ms6.536us; 20%=07s701ms569.363us; 50%=26s506ms612.997us; 80%=48s568ms20.007us; 90%=49s996ms903.847us; 95%=08m31s863ms9$
9.574us; 99%=08m31s872ms776.331us
Metric: InboundData
  TotalSamples: 8
  Counter: 32.00B
  ValueRate: 6.42B / second
  Rate: 1.60377 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=4.00B; 80%=4.00B; 90%=4.00B; 95%=4.00B; 99%=4.00B
Metric: OutboundData
  TotalSamples: 1776
  Counter: 3.99GB
  ValueRate: 1.63MB / second
  Rate: 0.732879 / second
  Percentiles: 1%=4.00B; 5%=3.00KB; 10%=3.00KB; 20%=3.00KB; 50%=3.00KB; 80%=2.25MB; 90%=9.00MB; 95%=9.00MB; 99%=9.00MB
Metric: ReleaseCompileHandlesTime
  TotalSamples: 21
  Counter: 51s900ms46.959us
  ValueRate: 053ms123.848us / second
  Rate: 0.0219175 / second
  Percentiles: 1%=001ms399.810us; 5%=075ms878.475us; 10%=076ms327.552us; 20%=078ms603.826us; 50%=093ms178.537us; 80%=134ms24.590us; 90%=158ms223.225us; 95%=168ms886.236us; 99%=49s92$
ms588.687us
Metric: ReleaseDataHandlesTime
  TotalSamples: 199
  Counter: 10m44s466ms427.265us
  ValueRate: 382ms897.492us / second
  Rate: 0.130029 / second
  Percentiles: 1%=693.193us; 5%=857.347us; 10%=001ms28.469us; 20%=001ms377.393us; 50%=011ms859.002us; 80%=083ms948.049us; 90%=091ms953.489us; 95%=07s718ms436.182us; 99%=34s533ms637.$
96us
Metric: TransferFromServerTime
  TotalSamples: 8
  Counter: 630ms626.723us
  ValueRate: 126ms222.070us / second
  Rate: 1.60377 / second
  Percentiles: 1%=055ms326.012us; 5%=055ms326.012us; 10%=055ms326.012us; 20%=075ms841.714us; 50%=084ms659.945us; 80%=086ms587.754us; 90%=086ms100.932us; 95%=086ms100.932us; 99%=086m$
100.932us
Metric: TransferToServerTime
  TotalSamples: 1776
  Counter: 58s129ms143.233us
  ValueRate: 021ms656.684us / second
  Rate: 0.732852 / second
  Percentiles: 1%=001ms77.893us; 5%=001ms333.707us; 10%=002ms648.236us; 20%=003ms963.647us; 50%=009ms12.887us; 80%=025ms304.105us; 90%=043ms907.376us; 95%=062ms141.035us; 99%=445ms31
7.699us
Counter: CachedSyncTensors
  Value: 70
Counter: CreateCompileHandles
  Value: 26
Counter: CreateDataHandles
  Value: 22496
Counter: CreateXlaTensor
  Value: 283344
Counter: DestroyCompileHandles
  Value: 21
Counter: DestroyDataHandles
  Value: 19067
Counter: DestroyXlaTensor
  Value: 280032
Counter: ReleaseCompileHandles
  Value: 21
Counter: ReleaseDataHandles
  Value: 19088
Counter: UncachedSyncTensors
  Value: 26
Counter: XRTAllocateFromTensor_Empty
  Value: 877
Counter: XrtCompile_Empty
  Value: 2176
Counter: XrtExecuteChained_Empty
  Value: 2176
Counter: XrtExecute_Empty
  Value: 2176
Counter: XrtRead_Empty
  Value: 2176
Counter: XrtReleaseAllocationHandle_Empty
  Value: 2176
Counter: XrtReleaseCompileHandle_Empty
  Value: 2176
Counter: XrtSessionCount
  Value: 25
Counter: XrtSubTuple_Empty
  Value: 2176
Counter: aten::_local_scalar_dense
  Value: 8
```
======
```
Metric: CompileTime
  TotalSamples: 26
  Counter: 09s569ms525.976us
  ValueRate: 031ms886.077us / second
  Rate: 0.0937195 / second
  Percentiles: 1%=001ms264.810us; 5%=109ms242.694us; 10%=117ms773.800us; 20%=163ms655.984us; 50%=180ms147.932us; 80%=689ms374.171us; 90%=764ms223.160us; 95%=773ms550.595us; 99%=801m$
414.583us
Metric: ExecuteTime
  TotalSamples: 96
  Counter: 02h13m27s145ms448.058us
  ValueRate: 10s585ms882.499us / second
  Rate: 0.409474 / second
  Percentiles: 1%=004ms977.020us; 5%=087ms492.667us; 10%=07s698ms101.465us; 20%=07s705ms642.971us; 50%=30s921ms628.814us; 80%=46s500ms808.826us; 90%=48s509ms422.445us; 95%=48s925ms8$
6.358us; 99%=48s124ms249.338us
Metric: InboundData
  TotalSamples: 8
  Counter: 32.00B
  ValueRate: 6.33B / second
  Rate: 1.58359 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=4.00B; 80%=4.00B; 90%=4.00B; 95%=4.00B; 99%=4.00B
Metric: OutboundData
  TotalSamples: 1776
  Counter: 3.99GB
  ValueRate: 22.90MB / second
  Rate: 10.3011 / second
  Percentiles: 1%=4.00B; 5%=3.00KB; 10%=3.00KB; 20%=3.00KB; 50%=3.00KB; 80%=2.25MB; 90%=9.00MB; 95%=9.00MB; 99%=9.00MB
Metric: ReleaseCompileHandlesTime
  TotalSamples: 21
  Counter: 01s321ms6.300us
  ValueRate: 014ms866.806us / second
  Rate: 0.22044 / second
  Percentiles: 1%=001ms203.361us; 5%=001ms282.931us; 10%=002ms715.837us; 20%=065ms71.876us; 50%=072ms954.902us; 80%=078ms846.972us; 90%=080ms6.362us; 95%=082ms998.077us; 99%=086ms31$
.302us
Metric: ReleaseDataHandlesTime
  TotalSamples: 208
  Counter: 05m58s952ms954.170us
  ValueRate: 01s271ms899.363us / second
  Rate: 0.887214 / second
  Percentiles: 1%=642.931us; 5%=854.286us; 10%=001ms61.277us; 20%=001ms360.484us; 50%=013ms359.460us; 80%=089ms231.317us; 90%=199ms853.200us; 95%=07s723ms828.767us; 99%=37s846ms415.$
32us
Metric: TransferFromServerTime
  TotalSamples: 8
  Counter: 586ms200.280us
  ValueRate: 116ms37.560us / second
  Rate: 1.58359 / second
  Percentiles: 1%=047ms81.506us; 5%=047ms81.506us; 10%=047ms81.506us; 20%=067ms359.779us; 50%=078ms402.407us; 80%=086ms37.306us; 90%=091ms530.224us; 95%=091ms530.224us; 99%=091ms530$
224us
Metric: TransferToServerTime
  TotalSamples: 1776
  Counter: 54s344ms382.214us
  ValueRate: 265ms861.249us / second
  Rate: 10.2978 / second
  Percentiles: 1%=001ms87.656us; 5%=001ms417.010us; 10%=002ms887.091us; 20%=004ms698.948us; 50%=009ms72.423us; 80%=024ms172.659us; 90%=041ms752.456us; 95%=055ms638.661us; 99%=085ms7$
4.880us
Counter: CachedSyncTensors
  Value: 70
Counter: CreateCompileHandles
  Value: 26
Counter: CreateDataHandles
  Value: 22496
Counter: CreateXlaTensor
  Value: 283344
Counter: DestroyCompileHandles
  Value: 21
Counter: DestroyDataHandles
  Value: 19071
Counter: DestroyXlaTensor
  Value: 280032
Counter: ReleaseCompileHandles
  Value: 21
Counter: ReleaseDataHandles
  Value: 19088
Counter: UncachedSyncTensors
  Value: 26
Counter: XRTAllocateFromTensor_Empty
  Value: 889
Counter: XrtCompile_Empty
  Value: 2176
Counter: XrtExecuteChained_Empty
  Value: 2176
Counter: XrtExecute_Empty
  Value: 2176
Counter: XrtRead_Empty
  Value: 2176
Counter: XrtReleaseAllocationHandle_Empty
  Value: 2176
Counter: XrtReleaseCompileHandle_Empty
  Value: 2176
Counter: XrtSessionCount
  Value: 25
Counter: XrtSubTuple_Empty
  Value: 2176
Counter: aten::_local_scalar_dense
  Value: 8
```

2- sometimes it hangs (as in here https://github.com/pytorch/xla/issues/821). Restarting the TPU fixes hanging (but it goes back to being super slow as in 1) 

3- when running the code without dataparallel and on only one of the TPU cores, I get a different behavior. It runs very fast (no slow compilation as in 1) then it gets stuck (hangs as in 2) at batch number 26, and it is always batch 26, even when batch size is different or batches are shuffled, so it is not about the content of that batch (weird)!!. Here, it gets stuck on `loss.backward()`. If I skip batch 26, it keeps processing fine, then gets stuck again at the end at the last `loss.item()`. Below are the `gdb` for the two places it gets stuck at. Notice that this is one thread, no dataparallel, only the main thread running on one core. 

backtrace for when it gets stuck at `loss.item()`
```
#1  0x00007fffe8aba56f in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/build/build-cc-gcc-final/x86_64-conda_cos6-linux-gnu/libstdc++-v3/include/x86_64-conda_cos6-linux-gnu/bits/gthr-default.h:877
#2  std::condition_variable::wait (this=<optimized out>, __lock=...)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007fffc6446ccb in xla::util::MultiWait::Wait() () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#4  0x00007fffc6451b81 in xla::XrtComputationClient::Compile(std::vector<xla::ComputationClient::CompileInstance, std::allocator<xla::ComputationClient::CompileInstance> >) ()
   from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/lib/libxla_computation_client.so
#5  0x00007fffdc4a416f in torch_xla::XLATensor::SyncTensorsGraphInternal (tensors=0x7fffffffd400, devices=..., config=...) at torch_xla/csrc/tensor.cpp:1256
#6  0x00007fffdc4a2987 in torch_xla::XLATensor::GetTensorsFused (tensors=0x7fffffffd400, writeable=0x7fffffffd418) at torch_xla/csrc/tensor.cpp:849
#7  0x00007fffdc4a2928 in torch_xla::XLATensor::GetTensors (tensors=0x7fffffffd400, writeable=0x7fffffffd418) at torch_xla/csrc/tensor.cpp:842
#8  0x00007fffdc5f92c2 in torch_xla::bridge::XlaCreateTensorList (tensors=..., writeable=0x7fffffffd680) at torch_xla/csrc/aten_xla_bridge.cpp:112
#9  0x00007fffdc794b11 in torch_xla::AtenXlaTypeDefault::_local_scalar_dense (self=...) at torch_xla/csrc/aten_xla_type_default.cpp:7010
#10 0x00007fffe69687a7 in torch::autograd::VariableType::_local_scalar_dense(at::Tensor const&) ()
   from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch.so
#11 0x00007fffe4c14502 in at::_local_scalar_dense(at::Tensor const&) () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch.so
#12 0x00007fffe4c140eb in at::native::item(at::Tensor const&) () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch.so
#13 0x00007fffe4fe9d5f in at::TypeDefault::item(at::Tensor const&) () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch.so
#14 0x00007fffe6b87d8c in torch::autograd::VariableType::item(at::Tensor const&) () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch.so
#15 0x00007fffe8d23e64 in at::Tensor::item() const () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#16 0x00007fffe8d20110 in torch::autograd::dispatch_to_CDouble(at::Tensor const&) () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#17 0x00007fffe8c598b8 in torch::autograd::THPVariable_item(_object*, _object*) () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#18 0x000055555566578a in _PyCFunction_FastCallDict () at /tmp/build/80754af9/python_1546130271559/work/Objects/methodobject.c:192
#19 0x00005555556ec42c in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4851
#20 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#21 0x00005555556e5bfe in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#22 0x00005555556e6771 in fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
#23 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#24 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#25 0x00005555556e5bfe in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#26 0x00005555556e6771 in fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
#27 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#28 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#29 0x00005555556e7289 in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwstep=2, kwcount=<optimized out>, 
    kwargs=0x0, kwnames=0x0, argcount=0, args=0x0, locals=0x7ffff7f64090, globals=0x7ffff7f64090, _co=0x7ffff6e8fd20)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#30 PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4187
#31 0x00005555556e801c in PyEval_EvalCode (co=co@entry=0x7ffff6e8fd20, globals=globals@entry=0x7ffff7f64090, locals=locals@entry=0x7ffff7f64090)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:731
#32 0x000055555576a3c4 in run_mod () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:1025
#33 0x000055555576a7c1 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:978
#34 0x000055555576a9c3 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:419
#35 0x000055555576aacd in PyRun_AnyFileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:81
#36 0x000055555576e4b3 in run_file (p_cf=0x7fffffffe77c, filename=0x5555558a8240 L"examples/lm_finetuning/finetune_on_pregenerated.py", fp=0x5555559376e0)
    at /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:340
#37 Py_Main () at /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:811
#38 0x000055555563702e in main () at /tmp/build/80754af9/python_1546130271559/work/Programs/python.c:69
#39 0x00007ffff783d2e1 in __libc_start_main (main=0x555555636f40 <main>, argc=20, argv=0x7fffffffe988, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe978) at ../csu/libc-start.c:291
#40 0x0000555555717e0e in _start () at ../sysdeps/x86_64/elf/start.S:103
```

backtrace for when it gets stuck at `loss.backward()` on a random batch:
```
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffe8aba56f in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/build/build-cc-gcc-final/x86_64-conda_cos6-linux-gnu/libstdc++-v3/include/x86_64-conda_cos6-linux-gnu/bits/gthr-default.h:877
#2  std::condition_variable::wait (this=<optimized out>, __lock=...)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007fffe71c81fb in torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) ()
   from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch.so
#4  0x00007fffe90730a7 in THPEngine_run_backward(THPEngine*, _object*, _object*) () from /root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libtorch_python.so
#5  0x0000555555665744 in _PyCFunction_FastCallDict () at /tmp/build/80754af9/python_1546130271559/work/Objects/methodobject.c:231
#6  0x0000555555692800 in _PyCFunction_FastCallKeywords () at /tmp/build/80754af9/python_1546130271559/work/Objects/methodobject.c:294
#7  0x00005555556ec42c in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4851
#8  0x0000555555712147 in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3351
#9  0x00005555556e58e4 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#10 0x00005555556e6771 in fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
#11 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#12 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#13 0x00005555556e58e4 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#14 0x00005555556e6771 in fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
#15 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#16 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#17 0x00005555556e5bfe in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#18 0x00005555556e6771 in fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
#19 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#20 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#21 0x00005555556e5bfe in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#22 0x00005555556e6771 in fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
#23 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#24 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#25 0x00005555556e7289 in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwstep=2, kwcount=<optimized out>, 
    kwargs=0x0, kwnames=0x0, argcount=0, args=0x0, locals=0x7ffff7f64090, globals=0x7ffff7f64090, _co=0x7ffff6e8fd20)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#26 PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4187
#27 0x00005555556e801c in PyEval_EvalCode (co=co@entry=0x7ffff6e8fd20, globals=globals@entry=0x7ffff7f64090, locals=locals@entry=0x7ffff7f64090)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:731
#28 0x000055555576a3c4 in run_mod () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:1025
#29 0x000055555576a7c1 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:978
#30 0x000055555576a9c3 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:419
#31 0x000055555576aacd in PyRun_AnyFileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:81
#32 0x000055555576e4b3 in run_file (p_cf=0x7fffffffe77c, filename=0x5555558a8240 L"examples/lm_finetuning/finetune_on_pregenerated.py", fp=0x5555559376e0)
    at /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:340
#33 Py_Main () at /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:811
#34 0x000055555563702e in main () at /tmp/build/80754af9/python_1546130271559/work/Programs/python.c:69
#35 0x00007ffff783d2e1 in __libc_start_main (main=0x555555636f40 <main>, argc=20, argv=0x7fffffffe988, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe978) at ../csu/libc-start.c:291
#36 0x0000555555717e0e in _start () at ../sysdeps/x86_64/elf/start.S:103
```

**Comment by ibeltagy** [comment]
Any thoughts what could be wrong, or what I can investigate to better understand the problem?

**Comment by ibeltagy** [comment]
Closing this issue in favor of this https://github.com/pytorch/xla/issues/898.
