### ISSUE TITLE
Pulling latest TF code crashes

### ISSUE THREAD

**Issue by dlibenzi** [pytorch/xla#904]
GDB stack:
```
[Switching to Thread 0x7ffed97fa700 (LWP 43382)]
0x00007fffdebdb42b in std::type_info::operator== (this=0x7fffdc6e15b8, __arg=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/typeinfo:123
(gdb) bt
#0  0x00007fffdebdb42b in std::type_info::operator== (this=0x7fffdc6e15b8, __arg=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/typeinfo:123
#1  0x00007fffdf0b6317 in std::_Sp_counted_ptr_inplace<xla::Shape, std::allocator<xla::Shape>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter (this=0x7ffebc9c4f70,  type_info node=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../
include/c++/8/bits/shared_ptr_base.h:573
#2  0x00007fffd73de7e3 in xla::ShapeTree<stream_executor::DeviceMemoryBase>::ShapeTree(xla::Shape) () from /usr/local/google/home/dlibenzi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-0.1-py3.6-linux-x86_64.egg/torch_xla
/lib/libxla_computation_client.so
#3  0x00007fffd73dd24b in xla::ScopedShapedBuffer::release() () from /usr/local/google/home/dlibenzi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-0.1-py3.6-linux-x86_64.egg/torch_xla/lib/libxla_computation_client.so
#4  0x00007fffd69e1ab6 in tensorflow::XRTTupleAllocation::CreateAndTransfer(xla::LiteralBase const&, tensorflow::XRTMemoryManager*, xla::Backend*, int, tensorflow::XRTTupleAllocation**) () from /usr/local/google/home/dlibenzi/anaconda3/
envs/pytorch/lib/python3.6/site-packages/torch_xla-0.1-py3.6-linux-x86_64.egg/torch_xla/lib/libxla_computation_client.so
#5  0x00007fffd69cf535 in tensorflow::XRTAllocateFromTensorOp<tensorflow::XRTGenericDeviceAccessor>::Compute(tensorflow::OpKernelContext*) () from /usr/local/google/home/dlibenzi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_
xla-0.1-py3.6-linux-x86_64.egg/torch_xla/lib/libxla_computation_client.so
#6  0x00007fffd69fea82 in tensorflow::XlaDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) () from /usr/local/google/home/dlibenzi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-0.1-py3.6-linux-x86_64.eg
g/torch_xla/lib/libxla_computation_client.so
#7  0x00007fffdbe0248d in ?? () from /usr/local/google/home/dlibenzi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-0.1-py3.6-linux-x86_64.egg/torch_xla/lib/libxla_computation_client.so
#8  0x00007fffdbe030f8 in ?? () from /usr/local/google/home/dlibenzi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-0.1-py3.6-linux-x86_64.egg/torch_xla/lib/libxla_computation_client.so
#9  0x00007fffdc11de42 in Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) () from /usr/local/google/home/dlibenzi/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla-0.1-py3.6-linux-x86_64.egg/torc
h_xla/lib/libxla_computation_client.so
#10 0x00007fffdc11d5f1 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /usr/local/google/home/dlibenzi/anaconda3/envs
/pytorch/lib/python3.6/site-packages/torch_xla-0.1-py3.6-linux-x86_64.egg/torch_xla/lib/libxla_computation_client.so
#11 0x00007fffe8be8aff in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007ffff7bbec73 in start_thread (arg=<optimized out>) at pthread_create.c:486
#13 0x00007ffff78f0def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by dlibenzi** [comment]
This is an issue with a particular version of clang-7 and its libraries.
If the crash above shows up, move to a different version, or build with:
```Shell
export XLA_DEBUG=1
```
